/* ── Disaster Management Feature – Seed data ─────────── */
import type {
  Disaster,
  EmergencyShelter,
  EmergencyContact,
  DisplacedPerson,
  DisasterVolunteer,
  EmergencyAlertRecord,
  MissingPerson,
} from "./types.js";

/* ── Emergency Contacts (always available) ───────────── */

export const SEED_CONTACTS: EmergencyContact[] = [
  {
    id: "ec_001",
    organization_name_ar: "الدفاع المدني اللبناني",
    organization_name_en: "Lebanese Civil Defense",
    contact_type: "civil_defense",
    service_provided_ar: "إطفاء وإنقاذ",
    service_area: "موطني",
    primary_phone: "01-575802",
    emergency_hotline: "125",
    available_24_7: true,
    priority_level: 1,
    is_emergency: true,
    active: true,
  },
  {
    id: "ec_002",
    organization_name_ar: "الصليب الأحمر اللبناني",
    organization_name_en: "Lebanese Red Cross",
    contact_type: "medical",
    service_provided_ar: "إسعاف ونقل طبي",
    service_area: "موطني",
    primary_phone: "01-372802",
    emergency_hotline: "140",
    available_24_7: true,
    priority_level: 1,
    is_emergency: true,
    active: true,
  },
  {
    id: "ec_003",
    organization_name_ar: "قوى الأمن الداخلي",
    organization_name_en: "Internal Security Forces",
    contact_type: "police",
    service_provided_ar: "طوارئ أمنية",
    service_area: "موطني",
    primary_phone: "01-425610",
    emergency_hotline: "112",
    available_24_7: true,
    priority_level: 1,
    is_emergency: true,
    active: true,
  },
  {
    id: "ec_004",
    organization_name_ar: "الجيش اللبناني — غرفة العمليات",
    organization_name_en: "Lebanese Army Operations Room",
    contact_type: "military",
    service_provided_ar: "عمليات عسكرية وطوارئ",
    service_area: "موطني",
    primary_phone: "01-980380",
    emergency_hotline: "1701",
    available_24_7: true,
    priority_level: 1,
    is_emergency: true,
    active: true,
  },
  {
    id: "ec_005",
    organization_name_ar: "وزارة الصحة العامة",
    organization_name_en: "Ministry of Public Health",
    contact_type: "government",
    service_provided_ar: "طوارئ صحية ومعلومات طبية",
    service_area: "موطني",
    primary_phone: "01-615700",
    emergency_hotline: "1214",
    available_24_7: false,
    priority_level: 2,
    is_emergency: true,
    active: true,
  },
  {
    id: "ec_006",
    organization_name_ar: "الهيئة العليا للإغاثة",
    organization_name_en: "Higher Relief Council",
    contact_type: "government",
    service_provided_ar: "إغاثة ومساعدات للكوارث",
    service_area: "موطني",
    primary_phone: "01-980870",
    available_24_7: false,
    priority_level: 2,
    is_emergency: false,
    active: true,
  },
  {
    id: "ec_007",
    organization_name_ar: "المفوضية العليا لشؤون اللاجئين (UNHCR)",
    organization_name_en: "UNHCR Lebanon",
    contact_type: "international",
    service_provided_ar: "مساعدة النازحين واللاجئين",
    service_area: "موطني",
    primary_phone: "01-849201",
    available_24_7: false,
    priority_level: 3,
    is_emergency: false,
    active: true,
  },
  {
    id: "ec_008",
    organization_name_ar: "هيئة إدارة الكوارث (NDM)",
    organization_name_en: "National Disaster Management",
    contact_type: "government",
    service_provided_ar: "تنسيق الاستجابة للكوارث",
    service_area: "موطني",
    primary_phone: "01-981701",
    available_24_7: false,
    priority_level: 2,
    is_emergency: false,
    active: true,
  },
];

/* ── Active Disasters ────────────────────────────────── */

export const SEED_DISASTERS: Disaster[] = [
  {
    id: "dis_001",
    disaster_type: "war",
    name_ar: "العدوان على الجنوب — تشرين ٢٠٢٥",
    name_en: "Southern Aggression Oct 2025",
    description_ar: "عدوان إسرائيلي على مناطق جنوب لبنان أدى إلى نزوح واسع. المنطقة لا تزال تحت المراقبة.",
    severity: "high",
    affected_areas: ["صور", "بنت جبيل", "مرجعيون", "النبطية", "صيدا"],
    status: "monitoring",
    started_at: "2025-10-01T00:00:00Z",
    displaced_count: 45000,
    casualties_count: 0,
    shelters_opened: 12,
    created_at: "2025-10-01",
  },
  {
    id: "dis_002",
    disaster_type: "flood",
    name_ar: "فيضانات البقاع — شباط ٢٠٢٦",
    name_en: "Bekaa Floods Feb 2026",
    description_ar: "أمطار غزيرة وفيضانات في سهل البقاع. أضرار في البنية التحتية وتهجير عائلات.",
    severity: "medium",
    affected_areas: ["زحلة", "بعلبك", "شتورا", "رياق"],
    status: "active",
    started_at: "2026-02-10T00:00:00Z",
    displaced_count: 3200,
    casualties_count: 0,
    shelters_opened: 5,
    created_at: "2026-02-10",
  },
];

/* ── Emergency Shelters ──────────────────────────────── */

export const SEED_SHELTERS: EmergencyShelter[] = [
  {
    id: "sh_001",
    disaster_id: "dis_001",
    name_ar: "ثكنة صور — مركز إيواء مؤقت",
    shelter_type: "military",
    address_ar: "ثكنة الجيش — صور",
    city: "صور",
    region: "الجنوب",
    total_capacity: 500,
    current_occupancy: 380,
    families_count: 75,
    individuals_count: 380,
    has_water: true,
    has_electricity: true,
    has_medical: true,
    has_food: true,
    has_bathrooms: true,
    has_heating: true,
    has_cooling: false,
    manager_name: "العقيد أحمد خالد",
    manager_phone: "+961-7-740123",
    emergency_contact: "+961-7-740124",
    status: "open",
    accepting_new: true,
    accepts_families: true,
    accepts_elderly: true,
    accepts_disabled: true,
  },
  {
    id: "sh_002",
    disaster_id: "dis_001",
    name_ar: "مدرسة صيدا الحكومية — مركز نزوح",
    shelter_type: "school",
    address_ar: "مدرسة صيدا الرسمية، شارع رياض الصلح",
    city: "صيدا",
    region: "الجنوب",
    total_capacity: 200,
    current_occupancy: 195,
    families_count: 40,
    individuals_count: 195,
    has_water: true,
    has_electricity: true,
    has_medical: false,
    has_food: true,
    has_bathrooms: true,
    has_heating: false,
    has_cooling: false,
    manager_name: "السيد وليد حمود",
    manager_phone: "+961-7-722345",
    status: "full",
    accepting_new: false,
    accepts_families: true,
    accepts_elderly: true,
    accepts_disabled: false,
  },
  {
    id: "sh_003",
    disaster_id: "dis_001",
    name_ar: "جامع النبطية الكبير — مركز إيواء",
    shelter_type: "mosque",
    address_ar: "الجامع الكبير، ساحة النبطية",
    city: "النبطية",
    region: "الجنوب",
    total_capacity: 150,
    current_occupancy: 120,
    families_count: 25,
    individuals_count: 120,
    has_water: true,
    has_electricity: true,
    has_medical: false,
    has_food: true,
    has_bathrooms: true,
    has_heating: true,
    has_cooling: false,
    manager_name: "الشيخ حسين",
    manager_phone: "+961-7-760123",
    status: "open",
    accepting_new: true,
    accepts_families: true,
    accepts_elderly: true,
    accepts_disabled: true,
  },
  {
    id: "sh_004",
    disaster_id: "dis_002",
    name_ar: "مركز زحلة الاجتماعي — إيواء مؤقت",
    shelter_type: "community_center",
    address_ar: "مركز الخدمات الاجتماعية، بولفار زحلة",
    city: "زحلة",
    region: "البقاع",
    total_capacity: 300,
    current_occupancy: 180,
    families_count: 35,
    individuals_count: 180,
    has_water: true,
    has_electricity: true,
    has_medical: true,
    has_food: true,
    has_bathrooms: true,
    has_heating: true,
    has_cooling: false,
    manager_name: "الأستاذ كريم شمص",
    manager_phone: "+961-8-801234",
    emergency_contact: "+961-8-801235",
    status: "open",
    accepting_new: true,
    accepts_families: true,
    accepts_elderly: true,
    accepts_disabled: true,
  },
  {
    id: "sh_005",
    disaster_id: "dis_002",
    name_ar: "كنيسة بعلبك — مركز مساعدة",
    shelter_type: "church",
    address_ar: "كنيسة مار يوحنا، بعلبك",
    city: "بعلبك",
    region: "البقاع",
    total_capacity: 100,
    current_occupancy: 60,
    families_count: 12,
    individuals_count: 60,
    has_water: true,
    has_electricity: true,
    has_medical: false,
    has_food: true,
    has_bathrooms: true,
    has_heating: true,
    has_cooling: false,
    manager_name: "الأب جورج",
    manager_phone: "+961-8-370123",
    status: "open",
    accepting_new: true,
    accepts_families: true,
    accepts_elderly: true,
    accepts_disabled: false,
  },
];

/* ── Alerts ──────────────────────────────────────────── */

export const SEED_ALERTS: EmergencyAlertRecord[] = [
  {
    id: "ea_001",
    disaster_id: "dis_002",
    title_ar: "تحذير من فيضانات إضافية في سهل البقاع",
    message_ar: "تتوقع الأرصاد الجوية أمطاراً غزيرة في الساعات الـ24 القادمة في منطقة البقاع. يُطلب من السكان القريبين من الأنهر الابتعاد والتوجه لأقرب مركز إيواء.",
    severity: "high",
    alert_type: "weather",
    affected_areas: ["زحلة", "بعلبك", "شتورا"],
    sent_at: "2026-03-02T08:00:00Z",
    expires_at: "2026-03-04T08:00:00Z",
    active: true,
  },
  {
    id: "ea_002",
    disaster_id: "dis_001",
    title_ar: "فتح مراكز توزيع مساعدات في صيدا",
    message_ar: "تم فتح مراكز توزيع مواد غذائية وبطانيات في منطقة صيدا. يمكن للنازحين التوجه إلى مدرسة صيدا الحكومية بين الساعة ٨ صباحاً و٤ مساء.",
    severity: "medium",
    alert_type: "aid",
    affected_areas: ["صيدا"],
    sent_at: "2026-03-01T10:00:00Z",
    active: true,
  },
  {
    id: "ea_003",
    disaster_id: "dis_001",
    title_ar: "إعادة فتح الطرقات في مرجعيون",
    message_ar: "تم إعادة فتح الطريق الرئيسي بين مرجعيون والنبطية. يُرجى اتباع توجيهات الجيش اللبناني عند المرور.",
    severity: "low",
    alert_type: "safety",
    affected_areas: ["مرجعيون", "النبطية"],
    sent_at: "2026-02-28T14:00:00Z",
    active: true,
  },
];

/* ── Mutable stores (in-memory) ──────────────────────── */

export const displacedPersons: DisplacedPerson[] = [];
export const volunteers: DisasterVolunteer[] = [];
export const missingPersons: MissingPerson[] = [];
