/*
  Koudama / WatanyBot numbered sitemap v1.
  Generated by APEX_KOUDAMA_NUMBERED_SITEMAP_LABEL_ID_MAPPING_ADAPTER_PREPATCH_v1_0.ps1.

  Safe integration rules:
  - Do not rename existing routes.
  - Do not replace original icon components.
  - Do not delete current feature objects.
  - Use this as metadata around the existing service catalog.
*/

export type KoudamaSitemapGroupId =
  | 'circulars'
  | 'money'
  | 'procedures'
  | 'entertainment'
  | 'services'
  | 'events'
  | 'account';

export type KoudamaListingOwnerScope = 'user' | 'eligible_user' | 'approved_provider';

export interface KoudamaSitemapItem {
  number: string;
  id: string;
  label: string;
  aliases: string[];
  routes: string[];
}

export interface KoudamaSitemapGroup {
  number: string;
  id: KoudamaSitemapGroupId;
  displayTitle: string;
  formalTitle: string;
  theme: string;
  items: KoudamaSitemapItem[];
}

export interface KoudamaPinnedAction {
  number: string;
  id: string;
  label: string;
  aliases: string[];
  routes: string[];
}

export interface KoudamaListingType {
  id: string;
  label: string;
  ownerScope: KoudamaListingOwnerScope;
  approvalRequired: boolean;
  routes: string[];
}

export const KOUDAMA_PINNED_ACTIONS_V1: KoudamaPinnedAction[] = [
  { number: '0.1', id: 'ask_watany', label: 'اسأل موطني', aliases: ['اسأل موطني', 'ask', 'chat', 'assistant', 'watany'], routes: ['/', '/chat'] },
  { number: '0.2', id: 'something_else', label: 'او شي تاني', aliases: ['او شي تاني', 'شي تاني', 'something else'], routes: ['/', '/chat'] },
  { number: '0.3', id: 'my_listings_services', label: 'إعلاناتي وخدماتي', aliases: ['إعلاناتي وخدماتي', 'إعلاناتي', 'خدماتي', 'my listings', 'my services'], routes: ['/profile', '/marketplace', '/jobs', '/taxi'] },
  { number: '0.4', id: 'my_notifications', label: 'إشعاراتي', aliases: ['إشعاراتي', 'الإشعارات', 'notifications', 'alerts'], routes: ['/notifications', '/alerts'] },
  { number: '0.5', id: 'global_search', label: 'بحث', aliases: ['بحث', 'search'], routes: ['/search'] },
];

export const KOUDAMA_SITEMAP_GROUPS_V1: KoudamaSitemapGroup[] = [
  {
    number: '1',
    id: 'circulars',
    displayTitle: 'التعاميم',
    formalTitle: 'الأخبار والتعاميم',
    theme: 'feed-blue-red',
    items: [
      { number: '1.1', id: 'official_circulars', label: 'تعاميم', aliases: ['تعاميم', 'تعميم', 'circular', 'ticker', 'announcement'], routes: ['/news', '/alerts'] },
      { number: '1.2', id: 'news', label: 'الأخبار', aliases: ['الأخبار', 'news'], routes: ['/news'] },
      { number: '1.3', id: 'fake_alerts', label: 'زائف', aliases: ['زائف', 'fake', 'verify'], routes: ['/fake-news', '/news'] },
      { number: '1.4', id: 'deaths', label: 'الوفيات', aliases: ['الوفيات', 'وفيات', 'al-wafiyat', 'death'], routes: ['/al-wafiyat'] },
      { number: '1.5', id: 'alerts_notifications', label: 'التنبيهات والإشعارات', aliases: ['التنبيهات والإشعارات', 'إشعارات', 'alerts', 'notifications'], routes: ['/alerts', '/notifications'] },
    ],
  },
  {
    number: '2',
    id: 'money',
    displayTitle: 'الاموال',
    formalTitle: 'الأموال',
    theme: 'trusted-emerald-gold',
    items: [
      { number: '2.1', id: 'pension_calculator', label: 'حاسبة المعاش', aliases: ['حاسبة المعاش', 'salary', 'pension'], routes: ['/salary'] },
      { number: '2.2', id: 'salary_statement', label: 'إفادة الراتب', aliases: ['إفادة الراتب', 'salary statement', 'pay statement'], routes: ['/salary'] },
      { number: '2.3', id: 'payment_status', label: 'حالة الدفعات', aliases: ['حالة الدفعات', 'payment', 'payments'], routes: ['/profile', '/admin/payments'] },
      { number: '2.4', id: 'compensation_benefits', label: 'التعويضات والحقوق', aliases: ['التعويضات', 'الحقوق', 'compensation', 'benefits', 'allowance'], routes: ['/legal', '/salary'] },
      { number: '2.5', id: 'school_grants', label: 'المساعدات المدرسية', aliases: ['المساعدات المدرسية', 'school grants', 'school-grants'], routes: ['/school-grants'] },
    ],
  },
  {
    number: '3',
    id: 'procedures',
    displayTitle: 'المعاملات',
    formalTitle: 'المعاملات',
    theme: 'official-navy-blue',
    items: [
      { number: '3.1', id: 'procedures', label: 'المعاملات', aliases: ['المعاملات', 'الإجراءات', 'procedures'], routes: ['/procedures'] },
      { number: '3.2', id: 'forms', label: 'النماذج', aliases: ['النماذج', 'forms'], routes: ['/forms'] },
      { number: '3.3', id: 'questions', label: 'الأسئلة', aliases: ['الأسئلة', 'faq', 'questions'], routes: ['/faq', '/search'] },
      { number: '3.4', id: 'laws', label: 'القوانين', aliases: ['القوانين', 'legal', 'laws', 'rabita'], routes: ['/legal'] },
      { number: '3.5', id: 'useful_links', label: 'روابط مفيدة', aliases: ['روابط مفيدة', 'links'], routes: ['/legal', '/services/official'] },
      { number: '3.6', id: 'official_services', label: 'الخدمات الرسمية', aliases: ['الخدمات الرسمية', 'official services', 'official-services'], routes: ['/services/official'] },
      { number: '3.7', id: 'documents_files', label: 'الملفات والمستندات', aliases: ['الملفات', 'المستندات', 'documents', 'files', 'download'], routes: ['/forms', '/services/official'] },
      { number: '3.8', id: 'my_transactions', label: 'معاملاتي', aliases: ['معاملاتي', 'my requests', 'cases'], routes: ['/cases', '/profile'] },
      { number: '3.9', id: 'new_request', label: 'طلب جديد', aliases: ['طلب جديد', 'new request', 'create request'], routes: ['/cases', '/services/official'] },
    ],
  },
  {
    number: '4',
    id: 'entertainment',
    displayTitle: 'ترفيه',
    formalTitle: 'ترفيه ومجتمع',
    theme: 'community-purple-teal',
    items: [
      { number: '4.1', id: 'group_chats', label: 'الدردشات الجماعية', aliases: ['الدردشات الجماعية', 'group chats', 'community threads', 'threads'], routes: ['/community', '/messages'] },
      { number: '4.2', id: 'community_rooms', label: 'غرف المجتمع', aliases: ['غرف المجتمع', 'community rooms', 'rooms'], routes: ['/community'] },
      { number: '4.3', id: 'messages', label: 'رسائلي', aliases: ['رسائلي', 'messages'], routes: ['/messages'] },
      { number: '4.4', id: 'saved_chats', label: 'المحادثات المحفوظة', aliases: ['المحادثات المحفوظة', 'saved chats', 'chat sessions'], routes: ['/saved', '/profile'] },
      { number: '4.5', id: 'voice_chat', label: 'الدردشة الصوتية', aliases: ['الدردشة الصوتية', 'voice', 'voice chat'], routes: ['/', '/chat'] },
      { number: '4.6', id: 'world_cup', label: 'كأس العالم', aliases: ['كأس العالم', 'world-cup', 'world cup'], routes: ['/world-cup'] },
      { number: '4.7', id: 'media_center', label: 'المركز الإعلامي', aliases: ['المركز الإعلامي', 'media center', 'media'], routes: ['/media'] },
    ],
  },
  {
    number: '5',
    id: 'services',
    displayTitle: 'الخدمات',
    formalTitle: 'الخدمات والفرص',
    theme: 'service-mint-lime',
    items: [
      { number: '5.1', id: 'jobs', label: 'الوظائف', aliases: ['الوظائف', 'jobs'], routes: ['/jobs'] },
      { number: '5.2', id: 'recruitment', label: 'التطويع', aliases: ['التطويع', 'recruitment'], routes: ['/services/recruitment', '/services/official/army-volunteering-conditions'] },
      { number: '5.3', id: 'opportunities', label: 'الفرص', aliases: ['الفرص', 'opportunities'], routes: ['/opportunities'] },
      { number: '5.4', id: 'market', label: 'السوق', aliases: ['السوق', 'market', 'marketplace'], routes: ['/marketplace'] },
      { number: '5.5', id: 'taxi', label: 'تاكسي', aliases: ['تاكسي', 'taxi'], routes: ['/taxi'] },
      { number: '5.6', id: 'assistance', label: 'المساعدات', aliases: ['المساعدات', 'assistance', 'aid'], routes: ['/services/official', '/school-grants'] },
      { number: '5.7', id: 'tourist_guide', label: 'المرشد السياحي', aliases: ['المرشد السياحي', 'tourist guide', 'guide', 'tour'], routes: ['/marketplace', '/profile'] },
      { number: '5.8', id: 'freelance_services', label: 'الخدمات الحرة', aliases: ['الخدمات الحرة', 'freelance', 'skills'], routes: ['/marketplace', '/profile', '/jobs'] },
      { number: '5.9', id: 'user_ads', label: 'الإعلانات', aliases: ['الإعلانات', 'ads', 'listing'], routes: ['/marketplace', '/profile'] },
      { number: '5.10', id: 'service_providers', label: 'مزودو الخدمات', aliases: ['مزودو الخدمات', 'provider', 'service provider'], routes: ['/marketplace', '/services/official'] },
      { number: '5.11', id: 'address_widget', label: 'أداة العنوان', aliases: ['أداة العنوان', 'address', 'governorate', 'qaza', 'village'], routes: ['/profile', '/marketplace'] },
      { number: '5.12', id: 'emergency_support', label: 'الدعم الطارئ', aliases: ['الدعم الطارئ', 'disaster', 'crisis', 'emergency'], routes: ['/services/official'] },
    ],
  },
  {
    number: '6',
    id: 'events',
    displayTitle: 'الفعاليات',
    formalTitle: 'المشاركة والفعاليات',
    theme: 'energy-violet-blue',
    items: [
      { number: '6.1', id: 'vote', label: 'صوّت', aliases: ['صوّت', 'vote', 'voting'], routes: ['/voting'] },
      { number: '6.2', id: 'surveys', label: 'الاستطلاعات', aliases: ['الاستطلاعات', 'survey', 'surveys'], routes: ['/voting', '/surveys'] },
      { number: '6.3', id: 'campaigns', label: 'الحملات', aliases: ['الحملات', 'campaigns'], routes: ['/media', '/voting'] },
      { number: '6.4', id: 'events', label: 'الفعاليات', aliases: ['الفعاليات', 'events'], routes: ['/media'] },
      { number: '6.5', id: 'my_participation', label: 'مشاركاتي', aliases: ['مشاركاتي', 'my participation'], routes: ['/profile', '/voting'] },
      { number: '6.6', id: 'my_invitations', label: 'دعواتي', aliases: ['دعواتي', 'invitations'], routes: ['/profile'] },
    ],
  },
  {
    number: '7',
    id: 'account',
    displayTitle: 'ملفي',
    formalTitle: 'الحساب والأدوات',
    theme: 'utility-slate-emerald',
    items: [
      { number: '7.1', id: 'my_account', label: 'ملفي', aliases: ['ملفي', 'حسابي', 'profile', 'account'], routes: ['/profile'] },
      { number: '7.2', id: 'my_listings_services', label: 'إعلاناتي وخدماتي', aliases: ['إعلاناتي وخدماتي', 'my listings', 'my services'], routes: ['/profile', '/marketplace'] },
      { number: '7.3', id: 'my_posts', label: 'منشوراتي', aliases: ['منشوراتي', 'my posts', 'posts'], routes: ['/profile'] },
      { number: '7.4', id: 'my_requests', label: 'طلباتي', aliases: ['طلباتي', 'requests'], routes: ['/profile', '/cases'] },
      { number: '7.5', id: 'my_tickets', label: 'تذاكري', aliases: ['تذاكري', 'tickets', 'support'], routes: ['/profile', '/support'] },
      { number: '7.6', id: 'my_open_cases', label: 'قضاياي المفتوحة', aliases: ['قضاياي المفتوحة', 'open cases', 'cases'], routes: ['/cases'] },
      { number: '7.7', id: 'bookmarks', label: 'المحفوظات', aliases: ['المحفوظات', 'bookmarks', 'saved'], routes: ['/bookmarks', '/saved'] },
      { number: '7.8', id: 'settings', label: 'الإعدادات', aliases: ['الإعدادات', 'settings'], routes: ['/settings'] },
      { number: '7.9', id: 'auth', label: 'الدخول والتسجيل', aliases: ['الدخول والتسجيل', 'login', 'register'], routes: ['/login', '/register'] },
      { number: '7.10', id: 'admin_tools', label: 'أدوات الإدارة', aliases: ['أدوات الإدارة', 'admin', 'superadmin'], routes: ['/admin'] },
      { number: '7.11', id: 'kb_studio', label: 'KB Studio', aliases: ['KB Studio', 'kb-studio', 'knowledge'], routes: ['/admin/kb'] },
      { number: '7.12', id: 'feature_controls', label: 'إدارة ظهور الميزات', aliases: ['إدارة ظهور الميزات', 'feature controls', 'feature gates'], routes: ['/admin/features'] },
      { number: '7.13', id: 'diagnostics', label: 'أدوات الفحص', aliases: ['أدوات الفحص', 'diagnostics', 'doctor', 'health'], routes: ['/admin/diagnostics'] },
    ],
  },
];

export const KOUDAMA_LISTING_TYPES_V1: KoudamaListingType[] = [
  { id: 'general_ad', label: 'إعلان', ownerScope: 'user', approvalRequired: true, routes: ['/marketplace', '/profile'] },
  { id: 'buy_request', label: 'أريد الشراء', ownerScope: 'user', approvalRequired: true, routes: ['/marketplace'] },
  { id: 'sell_offer', label: 'أريد البيع', ownerScope: 'user', approvalRequired: true, routes: ['/marketplace'] },
  { id: 'job_promotion', label: 'أبحث عن عمل', ownerScope: 'user', approvalRequired: true, routes: ['/jobs', '/profile'] },
  { id: 'freelance_skill', label: 'مهاراتي / خدماتي الحرة', ownerScope: 'eligible_user', approvalRequired: true, routes: ['/marketplace', '/profile'] },
  { id: 'taxi_service', label: 'خدمة تاكسي', ownerScope: 'approved_provider', approvalRequired: true, routes: ['/taxi', '/profile'] },
  { id: 'tourist_guide_service', label: 'مرشد سياحي', ownerScope: 'approved_provider', approvalRequired: true, routes: ['/marketplace', '/profile'] },
  { id: 'service_provider_listing', label: 'مزود خدمة', ownerScope: 'approved_provider', approvalRequired: true, routes: ['/marketplace', '/services/official'] },
  { id: 'assistance_request', label: 'طلب مساعدة', ownerScope: 'eligible_user', approvalRequired: true, routes: ['/services/official', '/profile'] },
  { id: 'community_info_post', label: 'معلومة أو خبر', ownerScope: 'user', approvalRequired: true, routes: ['/news', '/community'] },
  { id: 'system_ticket', label: 'تذكرة نظام', ownerScope: 'user', approvalRequired: false, routes: ['/support', '/profile'] },
  { id: 'open_case', label: 'قضية مفتوحة', ownerScope: 'user', approvalRequired: false, routes: ['/cases', '/profile'] },
];

export function getKoudamaSitemapItemById(id: string): KoudamaSitemapItem | undefined {
  for (const group of KOUDAMA_SITEMAP_GROUPS_V1) {
    const found = group.items.find((item) => item.id === id);
    if (found) return found;
  }
  return KOUDAMA_PINNED_ACTIONS_V1.find((item) => item.id === id);
}

export function getKoudamaSitemapGroupByItemId(id: string): KoudamaSitemapGroup | undefined {
  return KOUDAMA_SITEMAP_GROUPS_V1.find((group) => group.items.some((item) => item.id === id));
}