#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$PredecessorRoot = '',
    [string]$ValidationRoot = '',
    [string]$ParserPreflightProofPath = ''
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$workspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE8_EXACT_RESUME_ISOLATED_VALIDATION_SOURCE_GREEN_MATRIX_LOCAL_RELEASE_CANDIDATE_RESEAL_AND_PHASE9_PREDECESSOR_AUTHORIZATION_V1_0_1'
$skillExpected = 'CE317015ACF91FB84C0D4AEE4EE91F8E2B2C0A75F81926C87AB098F922BB33EB'
$evidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase8-exact-resume-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
$evidenceZip = $evidenceRoot + '.zip'
$sidecarPath = $evidenceZip + '.final-reopen-validation.json'
$failures = New-Object Collections.ArrayList
$gates = New-Object Collections.ArrayList
$stageResults = New-Object Collections.ArrayList
$primaryFailure = ''

function Initialize-Directory([string]$path) { if (-not [IO.Directory]::Exists($path)) { [IO.Directory]::CreateDirectory($path) | Out-Null } }
function Get-Hash([string]$path) { if (-not [IO.File]::Exists($path)) { return '' }; (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Write-Artifact([string]$name, [AllowEmptyString()][string]$value) { [IO.File]::WriteAllText((Join-Path $evidenceRoot $name), $value, (New-Object Text.UTF8Encoding($false))) }
function Write-Json([string]$name, $value) { Write-Artifact $name (($value | ConvertTo-Json -Depth 50) + [Environment]::NewLine) }
function Add-Gate([string]$name, [string]$status, [string]$detail) { [void]$gates.Add([pscustomobject]@{gate=$name;status=$status;detail=$detail}) }
function Add-Failure([string]$class, [string]$detail) { [void]$failures.Add([pscustomobject]@{failureClass=$class;detail=$detail;status='ACTIVE'}); if ([string]::IsNullOrWhiteSpace($primaryFailure)) { $script:primaryFailure = $class } }
function Gate([bool]$condition, [string]$name, [string]$failureClass, [string]$detail) { if ($condition) { Add-Gate $name 'PASS' $detail } else { Add-Failure $failureClass $detail; Add-Gate $name 'BLOCKED' $detail } }
function Get-Status([bool]$passed) { if ($passed) { return 'PASS' }; return 'BLOCKED' }
function Get-AuthorizationStatus([bool]$passed) { if ($passed) { return 'READY_FOR_SEPARATE_AUTHORITY' }; return 'NO' }
function Get-ErrorText([bool]$passed, $failureList) { if ($passed) { return 'No terminating error.' }; return ($failureList | ConvertTo-Json -Depth 10) }
function Invoke-NativeGate([string]$StageName, [string]$Executable, [string[]]$CommandArgs, [string]$WorkingDirectory, [string]$Expected) {
    $stageId = $StageName -replace '[^A-Za-z0-9_-]', '_'
    $stdoutPath = Join-Path $evidenceRoot ($stageId + '.stdout.log')
    $stderrPath = Join-Path $evidenceRoot ($stageId + '.stderr.log')
    $startUtc = (Get-Date).ToUniversalTime().ToString('o')
    $exitCode = 127
    $stdoutText = ''
    $stderrText = ''
    $missingExecutable = $false
    try {
        $commandInfo = Get-Command $Executable -ErrorAction SilentlyContinue
        if ($null -eq $commandInfo) { $missingExecutable = $true; $stderrText = 'Executable not found: ' + $Executable + [Environment]::NewLine }
        else { Push-Location $WorkingDirectory; try { & $Executable @CommandArgs 1> $stdoutPath 2> $stderrPath; $exitCode = $LASTEXITCODE } finally { Pop-Location }; if (Test-Path $stdoutPath) { $stdoutText = [IO.File]::ReadAllText($stdoutPath) }; if (Test-Path $stderrPath) { $stderrText = [IO.File]::ReadAllText($stderrPath) } }
    } catch { $stderrText = $_.Exception.ToString() + [Environment]::NewLine }
    if (-not (Test-Path $stdoutPath)) { Write-Artifact ($stageId + '.stdout.log') $stdoutText }
    if (-not (Test-Path $stderrPath)) { Write-Artifact ($stageId + '.stderr.log') $stderrText }
    $endUtc = (Get-Date).ToUniversalTime().ToString('o')
    $failureTokens = @('ParserError','Traceback','ELIFECYCLE','not recognized','Cannot find module','ERR_','FAILED','FAIL ')
    $foundFailures = @($failureTokens | Where-Object { $stdoutText.Contains($_) -or $stderrText.Contains($_) })
    $passed = (-not $missingExecutable -and $exitCode -eq 0 -and $foundFailures.Count -eq 0)
    $recordStatus=Get-Status $passed;$record = [pscustomobject]@{stage=$StageName;executable=$Executable;arguments=$CommandArgs;workingDirectory=$WorkingDirectory;startUtc=$startUtc;endUtc=$endUtc;exitCode=$exitCode;stdoutArtifact=($stageId + '.stdout.log');stderrArtifact=($stageId + '.stderr.log');expected=$Expected;failureTokens=$foundFailures;status=$recordStatus}
    [void]$stageResults.Add($record)
    if (-not $passed -and [string]::IsNullOrWhiteSpace($script:primaryFailure)) { Add-Failure 'APEX_PHASE8_EXACT_RESUME_MATRIX_STAGE_FAILED' ($StageName + ' exit=' + $exitCode) }
    return $record
}
function Invoke-ReadOnlyProbe([string]$StageName, [string]$Uri) {
    $startUtc=(Get-Date).ToUniversalTime().ToString('o');$statusCode=0;$body='';$errorText=''
    try { $response=Invoke-WebRequest -Uri $Uri -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop;$statusCode=[int]$response.StatusCode;$body=[string]$response.Content } catch { $errorText=$_.Exception.Message }
    $stageId=$StageName -replace '[^A-Za-z0-9_-]','_';Write-Artifact ($stageId+'.response.txt') ($body + [Environment]::NewLine + $errorText);$passed=($statusCode -ge 200 -and $statusCode -lt 300);$recordStatus=Get-Status $passed;$record=[pscustomobject]@{stage=$StageName;uri=$Uri;startUtc=$startUtc;endUtc=(Get-Date).ToUniversalTime().ToString('o');statusCode=$statusCode;responseArtifact=($stageId+'.response.txt');status=$recordStatus};[void]$stageResults.Add($record);if(-not $passed -and [string]::IsNullOrWhiteSpace($script:primaryFailure)){Add-Failure 'APEX_PHASE8_EXACT_RESUME_RUNTIME_HEALTH_UNAVAILABLE' ($StageName+' status='+$statusCode)};return $record
}

try {
    Initialize-Directory $evidenceRoot
    $artifactNames=@('00_RUN_METADATA.json','01_AUTHORITY_AND_SCOPE.txt','02_APEX_FAILURE_REGISTER_PROOF.json','03_PHASE8A_V101_PREDECESSOR_REVALIDATION.json','04_FROZEN_RELEASE_SOURCE_SET.json','05_ISOLATED_VALIDATION_SOURCE_IDENTITY.json','06_CONTROLLER_INPUT_CONTRACT_REPAIR.json','07_PS51_PARSER_PROOF.json','08_PRE_EXECUTION_HASH_PROOF.json','09_GREEN_MATRIX_DEFINITION.json','REGISTRATION_PRESERVATION.json','SUPERADMIN_ERP_REGRESSION.json','RUNTIME_CENSUS.json','RELEASE_SOURCE_PARITY.json','PHASE8_EXACT_RESUME.json','LOCAL_RELEASE_CANDIDATE.json','FINAL_STATUS.txt','AUTHORITY_CLOSEOUT_TOKEN.txt','EVIDENCE_MANIFEST.json','EVIDENCE_SHA256.txt','FINAL_REPORT.md','ERROR_LOG.txt','EXECUTION_LOG.txt','19_GATE_MATRIX.csv','20_FAILURE_LOG.json')
    foreach($artifact in $artifactNames){Write-Artifact $artifact ('NOT_STARTED' + [Environment]::NewLine)}
    Write-Artifact '01_AUTHORITY_AND_SCOPE.txt' ($authority + [Environment]::NewLine + 'PRODUCTION_DEPLOYMENT=NO' + [Environment]::NewLine + 'PRODUCTION_MUTATION=NO' + [Environment]::NewLine)
    Write-Artifact 'EXECUTION_LOG.txt' ('START=' + (Get-Date -Format o) + [Environment]::NewLine)
    $controllerHash=Get-Hash $PSCommandPath;$proofObject=$null;if(-not [string]::IsNullOrWhiteSpace($ParserPreflightProofPath) -and (Test-Path $ParserPreflightProofPath)){$proofObject=Get-Content -Raw -Encoding UTF8 $ParserPreflightProofPath|ConvertFrom-Json};$proofPass=($null -ne $proofObject -and [string]$proofObject.sha256 -eq $controllerHash -and [int]$proofObject.parserErrorCount -eq 0 -and [string]$proofObject.psVersion -like '5.1*');$proofStatus=Get-Status $proofPass;Write-Json '07_PS51_PARSER_PROOF.json' ([pscustomobject]@{proofPath=$ParserPreflightProofPath;controllerSha256=$controllerHash;proofSha256=[string]$proofObject.sha256;parserErrorCount=[int]$proofObject.parserErrorCount;psVersion=[string]$proofObject.psVersion;status=$proofStatus});Write-Json '08_PRE_EXECUTION_HASH_PROOF.json' ([pscustomobject]@{controllerSha256=$controllerHash;proofMatch=$proofPass;executionBytesHash=$controllerHash});Gate $proofPass 'PS51_PARSER_PREFLIGHT' 'APEX_PHASE8_EXACT_RESUME_PARSER_PROOF_INVALID' 'External exact-byte PS5.1 proof'
    $skillPath=Join-Path $workspaceRoot '.pma\skills\apex-ps1\SKILL.md';$skillHash=Get-Hash $skillPath;$registerPath=Join-Path $workspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md';$registerText=Get-Content -Raw -Encoding UTF8 $registerPath;$guardPass=($registerText -match 'APEX_PHASE8A_PHASE8_RESUME_WEAKENED_GATE' -and $registerText -match 'APEX_PHASE8_EXACT_RESUME_VALIDATION_SOURCE_DEPENDENCY_MISSING');Write-Json '02_APEX_FAILURE_REGISTER_PROOF.json' ([pscustomobject]@{skillPath=$skillPath;skillSha256=$skillHash;skillExpected=$skillExpected;skillPass=($skillHash -eq $skillExpected);registerPath=$registerPath;registerSha256=Get-Hash $registerPath;requiredGuardsPresent=$guardPass});Gate ($skillHash -eq $skillExpected) 'APEX_PS1_SKILL_LOAD' 'APEX_SKILL_UNVERIFIED' 'Repository skill hash';Gate $guardPass 'KNOWN_REGRESSION_GUARDS' 'APEX_PHASE8_EXACT_RESUME_GUARD_MISSING' 'Required exact-resume guards'
    if([string]::IsNullOrWhiteSpace($PredecessorRoot)){$candidate=Get-ChildItem $EvidenceBase -Directory|Where-Object{$_.Name -like 'watany-control-center-crm-phase8a-v101-final-freeze-*'}|Sort-Object LastWriteTime -Descending|Select-Object -First 1;$PredecessorRoot=[string]$candidate.FullName};$predZip=$PredecessorRoot+'.zip';$predSide=$predZip+'.final-reopen-validation.json';$predSideObject=Get-Content -Raw -Encoding UTF8 $predSide|ConvertFrom-Json;$predHash=Get-Hash $predZip;$predPass=($predSideObject.status -eq 'PASS' -and [string]$predSideObject.sha256 -eq $predHash -and $predSideObject.reopened -eq $true);Write-Json '03_PHASE8A_V101_PREDECESSOR_REVALIDATION.json' ([pscustomobject]@{root=$PredecessorRoot;zip=$predZip;zipSha256=$predHash;sidecarSha256=[string]$predSideObject.sha256;sidecarStatus=[string]$predSideObject.status;reopened=$predSideObject.reopened;pass=$predPass});Gate $predPass 'PHASE8A_V101_PREDECESSOR_REVALIDATION' 'APEX_PHASE8A_V101_PREDECESSOR_REVALIDATION' 'Sealed V1.0.1 predecessor'
    $sourceJson=Get-Content -Raw -Encoding UTF8 (Join-Path $PredecessorRoot '09_RELEASE_SOURCE_SET_FINAL.json')|ConvertFrom-Json;$source=@();if($sourceJson -is [array]){$source=@($sourceJson)}elseif($sourceJson.path -is [array]){for($sourceIndex=0;$sourceIndex -lt @($sourceJson.path).Count;$sourceIndex++){$source += [pscustomobject]@{path=[string]$sourceJson.path[$sourceIndex];sha256=[string]$sourceJson.sha256[$sourceIndex]}}}else{$source=@($sourceJson)};$sourceRows=@();foreach($entry in $source){$sourceRows += [pscustomobject]@{path=[string]$entry.path;expectedSha256=[string]$entry.sha256;actualSha256='';match=$false}};Write-Json '04_FROZEN_RELEASE_SOURCE_SET.json' ([pscustomobject]@{sourceCount=$source.Count;source=$source;manifestSha256=(Get-Content -Raw -Encoding UTF8 (Join-Path $PredecessorRoot '11_RELEASE_SOURCE_SET_FINAL.sha256')).Trim()})
    if([string]::IsNullOrWhiteSpace($ValidationRoot)){$validationIdentity=Get-Content -Raw -Encoding UTF8 (Join-Path $PredecessorRoot '14_VALIDATION_SOURCE_IDENTITY.json')|ConvertFrom-Json;$ValidationRoot=[string]$validationIdentity.root}else{$validationIdentity=Get-Content -Raw -Encoding UTF8 (Join-Path $PredecessorRoot '14_VALIDATION_SOURCE_IDENTITY.json')|ConvertFrom-Json};$sourcePass=(Test-Path $ValidationRoot -PathType Container);$actualRows=@();foreach($entry in $source){$candidatePath=Join-Path $ValidationRoot $entry.path;$actualHash=Get-Hash $candidatePath;$actualRows += [pscustomobject]@{path=$entry.path;expectedSha256=$entry.sha256;actualSha256=$actualHash;match=($actualHash -eq $entry.sha256)}};$sourcePass=($sourcePass -and @($actualRows|Where-Object{-not $_.match}).Count -eq 0 -and $validationIdentity.pass -eq $true);Write-Json '05_ISOLATED_VALIDATION_SOURCE_IDENTITY.json' ([pscustomobject]@{root=$ValidationRoot;baseCommit=$validationIdentity.baseCommit;predecessorIdentityPass=$validationIdentity.pass;sourceParity=$actualRows;pass=$sourcePass});Write-Json 'RELEASE_SOURCE_PARITY.json' $actualRows;Gate $sourcePass 'ISOLATED_VALIDATION_SOURCE_BYTE_PARITY' 'APEX_PHASE8A_RELEASE_VALIDATION_SOURCE_HASH_DRIFT' 'Frozen source bytes';Gate ($source.Count -eq 2) 'RELEASE_SOURCE_SET_CONSUMED' 'APEX_PHASE8A_RELEASE_SOURCE_SET_DRIFT' 'Exactly two frozen source paths'
    Write-Json '06_CONTROLLER_INPUT_CONTRACT_REPAIR.json' ([pscustomobject]@{existingPhase8Controller=(Join-Path $workspaceRoot 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE8_FULL_LOCAL_GREEN_MATRIX_AUTH_REGISTRATION_ISOLATION_SUPERADMIN_ERP_KB_GATEWAY_REGRESSION_AND_RELEASE_CANDIDATE_SEAL_V1_0_0.ps1');isolatedValidationRoot=$ValidationRoot;contract='V1.0.1 exact-resume controller executes repository-owned gates against frozen isolated source';canonicalWorktreeMutated=$false})
    $matrix=@([pscustomobject]@{name='GATEWAY_TYPECHECK';exe='pnpm.cmd';args=@('--dir','apps/gateway-api','typecheck');wd=$ValidationRoot;expected='exit 0'},[pscustomobject]@{name='GATEWAY_AUTH_RBAC_TESTS';exe='pnpm.cmd';args=@('--dir','apps/gateway-api','exec','vitest','run','src/tests/config-rag-path.test.ts','src/tests/admin-authority-negative-auth.test.ts','src/tests/auth-rbac.test.ts');wd=$ValidationRoot;expected='exit 0'},[pscustomobject]@{name='WEB_USER_TYPECHECK';exe='pnpm.cmd';args=@('--dir','apps/web-user','typecheck');wd=$ValidationRoot;expected='exit 0'},[pscustomobject]@{name='WEB_USER_BUILD';exe='pnpm.cmd';args=@('--dir','apps/web-user','build');wd=$ValidationRoot;expected='exit 0'},[pscustomobject]@{name='WEB_USER_TESTS';exe='pnpm.cmd';args=@('--dir','apps/web-user','exec','vitest','run');wd=$ValidationRoot;expected='exit 0'},[pscustomobject]@{name='API_AUTH_REGRESSION';exe='C:\xampp\htdocs\projectx\watanybot\.venv\Scripts\python.exe';args=@('-m','pytest','apps/api-backend/apps/api/tests/test_auth.py','-q');wd=$ValidationRoot;expected='exit 0'})
    Write-Json '09_GREEN_MATRIX_DEFINITION.json' ([pscustomobject]@{sourceRoot=$ValidationRoot;stages=$matrix;runtimeStages=@('PUBLIC_WATANYBOT_HEALTH','GATEWAY_HEALTH','ERPNEXT_READ_ONLY','REGISTRATION_PRESERVATION','SUPERADMIN_ERP_REGRESSION')})
    foreach($stage in $matrix){$result=Invoke-NativeGate $stage.name $stage.exe $stage.args $stage.wd $stage.expected;Add-Gate ($result.status -eq 'PASS') $stage.name 'APEX_PHASE8_EXACT_RESUME_MATRIX_STAGE_FAILED' ('exit=' + $result.exitCode)}
    $health8010=Invoke-ReadOnlyProbe 'GATEWAY_HEALTH' 'http://127.0.0.1:8010/health';$health18080=Invoke-ReadOnlyProbe 'ERPNEXT_READ_ONLY' 'http://127.0.0.1:18080/api/method/frappe.auth.get_logged_user';$health8080=Invoke-ReadOnlyProbe 'PUBLIC_WATANYBOT_HEALTH' 'http://127.0.0.1:8080/';Add-Gate ($health8010.status -eq 'PASS') 'GATEWAY_HEALTH' 'APEX_PHASE8_EXACT_RESUME_RUNTIME_HEALTH_UNAVAILABLE' 'Loopback gateway health';Add-Gate ($health18080.status -eq 'PASS') 'ERPNEXT_READ_ONLY' 'APEX_PHASE8_EXACT_RESUME_RUNTIME_HEALTH_UNAVAILABLE' 'Loopback ERPNext read-only probe';Add-Gate ($health8080.status -eq 'PASS') 'PUBLIC_WATANYBOT_HEALTH' 'APEX_PHASE8_EXACT_RESUME_RUNTIME_HEALTH_UNAVAILABLE' 'Public local health probe'
    $registrationPass=$false;$superadminPass=$false;Write-Json 'REGISTRATION_PRESERVATION.json' ([pscustomobject]@{status='BLOCKED';reason='Required runtime/auth matrix did not fully pass';dataMutation='NO'});Write-Json 'SUPERADMIN_ERP_REGRESSION.json' ([pscustomobject]@{status='BLOCKED';reason='Required Gateway/ERP runtime and canary proof unavailable';productionMutation='NO'});Write-Json 'RUNTIME_CENSUS.json' ([pscustomobject]@{gatewayHealth=$health8010.status;erpHealth=$health18080.status;publicHealth=$health8080.status;productionMutation='NO'});Gate $registrationPass 'REGISTRATION_PRESERVATION' 'APEX_PHASE8_EXACT_RESUME_REGISTRATION_UNPROVEN' 'Registration/auth preservation';Gate $superadminPass 'SUPERADMIN_ERP_REGRESSION' 'APEX_PHASE8_EXACT_RESUME_SUPERADMIN_ERP_UNPROVEN' 'Superadmin/ERP regression'
    $matrixPass=(@($stageResults|Where-Object{$_.status -ne 'PASS'}).Count -eq 0 -and $sourcePass);$resumePass=($matrixPass -and $registrationPass -and $superadminPass);$resumeStatus=Get-Status $resumePass;Write-Json 'PHASE8_EXACT_RESUME.json' ([pscustomobject]@{status=$resumeStatus;stageResults=$stageResults;sourceParity=$sourcePass;registrationPreservation=$registrationPass;superadminErp=$superadminPass});Write-Json 'LOCAL_RELEASE_CANDIDATE.json' ([pscustomobject]@{status=$resumeStatus;productionDeployment='NO';productionMutation='NO'});Gate $resumePass 'PHASE8_EXACT_RESUME' 'APEX_PHASE8_EXACT_RESUME_MATRIX_INCOMPLETE' 'Complete Green Matrix';Gate $resumePass 'LOCAL_RELEASE_CANDIDATE' 'APEX_PHASE8_EXACT_RESUME_MATRIX_INCOMPLETE' 'All local release gates'
    $statusText='FIRST_FAILED_GATE=' + $primaryFailure + [Environment]::NewLine + 'PHASE8_EXACT_RESUME=' + (if($resumePass){'PASS'}else{'BLOCKED'}) + [Environment]::NewLine + 'LOCAL_RELEASE_CANDIDATE=' + (if($resumePass){'PASS'}else{'BLOCKED'}) + [Environment]::NewLine + 'PRODUCTION_RELEASE_AUTHORIZATION=' + (if($resumePass){'READY_FOR_SEPARATE_AUTHORITY'}else{'NO'}) + [Environment]::NewLine + 'PRODUCTION_DEPLOYMENT=NO' + [Environment]::NewLine + 'PRODUCTION_MUTATION=NO' + [Environment]::NewLine + 'OVERALL_STATUS=' + (if($resumePass){'PASS'}else{'BLOCKED'}) + [Environment]::NewLine;Write-Artifact 'FINAL_STATUS.txt' $statusText;Write-Artifact 'AUTHORITY_CLOSEOUT_TOKEN.txt' $statusText;Write-Json '20_FAILURE_LOG.json' @($failures);$gateLines=@('gate,status,detail')+@($gates|ForEach-Object{'"{0}","{1}","{2}"' -f $_.gate,$_.status,([string]$_.detail -replace '"','""')});Write-Artifact '19_GATE_MATRIX.csv' (($gateLines -join [Environment]::NewLine)+[Environment]::NewLine);Write-Artifact 'FINAL_REPORT.md' ('# ' + $authority + [Environment]::NewLine + [Environment]::NewLine + $statusText + [Environment]::NewLine + 'No production or canonical-worktree mutation was performed.');Write-Artifact 'ERROR_LOG.txt' (if($resumePass){'No terminating error.'}else{($failures|ConvertTo-Json -Depth 10)})
    $manifest=@(Get-ChildItem $evidenceRoot -File|Sort-Object Name|ForEach-Object{[pscustomobject]@{name=$_.Name;sha256=Get-Hash $_.FullName;length=$_.Length}});Write-Json 'EVIDENCE_MANIFEST.json' $manifest;Write-Artifact 'EVIDENCE_SHA256.txt' (($manifest|ForEach-Object{$_.sha256 + '  ' + $_.name}) -join [Environment]::NewLine);Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem;$filesToZip=@(Get-ChildItem $evidenceRoot -File|Sort-Object Name);$archive=[IO.Compression.ZipFile]::Open($evidenceZip,[IO.Compression.ZipArchiveMode]::Create);try{foreach($file in $filesToZip){[IO.Compression.ZipFileExtensions]::CreateEntryFromFile($archive,$file.FullName,$file.Name)|Out-Null}}finally{$archive.Dispose()};$zipHash=Get-Hash $evidenceZip;$reopened=[IO.Compression.ZipFile]::OpenRead($evidenceZip);try{$entryCount=$reopened.Entries.Count;$names=@($reopened.Entries|ForEach-Object{$_.FullName})}finally{$reopened.Dispose()};$required=@('FINAL_STATUS.txt','AUTHORITY_CLOSEOUT_TOKEN.txt','PHASE8_EXACT_RESUME.json','LOCAL_RELEASE_CANDIDATE.json','19_GATE_MATRIX.csv');$missing=@($required|Where-Object{$_ -notin $names});$sidecar=[pscustomobject]@{status=if($missing.Count -eq 0){'PASS'}else{'BLOCKED'};reopened=$true;zip=$evidenceZip;sha256=$zipHash;entryCount=$entryCount;sourceArtifactCount=$filesToZip.Count;missingEntries=$missing};[IO.File]::WriteAllText($sidecarPath,(($sidecar|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Write-Output 'APEX_PS1_SKILL_UPDATE_NOT_REQUIRED';Write-Output ('EVIDENCE_ROOT=' + $evidenceRoot);Write-Output ('EVIDENCE_ZIP=' + $evidenceZip);Write-Output ('FINAL_SIDECAR=' + $sidecarPath);Write-Output ('PHASE8_EXACT_RESUME=' + (if($resumePass){'PASS'}else{'BLOCKED'}));Write-Output ('LOCAL_RELEASE_CANDIDATE=' + (if($resumePass){'PASS'}else{'BLOCKED'}));Write-Output ('PRODUCTION_RELEASE_AUTHORIZATION=' + (if($resumePass){'READY_FOR_SEPARATE_AUTHORITY'}else{'NO'}));Write-Output ('OVERALL_STATUS=' + (if($resumePass){'PASS'}else{'BLOCKED'}));if($resumePass){exit 0}else{exit 1}
} catch { try { Write-Artifact 'ERROR_LOG.txt' ($_.Exception.ToString() + [Environment]::NewLine);Write-Artifact 'FINAL_STATUS.txt' ('FIRST_FAILED_GATE=APEX_PHASE8_EXACT_RESUME_CONTROLLER_UNHANDLED_FAILURE' + [Environment]::NewLine + 'PHASE8_EXACT_RESUME=BLOCKED' + [Environment]::NewLine + 'OVERALL_STATUS=BLOCKED' + [Environment]::NewLine) } catch {};exit 1 }
