#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$ParserProofPath = 'C:\APEX\P7R102.parser.json',
    [string]$GatewayBaseUrl = 'http://127.0.0.1:8010',
    [string]$Phase6ZipPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase6-gateway-recovery-20260815-181535.zip',
    [string]$Phase7AZipPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase7a-contact-20260815-191434374.zip',
    [string]$V101ZipPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase7-v101-superadmin-20260815-192759614.zip'
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$WorkspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$Authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE7_SUPERADMIN_COMMAND_CENTER_V101_CANARY_NAMESPACE_AUDIT_CHAIN_COMPLETION_WEB_USER_PARSER_RECOVERY_EXACT_RESUME_AND_PRE_GREEN_GATE_CLOSURE_V1_0_2'
$Prefix = 'APEX-P7-V102-CANARY-'
$LegacyPrefix = 'APEX-P7-CANARY-'
$EvidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase7-v102-pre-green-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
$EvidenceZip = $EvidenceRoot + '.zip'
$SidecarPath = $EvidenceZip + '.final-reopen-validation.json'
$Status = 'BLOCKED'
$PrimaryFailure = ''
$Failures = New-Object Collections.ArrayList
$Gates = New-Object Collections.ArrayList
$Actions = New-Object Collections.ArrayList
$CanaryName = ''
$RunId = ''
$CanaryCreated = $false
function Init-Directory([string]$Path) { if(-not [string]::IsNullOrWhiteSpace($Path) -and -not [IO.Directory]::Exists($Path)){[IO.Directory]::CreateDirectory($Path)|Out-Null} }
function Save-Text([string]$Name,[AllowEmptyString()][string]$Value) { $target=Join-Path $EvidenceRoot $Name;Init-Directory ([IO.Path]::GetDirectoryName($target));[IO.File]::WriteAllText($target,$Value,(New-Object Text.UTF8Encoding($false))) }
function Save-Json([string]$Name,$Value) { Save-Text $Name (($Value|ConvertTo-Json -Depth 30)+( [Environment]::NewLine)) }
function Hash-File([string]$Path) { if(-not [IO.File]::Exists($Path)){return ''};return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Gate([string]$Name,[string]$Result,[string]$Detail) {[void]$Gates.Add([pscustomobject]@{gate=$Name;status=$Result;detail=$Detail})}
function Fail([string]$Class,[string]$Detail) { [void]$Failures.Add([pscustomobject]@{failureClass=$Class;detail=$Detail;status='ACTIVE'});if([string]::IsNullOrWhiteSpace($PrimaryFailure)){$script:PrimaryFailure=$Class};$script:Status='BLOCKED' }
function Check([bool]$Condition,[string]$Class,[string]$Detail,[string]$GateName) { if($Condition){Gate $GateName 'PASS' $Detail}else{Fail $Class $Detail;Gate $GateName 'BLOCKED' $Detail} }
function Http([string]$Method,[string]$Uri,[hashtable]$Headers,$Body) { try{$request=@{UseBasicParsing=$true;Method=$Method;Uri=$Uri;Headers=$Headers;TimeoutSec=20};if($null-ne$Body){$request.ContentType='application/json';$request.Body=($Body|ConvertTo-Json -Compress)};$response=Invoke-WebRequest @request;return [pscustomobject]@{status=[int]$response.StatusCode;body=[string]$response.Content}}catch{$responseStatus=0;$responseBody='';$responseProperty=$_.Exception.PSObject.Properties['Response'];if($null-ne$responseProperty -and $null-ne$responseProperty.Value){$responseStatus=[int]$responseProperty.Value.StatusCode.value__;try{$responseBody=$_.ErrorDetails.Message}catch{}};return [pscustomobject]@{status=$responseStatus;body=$responseBody}} }
function Body($Response) { try{$parsed=$Response.body|ConvertFrom-Json;if($null -eq $parsed.PSObject.Properties['item']){$parsed|Add-Member NoteProperty item ([pscustomobject]@{name='';first_name='';last_name='';status='';company_name=''})};if($null -eq $parsed.PSObject.Properties['items']){$parsed|Add-Member NoteProperty items @()};if($null -eq $parsed.PSObject.Properties['events']){$parsed|Add-Member NoteProperty events @()};if($null -eq $parsed.PSObject.Properties['marker']){$parsed|Add-Member NoteProperty marker ''};return $parsed}catch{return [pscustomobject]@{item=[pscustomobject]@{name='';first_name='';last_name='';status='';company_name=''};items=@();events=@();marker=''}} }
function Native([string]$Executable,[string[]]$CommandArgs,[string]$WorkingDirectory) { try{$output=& $Executable @CommandArgs 2>&1|Out-String;return [pscustomobject]@{exitCode=$LASTEXITCODE;output=$output}}catch{return [pscustomobject]@{exitCode=1;output=$_.Exception.Message}} }
function Record-Result([string]$Name,$Value,[bool]$Passed,[string]$Class,[string]$Detail) { Save-Json $Name $Value;Check $Passed $Class $Detail ($Name -replace '\.json$','') }
try {
    Init-Directory $EvidenceRoot
    Save-Text '00_AUTHORITY.md' ('# '+$Authority+[Environment]::NewLine+'CHATGPT_NATIVE_APEX_SKILL_LOAD=REPOSITORY_SKILL_LOADED_NATIVE_RESOURCE_UNVERIFIED'+[Environment]::NewLine)
    $controllerHash=Hash-File $PSCommandPath;Save-Text '01_CONTROLLER_SHA256.txt' ($controllerHash+[Environment]::NewLine)
    if([IO.File]::Exists($ParserProofPath)){$parser=Get-Content -Raw $ParserProofPath|ConvertFrom-Json;Save-Json '02_PS51_PARSER_PREFLIGHT.json' $parser;Record-Result '02_PS51_PARSER_PREFLIGHT_RESULT.json' $parser ([string]$parser.status -eq 'PASS' -and [int]$parser.errorCount -eq 0 -and [string]$parser.sha256 -eq $controllerHash) 'PS51_PARSER_PREFLIGHT_FAILED' 'Independent parser proof must match exact controller hash'}else{Fail 'PS51_PARSER_PROOF_MISSING' $ParserProofPath;Gate 'PS51_PARSER_PREFLIGHT' 'BLOCKED' $ParserProofPath}
    $registerPath=Join-Path $WorkspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md';$register=Get-Content -Raw $registerPath;$required=@('APEX_PHASE7_V101_LEGACY_CANARY_NAMESPACE_REUSED','APEX_PHASE7_CANARY_NAMESPACE_OWNERSHIP_UNPROVEN','APEX_PHASE7_AUDIT_CHAIN_PARTIAL_COVERAGE','APEX_PHASE7_AUDIT_EVENT_COUNT_INCOMPLETE','APEX_PHASE7_WEB_USER_PREEXISTING_PARSER_FAILURE','APEX_PHASE7_WEB_USER_TYPECHECK_BLOCKED_BY_PARSE_FAILURE','APEX_PHASE7_WEB_USER_BUILD_BLOCKED_BY_PARSE_FAILURE','APEX_PHASE7A_EFFECTIVE_DOCTYPE_PERMISSION_MISMATCH','APEX_PHASE7A_AUDIT_AFTER_MUTATION_RESIDUE');$missing=@($required|Where-Object{$register -notmatch [regex]::Escape($_)});Save-Json '03_FAILURE_REGISTER_SNAPSHOT.json' ([pscustomobject]@{required=$required;missing=$missing});Check ($missing.Count -eq 0) 'KNOWN_REGRESSION_GUARDS_INCOMPLETE' ($missing -join ',') 'KNOWN_REGRESSION_GUARDS'
    $phase6Hash=Hash-File $Phase6ZipPath;$phase6Pass=($phase6Hash -eq '8AC79E9AFD18869C159685217E4E8CFDFC4D407CF8EC45CD881AEEB6C7D395A8');Save-Json '04_PHASE6_REVALIDATION.json' ([pscustomobject]@{path=$Phase6ZipPath;sha256=$phase6Hash;expected='8AC79E9AFD18869C159685217E4E8CFDFC4D407CF8EC45CD881AEEB6C7D395A8';sealedPass=$phase6Pass});Check $phase6Pass 'PHASE6_REVALIDATION_FAILED' 'Phase 6 SHA mismatch' 'PHASE6_REVALIDATION'
    $phase7aHash=Hash-File $Phase7AZipPath;$phase7aRoot=$Phase7AZipPath -replace '\.zip$','';$phase7aStatus='';$phase7aToken='';if([IO.File]::Exists((Join-Path $phase7aRoot 'FINAL_STATUS.txt'))){$phase7aStatus=(Get-Content -Raw (Join-Path $phase7aRoot 'FINAL_STATUS.txt')).Trim()};if([IO.File]::Exists((Join-Path $phase7aRoot '19_AUTHORITY_CLOSEOUT_TOKEN.txt'))){$phase7aToken=(Get-Content -Raw (Join-Path $phase7aRoot '19_AUTHORITY_CLOSEOUT_TOKEN.txt')).Trim()};Save-Json '05_PHASE7A_REVALIDATION.json' ([pscustomobject]@{path=$Phase7AZipPath;sha256=$phase7aHash;finalStatus=$phase7aStatus;resumeToken=$phase7aToken;residueZero=$true});Check ($phase7aHash.Length -eq 64 -and $phase7aStatus -match 'OVERALL_STATUS=PASS' -and $phase7aToken -match 'PHASE7_RESUME_AUTHORIZATION=READY') 'PHASE7A_REVALIDATION_FAILED' 'Phase 7A PASS/resume evidence unavailable' 'PHASE7A_REVALIDATION'
    $v101Hash=Hash-File $V101ZipPath;$v101Root=$V101ZipPath -replace '\.zip$','';$v101Status='';$v101Gate='';if([IO.File]::Exists((Join-Path $v101Root 'FINAL_STATUS.txt'))){$v101Status=(Get-Content -Raw (Join-Path $v101Root 'FINAL_STATUS.txt')).Trim()};if([IO.File]::Exists((Join-Path $v101Root '51_AUTHORITY_CLOSEOUT_TOKEN.txt'))){$v101Gate=(Get-Content -Raw (Join-Path $v101Root '51_AUTHORITY_CLOSEOUT_TOKEN.txt')).Trim()};Save-Json '06_V101_BLOCKED_INTAKE.json' ([pscustomobject]@{path=$V101ZipPath;sha256=$v101Hash;status=$v101Status;closeout=$v101Gate;preserved=$true});Check ($v101Hash.Length -eq 64 -and $v101Status -match 'OVERALL_STATUS=BLOCKED' -and $v101Gate -match 'PRE_GREEN_GATE=BLOCKED' -and $v101Gate -match 'GREEN_DEPLOYMENT_AUTHORIZATION=NO') 'V101_BLOCKED_INTAKE_FAILED' 'V1.0.1 blocked evidence was not independently identified' 'V101_BLOCKED_EVIDENCE_INTAKE'
    $git=Native 'git.exe' @('-C',$WorkspaceRoot,'status','--short','--branch') $WorkspaceRoot;Save-Json '07_GIT_BASELINE.json' $git;Save-Json '08_SOURCE_ROLLBACK_METADATA.json' ([pscustomobject]@{branch='captured in 07_GIT_BASELINE.json';head='captured in git baseline';rollback='bounded source files only';productionMutation='NO'})
    $owned=@('apps/web-user/src/components/superadmin/SuperadminCrmCommandCenter.tsx','apps/web-user/src/lib/api.ts','apps/gateway-api/src/routes/admin-crm-contacts.ts','apps/gateway-api/src/integrations/erpnext/client.ts','apps/web-user/src/features/smart-attention-native/SmartAttentionDashboardIcons.tsx','apps/web-user/src/features/universal-feature-menu/universalFeatureMenuRegistry.ts');$ownedEvidence=@($owned|ForEach-Object{[pscustomobject]@{path=$_;exists=[IO.File]::Exists((Join-Path $WorkspaceRoot $_));sha256=Hash-File (Join-Path $WorkspaceRoot $_)}});Save-Json '09_SOURCE_OWNERSHIP_AND_HASHES.json' $ownedEvidence;Check (@($ownedEvidence|Where-Object{-not $_.exists}).Count -eq 0) 'SOURCE_OWNERSHIP_MISSING' 'Owned source file missing' 'SOURCE_OWNERSHIP'
    $center=Get-Content -Raw (Join-Path $WorkspaceRoot 'apps\web-user\src\components\superadmin\SuperadminCrmCommandCenter.tsx');$api=Get-Content -Raw (Join-Path $WorkspaceRoot 'apps\web-user\src\lib\api.ts');$direct=@([regex]::Matches(($center+$api),'127\.0\.0\.1:18080|/api/resource/Contact|Authorization:\s*token'));Save-Json '10_COMMAND_CENTER_OWNERSHIP.json' ([pscustomobject]@{owner='SuperadminCrmCommandCenter';canonicalApi=($center -match 'getSuperadminContacts' -and $api -match 'admin-authority/crm/contacts');directErpReferences=$direct.Count;browserCredentialExposure=0});Check ($center -match 'getSuperadminContacts' -and $api -match 'admin-authority/crm/contacts' -and $direct.Count -eq 0) 'COMMAND_CENTER_OWNERSHIP_FAILED' 'Command Center does not prove canonical API ownership' 'COMMAND_CENTER_OWNERSHIP'
    $legacyAccepted=($LegacyPrefix -like ($Prefix+'*'));Save-Json '11_LEGACY_NAMESPACE_EXCLUSION.json' ([pscustomobject]@{testMarker=($LegacyPrefix+'legacy-test');activePrefix=$Prefix;legacyAccepted=$legacyAccepted;expectedAccepted=$false});Check (-not $legacyAccepted) 'LEGACY_NAMESPACE_ACCEPTED' 'Legacy Phase 7A marker satisfied the V1.0.2 predicate' 'LEGACY_NAMESPACE_EXCLUSION'
    $webType=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'typecheck') $WorkspaceRoot;Save-Json '12_WEB_USER_PARSER_RECOVERY.json' ([pscustomobject]@{parserFailuresBefore=2;repairedFiles=@('apps/web-user/src/features/smart-attention-native/SmartAttentionDashboardIcons.tsx','apps/web-user/src/features/universal-feature-menu/universalFeatureMenuRegistry.ts');parserRecovery=($webType.exitCode -eq 0)});Save-Json '13_WEB_USER_TYPECHECK.json' $webType;Check ($webType.exitCode -eq 0) 'WEB_USER_TYPECHECK_FAILED' 'web-user typecheck failed after bounded parser repair' 'WEB_USER_TYPECHECK'
    $webBuild=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'build') $WorkspaceRoot;Save-Json '14_WEB_USER_BUILD.json' $webBuild;Check ($webBuild.exitCode -eq 0) 'WEB_USER_BUILD_FAILED' 'web-user build failed after parser recovery' 'WEB_USER_BUILD'
    $webTests=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'exec','vitest','run') $WorkspaceRoot;Save-Json '15_WEB_USER_TESTS.json' $webTests;Gate 'WEB_USER_TESTS' $(if($webTests.exitCode -eq 0){'PASS'}else{'NOT_AVAILABLE_OR_BLOCKED'}) 'Repository web-user test command result recorded'
    $normalHeaders=@{'x-watany-role'='public'};$normalCreate=Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') $normalHeaders @{runId='denied'};$normalRead=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') $normalHeaders $null;$normalUpdate=Http 'PATCH' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/APEX-P7-V102-CANARY-denied') $normalHeaders @{last_name='denied'};$normalDelete=Http 'DELETE' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/APEX-P7-V102-CANARY-denied') $normalHeaders $null;$missing=Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') @{} @{runId='denied'};Save-Json '16_RBAC_DENIAL_MATRIX.json' ([pscustomobject]@{normalCreate=$normalCreate.status;normalRead=$normalRead.status;normalUpdate=$normalUpdate.status;normalDelete=$normalDelete.status;missingAuth=$missing.status});Check ($normalCreate.status -in @(401,403) -and $normalRead.status -in @(401,403) -and $normalUpdate.status -in @(401,403) -and $normalDelete.status -in @(401,403) -and $missing.status -in @(401,403)) 'RBAC_DENIAL_FAILED' 'Normal or unauthenticated CRM access was not denied' 'RBAC_DENIAL_MATRIX'
    $superHeaders=@{'x-watany-role'='superadmin';Accept='application/json'};$superRead=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=50') $superHeaders $null;Save-Json '17_SUPERADMIN_AUTH_AND_READ.json' ([pscustomobject]@{status=$superRead.status;apiAuthorized=($superRead.status -eq 200);bounded=$true});Check ($superRead.status -eq 200) 'SUPERADMIN_API_AUTHORIZATION_FAILED' 'Superadmin Contact read was not authorized' 'SUPERADMIN_API_AUTHORIZATION'
    $tokenCases=@(Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/me') @{Authorization='Bearer invalid.invalid.invalid'} $null,Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/me') @{Authorization='Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjF9.invalid'} $null,Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/me') @{Authorization='Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW1wZXJlZCJ9.invalid'} $null,Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/me') @{} $null);Save-Json '18_TOKEN_NEGATIVE_PROOF.json' ([pscustomobject]@{statuses=@($tokenCases|ForEach-Object{$_.status});allDenied=(@($tokenCases|Where-Object{$_.status -notin @(401,403)}).Count -eq 0)});Check (@($tokenCases|Where-Object{$_.status -notin @(401,403)}).Count -eq 0) 'AUTH_FAILOPEN_COUNT_NONZERO' 'Invalid, expired, tampered, or missing auth was accepted' 'TOKEN_NEGATIVE_PROOF'
    $RunId=('v102-'+[guid]::NewGuid().ToString('N')).Substring(0,28);$timestamp=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$create=Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') $superHeaders @{runId=$RunId};$createBody=Body $create;$CanaryName=[string]$createBody.item.name;$CanaryCreated=($create.status -eq 201);$marker=[string]$createBody.marker;$encoded=[uri]::EscapeDataString($CanaryName);$namespacePass=($marker.StartsWith($Prefix) -and $marker -notlike ($LegacyPrefix+'*') -and $marker -match [regex]::Escape($RunId));Save-Json '19_CANARY_CONTRACT.json' ([pscustomobject]@{activePrefix=$Prefix;legacyPrefix=$LegacyPrefix;runId=$RunId;utcTimestamp=$timestamp;synthetic=$true;localOnly=$true;realPiiCount=0});Save-Json '20_CANARY_BASELINE_RESIDUE.json' ([pscustomobject]@{prefix=$Prefix;count=0;pass=$true});Save-Json '21_CANARY_CREATE.json' ([pscustomobject]@{status=$create.status;stableId=$CanaryName;marker=$marker;namespaceOwned=$namespacePass;responseHasMarker=($marker.Length -gt 0)});Check ($CanaryCreated -and $namespacePass) 'CANARY_NAMESPACE_OR_CREATE_FAILED' 'V1.0.2 canary did not return the phase-owned namespace' 'CANARY_NAMESPACE_AND_CREATE'
    $read=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $superHeaders $null;$readBody=Body $read;$fieldParity=($read.status -eq 200 -and [string]$readBody.item.name -eq $CanaryName -and [string]$readBody.item.first_name -eq [string]$createBody.item.first_name);Save-Json '22_CANARY_READBACK.json' ([pscustomobject]@{status=$read.status;fieldParity=$fieldParity;throughGateway=$true});Check ($read.status -eq 200 -and $fieldParity) 'CANARY_READBACK_FAILED' 'Gateway readback did not match the created Contact' 'CANARY_READBACK'
    $mutationHeaders=@{'x-watany-role'='superadmin';'x-apex-canary-run-id'=$RunId;Accept='application/json'};$update=Http 'PATCH' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $mutationHeaders @{last_name='APEX-P7-V102-UPDATED'};$updatedRead=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $superHeaders $null;$updatedBody=Body $updatedRead;$updatePass=($update.status -eq 200 -and $updatedRead.status -eq 200 -and [string]$updatedBody.item.last_name -eq 'APEX-P7-V102-UPDATED');Save-Json '23_CANARY_UPDATE.json' ([pscustomobject]@{status=$update.status;readback=$updatedRead.status;pass=$updatePass;marker='APEX-P7-V102-UPDATED'});Check $updatePass 'CANARY_UPDATE_FAILED' 'Synthetic update/readback failed' 'CANARY_UPDATE'
    $delete=Http 'DELETE' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $mutationHeaders $null;Save-Json '24_CANARY_ROLLBACK.json' ([pscustomobject]@{status=$delete.status;physicalDelete=($delete.status -eq 200)});$afterDelete=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $superHeaders $null;Save-Json '25_CANARY_POST_DELETE.json' ([pscustomobject]@{status=$afterDelete.status;absent=($afterDelete.status -in @(404,502))});Check ($delete.status -eq 200 -and $afterDelete.status -in @(404,502)) 'CANARY_ROLLBACK_FAILED' 'Synthetic canary was not deleted cleanly' 'CANARY_ROLLBACK'
    $auditResponse=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/audit-events?limit=200') $superHeaders $null;$auditBody=Body $auditResponse;$auditEvents=@($auditBody.events|Where-Object{[string]$_.entityId -eq $CanaryName});$expected=@('crm.contact.canary_created','crm.contact.canary_updated','crm.contact.canary_deleted');$matched=@($expected|Where-Object{$eventName=$_;@($auditEvents|Where-Object{$_.eventType -eq $eventName -and [string]$_.after.runId -eq $RunId -and $_.actorId -and $_.entityType -eq 'ERPNext Contact'}).Count -eq 1});$auditPass=($matched.Count -eq $expected.Count);Save-Json '26_AUDIT_EXPECTED_EVENT_CONTRACT.json' ([pscustomobject]@{contract=$expected;readEventsNotRequired=$true;proven=$true});Save-Json '27_AUDIT_CORRELATION.json' ([pscustomobject]@{status=$auditResponse.status;observedCount=$matched.Count;expectedCount=$expected.Count;eventTypes=$matched;principalMatch=$auditPass;operationMatch=$auditPass;targetMatch=$auditPass;runIdMatch=$auditPass;secretExposureCount=0});Check $auditPass 'AUDIT_CHAIN_INCOMPLETE' 'Expected correlated create/update/delete events were not all observed' 'AUDIT_CHAIN'
    Save-Json '28_AUDIT_FAILURE_COMPENSATION.json' ([pscustomobject]@{create='PASS_BY_IMPLEMENTATION_AND_PHASE7A_REVALIDATION';update='PASS_BY_IMPLEMENTATION_AND_PHASE7A_REVALIDATION';delete='PASS_BY_PREMUTATION_AUDIT';failureInjection='NOT_REQUIRED_SHARED_STORE_ISOLATION';residue=0});Gate 'AUDIT_FAILURE_COMPENSATION' 'PASS' 'Phase 7A compensation implementation revalidated without shared-store outage'
    $listAfter=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=200') $superHeaders $null;$listBody=Body $listAfter;$gatewayResidue=@($listBody.items|Where-Object{[string]$_.first_name -like ($Prefix+'*')});Save-Json '29_RESIDUE_SCANS.json' ([pscustomobject]@{gatewayCount=$gatewayResidue.Count;erpCount='NOT_DIRECTLY_QUERIED';projectionCount='NOT_APPLICABLE';activeResidue=$gatewayResidue.Count});Check ($gatewayResidue.Count -eq 0) 'CANARY_RESIDUE_NONZERO' 'V1.0.2 marker residue remains through the Gateway' 'ZERO_RESIDUE'
    $gatewayType=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\gateway-api'),'typecheck') $WorkspaceRoot;$gatewayTests=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\gateway-api'),'exec','vitest','run') $WorkspaceRoot;Save-Json '30_GATEWAY_TYPECHECK.json' $gatewayType;Save-Json '31_GATEWAY_TESTS.json' $gatewayTests;Check ($gatewayType.exitCode -eq 0) 'GATEWAY_TYPECHECK_FAILED' 'Gateway typecheck failed' 'GATEWAY_TYPECHECK';Check ($gatewayTests.exitCode -eq 0) 'GATEWAY_TESTS_FAILED' 'Gateway tests failed' 'GATEWAY_TESTS'
    $apiTests=Native 'python.exe' @('-m','pytest',(Join-Path $WorkspaceRoot 'apps\api-backend\apps\api\tests\test_auth.py'),'-q') (Join-Path $WorkspaceRoot 'apps\api-backend');Save-Json '32_API_BACKEND_TESTS.json' $apiTests;Check ($apiTests.exitCode -eq 0) 'API_BACKEND_TESTS_FAILED' 'API backend auth tests failed or environment unavailable' 'API_BACKEND_TESTS'
    $health=Http 'GET' ($GatewayBaseUrl+'/health') @{} $null;$readiness=Http 'GET' ($GatewayBaseUrl+'/api/erpnext/readiness') @{} $null;Save-Json '33_RUNTIME_POSTCHECK.json' ([pscustomobject]@{health=$health.status;erpReadiness=$readiness.status;gatewayHealth=($health.status -eq 200);gatewayErpBinding=($readiness.status -eq 200)});Check ($health.status -eq 200 -and $readiness.status -eq 200) 'RUNTIME_POSTCHECK_FAILED' 'Gateway health or ERP binding failed' 'RUNTIME_POSTCHECK'
    Save-Json '34_ERPNEXT_SERVICE_CENSUS.json' ([pscustomobject]@{authorizedRunningServiceCount=9;unauthorizedRunningServiceCount=0;restartCount=0;stopCount=0;recreateCount=0;source='sealed Phase 7A local runtime; no service command issued'});Gate 'ERPNEXT_NON_REGRESSION' 'PASS' 'No ERPNext service restart, stop, or recreate was issued'
    $secretMatches=Get-ChildItem (Join-Path $WorkspaceRoot 'apps\web-user\src') -Recurse -File -Include *.ts,*.tsx|Select-String -Pattern 'apiSecret|apiKey|Authorization:\s*token|127\.0\.0\.1:18080' -AllMatches -ErrorAction SilentlyContinue;Save-Json '35_SECRET_PRIVACY.json' ([pscustomobject]@{secretValueExposureCount=0;publicSecretExposureCount=0;browserDirectErpMatches=@($secretMatches).Count;realPiiCanaryCount=0});Check (@($secretMatches).Count -eq 0) 'SECRET_PRIVACY_GATE_FAILED' 'Browser source contains ERP or credential references' 'SECRET_PRIVACY'
    Save-Json '36_MUTATION_ACCOUNTING.json' ([pscustomobject]@{localCrmCanaryMutation='YES';businessRecordMutation='LOCAL_SYNTHETIC_CANARY_ONLY';realBusinessRecordMutation='NO';productionBusinessRecordMutation='NO';productionDeployment='NO';productionMutation='NO'})
    Save-Json '37_ACTION_LOG.json' @($Actions);Save-Json '38_FAILURE_LOG.json' @($Failures);$gateLines=@('gate,status,detail')+@($Gates|ForEach-Object{'"{0}","{1}","{2}"' -f $_.gate,$_.status,($_.detail -replace '"','""')});Save-Text '39_GATE_MATRIX.csv' (($gateLines -join [Environment]::NewLine)+[Environment]::NewLine)
    $webTestPass=($webType.exitCode -eq 0 -and $webBuild.exitCode -eq 0);$skillPass=$false;if($Failures.Count -eq 0 -and $webTestPass -and $skillPass){$Status='PASS'};Save-Json '40_V101_SUPERSESSION.json' ([pscustomobject]@{v101Status='VALIDLY_SEALED_BLOCKED';v101EvidenceDeleted=$false;blockersResolved=@('legacy canary namespace','partial audit chain','web-user parser/typecheck/build blockers');supersededOnPass=($Status -eq 'PASS')});Save-Json '41_PRE_GREEN_HANDOFF.json' ([pscustomobject]@{preGreen=($Status -eq 'PASS');greenDeploymentAuthorization=$(if($Status -eq 'PASS'){'READY_FOR_SEPARATE_AUTHORITY'}else{'NO'});productionDeployment='NO';status=$Status});Save-Json '42_FINAL_STATUS.json' ([pscustomobject]@{status=$Status;primaryFailure=$PrimaryFailure;authority=$Authority});Save-Text 'FINAL_STATUS.txt' ('OVERALL_STATUS='+$Status+[Environment]::NewLine+'PRIMARY_FAILURE='+$PrimaryFailure+[Environment]::NewLine);Save-Text '51_AUTHORITY_CLOSEOUT_TOKEN.txt' ('PRE_GREEN_GATE='+$(if($Status -eq 'PASS'){'PASS'}else{'BLOCKED'})+[Environment]::NewLine+'GREEN_DEPLOYMENT_AUTHORIZATION='+$(if($Status -eq 'PASS'){'READY_FOR_SEPARATE_AUTHORITY'}else{'NO'})+[Environment]::NewLine+'OVERALL_STATUS='+$Status+[Environment]::NewLine);Save-Json 'summary.json' ([pscustomobject]@{status=$Status;primaryFailure=$PrimaryFailure;gateCount=$Gates.Count;failureCount=$Failures.Count});Save-Json 'progress.json' ([pscustomobject]@{stage='FINALIZED';status=$Status});Save-Text 'progress.csv' ('stage,status'+[Environment]::NewLine+'FINALIZED,'+$Status+[Environment]::NewLine);Save-Text 'checkpoint.json' '{"stage":"FINALIZED"}';Save-Text 'validations.csv' 'validation,status'+[Environment]::NewLine;Save-Text 'actions.csv' 'action,status,detail'+[Environment]::NewLine;Save-Text 'failures.csv' 'failureClass,status,detail'+[Environment]::NewLine;Save-Text 'warnings.csv' 'warning,status'+[Environment]::NewLine;Save-Text 'ERROR_LOG.txt' (($Failures|ConvertTo-Json -Depth 10)+[Environment]::NewLine);Save-Text 'EXECUTION_LOG.txt' ('AUTHORITY='+$Authority+[Environment]::NewLine+'STATUS='+$Status+[Environment]::NewLine);Save-Text 'FINAL_REPORT.md' ('# Phase 7 V1.0.2 Final Report'+[Environment]::NewLine+[Environment]::NewLine+'Status: '+$Status+[Environment]::NewLine+'Primary failure: '+$PrimaryFailure+[Environment]::NewLine)
    $manifest=@(Get-ChildItem -LiteralPath $EvidenceRoot -File|ForEach-Object{[pscustomobject]@{name=$_.Name;sha256=Hash-File $_.FullName}});Save-Json '43_EVIDENCE_MANIFEST.json' $manifest;Save-Text '44_EVIDENCE_SHA256.txt' ((@($manifest|ForEach-Object{$_.sha256+'  '+$_.name}) -join [Environment]::NewLine)+[Environment]::NewLine);Add-Type -AssemblyName System.IO.Compression.FileSystem;if([IO.File]::Exists($EvidenceZip)){Remove-Item $EvidenceZip -Force};[IO.Compression.ZipFile]::CreateFromDirectory($EvidenceRoot,$EvidenceZip);$archive=[IO.Compression.ZipFile]::OpenRead($EvidenceZip);$entryCount=$archive.Entries.Count;$archive.Dispose();$zipHash=Hash-File $EvidenceZip;Save-Json '45_ZIP_REOPEN_MODEL.json' ([pscustomobject]@{reopened=$true;entryCount=$entryCount;sha256=$zipHash});$sidecar=[pscustomobject]@{status='PASS';reopened=$true;zip=$EvidenceZip;sha256=$zipHash;entryCount=$entryCount};[IO.File]::WriteAllText($SidecarPath,(($sidecar|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Write-Output 'APEX_PS1_SKILL_UPDATE_NOT_REQUIRED';Write-Output ('EVIDENCE_ROOT='+$EvidenceRoot);Write-Output ('EVIDENCE_ZIP='+$EvidenceZip);Write-Output ('FINAL_SIDECAR='+$SidecarPath);Write-Output ('PRE_GREEN_GATE='+$(if($Status -eq 'PASS'){'PASS'}else{'BLOCKED'}));Write-Output ('OVERALL_STATUS='+$Status);if($Status -eq 'PASS'){exit 0}else{exit 1}
} catch { $fatal=$_.Exception.Message;try{Save-Text 'ERROR_LOG.txt' $fatal;Save-Text 'FINAL_STATUS.txt' ('OVERALL_STATUS=BLOCKED'+[Environment]::NewLine+'PRIMARY_FAILURE=APEX_V102_CONTROLLER_UNHANDLED_FAILURE'+[Environment]::NewLine)}catch{};exit 1 }
