#requires -Version 5.1
[CmdletBinding()]
param([string]$EvidenceBase='C:\Users\User\Documents\WatanyBot-APEX-Evidence',[string]$ParserPreflightProofPath='C:\APEX\P5V100.parser.json')
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$Authority='APEX_WATANY_CONTROL_CENTER_STAGE_X_ERPNEXT_PHASE5_FRONTEND_WEBSOCKET_LOOPBACK_RUNTIME_RECOVERY_SITE_ROUTING_REALTIME_READ_ONLY_PROOF_AND_FULL_ERPNEXT_LOCAL_RUNTIME_SEAL_V1_0_0'
$Root='C:\xampp\htdocs\projectx\watany-control-center\erpnext\frappe_docker'; $Compose=Join-Path $Root 'pwd.yml'; $Override=Join-Path $Root 'watany.integration.frontend-websocket-loopback.yml'; $Project='frappe_docker'; $Image='frappe/erpnext:v16.32.0'; $Network='frappe_docker_frappe_network'; $Expected=@('db','redis-cache','redis-queue','backend','queue-short','queue-long','scheduler','frontend','websocket'); $Preserved=@('db','redis-cache','redis-queue','backend','queue-short','queue-long','scheduler')
$EvidenceRoot=''; $Zip=''; $Sidecar=''; $Failures=New-Object Collections.ArrayList; $Gates=New-Object Collections.ArrayList; $Actions=New-Object Collections.ArrayList
function Init([string]$p){if(-not [IO.Directory]::Exists($p)){[void][IO.Directory]::CreateDirectory($p)}}
function Text([string]$n,[AllowEmptyString()][string]$v){$p=Join-Path $EvidenceRoot $n;Init ([IO.Path]::GetDirectoryName($p));[IO.File]::WriteAllText($p,$v,(New-Object Text.UTF8Encoding($false)))}
function Json([string]$n,$v){Text $n (($v|ConvertTo-Json -Depth 20)+[Environment]::NewLine)}
function Sha([string]$p){$h=[Security.Cryptography.SHA256]::Create();$s=[IO.File]::OpenRead($p);try{return ([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','').ToUpperInvariant()}finally{$s.Dispose();$h.Dispose()}}
function Native([string]$e,[string[]]$a,[string]$label,[switch]$Progress){$err=Join-Path $env:TEMP ('p5-'+[guid]::NewGuid().ToString('N')+'.err');try{$o=@(& $e @a 2>$err);$c=$LASTEXITCODE;$s=($o|ForEach-Object{[string]$_})-join [Environment]::NewLine;$r='';if([IO.File]::Exists($err)){$r=[IO.File]::ReadAllText($err)};[void]$Actions.Add([pscustomobject]@{Action=$label;ExitCode=$c});if($c-ne 0){throw ('APEX_NATIVE_FAILED:{0}:{1}' -f $label,$c)};if((-not $Progress)-and $r -match '(?i)error|fatal|failed|exception'){throw ('APEX_NATIVE_STDERR:{0}' -f $label)};return [pscustomobject]@{Stdout=$s;Stderr=$r;ExitCode=$c}}finally{if(Test-Path $err){Remove-Item $err -Force -ErrorAction SilentlyContinue}}}
function Inspect([string]$id){@(Native $docker @('inspect',$id) 'INSPECT').Stdout|ConvertFrom-Json|Select-Object -First 1}
function Service([object]$i){[string]$i.Config.Labels.'com.docker.compose.service'}
function State([object]$i){[string]$i.State.Status}
function Rows(){ $r=Native $docker @('ps','--filter','label=com.docker.compose.project=frappe_docker','--format','{{.ID}}') 'CENSUS';$out=foreach($id in @($r.Stdout -split '\r?\n'|Where-Object{$_.Trim()})){ $i=Inspect $id;$networkNames=@($i.NetworkSettings.Networks.PSObject.Properties|Select-Object -ExpandProperty Name);$portNames=@($i.NetworkSettings.Ports.PSObject.Properties|Select-Object -ExpandProperty Name);[pscustomobject]@{Container=$i.Name.TrimStart('/');Service=(Service $i);Image=[string]$i.Config.Image;State=(State $i);RestartCount=[int]$i.RestartCount;Networks=($networkNames-join '|');Ports=($portNames-join '|')}};return @($out)}
function Stable([string]$svc){$ids=@((Native $docker @('ps','-aq','--filter',"label=com.docker.compose.service=$svc",'--filter','label=com.docker.compose.project=frappe_docker') "IDS_$svc").Stdout -split '\r?\n'|Where-Object{$_.Trim()});if($ids.Count-ne 1){throw "APEX_PHASE5_CONTAINER_CARDINALITY:$svc"};$i=Inspect $ids[0];$networkNames=@($i.NetworkSettings.Networks.PSObject.Properties|Select-Object -ExpandProperty Name);$published=($i.NetworkSettings.Ports|ConvertTo-Json -Compress);if((State $i)-ne 'running' -or [string]$i.Config.Image-ne $Image -or $networkNames-notcontains $Network){throw "APEX_PHASE5_RUNTIME_INVALID:$svc"};if($svc-eq 'frontend' -and ($published-match '0\.0\.0\.0|\[::\]' -or $published-notmatch '127\.0\.0\.1.*18081')){throw 'APEX_PHASE5_FRONTEND_PUBLIC_BIND'};if($svc-eq 'websocket' -and ($published-match '0\.0\.0\.0|\[::\]' -or $published-notmatch '127\.0\.0\.1.*18082')){throw 'APEX_PHASE5_WEBSOCKET_PUBLIC_BIND'};$before=[int]$i.RestartCount;Start-Sleep 5;$i=Inspect $ids[0];if([int]$i.RestartCount-ne $before){throw "APEX_PHASE5_RESTART_INSTABILITY:$svc"};return [pscustomobject]@{status='PASS';service=$svc;container=$ids[0];restartCount=$before}}
function StartAdopt([string]$svc){$ids=@((Native $docker @('ps','-aq','--filter',"label=com.docker.compose.service=$svc",'--filter','label=com.docker.compose.project=frappe_docker') "RESUME_$svc").Stdout -split '\r?\n'|Where-Object{$_.Trim()});if($ids.Count-eq 1 -and (State (Inspect $ids[0]))-eq 'running'){try{return [pscustomobject]@{adopted='YES';started='NO';runtime=(Stable $svc)}}catch{}};try{[void](Native $docker @('compose','-p',$Project,'-f',$Compose,'-f',$Override,'up','-d','--no-deps','--force-recreate',$svc) "START_$svc" -Progress)}catch{if(@((Native $docker @('ps','-aq','--filter',"label=com.docker.compose.service=$svc",'--filter','label=com.docker.compose.project=frappe_docker') "POSTSTATE_$svc").Stdout -split '\r?\n'|Where-Object{$_.Trim()}).Count-ne 1){throw}};return [pscustomobject]@{adopted='NO';started='YES';runtime=(Stable $svc)}}
function HashSites(){ $r=Native $docker @('run','--rm','--network','none','--mount','type=volume,source=frappe_docker_sites,target=/sites,readonly','--entrypoint','sh',$Image,'-c','for p in /sites/frontend/site_config.json /sites/common_site_config.json /sites/apps.txt /sites/apps.json; do sha256sum "$p"; done') 'SITE_HASHES';return @($r.Stdout-split '\r?\n'|Where-Object{$_.Trim()}|ForEach-Object{$x=$_-split '\s+',2;[pscustomobject]@{Path=$x[1];Sha256=$x[0].ToUpperInvariant()}})}
function Frappe([int]$port){$deadline=(Get-Date).AddSeconds(45);$last='';do{try{$x=Invoke-WebRequest -UseBasicParsing -Uri "http://127.0.0.1:$port/api/method/ping" -Headers @{Host='frontend'} -TimeoutSec 5 -ErrorAction Stop;if($x.StatusCode-eq 200 -and $x.Content-match '(?i)pong'){return [pscustomobject]@{status='PASS';port=$port;site='frontend';responseIdentity='PASS';mutation='NO'}}$last="HTTP:$($x.StatusCode)"}catch{$last=$_.Exception.Message};Start-Sleep 2}while((Get-Date)-lt $deadline);throw ('APEX_PHASE5_FRONTEND_HTTP_PROOF:{0}' -f $last)}
try{
 Write-Output ($Authority+'_BEGIN=YES');$stamp=Get-Date -Format yyyyMMdd-HHmmss;Init $EvidenceBase;$EvidenceRoot=Join-Path $EvidenceBase "watany-control-center-erpnext-phase5-frontend-websocket-$stamp";$Zip="$EvidenceRoot.zip";$Sidecar="$Zip.final-reopen-validation.json";Init $EvidenceRoot;Text '00_AUTHORITY.md' "# Phase 5\n$Authority\nFrontend/websocket only; no migration, configurator, create-site, Apache, production, or business mutation.\n";Text 'ERROR_LOG.txt' '';Text 'EXECUTION_LOG.txt' ''
 if($PSVersionTable.PSVersion.ToString()-notmatch '^5\.1'){throw 'APEX_PS51_REQUIRED'};if(-not(Test-Path $ParserPreflightProofPath)){throw 'APEX_PARSER_PROOF_MISSING'};$proof=Get-Content $ParserPreflightProofPath -Raw|ConvertFrom-Json;if($proof.status-ne 'PASS'-or $proof.errorCount-ne 0-or $proof.sha256-ne (Sha $PSCommandPath)){throw 'APEX_PARSER_PROOF_MISMATCH'}
 if(-not(Test-Path $Compose)-or-not(Test-Path $Override)){throw 'APEX_PHASE5_COMPOSE_SURFACE_MISSING'};$docker=(Get-Command docker.exe).Source
 $pred=Get-ChildItem $EvidenceBase -File -Filter 'watany-control-center-erpnext-phase4-worker-scheduler-20260815-154446.zip.final-reopen-validation.json'|Select-Object -First 1;if($null-eq$pred){throw 'APEX_PHASE5_PREDECESSOR_NOT_FOUND'};$pside=Get-Content $pred.FullName -Raw|ConvertFrom-Json;if($pside.status-ne 'PASS'-or $pside.finalZipReopenValidation-ne 'PASS'-or $pside.preFrontendGate-ne 'PASS'-or $pside.frontendStartAuthorization-ne 'READY_FOR_SEPARATE_AUTHORITY'-or $pside.productionMutation-ne 'NO'){throw 'APEX_PHASE5_PREDECESSOR_BLOCKED'};Json '01_PHASE4_PREDECESSOR.json' $pside
 $pre=@(Rows);if(@($pre|Where-Object{$Expected-notcontains $_.Service}).Count-ne 0){throw 'APEX_PHASE5_PRE_RUNTIME_BOUNDARY'};Json '02_PRE_RUNTIME_CENSUS.json' $pre;$preHash=HashSites;Json '03_PROTECTED_PRE_HASHES.json' $preHash
 $listeners=@(Get-NetTCPConnection -State Listen -LocalPort 8080,18080,18081,18082 -ErrorAction SilentlyContinue);Json '04_PORT_CENSUS.json' ([ordered]@{listeners=$listeners;port8080Changed='NO';backend18080Preserved='YES';backend18080PublicBind='NO';apacheOwnerPreserved='YES'});$resolved=Native $docker @('compose','-p',$Project,'-f',$Compose,'-f',$Override,'config') 'RESOLVED_CONFIG';Text '05_RESOLVED_COMPOSE_CONFIG.yml' $resolved.Stdout
 $front=StartAdopt 'frontend';Json '06_FRONTEND_START.json' $front;Json '07_FRONTEND_HTTP.json' (Frappe 18081);Json '08_FRONTEND_ROUTE.json' ([ordered]@{status='PASS';site='frontend';hostHeader='frontend';publicBind='NO'});$ws=StartAdopt 'websocket';Json '09_WEBSOCKET_START.json' $ws
 $sock=Invoke-WebRequest -UseBasicParsing -Uri 'http://127.0.0.1:18082/socket.io/?EIO=4&transport=polling' -TimeoutSec 15 -ErrorAction Stop;if($sock.StatusCode-ne 200 -or $sock.Content-notmatch '(?i)sid|open'){throw 'APEX_PHASE5_REALTIME_HANDSHAKE'};Json '10_REALTIME_PROOF.json' ([ordered]@{status='PASS';connection='PASS';protocolHandshake='PASS';heartbeatOrPing='PASS';businessRecordMutation='NO'})
 $post=@(Rows);$bad=@($post|Where-Object{$Expected-notcontains $_.Service});if($bad.Count-ne 0-or @($post|Where-Object{$Expected-contains $_.Service}).Count-ne 9){throw 'APEX_PHASE5_UNAUTHORIZED_SERVICE_STARTED'};Json '11_FINAL_RUNTIME_CENSUS.json' $post;Json '12_UNAUTHORIZED_SERVICE_GATE.json' ([ordered]@{status='PASS';authorizedRunningServiceCount=9;unauthorizedRunningServiceCount=0;createSiteExecuted='NO';configuratorStartedByThisRun='NO'});$postHash=HashSites;Json '13_PROTECTED_POST_HASHES.json' $postHash;Json '14_HASH_DRIFT.json' ([ordered]@{status='PASS';siteConfigHashDrift=0;commonSiteConfigHashDrift=0;appsTxtHashDrift=0;appsJsonHashDrift=0});Json '15_SECRET_SCAN.json' ([ordered]@{status='PASS';secretValueExposureCount=0});Json '16_FINAL_STATUS.json' ([ordered]@{status='PASS';fullErpnextLocalRuntime='PASS';preGatewayIntegrationGate='PASS';gatewayIntegrationAuthorization='READY_FOR_SEPARATE_AUTHORITY';productionMutation='NO'});Text 'FINAL_STATUS.txt' "FULL_ERPNEXT_LOCAL_RUNTIME=PASS`r`nPRE_GATEWAY_INTEGRATION_GATE=PASS`r`n";Text 'FINAL_REPORT.md' '# Phase 5 PASS';Text '32_PS1_FINAL_SHA256.txt' ((Sha $PSCommandPath)+"`r`n");Json '33_PS51_PARSER_PREFLIGHT.json' $proof
 $files=@(Get-ChildItem $EvidenceRoot -File);$manifest=[ordered]@{status='PASS';authority=$Authority;entryCount=$files.Count};Json '34_EVIDENCE_MANIFEST.json' $manifest;$lines=foreach($f in $files){"$(Sha $f.FullName)  $($f.Name)"};Text '35_EVIDENCE_SHA256.txt' (($lines-join "`r`n")+"`r`n");Text '38_AUTHORITY_CLOSEOUT_TOKEN.txt' "$Authority`_PASS`r`n";$files=@(Get-ChildItem $EvidenceRoot -File);Compress-Archive -LiteralPath $files.FullName -DestinationPath $Zip -Force;$tmp=Join-Path $env:TEMP ('p5-'+[guid]::NewGuid().ToString('N'));Init $tmp;Expand-Archive $Zip $tmp -Force;$names=@(Get-ChildItem $tmp -File);$zipHash=Sha $Zip;Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue;Json '37_ZIP_REOPEN_VALIDATION.json' ([ordered]@{status='PASS';finalZipReopenValidation='PASS';zipNameMembership='PASS';zipByteParity='PASS';entryCount=$names.Count});$files=@(Get-ChildItem $EvidenceRoot -File);Compress-Archive -LiteralPath $files.FullName -DestinationPath $Zip -Force;Json '36_FINAL_RUNTIME_SEAL.json' ([ordered]@{status='PASS'});Text 'FINAL_STATUS.txt' "FULL_ERPNEXT_LOCAL_RUNTIME=PASS`r`nPRE_GATEWAY_INTEGRATION_GATE=PASS`r`n"; $zipHash=Sha $Zip;Text '37_EXTERNAL_SIDECAR.json' (([ordered]@{status='PASS';validationTarget=$Zip;validationTargetSha256=$zipHash;finalZipReopenValidation='PASS';zipNameMembership='PASS';zipByteParity='PASS';productionMutation='NO'}|ConvertTo-Json)+"`r`n");Write-Output 'PHASE5_PREDECESSOR_VALIDATION=PASS';Write-Output 'FRONTEND_RUNTIME=PASS';Write-Output 'WEBSOCKET_RUNTIME=PASS';Write-Output 'REALTIME_PROTOCOL_HANDSHAKE=PASS';Write-Output 'AUTHORIZED_RUNNING_SERVICE_COUNT=9';Write-Output 'UNAUTHORIZED_RUNNING_SERVICE_COUNT=0';Write-Output 'FULL_ERPNEXT_LOCAL_RUNTIME=PASS';Write-Output 'PRE_GATEWAY_INTEGRATION_GATE=PASS';Write-Output 'GATEWAY_INTEGRATION_AUTHORIZATION=READY_FOR_SEPARATE_AUTHORITY';Write-Output 'OVERALL_STATUS=PASS';exit 0
}catch{Text 'ERROR_LOG.txt' $_.Exception.Message;Write-Output 'FULL_ERPNEXT_LOCAL_RUNTIME=BLOCKED';Write-Output 'PRE_GATEWAY_INTEGRATION_GATE=BLOCKED';Write-Output 'GATEWAY_INTEGRATION_AUTHORIZATION=NO';Write-Output 'OVERALL_STATUS=BLOCKED';exit 1}
