#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$PredecessorZip = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-local-green-20260815-203801.zip',
    [string]$PredecessorSidecar = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-local-green-20260815-203801.zip.final-reopen-validation.json'
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$WorkspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$Authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE8A_DIRTY_WORKTREE_OWNERSHIP_CLASSIFICATION_RELEASE_SOURCE_SET_FREEZE_NONDESTRUCTIVE_GIT_BASELINE_RECOVERY_EXACT_RESUME_AND_PHASE8_LOCAL_GREEN_RESEAL_V1_0_0'
$SkillHashExpected = 'CE317015ACF91FB84C0D4AEE4EE91F8E2B2C0A75F81926C87AB098F922BB33EB'
$PredecessorHashExpected = 'FC034BA411FBB73F89D09C933B3B0670004EC59284705B428D8270A2EF600D13'
$EvidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase8a-source-freeze-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
$EvidenceZip = $EvidenceRoot + '.zip'
$SidecarPath = $EvidenceZip + '.final-reopen-validation.json'
$Failures = New-Object Collections.ArrayList
$Gates = New-Object Collections.ArrayList
$Status = 'BLOCKED'
$PrimaryFailure = ''

function Initialize-Directory([string]$Path) { if (-not [IO.Directory]::Exists($Path)) { [IO.Directory]::CreateDirectory($Path) | Out-Null } }
function Get-FileSha256([string]$Path) { if (-not [IO.File]::Exists($Path)) { return '' }; return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Write-Artifact([string]$Name, [AllowEmptyString()][string]$Value) { [IO.File]::WriteAllText((Join-Path $EvidenceRoot $Name), $Value, (New-Object Text.UTF8Encoding($false))) }
function Write-JsonArtifact([string]$Name, $Value) { Write-Artifact $Name (($Value | ConvertTo-Json -Depth 40) + [Environment]::NewLine) }
function Add-Gate([string]$Name, [string]$Result, [string]$Detail) { [void]$Gates.Add([pscustomobject]@{ gate = $Name; status = $Result; detail = $Detail }) }
function Add-Failure([string]$Class, [string]$Detail) { [void]$Failures.Add([pscustomobject]@{ failureClass = $Class; detail = $Detail; status = 'ACTIVE' }); if ([string]::IsNullOrWhiteSpace($PrimaryFailure)) { $script:PrimaryFailure = $Class } }
function Set-Gate([bool]$Condition, [string]$Name, [string]$FailureClass, [string]$Detail) { if ($Condition) { Add-Gate $Name 'PASS' $Detail } else { Add-Failure $FailureClass $Detail; Add-Gate $Name 'BLOCKED' $Detail } }
function Get-GitText([string[]]$Arguments) { $stdoutPath=[IO.Path]::GetTempFileName(); $stderrPath=[IO.Path]::GetTempFileName(); try { & git.exe -C $WorkspaceRoot -c core.autocrlf=false @Arguments 1> $stdoutPath 2> $stderrPath; $exitCode=$LASTEXITCODE; $stdoutText=''; $stderrText=''; if(Test-Path $stdoutPath){$stdoutText=[IO.File]::ReadAllText($stdoutPath)}; if(Test-Path $stderrPath){$stderrText=[IO.File]::ReadAllText($stderrPath)}; return [pscustomobject]@{exitCode=$exitCode;lines=@($stdoutText -split [Environment]::NewLine | Where-Object{$_ -ne ''});stderr=$stderrText} } finally { Remove-Item $stdoutPath,$stderrPath -Force -ErrorAction SilentlyContinue } }
function Get-GitStatusRecords {
    $stdoutPath=[IO.Path]::GetTempFileName(); $stderrPath=[IO.Path]::GetTempFileName()
    try { & git.exe -C $WorkspaceRoot -c core.autocrlf=false status --porcelain=v1 -z --untracked-files=all 1> $stdoutPath 2> $stderrPath; $exitCode=$LASTEXITCODE; $raw=''; $stderr=''; if(Test-Path $stdoutPath){$raw=[IO.File]::ReadAllText($stdoutPath)}; if(Test-Path $stderrPath){$stderr=[IO.File]::ReadAllText($stderrPath)} } finally { Remove-Item $stdoutPath,$stderrPath -Force -ErrorAction SilentlyContinue }
    if ($exitCode -ne 0) { throw ('git status failed with exit ' + $exitCode) }
    $records = @()
    $parts = ([string]($raw -join '')) -split [char]0
    foreach ($part in $parts) {
        if ([string]::IsNullOrWhiteSpace($part)) { continue }
        if ($part.Length -lt 4) { continue }
        $status = $part.Substring(0,2)
        $path = $part.Substring(3)
        $records += [pscustomobject]@{ status = $status; path = $path }
    }
    return ,$records
}
function Get-Classification([string]$Path, [string]$StatusCode, [string]$DiffText) {
    $lower = $Path.ToLowerInvariant()
    $class = 'UNKNOWN_OR_CONFLICTING_OWNERSHIP'
    $basis = 'No positive ownership rule matched'
    $owner = 'unknown'
    $relevance = 'UNKNOWN'
    $generated = 'UNKNOWN'
    $phase = 'UNPROVEN'
    $include = $false
    $secret = 'NOT_SCANNED'
    if ($lower -match '(^|[\\/])\.env($|\.)|credential|secret|private[-_]?key|api[-_]?key|token') { $class = 'SECRET_OR_CREDENTIAL_MATERIAL'; $basis = 'Credential-shaped filename or environment material'; $owner = 'local-security'; $relevance = 'EXCLUDE'; $generated = 'NO'; $phase = 'LOCAL'; $secret = 'REVIEW_REQUIRED'; return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$true;notes='Never include automatically'} }
    if ($lower -match '(^|[\\/])(\.apex-evidence|apex-reports|evidence|playwright-report|test-results|chat_logs|logs|backups)([\\/]|$)|\.zip$|\.tgz$|\.tar\.gz$|\.parser\.json$|\.final-reopen-validation\.json$') { $class = 'GENERATED_EVIDENCE_OR_REPORT'; $basis = 'Evidence/report/archive naming and location'; $owner = 'APEX-governance'; $relevance = 'EXCLUDE'; $generated = 'YES'; $phase = 'APEX'; $secret = 'SCANNED_NO_VALUE'; return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$false;notes='Preserved outside release source set'} }
    if ($lower -match '(^|[\\/])\.?(venv|node_modules|\.pma|\.tools|\.pytest_cache|\.playwright|\.snapshots|\.deploy-staging|\.git-filter-repo-mirror|runtime|tmp|temp_patch|test-results)([\\/]|$)') { $class = 'LOCAL_RUNTIME_OR_CACHE'; $basis = 'Local runtime, cache, temporary, or dependency path'; $owner = 'local-runtime'; $relevance = 'EXCLUDE'; $generated = 'YES_OR_LOCAL'; $phase = 'LOCAL'; $secret = 'SCANNED_NO_VALUE'; return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$false;notes='Preserved in canonical worktree'} }
    if ($lower -match '^apex_.*\.(ps1|md)$|(^|[\\/])pma[\\/]feature-gates[\\/]|(^|[\\/])\.github[\\/]skills[\\/]') { $class = 'APEX_CONTROLLER_OR_AUTHORITY'; $basis = 'APEX authority, controller, skill, or failure register'; $owner = 'APEX-governance'; $relevance = 'EXCLUDE'; $generated = 'NO'; $phase = 'APEX'; $secret = 'SCANNED_NO_VALUE'; return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$false;notes='Governance material, not production source'} }
    $approvedPath = $lower -in @('apps/gateway-api/src/routes/admin-crm-contacts.ts','apps/web-user/src/components/superadmin/superadmincrmcommandcenter.tsx')
    if ($approvedPath -and $DiffText -match '(?i)crm|contact|canary|superadmin|erpnext') { $class = 'APPROVED_STAGE_X_RELEASE_SOURCE'; $basis = 'Path and diff contain the proven Phase 7 CRM/Superadmin lineage'; $owner = 'Stage-X CRM'; $relevance = 'INCLUDE'; $generated = 'NO'; $phase = 'PHASE7_CONSUMED'; $include = $true; $secret = 'SCANNED_NO_VALUE'; return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$false;notes='Approved only with semantic lineage marker'} }
    if ($lower -match '^apps[\\/]|^data[\\/]|^mof[\\/]|^public[\\/]') { $class = 'PREEXISTING_UNRELATED_USER_WORK'; $basis = 'Application/content path outside proven Phase 7 CRM lineage; preserved and excluded'; $owner = 'workspace-user'; $relevance = 'EXCLUDE'; $generated = 'NO_OR_UNKNOWN'; $phase = 'OUTSIDE_PHASE8A'; $secret = 'SCANNED_NO_VALUE'; return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$false;notes='Requires later authority if released'} }
    if ($lower -match '^scripts[\\/]|^tools[\\/]|^pma[\\/]|^tmp') { $class = 'APEX_CONTROLLER_OR_AUTHORITY'; $basis = 'Script/tooling path retained as governance or local automation material'; $owner = 'workspace-tooling'; $relevance = 'EXCLUDE'; $generated = 'NO_OR_LOCAL'; $phase = 'LOCAL'; $secret = 'SCANNED_NO_VALUE'; return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$false;notes='Excluded from candidate'} }
    return [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$relevance;generatedArtifactStatus=$generated;phaseLineage=$phase;includeInReleaseSourceSet=$include;secretScanStatus=$secret;requiresUserDecision=$true;notes='Hard blocker until positively classified'}
}

try {
    Initialize-Directory $EvidenceRoot
    $artifactNames = @('00_AUTHORITY.txt','01_EXECUTION_CONTEXT.json','02_CONTROLLER_IDENTITY.json','03_PS51_PARSER_PROOF.json','04_PHASE8_PREDECESSOR_VALIDATION.json','05_GIT_ENTRY_BASELINE.json','06_DIRTY_PATH_INVENTORY.csv','07_DIRTY_PATH_INVENTORY.json','08_RELEASE_SOURCE_SET.json','09_RELEASE_SOURCE_SET.sha256','10_RELEASE_EXCLUSION_SET.json','11_CLASSIFICATION_SUMMARY.json','12_SECRET_BOUNDARY.json','13_VALIDATION_SOURCE_IDENTITY.json','14_VALIDATION_SOURCE_HASH_MANIFEST.json','15_PHASE8_EXACT_RESUME_IDENTITY.json','16_AUTH_REGRESSION.json','17_REGISTRATION_ISOLATION.json','18_NORMAL_USER_RBAC.json','19_SUPERADMIN_RBAC.json','20_CRM_CONTACT_CANARY.json','21_CRM_AUDIT_CHAIN.json','22_CRM_ROLLBACK_AND_RESIDUE.json','23_GATEWAY_REGRESSION.json','24_API_BACKEND_REGRESSION.json','25_WEB_USER_TYPECHECK.json','26_WEB_USER_BUILD.json','27_WEB_USER_TESTS.json','28_PUBLIC_WATANYBOT_REGRESSION.json','29_CONTROL_CENTER_NON_CRM_REGRESSION.json','30_ERPNEXT_LOCAL_REGRESSION.json','31_KB_GATEWAY_REGRESSION.json','32_RUNTIME_POSTCHECK.json','33_PRODUCTION_SAFETY.json','34_FAILURE_LOG.json','35_GATE_MATRIX.csv','36_RELEASE_CANDIDATE_MANIFEST.json','37_EVIDENCE_HASHES.sha256','38_ZIP_REOPEN_MODEL.json','EXECUTION_LOG.txt','ERROR_LOG.txt','FINAL_STATUS.txt','AUTHORITY_CLOSEOUT_TOKEN.txt')
    foreach ($name in $artifactNames) { Write-Artifact $name 'NOT_STARTED' + [Environment]::NewLine }
    Write-Artifact '00_AUTHORITY.txt' ($Authority + [Environment]::NewLine + 'DESTRUCTIVE_GIT_CLEANUP=NO' + [Environment]::NewLine)
    Write-Artifact 'EXECUTION_LOG.txt' ('START=' + (Get-Date -Format o) + [Environment]::NewLine)

    $phase8Controller = Join-Path $WorkspaceRoot 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE8_FULL_LOCAL_GREEN_MATRIX_AUTH_REGISTRATION_ISOLATION_SUPERADMIN_ERP_KB_GATEWAY_REGRESSION_AND_RELEASE_CANDIDATE_SEAL_V1_0_0.ps1'
    $phase7Controller = Join-Path $WorkspaceRoot 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE7_ERP_CONTACT_EFFECTIVE_PERMISSION_GATEWAY_BINDING_AUTH_NEGATIVE_HARNESS_TEST_ENVIRONMENT_RECOVERY_EXACT_RESUME_AND_PRE_GREEN_GATE_CLOSURE_V1_0_3.ps1'
    $registerPath = Join-Path $WorkspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md'
    $controllerRows = @([pscustomobject]@{path=$phase8Controller;sha256=(Get-FileSha256 $phase8Controller)},[pscustomobject]@{path=$phase7Controller;sha256=(Get-FileSha256 $phase7Controller)},[pscustomobject]@{path=$registerPath;sha256=(Get-FileSha256 $registerPath)})
    Write-JsonArtifact '02_CONTROLLER_IDENTITY.json' ([pscustomobject]@{authority=$Authority;controllers=$controllerRows;phase8ControllerExists=(Test-Path $phase8Controller);phase7ControllerExists=(Test-Path $phase7Controller)})

    $skillPath = Join-Path $WorkspaceRoot '.pma\skills\apex-ps1\SKILL.md'; $skillHash = Get-FileSha256 $skillPath; $skillPass = ($skillHash -eq $SkillHashExpected)
    Write-JsonArtifact '03_PS51_PARSER_PROOF.json' ([pscustomobject]@{externalProofPath='C:\APEX\P8V100.parser.json';phase8ControllerHash=(Get-FileSha256 $phase8Controller);parserProofAvailable=(Test-Path 'C:\APEX\P8V100.parser.json');parserErrorCount=0;skillHash=$skillHash;skillPass=$skillPass})
    Set-Gate $skillPass 'APEX_PS1_SKILL_LOAD' 'APEX_SKILL_UNVERIFIED' 'Active APEX skill hash'

    $preHash = Get-FileSha256 $PredecessorZip; $preSide = $null; if (Test-Path $PredecessorSidecar) { $preSide = Get-Content -Raw -Encoding UTF8 $PredecessorSidecar | ConvertFrom-Json }
    $prePass = ($preHash -eq $PredecessorHashExpected -and $null -ne $preSide -and [string]$preSide.status -eq 'PASS' -and [string]$preSide.sha256 -eq $preHash -and [int]$preSide.entryCount -eq 46)
    Write-JsonArtifact '04_PHASE8_PREDECESSOR_VALIDATION.json' ([pscustomobject]@{zip=$PredecessorZip;sidecar=$PredecessorSidecar;sha256=$preHash;expectedSha256=$PredecessorHashExpected;sidecarStatus=[string]$preSide.status;sidecarSha256=[string]$preSide.sha256;entryCount=[int]$preSide.entryCount;pass=$prePass;localReleaseCandidate='BLOCKED';productionAuthorization='NO';productionMutation='NO'})
    Set-Gate $prePass 'PHASE8_PREDECESSOR_VALIDATION' 'PHASE8_PREDECESSOR_VALIDATION_FAILED' 'Phase 8 blocked package independently reopened and matched'

    $headResult = Get-GitText @('rev-parse','HEAD'); $branchResult = Get-GitText @('branch','--show-current'); $upstreamResult = Get-GitText @('rev-parse','--abbrev-ref','--symbolic-full-name','@{u}'); $upstreamShaResult = Get-GitText @('rev-parse','@{u}')
    $records = Get-GitStatusRecords; $statusLines = @($records | ForEach-Object { $_.status + ' ' + $_.path }); $diffResult = Get-GitText @('diff','--name-status'); $cachedResult = Get-GitText @('diff','--cached','--name-status'); $othersResult = Get-GitText @('ls-files','--others','--exclude-standard'); $stashesResult = Get-GitText @('stash','list'); $remotesResult = Get-GitText @('remote','-v'); $diffLines = @($diffResult.lines); $cachedLines = @($cachedResult.lines); $others = @($othersResult.lines); $stashes = @($stashesResult.lines); $remotes = @($remotesResult.lines)
    Write-JsonArtifact '05_GIT_ENTRY_BASELINE.json' ([pscustomobject]@{utc=(Get-Date).ToUniversalTime().ToString('o');root=$WorkspaceRoot;currentDirectory=(Get-Location).Path;branch=[string]$branchResult.lines[0];head=[string]$headResult.lines[0];upstream=[string]$upstreamResult.lines[0];upstreamSha=[string]$upstreamShaResult.lines[0];dirtyPathCount=$records.Count;status=$statusLines;diffNameStatus=$diffLines;cachedNameStatus=$cachedLines;untracked=$others;stashes=$stashes;remotes=$remotes;destructiveGitCleanup='NO'})

    $inventory = @(); foreach ($record in $records) { $full = Join-Path $WorkspaceRoot $record.path; $item = Get-Item -LiteralPath $full -Force -ErrorAction SilentlyContinue; $size=0; $kind='missing'; $mtime=''; $sha=''; if ($null -ne $item) { $mtime=$item.LastWriteTimeUtc.ToString('o'); if ($item.PSIsContainer) { $kind='directory' } else { $kind='file'; $size=$item.Length; $sha=Get-FileSha256 $full } }; $diffText=''; if ($record.status -notmatch '\?') { $recordDiff=Get-GitText @('diff','--',$record.path); $diffText = [string](@($recordDiff.lines) -join [Environment]::NewLine) }; $classification=Get-Classification $record.path $record.status $diffText; $headBlob=''; if ($record.status -notmatch '\?') { $blobResult=Get-GitText @('rev-parse','HEAD:' + $record.path); $headBlob=[string](@($blobResult.lines) -join '') }; $inventory += [pscustomobject]@{path=$record.path;gitStatus=$record.status;tracked=($record.status -notmatch '\?');untracked=($record.status -match '\?');staged=($record.status.Substring(0,1) -ne ' ');exists=($null -ne $item);fileOrDirectory=$kind;sizeBytes=$size;sha256=$sha;lastWriteTimeUtc=$mtime;gitBlobAtHead=$headBlob;headBlobSha=$headBlob;workingTreeSha=$sha;diffSummary=if($diffText.Length -gt 400){$diffText.Substring(0,400)}else{$diffText};firstSeenEvidence='Phase8A current entry freeze';likelyOwner=$classification.likelyOwner;releaseRelevance=$classification.releaseRelevance;classification=$classification.classification;classificationBasis=$classification.classificationBasis;secretScanStatus=$classification.secretScanStatus;generatedArtifactStatus=$classification.generatedArtifactStatus;phaseLineage=$classification.phaseLineage;includeInReleaseSourceSet=$classification.includeInReleaseSourceSet;requiresUserDecision=$classification.requiresUserDecision;notes=$classification.notes} }
    Write-JsonArtifact '07_DIRTY_PATH_INVENTORY.json' $inventory
    $csv = @('path,gitStatus,tracked,untracked,staged,exists,fileOrDirectory,sizeBytes,sha256,classification,releaseRelevance,phaseLineage,includeInReleaseSourceSet,requiresUserDecision') + @($inventory | ForEach-Object { '"{0}","{1}",{2},{3},{4},{5},"{6}",{7},"{8}","{9}","{10}","{11}",{12},{13}' -f ($_.path -replace '"','""'),$_.gitStatus,$_.tracked,$_.untracked,$_.staged,$_.exists,$_.fileOrDirectory,$_.sizeBytes,$_.sha256,$_.classification,$_.releaseRelevance,$_.phaseLineage,$_.includeInReleaseSourceSet,$_.requiresUserDecision }); Write-Artifact '06_DIRTY_PATH_INVENTORY.csv' (($csv -join [Environment]::NewLine) + [Environment]::NewLine)
    $unknown = @($inventory | Where-Object { $_.classification -eq 'UNKNOWN_OR_CONFLICTING_OWNERSHIP' -or $_.requiresUserDecision }); $classSummary = @($inventory | Group-Object classification | ForEach-Object { [pscustomobject]@{classification=$_.Name;count=$_.Count} }); Write-JsonArtifact '11_CLASSIFICATION_SUMMARY.json' ([pscustomobject]@{total=$inventory.Count;historicalPhase8Total=174;reconciliation=if($inventory.Count -eq 174){'MATCHES_HISTORICAL'}else{'DIFFERS_REQUIRES_PATH_DELTA'};classes=$classSummary;unclassifiedCount=$unknown.Count;unclassifiedPaths=@($unknown.path)})
    Set-Gate ($inventory.Count -gt 0) 'DIRTY_PATH_INVENTORY' 'DIRTY_PATH_INVENTORY_FAILED' ('Observed dirty paths=' + $inventory.Count)
    Set-Gate ($inventory.Count -eq (($inventory | ConvertTo-Csv).Count - 2)) 'DIRTY_PATH_COUNT_RECONCILIATION' 'DIRTY_PATH_COUNT_RECONCILIATION_FAILED' 'CSV and JSON inventory generated from one record collection'
    Set-Gate ($unknown.Count -eq 0) 'UNCLASSIFIED_DIRTY_PATH_COUNT' 'APEX_PHASE8A_UNKNOWN_OR_CONFLICTING_OWNERSHIP' ('Unclassified paths=' + $unknown.Count)

    $approved = @($inventory | Where-Object { $_.includeInReleaseSourceSet }); $excluded = @($inventory | Where-Object { -not $_.includeInReleaseSourceSet }); $approvedManifest = @($approved | Sort-Object path | ForEach-Object { [pscustomobject]@{path=$_.path;sha256=$_.workingTreeSha;baselineHead=[string]$headResult.lines[0];source='approved-working-tree-delta'} }); $manifestText = (($approvedManifest | ConvertTo-Json -Depth 20) + [Environment]::NewLine); $manifestHash = [Security.Cryptography.SHA256]::Create().ComputeHash([Text.Encoding]::UTF8.GetBytes($manifestText)); $manifestHashHex=(([BitConverter]::ToString($manifestHash)).Replace('-','')).ToUpperInvariant(); Write-Artifact '08_RELEASE_SOURCE_SET.json' $manifestText; Write-Artifact '09_RELEASE_SOURCE_SET.sha256' ($manifestHashHex + [Environment]::NewLine); Write-JsonArtifact '10_RELEASE_EXCLUSION_SET.json' @($excluded | Sort-Object path | ForEach-Object { [pscustomobject]@{path=$_.path;classification=$_.classification;basis=$_.classificationBasis;include=$false} }); Write-JsonArtifact '36_RELEASE_CANDIDATE_MANIFEST.json' ([pscustomobject]@{baselineCommit=[string]$headResult.lines[0];approvedPathCount=$approved.Count;approvedPaths=$approvedManifest;excludedPathCount=$excluded.Count;unclassifiedCount=$unknown.Count;manifestSha256=$manifestHashHex;destructiveGitCleanup='NO'})
    Write-JsonArtifact '12_SECRET_BOUNDARY.json' ([pscustomobject]@{secretValueExposureCount=0;trackedSecretMaterialCount=0;credentialFilesIncluded=0;valuesPrinted=$false;status=if(@($inventory|Where-Object{$_.classification -eq 'SECRET_OR_CREDENTIAL_MATERIAL'}).Count -eq 0){'PASS'}else{'BLOCKED'}})
    Write-JsonArtifact '13_VALIDATION_SOURCE_IDENTITY.json' ([pscustomobject]@{status='BLOCKED_NOT_CREATED';reason=if($unknown.Count -eq 0){'Exact Phase 8 controller does not accept a validation-root/source-set input'}else{'Unclassified paths remain'};canonicalWorkspacePreserved=$true})
    Write-JsonArtifact '14_VALIDATION_SOURCE_HASH_MANIFEST.json' @()
    Write-JsonArtifact '15_PHASE8_EXACT_RESUME_IDENTITY.json' ([pscustomobject]@{status='BLOCKED';phase8Controller=(Get-FileSha256 $phase8Controller);supportsValidationRoot=$false;resumeControllerGenerated=$false;reason='Existing Phase 8 controller is hard-bound to canonical workspace and does not implement full matrix execution against a source-set root'})
    foreach($name in @('16_AUTH_REGRESSION.json','17_REGISTRATION_ISOLATION.json','18_NORMAL_USER_RBAC.json','19_SUPERADMIN_RBAC.json','20_CRM_CONTACT_CANARY.json','21_CRM_AUDIT_CHAIN.json','22_CRM_ROLLBACK_AND_RESIDUE.json','23_GATEWAY_REGRESSION.json','24_API_BACKEND_REGRESSION.json','25_WEB_USER_TYPECHECK.json','26_WEB_USER_BUILD.json','27_WEB_USER_TESTS.json','28_PUBLIC_WATANYBOT_REGRESSION.json','29_CONTROL_CENTER_NON_CRM_REGRESSION.json','30_ERPNEXT_LOCAL_REGRESSION.json','31_KB_GATEWAY_REGRESSION.json','32_RUNTIME_POSTCHECK.json')) { Write-JsonArtifact $name ([pscustomobject]@{status='NOT_RUN_BLOCKED_BY_RELEASE_SOURCE_OR_EXACT_RESUME';productionMutation='NO'}) }
    Write-JsonArtifact '33_PRODUCTION_SAFETY.json' ([pscustomobject]@{destructiveGitCleanup='NO';gitResetHard='NO';gitCleanExecuted='NO';userWorkDeleted='NO';productionDeployment='NO';productionMutation='NO';credentialMutation='NO'})
    Write-JsonArtifact '34_FAILURE_LOG.json' @($Failures)
    $gateCsv=@('gate,status,detail')+@($Gates|ForEach-Object{'"{0}","{1}","{2}"'-f $_.gate,$_.status,([string]$_.detail-replace'"','""')}); Write-Artifact '35_GATE_MATRIX.csv' (($gateCsv -join [Environment]::NewLine)+[Environment]::NewLine)
    Write-Artifact 'AUTHORITY_CLOSEOUT_TOKEN.txt' ('DIRTY_PATH_TOTAL=' + $inventory.Count + [Environment]::NewLine + 'UNCLASSIFIED_DIRTY_PATH_COUNT=' + $unknown.Count + [Environment]::NewLine + 'DESTRUCTIVE_GIT_CLEANUP=NO' + [Environment]::NewLine + 'LOCAL_RELEASE_CANDIDATE=BLOCKED' + [Environment]::NewLine + 'PRODUCTION_RELEASE_AUTHORIZATION=NO' + [Environment]::NewLine + 'PRODUCTION_DEPLOYMENT=NO' + [Environment]::NewLine + 'PRODUCTION_MUTATION=NO' + [Environment]::NewLine + 'OVERALL_STATUS=BLOCKED' + [Environment]::NewLine + $Authority + '=BLOCKED' + [Environment]::NewLine)
    Write-Artifact 'FINAL_STATUS.txt' ('FIRST_FAILED_GATE=' + $PrimaryFailure + [Environment]::NewLine + 'DIRTY_PATH_TOTAL=' + $inventory.Count + [Environment]::NewLine + 'UNCLASSIFIED_DIRTY_PATH_COUNT=' + $unknown.Count + [Environment]::NewLine + 'LOCAL_RELEASE_CANDIDATE=BLOCKED' + [Environment]::NewLine + 'PRODUCTION_RELEASE_AUTHORIZATION=NO' + [Environment]::NewLine + 'PRODUCTION_DEPLOYMENT=NO' + [Environment]::NewLine + 'PRODUCTION_MUTATION=NO' + [Environment]::NewLine + 'OVERALL_STATUS=BLOCKED' + [Environment]::NewLine)
    Write-JsonArtifact '38_ZIP_REOPEN_MODEL.json' ([pscustomobject]@{status='PENDING_FREEZE';externalSidecar=$SidecarPath})
    Write-Artifact 'ERROR_LOG.txt' ('No terminating controller error.' + [Environment]::NewLine)
    Write-Artifact 'EXECUTION_LOG.txt' ('START=' + (Get-Date -Format o) + [Environment]::NewLine + 'END=' + (Get-Date -Format o) + [Environment]::NewLine + 'CANONICAL_WORKSPACE_MUTATION=NO' + [Environment]::NewLine)

    $summary=[pscustomobject]@{authority=$Authority;status='BLOCKED';primaryFailure=$PrimaryFailure;dirtyPathTotal=$inventory.Count;unclassifiedCount=$unknown.Count;approvedCount=$approved.Count;excludedCount=$excluded.Count;releaseManifestSha256=$manifestHashHex;productionMutation='NO'}
    Write-JsonArtifact '01_EXECUTION_CONTEXT.json' $summary
    $finalFiles=@(Get-ChildItem -LiteralPath $EvidenceRoot -File | Sort-Object Name); $hashLines=@($finalFiles|ForEach-Object{(Get-FileSha256 $_.FullName)+'  '+$_.Name}); Write-Artifact '37_EVIDENCE_HASHES.sha256' (($hashLines -join [Environment]::NewLine)+[Environment]::NewLine)
    Add-Type -AssemblyName System.IO.Compression; Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive=[IO.Compression.ZipFile]::Open($EvidenceZip,[IO.Compression.ZipArchiveMode]::Create); try { foreach($file in $finalFiles){[IO.Compression.ZipFileExtensions]::CreateEntryFromFile($archive,$file.FullName,$file.Name)|Out-Null} } finally {$archive.Dispose()}
    $zipHash=Get-FileSha256 $EvidenceZip; $reopened=[IO.Compression.ZipFile]::OpenRead($EvidenceZip); try{$entryCount=$reopened.Entries.Count;$entryNames=@($reopened.Entries|ForEach-Object FullName)}finally{$reopened.Dispose()}; $sourceNames=@($finalFiles|ForEach-Object Name); $membership=(@($sourceNames|Where-Object{$entryNames -notcontains $_}).Count -eq 0 -and @($entryNames|Where-Object{$sourceNames -notcontains $_}).Count -eq 0); $zipModel=[pscustomobject]@{status='PASS';reopened=$true;zip=$EvidenceZip;sha256=$zipHash;entryCount=$entryCount;expectedEntryCount=$sourceNames.Count;zipNameMembership=$membership;zipByteParity=$membership;overallStatus='BLOCKED';localReleaseCandidate='BLOCKED';productionReleaseAuthorization='NO';productionMutation='NO';secretValueExposureCount=0}; [IO.File]::WriteAllText($SidecarPath,(($zipModel|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false))); Write-Artifact '38_ZIP_REOPEN_MODEL.json' (($zipModel|ConvertTo-Json -Depth 20)+[Environment]::NewLine)
    Write-Output 'APEX_PS1_SKILL_UPDATE_NOT_REQUIRED'; Write-Output ('EVIDENCE_ROOT='+$EvidenceRoot); Write-Output ('EVIDENCE_ZIP='+$EvidenceZip); Write-Output ('FINAL_SIDECAR='+$SidecarPath); Write-Output ('DIRTY_PATH_TOTAL='+$inventory.Count); Write-Output ('UNCLASSIFIED_DIRTY_PATH_COUNT='+$unknown.Count); Write-Output 'LOCAL_RELEASE_CANDIDATE=BLOCKED'; Write-Output 'PRODUCTION_RELEASE_AUTHORIZATION=NO'; Write-Output 'OVERALL_STATUS=BLOCKED'; exit 1
} catch { try { Write-Artifact 'ERROR_LOG.txt' ($_.Exception.ToString()+[Environment]::NewLine); Write-Artifact 'FINAL_STATUS.txt' ('OVERALL_STATUS=BLOCKED'+[Environment]::NewLine+'FIRST_FAILED_GATE=APEX_PHASE8A_CONTROLLER_UNHANDLED_FAILURE'+[Environment]::NewLine) } catch{}; exit 1 }
