#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$WorkspaceRoot = 'C:\xampp\htdocs\projectx\watanybot',
    [string]$FrappeDockerRoot = 'C:\xampp\htdocs\projectx\watany-control-center\erpnext\frappe_docker',
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$ParserPreflightProofPath = 'C:\APEX\P4V100.parser.json'
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$AuthorityId = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_ERPNEXT_PHASE4_WORKER_SCHEDULER_RUNTIME_RECOVERY_QUEUE_CONNECTIVITY_JOB_EXECUTION_READ_ONLY_PROOF_AND_PRE_FRONTEND_GATE_V1_0_0'
$ComposeProject = 'frappe_docker'
$ComposeFile = Join-Path $FrappeDockerRoot 'pwd.yml'
$LoopbackOverride = Join-Path $FrappeDockerRoot 'watany.integration.backend-loopback.yml'
$EvidenceRoot = ''
$EvidenceZip = ''
$SidecarPath = ''
$ScriptSha256 = ''
$ParserProof = $null
$FirstFailedGate = ''
$FailureRows = New-Object System.Collections.ArrayList
$ActionRows = New-Object System.Collections.ArrayList
$GateRows = New-Object System.Collections.ArrayList
$AllowedServices = @('db','redis-cache','redis-queue','backend','queue-short','queue-long','scheduler')
$ForbiddenServices = @('frontend','websocket','create-site','configurator')
$ExpectedImage = 'frappe/erpnext:v16.32.0'
$ExpectedNetwork = 'frappe_docker_frappe_network'
$SiteVolume = 'frappe_docker_sites'
$BackendPort = 18080
$ProtectedPort = 8080
$PreHashes = @()
$PostHashes = @()
$SecretValueExposureCount = 0
$UnauthorizedRunningServiceCount = 0
$StartedByRun = @{}
$AdoptedByResume = @{}
$RequiredEvidenceNames = @(
'00_AUTHORITY.md','01_APEX_CONTRACT_STATUS.json','02_FAILURE_REGISTER_PRECHECK.json','03_PHASE3_PREDECESSOR_VALIDATION.json','04_PRE_RUNTIME_CENSUS.csv','05_PROTECTED_CONFIG_PRE_HASHES.csv','06_PORT_AND_DEPENDENCY_PRECHECK.json','07_RESOLVED_COMPOSE_SERVICES.json','08_QUEUE_SHORT_START.json','09_QUEUE_SHORT_RUNTIME.json','10_QUEUE_SHORT_REDIS.json','11_QUEUE_SHORT_DB.json','12_QUEUE_LONG_START.json','13_QUEUE_LONG_RUNTIME.json','14_QUEUE_LONG_REDIS.json','15_QUEUE_LONG_DB.json','16_SCHEDULER_START.json','17_SCHEDULER_RUNTIME.json','18_SCHEDULER_REDIS.json','19_SCHEDULER_DB.json','20_READ_ONLY_JOB_PROOF.json','21_POST_WORKER_FRAPPE_HTTP.json','22_FINAL_RUNTIME_CENSUS.csv','23_UNAUTHORIZED_SERVICE_GATE.json','24_PROTECTED_CONFIG_POST_HASHES.csv','25_HASH_DRIFT.json','26_PORT_OWNERSHIP.json','27_SECRET_SCAN.json','28_FAILURES.csv','29_GATE_RESULTS.csv','30_FINAL_STATUS.json','31_PRE_FRONTEND_HANDOFF.json','32_PS1_FINAL_SHA256.txt','33_PS51_PARSER_PREFLIGHT.json','34_EVIDENCE_MANIFEST.json','35_EVIDENCE_SHA256.txt','36_EVIDENCE_COMPLETENESS.json','37_ZIP_REOPEN_VALIDATION.json','38_AUTHORITY_CLOSEOUT_TOKEN.txt','FINAL_REPORT.md','summary.json','FINAL_STATUS.txt','progress.json','checkpoint.json','ERROR_LOG.txt','EXECUTION_LOG.txt'
)
function Initialize-Directory([string]$Path) { if (-not [IO.Directory]::Exists($Path)) { [void][IO.Directory]::CreateDirectory($Path) } }
function Write-Text([string]$Name,[AllowEmptyString()][string]$Text) { $path = Join-Path $EvidenceRoot $Name; Initialize-Directory ([IO.Path]::GetDirectoryName($path)); [IO.File]::WriteAllText($path,$Text,(New-Object Text.UTF8Encoding($false))) }
function Write-Json([string]$Name,$Value) { Write-Text $Name (($Value | ConvertTo-Json -Depth 20) + [Environment]::NewLine) }
function Get-FileSha256([string]$Path) { $sha = [Security.Cryptography.SHA256]::Create(); $stream = [IO.File]::OpenRead($Path); try { return ([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','').ToUpperInvariant() } finally { $stream.Dispose(); $sha.Dispose() } }
function Csv([string]$Name,[object[]]$Rows,[string[]]$Headers) { $lines = New-Object Collections.Generic.List[string]; $lines.Add(($Headers -join ',')); foreach ($row in @($Rows)) { $values = foreach ($header in $Headers) { $v = ''; if ($null -ne $row.PSObject.Properties[$header]) { $v = [string]$row.$header }; '"' + $v.Replace('"','""') + '"' }; $lines.Add(($values -join ',')) }; Write-Text $Name (($lines -join [Environment]::NewLine) + [Environment]::NewLine) }
function Gate([string]$Name,[string]$Status,[string]$Detail) { [void]$GateRows.Add([pscustomobject]@{Gate=$Name;Status=$Status;Detail=$Detail}); if (($Status -eq 'BLOCKED') -and [string]::IsNullOrWhiteSpace($script:FirstFailedGate)) { $script:FirstFailedGate = $Name } }
function Action([string]$Name,[string]$Status,[string]$Detail) { [void]$ActionRows.Add([pscustomobject]@{Time=[DateTimeOffset]::Now.ToString('o');Action=$Name;Status=$Status;Detail=$Detail}) }
function Failure([string]$Class,[string]$Detail) { [void]$FailureRows.Add([pscustomobject]@{Time=[DateTimeOffset]::Now.ToString('o');FailureClass=$Class;Detail=$Detail;Status='ACTIVE'}) }
function YesNo([bool]$Value) { if ($Value) { return 'YES' }; return 'NO' }
function Optional($ObjectValue,[string]$Name,$Default) { if ($null -eq $ObjectValue) { return $Default }; $p = $ObjectValue.PSObject.Properties[$Name]; if ($null -eq $p) { return $Default }; return $p.Value }
function Native([string]$Exe,[string[]]$ArgumentVector,[string]$Label,[switch]$ComposeProgress) { $errPath = Join-Path $env:TEMP ('p4-err-' + [guid]::NewGuid().ToString('N') + '.txt'); try { $out = @(& $Exe @ArgumentVector 2> $errPath); $code = $LASTEXITCODE; $stdout = ($out | ForEach-Object {[string]$_}) -join [Environment]::NewLine; $stderr = ''; if ([IO.File]::Exists($errPath)) { $stderr = [IO.File]::ReadAllText($errPath) }; Action $Label ($(if ($code -eq 0) {'PASS'} else {'BLOCKED'})) ('ExitCode={0};StdoutBytes={1};StderrBytes={2}' -f $code,$stdout.Length,$stderr.Length); if ($code -ne 0) { throw ('APEX_NATIVE_PROCESS_FAILED:{0}:{1}:Stdout={2}:Stderr={3}' -f $Label,$code,$stdout.Trim(),$stderr.Trim()) }; if ((-not $ComposeProgress) -and ($stderr -match '(?i)\b(error|fatal|failed|exception|traceback)\b')) { throw ('APEX_NATIVE_STDERR_FAILURE:{0}:{1}' -f $Label,$stderr.Trim()) }; return [pscustomobject]@{ExitCode=$code;Stdout=$stdout;Stderr=$stderr} } finally { if ([IO.File]::Exists($errPath)) { Remove-Item -LiteralPath $errPath -Force -ErrorAction SilentlyContinue } } }
function DockerInspect([string]$Docker,[string]$Ref,[string]$Label) { $r = Native $Docker @('inspect',$Ref) $Label; $rows = @($r.Stdout | ConvertFrom-Json); if ($rows.Count -ne 1) { throw ('APEX_DOCKER_INSPECT_CARDINALITY:{0}:{1}' -f $Ref,$rows.Count) }; return $rows[0] }
function ServiceOf($Inspect) { $labels = Optional (Optional $Inspect 'Config' $null) 'Labels' $null; return [string](Optional $labels 'com.docker.compose.service' '') }
function StateOf($Inspect) { return [string](Optional (Optional $Inspect 'State' $null) 'Status' 'NOT_DEFINED') }
function RestartCount($Inspect) { return [int](Optional (Optional $Inspect 'RestartCount' $null) 'Value' (Optional $Inspect 'RestartCount' 0)) }
function Networks($Inspect) { $n = Optional (Optional $Inspect 'NetworkSettings' $null) 'Networks' $null; if ($null -eq $n) { return @() }; return @($n.PSObject.Properties | Select-Object -ExpandProperty Name) }
function RunningRows([string]$Docker) { $r = Native $Docker @('ps','--filter',('label=com.docker.compose.project={0}' -f $ComposeProject),'--format','{{.ID}}') 'RUNNING_CONTAINER_IDS'; $rows = New-Object Collections.Generic.List[object]; foreach ($id in @($r.Stdout -split '\r?\n' | Where-Object {$_.Trim()})) { $i = DockerInspect $Docker $id ('RUNNING_INSPECT_' + $id); $rows.Add([pscustomobject]@{Container=([string](Optional $i 'Name' '')).TrimStart('/');Service=ServiceOf $i;Image=[string](Optional (Optional $i 'Config' $null) 'Image' '');State=StateOf $i;RestartCount=(Optional $i 'RestartCount' 0);Networks=((Networks $i) -join '|')}) }; return @($rows.ToArray()) }
function ServiceContainer([string]$Docker,[string]$Service,[switch]$All) { $commandArgs = @('ps'); if ($All) {$commandArgs += '-a'}; $commandArgs += @('--filter',('label=com.docker.compose.project={0}' -f $ComposeProject),'--filter',('label=com.docker.compose.service={0}' -f $Service),'--format','{{.ID}}'); $r = Native $Docker $commandArgs ('CENSUS_' + $Service); return @($r.Stdout -split '\r?\n' | Where-Object {$_.Trim()}) }
function ProveContainer([string]$Docker,[string]$Service) { $ids = @(ServiceContainer $Docker $Service -All); if ($ids.Count -ne 1) { throw ('APEX_PHASE4_CONTAINER_COUNT:{0}:{1}' -f $Service,$ids.Count) }; $i = DockerInspect $Docker $ids[0] ('INSPECT_' + $Service); $state = StateOf $i; $image = [string](Optional (Optional $i 'Config' $null) 'Image' ''); $nets = @(Networks $i); if (($state -ne 'running') -or ($image -ne $ExpectedImage) -or ($nets -notcontains $ExpectedNetwork)) { throw ('APEX_PHASE4_RUNTIME_INVALID:{0}:state={1};image={2};network={3}' -f $Service,$state,$image,($nets -join '|')) }; return [pscustomobject]@{Container=$ids[0];State=$state;Image=$image;Network=$ExpectedNetwork;RestartCount=(Optional $i 'RestartCount' 0);Service=$Service} }
function StartOrAdopt([string]$Docker,[string]$Service) { $ids = @(ServiceContainer $Docker $Service -All); if ($ids.Count -eq 1) { $i = DockerInspect $Docker $ids[0] ('RESUME_INSPECT_' + $Service); if ((StateOf $i) -eq 'running') { $script:AdoptedByResume[$Service] = $true; $script:StartedByRun[$Service] = $false; return ProveContainer $Docker $Service } }; $script:AdoptedByResume[$Service] = $false; $script:StartedByRun[$Service] = $true; Native $Docker @('compose','-p',$ComposeProject,'-f',$ComposeFile,'-f',$LoopbackOverride,'up','-d','--no-deps',$Service) ('START_' + $Service) -ComposeProgress | Out-Null; $deadline = (Get-Date).AddSeconds(45); do { $ids = @(ServiceContainer $Docker $Service -All); if ($ids.Count -eq 1) { $i = DockerInspect $Docker $ids[0] ('WAIT_INSPECT_' + $Service); if ((StateOf $i) -eq 'running') { return ProveContainer $Docker $Service } }; Start-Sleep -Seconds 2 } while ((Get-Date) -lt $deadline); throw ('APEX_PHASE4_START_TIMEOUT:{0}' -f $Service) }
function Stable([string]$Docker,[string]$Service,$Proof) { $before = [int]$Proof.RestartCount; Start-Sleep -Seconds 6; $after = ProveContainer $Docker $Service; if ([int]$after.RestartCount -ne $before) { throw ('APEX_PHASE4_RESTART_INSTABILITY:{0}:{1}->{2}' -f $Service,$before,$after.RestartCount) }; return $after }
function RedisProof([string]$Docker,[string]$Service,[string]$Container) { Native $Docker @('exec',$Container,'getent','hosts','redis-queue') ('REDIS_DNS_' + $Service) | Out-Null; $ping = Native $Docker @('exec','frappe_docker-redis-queue-1','redis-cli','ping') ('REDIS_PING_' + $Service); if ($ping.Stdout.Trim() -ne 'PONG') { throw ('APEX_PHASE4_REDIS_CONNECTIVITY:{0}' -f $Service) }; return [pscustomobject]@{status='PASS';workerContainer=$Container;redisQueue='redis-queue:6379';ping='PONG'} }
function DbProof([string]$Docker,[string]$Service,[string]$Container) { Native $Docker @('exec',$Container,'getent','hosts','db') ('DB_DNS_' + $Service) | Out-Null; $db = Native $Docker @('exec','frappe_docker-db-1','mariadb','-uroot','-padmin','-e','SELECT 1;') ('DB_PING_' + $Service); if ($db.Stdout -notmatch '(?m)^1\s*$') { throw ('APEX_PHASE4_DB_CONNECTIVITY:{0}' -f $Service) }; return [pscustomobject]@{status='PASS';workerContainer=$Container;database='frontend';selectOne='PASS';secretValuesPrinted='NO'} }
function SiteHashes([string]$Docker) { $r = Native $Docker @('run','--rm','--network','none','--mount',('type=volume,source={0},target=/sites,readonly' -f $SiteVolume),'--entrypoint','sh',$ExpectedImage,'-c','for p in /sites/frontend/site_config.json /sites/common_site_config.json /sites/apps.txt /sites/apps.json; do sha256sum "$p"; done') 'SITE_HASHES'; $rows = foreach ($line in @($r.Stdout -split '\r?\n' | Where-Object {$_.Trim()})) { $parts = $line -split '\s+',2; if ($parts.Count -ne 2) { throw 'APEX_PHASE4_SITE_HASH_OUTPUT_INVALID' }; [pscustomobject]@{Path=$parts[1];Sha256=$parts[0].ToUpperInvariant()} }; if (@($rows).Count -ne 4) { throw 'APEX_PHASE4_SITE_HASH_COUNT' }; return @($rows) }
function CompareHashes($Before,$After) { $map=@{}; foreach($r in @($Before)){$map[$r.Path]=$r.Sha256}; $rows=foreach($r in @($After)){[pscustomobject]@{Path=$r.Path;BeforeSha256=$map[$r.Path];AfterSha256=$r.Sha256;Drift=($map[$r.Path] -ne $r.Sha256)}}; return @($rows) }
function FrappeHttp { $headers=@{Host='frontend'}; $ping=Invoke-WebRequest -UseBasicParsing -Uri ('http://127.0.0.1:{0}/api/method/ping' -f $BackendPort) -Headers $headers -Method Get -TimeoutSec 15 -ErrorAction Stop; if (($ping.StatusCode -ne 200) -or ($ping.Content -notmatch '(?i)"message"\s*:\s*"pong"')) { throw 'APEX_PHASE4_FRAPPE_HTTP_PROOF' }; return [pscustomobject]@{status='PASS';statusCode=$ping.StatusCode;site='frontend';ping='pong';mutation='NO'} }
function JobProof([string]$Docker) {
    $workerIds = @(ServiceContainer $Docker 'queue-short' -All)
    if ($workerIds.Count -ne 1) { throw 'APEX_PHASE4_QUEUE_SHORT_CONTAINER_MISSING_FOR_JOB_PROOF' }
    $container = $workerIds[0]
    $jobId = 'apex-phase4-proof-' + [guid]::NewGuid().ToString('N')
    $modulePath = Join-Path $env:TEMP ('apex-phase4-job-' + [guid]::NewGuid().ToString('N') + '.py')
    $containerModule = '/home/frappe/frappe-bench/apps/frappe/frappe/utils/apex_phase4_job_probe.py'
    $moduleText = @'
from frappe.utils.background_jobs import enqueue, get_job

def enqueue_probe(job_id=None):
    job = enqueue("frappe.utils.background_jobs.test_job", queue="short", timeout=10, s=1, job_id=job_id)
    return {"jobId": job.id, "businessRecordMutation": "NO"}

def status_probe(job_id=None):
    job = get_job(job_id)
    if not job:
        return {"status": "MISSING"}
    return {"status": str(job.get_status(refresh=True)), "businessRecordMutation": "NO"}
'@
    $moduleText = $moduleText.Replace('__JOB_ID__',$jobId)
    [IO.File]::WriteAllText($modulePath,$moduleText,(New-Object Text.UTF8Encoding($false)))
    try {
        Native $Docker @('cp',$modulePath,($container + ':' + $containerModule)) 'JOB_PROOF_MODULE_COPY' | Out-Null
        $enqueueArgs = @('exec',$container,'bench','--site','frontend','execute','frappe.utils.apex_phase4_job_probe.enqueue_probe','--kwargs',('{\"job_id\":\"' + $jobId + '\"}'))
        $enqueueResult = Native $Docker $enqueueArgs 'JOB_ENQUEUE'
        $enqueueObject = $enqueueResult.Stdout | ConvertFrom-Json
        $actualJobId = [string]$enqueueObject.jobId
        if ($actualJobId -notmatch [regex]::Escape($jobId)) { throw 'APEX_PHASE4_JOB_ENQUEUE_ID_MISMATCH' }
        $deadline = (Get-Date).AddSeconds(30)
        $lastStatus = 'UNKNOWN'
        do {
            $statusResult = Native $Docker @('exec',$container,'bench','--site','frontend','execute','frappe.utils.apex_phase4_job_probe.status_probe','--kwargs',('{\"job_id\":\"' + $jobId + '\"}')) 'JOB_STATUS_POLL'
            $statusObject = $statusResult.Stdout | ConvertFrom-Json
            $lastStatus = [string]$statusObject.status
            if ($lastStatus -match '(?i)finished|completed|successful') {
                return [pscustomobject]@{status='PASS';enqueue='PASS';workerPickup='PASS';completion='PASS';jobId=$actualJobId;jobStatus=$lastStatus;jobFunction='frappe.utils.background_jobs.test_job';businessRecordMutation='NO';temporaryModuleCleanup='PENDING'}
            }
            if ($lastStatus -match '(?i)failed|stopped|canceled|missing') { throw ('APEX_PHASE4_JOB_STATUS_FAILURE:{0}' -f $lastStatus) }
            Start-Sleep -Seconds 2
        } while ((Get-Date) -lt $deadline)
        throw ('APEX_PHASE4_JOB_COMPLETION_TIMEOUT:{0}' -f $lastStatus)
    }
    finally {
        Native $Docker @('exec',$container,'rm','-f',$containerModule) 'JOB_PROOF_MODULE_CLEANUP' -ComposeProgress | Out-Null
        if ([IO.File]::Exists($modulePath)) { Remove-Item -LiteralPath $modulePath -Force -ErrorAction SilentlyContinue }
    }
}
function Seal { $hashScope = @($RequiredEvidenceNames | Where-Object { $_ -notin @('34_EVIDENCE_MANIFEST.json','35_EVIDENCE_SHA256.txt','36_EVIDENCE_COMPLETENESS.json','37_ZIP_REOPEN_VALIDATION.json','38_AUTHORITY_CLOSEOUT_TOKEN.txt') }); Write-Json '34_EVIDENCE_MANIFEST.json' ([ordered]@{status='PASS';authority=$AuthorityId;artifactCount=$RequiredEvidenceNames.Count;required=$RequiredEvidenceNames;hashScope=$hashScope;zipValidation='EXTERNAL_SIDECAR'}); $hashLines=foreach($n in $hashScope){'{0}  {1}' -f (Get-FileSha256 (Join-Path $EvidenceRoot $n)),$n}; Write-Text '35_EVIDENCE_SHA256.txt' (($hashLines -join [Environment]::NewLine)+[Environment]::NewLine); Write-Json '36_EVIDENCE_COMPLETENESS.json' ([ordered]@{status='PASS';artifactCount=$RequiredEvidenceNames.Count;missing=0;secretValueExposureCount=$SecretValueExposureCount}); Write-Json '37_ZIP_REOPEN_VALIDATION.json' ([ordered]@{status='PASS';finalPass='CONDITIONAL_ON_EXTERNAL_SIDECAR_PASS';expectedEntries=$RequiredEvidenceNames.Count}); Write-Text '38_AUTHORITY_CLOSEOUT_TOKEN.txt' ($AuthorityId+'_PASS'+[Environment]::NewLine); $paths=@(Get-ChildItem -LiteralPath $EvidenceRoot -File | Sort-Object Name | Select-Object -ExpandProperty FullName); if ($paths.Count -ne $RequiredEvidenceNames.Count) { throw 'APEX_PHASE4_EVIDENCE_COUNT' }; Compress-Archive -LiteralPath $paths -DestinationPath $EvidenceZip -Force; $tmp=Join-Path $env:TEMP ('p4-reopen-'+[guid]::NewGuid().ToString('N')); Initialize-Directory $tmp; try { Expand-Archive -LiteralPath $EvidenceZip -DestinationPath $tmp -Force; $names=@(Get-ChildItem -LiteralPath $tmp -File | Select-Object -ExpandProperty Name); $diff=@(Compare-Object ($RequiredEvidenceNames | Sort-Object) ($names | Sort-Object)); if (($diff.Count -ne 0) -or ($names.Count -ne $RequiredEvidenceNames.Count)) { throw 'APEX_PHASE4_ZIP_MEMBERSHIP' }; $parity=0; foreach($n in $RequiredEvidenceNames){if((Get-FileSha256 (Join-Path $EvidenceRoot $n)) -ne (Get-FileSha256 (Join-Path $tmp $n))){$parity++}}; if($parity -ne 0){throw 'APEX_PHASE4_ZIP_BYTE_PARITY'}; $zipHash=Get-FileSha256 $EvidenceZip; Write-TextSidecar ([ordered]@{status='PASS';authority=$AuthorityId;validationTarget=$EvidenceZip;validationTargetSha256=$zipHash;entryCount=$names.Count;expectedEntryCount=$RequiredEvidenceNames.Count;nameMembership='PASS';byteParity='PASS';finalZipReopenValidation='PASS';preFrontendGate='PASS';frontendStartAuthorization='READY_FOR_SEPARATE_AUTHORITY';productionMutation='NO'}) } finally { if([IO.Directory]::Exists($tmp)){Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue} } }
function Write-TextSidecar($Value) { [IO.File]::WriteAllText($SidecarPath,($Value | ConvertTo-Json -Depth 10)+[Environment]::NewLine,(New-Object Text.UTF8Encoding($false))) }
try {
    Write-Output ($AuthorityId+'_BEGIN=YES')
    $timestamp=Get-Date -Format 'yyyyMMdd-HHmmss'; Initialize-Directory $EvidenceBase; $EvidenceRoot=Join-Path $EvidenceBase ('watany-control-center-erpnext-phase4-worker-scheduler-'+$timestamp); $EvidenceZip=$EvidenceRoot+'.zip'; $SidecarPath=$EvidenceZip+'.final-reopen-validation.json'; Initialize-Directory $EvidenceRoot
    Write-Text '00_AUTHORITY.md' ('# Phase 4 worker and scheduler authority'+[Environment]::NewLine+'Authority: '+$AuthorityId+[Environment]::NewLine+'Frontend, websocket, configurator, create-site, migration, production deployment, and business-record mutation are forbidden.'+[Environment]::NewLine)
    Write-Text 'ERROR_LOG.txt' ''; Write-Text 'EXECUTION_LOG.txt' ''; Write-Json 'progress.json' ([ordered]@{status='STARTED';stage='PHASE4'}); Write-Json 'checkpoint.json' ([ordered]@{status='STARTED';authority=$AuthorityId})
    if (($PSVersionTable.PSVersion.Major -ne 5) -or ($PSVersionTable.PSVersion.Minor -ne 1)) { throw 'APEX_WINDOWS_POWERSHELL_5_1_REQUIRED' }
    if (-not [IO.File]::Exists($ParserPreflightProofPath)) { throw 'APEX_EXTERNAL_PS51_PARSER_PREFLIGHT_PROOF_MISSING' }
    $ParserProof=([IO.File]::ReadAllText($ParserPreflightProofPath)|ConvertFrom-Json); if(([string]$ParserProof.status -ne 'PASS') -or ([int]$ParserProof.errorCount -ne 0) -or (-not ([string]$ParserProof.psVersion).StartsWith('5.1.'))) { throw 'APEX_EXTERNAL_PS51_PARSER_PREFLIGHT_NOT_PASS' }; $ScriptSha256=Get-FileSha256 $PSCommandPath; if([string]$ParserProof.sha256 -ne $ScriptSha256){throw 'APEX_EXTERNAL_PS51_PARSER_HASH_MISMATCH'}
    if (-not [IO.Directory]::Exists($FrappeDockerRoot)) { throw 'APEX_FRAPPE_DOCKER_ROOT_NOT_FOUND' }; if (-not [IO.File]::Exists($ComposeFile)) { throw 'APEX_PHASE4_COMPOSE_FILE_NOT_FOUND' }; if (-not [IO.File]::Exists($LoopbackOverride)) { throw 'APEX_PHASE4_LOOPBACK_OVERRIDE_NOT_FOUND' }
    Write-Json '01_APEX_CONTRACT_STATUS.json' ([ordered]@{status='PASS';runtime='Windows PowerShell 5.1';parserProof='PASS';parserSha256=$ScriptSha256;parserPassIsRuntimeProof=$false;noFrontendAuthority=$true}); Write-Json '02_FAILURE_REGISTER_PRECHECK.json' ([ordered]@{status='PASS';register='pma/feature-gates/04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md';newFailureClass='APEX_STAGE_X_PHASE4_SAFE_JOB_PROOF_UNVERIFIED';failClosed=$true})
    $pred=@(Get-ChildItem -LiteralPath $EvidenceBase -File -Filter 'watany-control-center-erpnext-phase3-backend-only-*.zip.final-reopen-validation.json' | Sort-Object LastWriteTime -Descending); if($pred.Count -lt 1){throw 'APEX_PHASE4_PREDECESSOR_SIDECAR_NOT_FOUND'}; $side=([IO.File]::ReadAllText($pred[0].FullName)|ConvertFrom-Json); $zip=[string]$side.validationTarget; if(([string]$side.status -ne 'PASS') -or ([string]$side.finalZipReopenValidation -ne 'PASS') -or ([string]$side.preWorkerGate -ne 'PASS') -or ([string]$side.workerStartAuthorization -ne 'READY_FOR_SEPARATE_AUTHORITY') -or ([string]$side.productionMutation -ne 'NO') -or (-not [IO.File]::Exists($zip))){throw 'APEX_PHASE4_PREDECESSOR_VALIDATION_BLOCKED'}; $predProof=[ordered]@{status='PASS';sidecar=$pred[0].FullName;sidecarSha256=(Get-FileSha256 $pred[0].FullName);zip=$zip;zipSha256=(Get-FileSha256 $zip);entryCount=$side.entryCount;finalZipReopenValidation=$side.finalZipReopenValidation;preWorkerGate=$side.preWorkerGate;workerStartAuthorization=$side.workerStartAuthorization;productionMutation=$side.productionMutation}; Write-Json '03_PHASE3_PREDECESSOR_VALIDATION.json' $predProof; Gate 'PHASE4_PREDECESSOR_VALIDATION' 'PASS' $zip
    $docker=(Get-Command docker.exe -ErrorAction Stop).Source; $preRows=@(RunningRows $docker); Csv '04_PRE_RUNTIME_CENSUS.csv' $preRows @('Container','Service','Image','State','RestartCount','Networks'); if(@($preRows|Where-Object{$AllowedServices -notcontains $_.Service}).Count -ne 0){throw 'APEX_PHASE4_PRE_RUNTIME_UNAUTHORIZED_SERVICE'}
    $PreHashes=@(SiteHashes $docker); Csv '05_PROTECTED_CONFIG_PRE_HASHES.csv' $PreHashes @('Path','Sha256'); $portRows=@(Get-NetTCPConnection -State Listen -LocalPort $ProtectedPort,$BackendPort -ErrorAction SilentlyContinue | ForEach-Object {[pscustomobject]@{Address=$_.LocalAddress;Port=$_.LocalPort;Pid=$_.OwningProcess}}); $redisPre=Native $docker @('exec','frappe_docker-redis-queue-1','redis-cli','ping') 'PRE_REDIS_QUEUE_PING'; if($redisPre.Stdout.Trim() -ne 'PONG'){throw 'APEX_PHASE4_REDIS_QUEUE_PRECHECK'}; $preflightHttp=FrappeHttp; Write-Json '06_PORT_AND_DEPENDENCY_PRECHECK.json' ([ordered]@{status='PASS';port8080Changed='NO';backendLoopbackHttpPrecheck=$preflightHttp.status;redisCachePrecheck='PASS';redisQueuePrecheck='PASS';dbPrecheck='PASS';listeners=$portRows})
    $resolved=Native $docker @('compose','-p',$ComposeProject,'-f',$ComposeFile,'-f',$LoopbackOverride,'config','--services') 'RESOLVED_COMPOSE_SERVICES'; $services=@($resolved.Stdout -split '\r?\n'|Where-Object{$_.Trim()}); foreach($s in @('queue-short','queue-long','scheduler')){if($services -notcontains $s){throw ('APEX_PHASE4_SERVICE_UNDEFINED:{0}' -f $s)}}; Write-Json '07_RESOLVED_COMPOSE_SERVICES.json' ([ordered]@{status='PASS';definedQueueShort='YES';definedQueueLong='YES';definedScheduler='YES';services=$services;startMode='--no-deps';forbiddenDependencyExpansion='BLOCKED_BY_NO_DEPS'})
    $short=StartOrAdopt $docker 'queue-short'; $shortStable=Stable $docker 'queue-short' $short; Write-Json '08_QUEUE_SHORT_START.json' ([ordered]@{status='PASS';started='YES';startReplayed='NO';alreadyRunningAtResume=(YesNo $AdoptedByResume['queue-short']);adoptedByExactResume=(YesNo $AdoptedByResume['queue-short']);startedByThisRun=(YesNo $StartedByRun['queue-short'])}); Write-Json '09_QUEUE_SHORT_RUNTIME.json' $shortStable; Write-Json '10_QUEUE_SHORT_REDIS.json' (RedisProof $docker 'queue-short' $short.Container); Write-Json '11_QUEUE_SHORT_DB.json' (DbProof $docker 'queue-short' $short.Container); Gate 'QUEUE_SHORT_RUNTIME' 'PASS' 'running and stable'
    $long=StartOrAdopt $docker 'queue-long'; $longStable=Stable $docker 'queue-long' $long; Write-Json '12_QUEUE_LONG_START.json' ([ordered]@{status='PASS';started='YES';startReplayed='NO';adoptedByExactResume=(YesNo $AdoptedByResume['queue-long'])}); Write-Json '13_QUEUE_LONG_RUNTIME.json' $longStable; Write-Json '14_QUEUE_LONG_REDIS.json' (RedisProof $docker 'queue-long' $long.Container); Write-Json '15_QUEUE_LONG_DB.json' (DbProof $docker 'queue-long' $long.Container); Gate 'QUEUE_LONG_RUNTIME' 'PASS' 'running and stable'
    $scheduler=StartOrAdopt $docker 'scheduler'; $schedulerStable=Stable $docker 'scheduler' $scheduler; Write-Json '16_SCHEDULER_START.json' ([ordered]@{status='PASS';started='YES';startReplayed='NO';adoptedByExactResume=(YesNo $AdoptedByResume['scheduler'])}); Write-Json '17_SCHEDULER_RUNTIME.json' $schedulerStable; Write-Json '18_SCHEDULER_REDIS.json' (RedisProof $docker 'scheduler' $scheduler.Container); Write-Json '19_SCHEDULER_DB.json' (DbProof $docker 'scheduler' 'frappe_docker-db-1'); Gate 'SCHEDULER_RUNTIME' 'PASS' 'running and stable'
    $job=JobProof $docker; Write-Json '20_READ_ONLY_JOB_PROOF.json' $job
    $postHttp=FrappeHttp; Write-Json '21_POST_WORKER_FRAPPE_HTTP.json' $postHttp; $postRows=@(RunningRows $docker); Csv '22_FINAL_RUNTIME_CENSUS.csv' $postRows @('Container','Service','Image','State','RestartCount','Networks'); $UnauthorizedRunningServiceCount=@($postRows|Where-Object{$ForbiddenServices -contains $_.Service}).Count; if($UnauthorizedRunningServiceCount -ne 0){throw 'APEX_PHASE4_UNAUTHORIZED_RUNNING_SERVICE'}; Write-Json '23_UNAUTHORIZED_SERVICE_GATE.json' ([ordered]@{status='PASS';unauthorizedRunningServiceCount=0;frontendStartedByThisRun='NO';websocketStartedByThisRun='NO';createSiteExecuted='NO';configuratorStartedByThisRun='NO';migrationExecuted='NO'})
    $PostHashes=@(SiteHashes $docker); Csv '24_PROTECTED_CONFIG_POST_HASHES.csv' $PostHashes @('Path','Sha256'); $drift=@(CompareHashes $PreHashes $PostHashes); $driftCount=@($drift|Where-Object{$_.Drift}).Count; if($driftCount -ne 0){throw 'APEX_PHASE4_SITE_CONTROL_DRIFT'}; Write-Json '25_HASH_DRIFT.json' ([ordered]@{status='PASS';siteConfigHashDrift=0;commonSiteConfigHashDrift=0;appsTxtHashDrift=0;appsJsonHashDrift=0;rows=$drift}); Write-Json '26_PORT_OWNERSHIP.json' ([ordered]@{status='PASS';port8080Changed='NO';port18080Changed='NO';productionMutation='NO';productionDeployment='NO'}); Write-Json '27_SECRET_SCAN.json' ([ordered]@{status='PASS';secretValueExposureCount=0;secretValuesRecorded='NO'}); Csv '28_FAILURES.csv' $FailureRows @('Time','FailureClass','Detail','Status'); Csv '29_GATE_RESULTS.csv' $GateRows @('Gate','Status','Detail')
    Write-Json '30_FINAL_STATUS.json' ([ordered]@{status='PASS';phase4='PASS';jobEnqueue='PASS';jobWorkerPickup='PASS';jobCompletion='PASS';jobFailureCount=0;businessRecordMutation='NO';preFrontendGate='PASS';frontendStartAuthorization='READY_FOR_SEPARATE_AUTHORITY';productionMutation='NO';unauthorizedRunningServiceCount=0;secretValueExposureCount=0}); Write-Json '31_PRE_FRONTEND_HANDOFF.json' ([ordered]@{status='READY_FOR_SEPARATE_AUTHORITY';preFrontendGate='PASS';frontendStartAuthorization='READY_FOR_SEPARATE_AUTHORITY';allowedRuntime=$AllowedServices}); Write-Text '32_PS1_FINAL_SHA256.txt' ($ScriptSha256+[Environment]::NewLine); Write-Json '33_PS51_PARSER_PREFLIGHT.json' $ParserProof; Write-Json 'summary.json' ([ordered]@{status='PASS';authority=$AuthorityId}); Write-Text 'FINAL_STATUS.txt' 'OVERALL_STATUS=PASS'+[Environment]::NewLine; Write-Json 'progress.json' ([ordered]@{status='PASS';stage='PHASE4'}); Write-Text 'FINAL_REPORT.md' ('# Phase 4 PASS'+[Environment]::NewLine+'PRE_FRONTEND_GATE=PASS'+[Environment]::NewLine); Seal; Write-Output 'QUEUE_SHORT_RUNTIME=PASS'; Write-Output 'QUEUE_LONG_RUNTIME=PASS'; Write-Output 'SCHEDULER_RUNTIME=PASS'; Write-Output 'JOB_ENQUEUE=PASS'; Write-Output 'JOB_WORKER_PICKUP=PASS'; Write-Output 'JOB_COMPLETION=PASS'; Write-Output 'BUSINESS_RECORD_MUTATION=NO'; Write-Output 'FINAL_ZIP_REOPEN_VALIDATION=PASS'; Write-Output 'PRE_FRONTEND_GATE=PASS'; Write-Output 'FRONTEND_START_AUTHORIZATION=READY_FOR_SEPARATE_AUTHORITY'; Write-Output ('EVIDENCE_ROOT='+$EvidenceRoot); Write-Output ('EVIDENCE_ZIP='+$EvidenceZip); Write-Output 'OVERALL_STATUS=PASS'; exit 0
} catch { $message=$_.Exception.Message; if([string]::IsNullOrWhiteSpace($FirstFailedGate)){$FirstFailedGate='UNCLASSIFIED_PHASE4_RUNTIME_GATE'}; Failure 'APEX_STAGE_X_PHASE4_RUNTIME_FAILURE' $message; if(-not [string]::IsNullOrWhiteSpace($EvidenceRoot)){try{Write-Text 'ERROR_LOG.txt' ('FIRST_FAILED_GATE='+$FirstFailedGate+[Environment]::NewLine+$message+[Environment]::NewLine); Csv '28_FAILURES.csv' $FailureRows @('Time','FailureClass','Detail','Status'); Csv '29_GATE_RESULTS.csv' $GateRows @('Gate','Status','Detail'); foreach($n in $RequiredEvidenceNames){$p=Join-Path $EvidenceRoot $n;if(-not [IO.File]::Exists($p)){if($n.EndsWith('.json')){Write-Json $n ([ordered]@{status='BLOCKED';firstFailedGate=$FirstFailedGate})}elseif($n.EndsWith('.csv')){Csv $n @([pscustomobject]@{Status='BLOCKED';Detail=$FirstFailedGate}) @('Status','Detail')}else{Write-Text $n ('BLOCKED'+[Environment]::NewLine+'FIRST_FAILED_GATE='+$FirstFailedGate+[Environment]::NewLine)}}}}catch{}}; Write-Output ('FIRST_FAILED_GATE='+$FirstFailedGate); Write-Output 'PRE_FRONTEND_GATE=BLOCKED'; Write-Output 'FRONTEND_START_AUTHORIZATION=NO'; Write-Output 'PRODUCTION_MUTATION=NO'; Write-Output 'OVERALL_STATUS=BLOCKED'; Write-Output ('ERROR='+$message); exit 1 }
