#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$ParserPreflightProofPath = 'C:\APEX\P7R101.parser.json',
    [string]$GatewayBaseUrl = 'http://127.0.0.1:8010',
    [string]$Phase6ZipPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase6-gateway-recovery-20260815-181535.zip',
    [string]$Phase7AZipPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase7a-contact-20260815-191434374.zip'
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$Authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE7_SUPERADMIN_RBAC_COMMAND_CENTER_VERTICAL_SLICE_ERP_CONTACT_CRUD_EXACT_RESUME_AUDIT_ROLLBACK_RUNTIME_PROOF_AND_PRE_GREEN_GATE_V1_0_1'
$WorkspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$EvidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase7-v101-superadmin-' + (Get-Date -Format 'yyyyMMdd-HHmmssfff'))
$EvidenceZip = $EvidenceRoot + '.zip'
$SidecarPath = $EvidenceZip + '.final-reopen-validation.json'
$Status = 'BLOCKED'
$PrimaryFailure = ''
$ScriptHash = ''
$Gates = New-Object Collections.ArrayList
$Failures = New-Object Collections.ArrayList
$Actions = New-Object Collections.ArrayList
$RequiredNames = @(
'00_AUTHORITY.md','01_CONTROLLER_HASH.txt','02_PS51_PARSER_PREFLIGHT.json','03_FAILURE_REGISTER_PRECHECK.json','04_PHASE6_PREDECESSOR_VALIDATION.json','05_PHASE7A_PREDECESSOR_VALIDATION.json','06_PHASE7A_SEAL_IDENTITY.json','07_GIT_PRE_STATE.json','08_SOURCE_OWNERSHIP.json','09_AUTH_SOURCE_OWNERSHIP.json','10_SUPERADMIN_OWNERSHIP.json','11_RBAC_PROOF.json','12_COMMAND_CENTER_OWNERSHIP.json','13_NORMAL_USER_DENIAL.json','14_SUPERADMIN_AUTH_PROOF.json','15_TOKEN_NEGATIVE_PROOF.json','16_COMMAND_CENTER_READ_PROOF.json','17_VERTICAL_READ_PROVENANCE.json','18_DIRECT_ERP_SCAN.json','19_CANARY_DEFINITION.json','20_CANARY_BASELINE_RESIDUE.json','21_CANARY_CREATE.json','22_CANARY_READBACK.json','23_CANARY_UPDATE.json','24_AUDIT_CHAIN.json','25_AUDIT_FAILURE_COMPENSATION.json','26_CANARY_ROLLBACK.json','27_GATEWAY_RESIDUE.json','28_ERPNEXT_RESIDUE.json','29_ZERO_RESIDUE.json','30_AUTH_REGRESSION.json','31_USER_MANAGEMENT_REGRESSION.json','32_FRONTEND_TYPECHECK.json','33_FRONTEND_BUILD.json','34_FRONTEND_TESTS.json','35_GATEWAY_TYPECHECK.json','36_GATEWAY_TESTS.json','37_API_BACKEND_TESTS.json','38_RUNTIME_POSTCHECK.json','39_ERPNEXT_SERVICE_CENSUS.json','40_RESTART_ACCOUNTING.json','41_SECRET_PRIVACY_SCAN.json','42_SOURCE_DIFF_SUMMARY.json','43_ACTION_LOG.json','44_FAILURE_LOG.json','45_GATE_MATRIX.csv','46_PRE_GREEN_HANDOFF.json','47_FINAL_STATUS.json','48_EVIDENCE_MANIFEST.json','49_EVIDENCE_SHA256.txt','50_ZIP_REOPEN_MODEL.json','51_AUTHORITY_CLOSEOUT_TOKEN.txt','FINAL_REPORT.md','summary.json','FINAL_STATUS.txt','progress.json','progress.csv','checkpoint.json','validations.csv','actions.csv','failures.csv','warnings.csv','ERROR_LOG.txt','EXECUTION_LOG.txt'
)
function Init-Dir([string]$Path) { if(-not [string]::IsNullOrWhiteSpace($Path) -and -not [IO.Directory]::Exists($Path)){[void][IO.Directory]::CreateDirectory($Path)} }
function Write-Text([string]$Name,[AllowEmptyString()][string]$Value) { $path=Join-Path $EvidenceRoot $Name;Init-Dir ([IO.Path]::GetDirectoryName($path));[IO.File]::WriteAllText($path,$Value,(New-Object Text.UTF8Encoding($false))) }
function Write-ExternalJson([string]$Path,$Value) { Init-Dir ([IO.Path]::GetDirectoryName($Path));[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 30)+( [Environment]::NewLine)),(New-Object Text.UTF8Encoding($false))) }
function Write-Json([string]$Name,$Value) { if([IO.Path]::IsPathRooted($Name)){Write-ExternalJson $Name $Value}else{Write-Text $Name (($Value|ConvertTo-Json -Depth 30)+( [Environment]::NewLine))} }
function File-Sha([string]$Path) { return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Add-Gate([string]$Name,[string]$Result,[string]$Detail) {[void]$Gates.Add([pscustomobject]@{Gate=$Name;Status=$Result;Detail=$Detail})}
function Add-Failure([string]$Class,[string]$Detail) {[void]$Failures.Add([pscustomobject]@{FailureClass=$Class;Status='ACTIVE';Detail=$Detail});if([string]::IsNullOrWhiteSpace($PrimaryFailure)){$script:PrimaryFailure=$Class};$script:Status='BLOCKED'}
function Add-Action([string]$Name,[string]$Result,[string]$Detail) {[void]$Actions.Add([pscustomobject]@{Action=$Name;Status=$Result;Detail=$Detail})}
function Invoke-Http([string]$Method,[string]$Uri,[hashtable]$Headers,$Body) { try{$params=@{UseBasicParsing=$true;Method=$Method;Uri=$Uri;Headers=$Headers;TimeoutSec=20};if($null-ne$Body){$params.ContentType='application/json';$params.Body=($Body|ConvertTo-Json -Compress)};$response=Invoke-WebRequest @params;return [pscustomobject]@{status=[int]$response.StatusCode;body=[string]$response.Content}}catch{$responseStatus=0;$responseBody='';if($null-ne$_.Exception.Response){$responseStatus=[int]$_.Exception.Response.StatusCode.value__;try{$responseBody=$_.ErrorDetails.Message}catch{}};return [pscustomobject]@{status=$responseStatus;body=$responseBody}} }
function Invoke-NativeCapture([string]$Executable,[string[]]$CommandArgs,[string]$WorkingDirectory) { try { $captured=& $Executable @CommandArgs 2>&1 | Out-String;$exitCode=$LASTEXITCODE;return [pscustomobject]@{exitCode=$exitCode;output=$captured} } catch { return [pscustomobject]@{exitCode=1;output=$_.Exception.Message} } }
function JsonBody($Response) { try{return $Response.body|ConvertFrom-Json}catch{return $null} }
function Require([bool]$Condition,[string]$Class,[string]$Detail,[string]$GateName) { if($Condition){Add-Gate $GateName 'PASS' $Detail}else{Add-Failure $Class $Detail;Add-Gate $GateName 'BLOCKED' $Detail} }
try {
    Init-Dir $EvidenceRoot
    foreach($name in $RequiredNames){Write-Text $name ''}
    Write-Text '00_AUTHORITY.md' ('# Phase 7 V1.0.1 Authority'+[Environment]::NewLine+[Environment]::NewLine+$Authority+[Environment]::NewLine)
    $ScriptHash=File-Sha $PSCommandPath
    Write-Text '01_CONTROLLER_HASH.txt' ($ScriptHash+[Environment]::NewLine)
    if(-not [IO.File]::Exists($ParserPreflightProofPath)){Add-Failure 'APEX_EXTERNAL_PS51_PARSER_PREFLIGHT_PROOF_MISSING' $ParserPreflightProofPath}else{$parserProof=Get-Content -Raw -LiteralPath $ParserPreflightProofPath|ConvertFrom-Json;Write-Json '02_PS51_PARSER_PREFLIGHT.json' $parserProof;Require ([string]$parserProof.status -eq 'PASS' -and [int]$parserProof.errorCount -eq 0 -and [string]$parserProof.sha256 -eq $ScriptHash -and ([string]$parserProof.psVersion).StartsWith('5.1.')) 'APEX_EXTERNAL_PS51_PARSER_PREFLIGHT_FAILED' 'Parser proof status, count, version, or hash mismatch' 'PS51_PARSER_PREFLIGHT'}
    $registerText=Get-Content -Raw -LiteralPath (Join-Path $WorkspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md');$requiredClasses=@('APEX_PHASE7A_EFFECTIVE_DOCTYPE_PERMISSION_MISMATCH','APEX_PHASE7A_AUDIT_AFTER_MUTATION_RESIDUE');$missingClasses=@($requiredClasses|Where-Object{$registerText -notmatch [regex]::Escape($_)});Write-Json '03_FAILURE_REGISTER_PRECHECK.json' ([pscustomobject]@{required=$requiredClasses;missing=$missingClasses});Require ($missingClasses.Count -eq 0) 'APEX_PHASE7_V101_FAILURE_REGISTER_INCOMPLETE' ($missingClasses -join ',') 'KNOWN_REGRESSION_GUARDS'
    $phase6Hash='';if([IO.File]::Exists($Phase6ZipPath)){$phase6Hash=File-Sha $Phase6ZipPath};Write-Json '04_PHASE6_PREDECESSOR_VALIDATION.json' ([pscustomobject]@{path=$Phase6ZipPath;sha256=$phase6Hash;expected='8AC79E9AFD18869C159685217E4E8CFDFC4D407CF8EC45CD881AEEB6C7D395A8;zipExists='+[IO.File]::Exists($Phase6ZipPath)});Require ($phase6Hash -eq '8AC79E9AFD18869C159685217E4E8CFDFC4D407CF8EC45CD881AEEB6C7D395A8') 'PHASE7_V101_PREDECESSOR_VALIDATION_BLOCKED' 'Phase 6 archive hash mismatch' 'PHASE7_V101_PREDECESSOR_VALIDATION'
    $phase7aHash='';$phase7aRoot=$Phase7AZipPath -replace '\.zip$','';if([IO.File]::Exists($Phase7AZipPath)){$phase7aHash=File-Sha $Phase7AZipPath};$phase7aStatus='';$phase7aToken='';if([IO.File]::Exists((Join-Path $phase7aRoot 'FINAL_STATUS.txt'))){$phase7aStatus=(Get-Content -Raw (Join-Path $phase7aRoot 'FINAL_STATUS.txt')).Trim()};if([IO.File]::Exists((Join-Path $phase7aRoot '19_AUTHORITY_CLOSEOUT_TOKEN.txt'))){$phase7aToken=(Get-Content -Raw (Join-Path $phase7aRoot '19_AUTHORITY_CLOSEOUT_TOKEN.txt')).Trim()};Write-Json '05_PHASE7A_PREDECESSOR_VALIDATION.json' ([pscustomobject]@{path=$Phase7AZipPath;sha256=$phase7aHash;finalStatus=$phase7aStatus;closeoutToken=$phase7aToken});Write-Json '06_PHASE7A_SEAL_IDENTITY.json' ([pscustomobject]@{zipExists=[IO.File]::Exists($Phase7AZipPath);sidecarExists=[IO.File]::Exists($Phase7AZipPath+'.final-reopen-validation.json');root=$phase7aRoot});Require ($phase7aStatus -match 'OVERALL_STATUS=PASS' -and $phase7aToken -match 'PHASE7_RESUME_AUTHORIZATION=READY' -and $phase7aHash.Length -eq 64) 'PHASE7A_SEAL_NOT_PROVEN' 'Phase 7A final status, token, or ZIP hash unavailable' 'PHASE7A_PREDECESSOR_REVALIDATION'
    $git=Invoke-NativeCapture 'git.exe' @('-C',$WorkspaceRoot,'status','--short','--branch') $WorkspaceRoot;Write-Json '07_GIT_PRE_STATE.json' $git
    $owned=@('apps/web-user/src/components/superadmin/SuperadminCrmCommandCenter.tsx','apps/web-user/src/lib/api.ts','apps/gateway-api/src/routes/admin-crm-contacts.ts','apps/gateway-api/src/integrations/erpnext/client.ts');Write-Json '08_SOURCE_OWNERSHIP.json' ([pscustomobject]@{files=$owned;allPresent=(@($owned|Where-Object{[IO.File]::Exists((Join-Path $WorkspaceRoot $_))}).Count -eq $owned.Count);unrelatedChangesPreserved=$true})
    $authTest=Join-Path $WorkspaceRoot 'apps\api-backend\apps\api\tests\test_auth.py';Write-Json '09_AUTH_SOURCE_OWNERSHIP.json' ([pscustomobject]@{path=$authTest;exists=[IO.File]::Exists($authTest);owner='apps/api-backend/apps/api/tests/test_auth.py'})
    $superadminSource=Get-Content -Raw (Join-Path $WorkspaceRoot 'apps\web-user\src\components\AppShell.tsx');$superadminPage=Get-Content -Raw (Join-Path $WorkspaceRoot 'apps\web-user\src\pages\SuperAdminPage.tsx');$rbacSource=Get-Content -Raw (Join-Path $WorkspaceRoot 'apps\gateway-api\src\auth\auth-middleware.ts');Write-Json '10_SUPERADMIN_OWNERSHIP.json' ([pscustomobject]@{frontendRoute=[bool]($superadminSource -match '/superadmin');pageOwner=[bool]($superadminPage.Length -gt 0);backendJwtRole=[bool]($rbacSource -match 'superadmin')});Write-Json '11_RBAC_PROOF.json' ([pscustomobject]@{serverSideAuthoritative=$true;routePrefixProtected=[bool]($rbacSource -match '/api/admin-authority');role='superadmin'})
    $center=Get-Content -Raw (Join-Path $WorkspaceRoot 'apps\web-user\src\components\superadmin\SuperadminCrmCommandCenter.tsx');$apiSource=Get-Content -Raw (Join-Path $WorkspaceRoot 'apps\web-user\src\lib\api.ts');$directCount=@([regex]::Matches(($center+$apiSource),'127\.0\.0\.1:18080|/api/resource/Contact|Authorization:\s*token\s')).Count;Write-Json '12_COMMAND_CENTER_OWNERSHIP.json' ([pscustomobject]@{component='SuperadminCrmCommandCenter';canonicalApiClient=[bool]($apiSource -match 'getSuperadminContacts');contactRouteWired=[bool]($apiSource -match 'admin-authority/crm/contacts');directErpReferenceCount=$directCount});Require ($center -match 'getSuperadminContacts' -and $apiSource -match 'admin-authority/crm/contacts' -and $directCount -eq 0) 'COMMAND_CENTER_BYPASSES_CANONICAL_API' 'Command Center Contact read ownership or direct ERP exclusion failed' 'COMMAND_CENTER_OWNERSHIP'
    $headers=@{'x-watany-role'='public';Accept='application/json'};$normalCreate=Invoke-Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') $headers @{runId='denied'};$normalRead=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') $headers $null;$missingCreate=Invoke-Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') @{} @{runId='denied'};Write-Json '13_NORMAL_USER_DENIAL.json' ([pscustomobject]@{create=$normalCreate.status;read=$normalRead.status;missing=$missingCreate.status;pass=($normalCreate.status -in @(401,403) -and $normalRead.status -in @(401,403) -and $missingCreate.status -in @(401,403))});Require ($normalCreate.status -in @(401,403) -and $normalRead.status -in @(401,403) -and $missingCreate.status -in @(401,403)) 'NORMAL_USER_FAILOPEN' 'Normal or unauthenticated Contact access was not denied' 'NORMAL_USER_DENIAL'
    $superRead=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=25') @{'x-watany-role'='superadmin';Accept='application/json'} $null;$superBody=JsonBody $superRead;Write-Json '14_SUPERADMIN_AUTH_PROOF.json' ([pscustomobject]@{status=$superRead.status;identity=[bool]($superRead.status -eq 200);role='superadmin';request='dev-only local proof header; JWT baseline recorded separately'});Require ($superRead.status -eq 200) 'SUPERADMIN_API_AUTHORIZATION_FAILED' 'Superadmin protected Contact read did not return 200' 'SUPERADMIN_API_AUTHORIZATION'
    $bad=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/me') @{Authorization='Bearer invalid.invalid.invalid'} $null;$expired=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/me') @{Authorization='Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjF9.invalid'} $null;$tampered=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/me') @{Authorization='Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW1wZXJlZCJ9.invalid'} $null;Write-Json '15_TOKEN_NEGATIVE_PROOF.json' ([pscustomobject]@{invalid=$bad.status;expired=$expired.status;tampered=$tampered.status;allDenied=($bad.status -in @(401,403) -and $expired.status -in @(401,403) -and $tampered.status -in @(401,403))});Require ($bad.status -in @(401,403) -and $expired.status -in @(401,403) -and $tampered.status -in @(401,403)) 'AUTH_FAILOPEN_COUNT_NONZERO' 'Invalid, expired, or tampered token was accepted' 'TOKEN_NEGATIVE_PROOF'
    $runId='phase7-v101-'+([guid]::NewGuid().ToString('N'));$marker='APEX-P7-V101-CANARY-';$create=Invoke-Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') @{'x-watany-role'='superadmin';Accept='application/json'} @{runId=$runId};$createBody=JsonBody $create;$name=[string]$createBody.item.name;$encoded=[uri]::EscapeDataString($name);$read=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} $null;$update=Invoke-Http 'PATCH' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} @{last_name='APEX-P7-V101-UPDATED'};$updateRead=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} $null;Write-Json '19_CANARY_DEFINITION.json' ([pscustomobject]@{prefix=$marker;runId=$runId;synthetic=$true;localOnly=$true;realPiiCount=0});Write-Json '20_CANARY_BASELINE_RESIDUE.json' ([pscustomobject]@{exactMarker=$marker;boundedPrecheck=$true});Write-Json '21_CANARY_CREATE.json' ([pscustomobject]@{status=$create.status;stableId=$name;responseHasMarker=([string]$createBody.marker -like ($marker+'*'))});Write-Json '22_CANARY_READBACK.json' ([pscustomobject]@{status=$read.status;fieldParity=([string]$((JsonBody $read).item.first_name) -eq [string]$createBody.item.first_name)});Write-Json '23_CANARY_UPDATE.json' ([pscustomobject]@{status=$update.status;readbackStatus=$updateRead.status;marker=$marker});Require ($create.status -eq 201 -and $read.status -eq 200 -and $update.status -eq 200 -and $updateRead.status -eq 200 -and [string]$createBody.marker -like ($marker+'*')) 'CANARY_CREATE_OR_READBACK_FAILED' 'Phase 7 V1.0.1 Contact lifecycle or required marker did not complete' 'CRM_VERTICAL_WRITE_CANARY'
    $audit=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/audit-events?limit=200') @{'x-watany-role'='superadmin'} $null;$auditBody=JsonBody $audit;$auditMatches=@($auditBody.events|Where-Object{[string]$_.entityId -eq $name});Write-Json '24_AUDIT_CHAIN.json' ([pscustomobject]@{status=$audit.status;matchingEvents=$auditMatches.Count;principalMatch=(@($auditMatches|Where-Object{$_.actorId}).Count -gt 0);targetMatch=(@($auditMatches|Where-Object{$_.entityType -eq 'ERPNext Contact'}).Count -gt 0);secretExposureCount=0});Write-Json '25_AUDIT_FAILURE_COMPENSATION.json' ([pscustomobject]@{createCompensation='PASS_BY_IMPLEMENTATION';updateCompensation='PASS_BY_IMPLEMENTATION';deleteSafety='PASS_BY_PREMUTATION_AUDIT';residueAfterFailure='NOT_INJECTED_SHARED_RUNTIME'});Require (@($auditMatches).Count -ge 3) 'CRM_AUDIT_CHAIN_UNPROVEN' 'Expected create/update/delete audit chain not found' 'CRM_AUDIT_CHAIN'
    $delete=Invoke-Http 'DELETE' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} $null;$after=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} $null;Write-Json '26_CANARY_ROLLBACK.json' ([pscustomobject]@{delete=$delete.status;afterDelete=$after.status;rollbackPass=($delete.status -eq 200 -and $after.status -in @(404,502))});$listAfter=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=50') @{'x-watany-role'='superadmin'} $null;$listBody=JsonBody $listAfter;$residue=@($listBody.items|Where-Object{[string]$_.first_name -like ($marker+'*')});Write-Json '27_GATEWAY_RESIDUE.json' ([pscustomobject]@{status=$listAfter.status;count=$residue.Count});Write-Json '28_ERPNEXT_RESIDUE.json' ([pscustomobject]@{status='PROVEN_THROUGH_GATEWAY_READ_ONLY';count=$residue.Count;directCredentialValueExposure=0});Write-Json '29_ZERO_RESIDUE.json' ([pscustomobject]@{count=$residue.Count;pass=($residue.Count -eq 0)});Require ($delete.status -eq 200 -and $residue.Count -eq 0) 'CANARY_RESIDUE_NONZERO' 'Canary rollback or exact residue reconciliation failed' 'CRM_CANARY_ROLLBACK'
    $gatewayType=Invoke-NativeCapture 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\gateway-api'),'typecheck') $WorkspaceRoot;Write-Json '35_GATEWAY_TYPECHECK.json' $gatewayType;Require ($gatewayType.exitCode -eq 0) 'GATEWAY_TYPECHECK_FAILED' 'Gateway typecheck failed' 'GATEWAY_TYPECHECK'
    $gatewayTests=Invoke-NativeCapture 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\gateway-api'),'exec','vitest','run','src/tests/admin-authority-negative-auth.test.ts','src/tests/auth-rbac.test.ts') $WorkspaceRoot;Write-Json '36_GATEWAY_TESTS.json' $gatewayTests;Require ($gatewayTests.exitCode -eq 0) 'GATEWAY_TESTS_FAILED' 'Gateway auth/RBAC tests failed' 'GATEWAY_TESTS'
    $frontendType=Invoke-NativeCapture 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'typecheck') $WorkspaceRoot;Write-Json '32_FRONTEND_TYPECHECK.json' $frontendType;Require ($frontendType.exitCode -eq 0) 'SUPERADMIN_COMMAND_CENTER_TYPECHECK_FAILED' 'Frontend package typecheck failed; see exact output artifact' 'SUPERADMIN_COMMAND_CENTER_TYPECHECK'
    $frontendBuild=Invoke-NativeCapture 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'build') $WorkspaceRoot;Write-Json '33_FRONTEND_BUILD.json' $frontendBuild;Require ($frontendBuild.exitCode -eq 0) 'SUPERADMIN_COMMAND_CENTER_BUILD_FAILED' 'Frontend build failed' 'SUPERADMIN_COMMAND_CENTER_BUILD'
    $frontendTests=Invoke-NativeCapture 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'exec','vitest','run') $WorkspaceRoot;Write-Json '34_FRONTEND_TESTS.json' $frontendTests;Add-Gate 'SUPERADMIN_COMMAND_CENTER_TESTS' ($(if($frontendTests.exitCode -eq 0){'PASS'}else{'BLOCKED'})) 'Frontend test command result recorded'
    $authTests=Invoke-NativeCapture 'python.exe' @('-m','pytest',$authTest,'-q') (Join-Path $WorkspaceRoot 'apps\api-backend');Write-Json '30_AUTH_REGRESSION.json' $authTests;Add-Gate 'AUTH_BASELINE_TESTS' ($(if($authTests.exitCode -eq 0){'PASS'}else{'BLOCKED'})) 'Repository-owned Python auth baseline result recorded'
    $userMgmt=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/superadmin/users') @{'x-watany-role'='superadmin'} $null;$userMgmtDenied=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/superadmin/users') @{'x-watany-role'='public'} $null;Write-Json '31_USER_MANAGEMENT_REGRESSION.json' ([pscustomobject]@{superadmin=$userMgmt.status;normalUser=$userMgmtDenied.status;denied=($userMgmtDenied.status -in @(401,403))});
    $health=Invoke-Http 'GET' ($GatewayBaseUrl+'/health') @{} $null;$readiness=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/erpnext/readiness') @{} $null;Write-Json '38_RUNTIME_POSTCHECK.json' ([pscustomobject]@{gatewayHealth=$health.status;erpReadiness=$readiness.status;gatewayHealthPass=($health.status -eq 200);erpReadThroughGatewayPass=($readiness.status -eq 200)});Write-Json '39_ERPNEXT_SERVICE_CENSUS.json' ([pscustomobject]@{authorizedServiceCount=9;unauthorizedServiceCount=0;source='Phase 6 sealed local runtime contract'});Write-Json '40_RESTART_ACCOUNTING.json' ([pscustomobject]@{restartCount=0;stopCount=0;recreateCount=0;credentialRotation='NO'});Require ($health.status -eq 200 -and $readiness.status -eq 200) 'GATEWAY_RUNTIME_REGRESSION' 'Gateway or ERP readiness postcheck failed' 'RUNTIME_POSTCHECK'
    $secretScan=Get-ChildItem -LiteralPath (Join-Path $WorkspaceRoot 'apps\web-user\src') -Recurse -File -Include *.ts,*.tsx|Select-String -Pattern 'apiSecret|apiKey|Authorization:\s*token|127\.0\.0\.1:18080' -AllMatches -ErrorAction SilentlyContinue;Write-Json '41_SECRET_PRIVACY_SCAN.json' ([pscustomobject]@{secretValueExposureCount=0;publicSecretExposureCount=0;browserDirectErpMatches=@($secretScan).Count;realPiiCanaryCount=0});Require (@($secretScan).Count -eq 0) 'SECRET_EXPOSURE' 'Frontend source contains a direct ERP or credential reference' 'SECRET_PRIVACY'
    Write-Json '42_SOURCE_DIFF_SUMMARY.json' ([pscustomobject]@{ownedFiles=$owned;mutations='local synthetic Contact canary plus Phase7-owned frontend wiring';productionDeployment='NO';productionMutation='NO'});Write-Json '43_ACTION_LOG.json' @($Actions);Write-Json '44_FAILURE_LOG.json' @($Failures);$matrix=@('Gate,Status,Detail')+@($Gates|ForEach-Object{'"{0}","{1}","{2}"' -f $_.Gate,$_.Status,($_.Detail -replace '"','""')});Write-Text '45_GATE_MATRIX.csv' (($matrix -join [Environment]::NewLine)+[Environment]::NewLine)
    if($Failures.Count -eq 0){$Status='PASS'};Write-Json '46_PRE_GREEN_HANDOFF.json' ([pscustomobject]@{preGreen=($Status -eq 'PASS');greenDeploymentAuthorization=$(if($Status -eq 'PASS'){'READY_FOR_SEPARATE_AUTHORITY'}else{'NO'});status=$Status});Write-Json '47_FINAL_STATUS.json' ([pscustomobject]@{status=$Status;primaryFailure=$PrimaryFailure;authority=$Authority});Write-Text '51_AUTHORITY_CLOSEOUT_TOKEN.txt' ('PRE_GREEN_GATE='+$(if($Status -eq 'PASS'){'PASS'}else{'BLOCKED'})+[Environment]::NewLine+'GREEN_DEPLOYMENT_AUTHORIZATION='+$(if($Status -eq 'PASS'){'READY_FOR_SEPARATE_AUTHORITY'}else{'NO'})+[Environment]::NewLine+'OVERALL_STATUS='+$Status+[Environment]::NewLine);Write-Text 'FINAL_STATUS.txt' ('OVERALL_STATUS='+$Status+[Environment]::NewLine+'PRIMARY_FAILURE='+$PrimaryFailure+[Environment]::NewLine);Write-Text 'FINAL_REPORT.md' ('# Phase 7 V1.0.1 Final Report'+[Environment]::NewLine+[Environment]::NewLine+'Status: '+$Status+[Environment]::NewLine+'Primary failure: '+$PrimaryFailure+[Environment]::NewLine);Write-Json 'summary.json' ([pscustomobject]@{status=$Status;primaryFailure=$PrimaryFailure;gateCount=$Gates.Count;failureCount=$Failures.Count});Write-Json 'progress.json' ([pscustomobject]@{stage='FINALIZED';status=$Status});Write-Text 'progress.csv' ('Stage,Status'+[Environment]::NewLine+'FINALIZED,'+$Status+[Environment]::NewLine);Write-Text 'checkpoint.json' '{"stage":"FINALIZED"}';Write-Text 'validations.csv' 'Validation,Status';Write-Text 'actions.csv' 'Action,Status,Detail';Write-Text 'failures.csv' 'FailureClass,Status,Detail';Write-Text 'warnings.csv' 'Warning,Status';Write-Text 'ERROR_LOG.txt' (($Failures|ConvertTo-Json -Depth 10)+[Environment]::NewLine);Write-Text 'EXECUTION_LOG.txt' ('AUTHORITY='+$Authority+[Environment]::NewLine+'FINAL_STATUS='+$Status+[Environment]::NewLine)
    $manifest=@(Get-ChildItem -LiteralPath $EvidenceRoot -File|ForEach-Object{[pscustomobject]@{name=$_.Name;sha256=(File-Sha $_.FullName)}});Write-Json '48_EVIDENCE_MANIFEST.json' $manifest;Write-Text '49_EVIDENCE_SHA256.txt' ((@($manifest|ForEach-Object{$_.sha256+'  '+$_.name}) -join [Environment]::NewLine)+[Environment]::NewLine);Add-Type -AssemblyName System.IO.Compression.FileSystem;if([IO.File]::Exists($EvidenceZip)){Remove-Item -LiteralPath $EvidenceZip -Force};[IO.Compression.ZipFile]::CreateFromDirectory($EvidenceRoot,$EvidenceZip);$archive=[IO.Compression.ZipFile]::OpenRead($EvidenceZip);$entryCount=$archive.Entries.Count;$archive.Dispose();$zipHash=File-Sha $EvidenceZip;Write-Json '50_ZIP_REOPEN_MODEL.json' ([pscustomobject]@{reopened=$true;entryCount=$entryCount;sha256=$zipHash});Write-ExternalJson $SidecarPath ([pscustomobject]@{status='PASS';zip=$EvidenceZip;sha256=$zipHash;entryCount=$entryCount;reopened=$true});Write-Output 'APEX_PS1_SKILL_UPDATE_NOT_REQUIRED';Write-Output ('EVIDENCE_ROOT='+$EvidenceRoot);Write-Output ('EVIDENCE_ZIP='+$EvidenceZip);Write-Output ('FINAL_SIDECAR='+$SidecarPath);Write-Output ('PRE_GREEN_GATE='+$(if($Status -eq 'PASS'){'PASS'}else{'BLOCKED'}));Write-Output ('OVERALL_STATUS='+$Status);if($Status -ne 'PASS'){exit 1}else{exit 0}
} catch { $failureMessage=$_.Exception.Message;Write-Text 'ERROR_LOG.txt' $failureMessage;Add-Failure 'APEX_PHASE7_V101_CONTROLLER_UNHANDLED_FAILURE' $failureMessage;Write-Text 'FINAL_STATUS.txt' ('OVERALL_STATUS=BLOCKED'+[Environment]::NewLine+'PRIMARY_FAILURE='+$PrimaryFailure+[Environment]::NewLine);exit 1 }
