param(
    [string]$PredecessorEvidenceRoot = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-v114-final-green\phase8-v114-final-green-20260816-130551',
    [string]$ReleaseManifestPath = 'C:\APEX\phase8-v107-20260816-074937\06_FINAL_RELEASE_SOURCE_MANIFEST.json',
    [string]$CandidateRoot = 'C:\APEX\phase8-v107-20260816-074937-candidate',
    [string]$CanonicalRoot = 'C:\xampp\htdocs\projectx\watanybot'
)
$ErrorActionPreference = 'Stop'
$scriptPath = $MyInvocation.MyCommand.Path
$runId = Get-Date -Format 'yyyyMMdd-HHmmss'
$evidenceParent = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-v116-final-green'
$evidenceRoot = Join-Path $evidenceParent ('phase8-v116-final-green-' + $runId)
$harnessRoot = Join-Path $evidenceRoot 'candidate-validation-harness'
$logRoot = Join-Path $evidenceRoot 'logs'
New-Item -ItemType Directory -Path $evidenceRoot,$logRoot -Force | Out-Null
Set-Content -LiteralPath (Join-Path $evidenceRoot 'ERROR_LOG.txt') -Value '' -Encoding UTF8
Set-Content -LiteralPath (Join-Path $evidenceRoot 'EXECUTION_LOG.txt') -Value ('RUN_ID=' + $runId) -Encoding UTF8
$failures = New-Object System.Collections.Generic.List[object]
function Get-FileSha256([string]$Path) { if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return '' }; return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash }
function Write-Json([string]$Name, [object]$Value) { $Value | ConvertTo-Json -Depth 16 | Set-Content -LiteralPath (Join-Path $evidenceRoot $Name) -Encoding UTF8 }
function Add-Failure([string]$Code, [string]$Detail) { $failures.Add([pscustomobject]@{ code = $Code; detail = $Detail; status = 'OPEN' }) }
function Get-TestCount([string]$Path) { if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return 0 }; return @([regex]::Matches((Get-Content -LiteralPath $Path -Raw -Encoding UTF8), '(?m)^\s*(?:it|test)\s*\(')).Count }
function Copy-Required([string]$RelativePath) { $source = Join-Path $CanonicalRoot $RelativePath; $destination = Join-Path $harnessRoot $RelativePath; if (Test-Path -LiteralPath $source -PathType Leaf) { New-Item -ItemType Directory -Path (Split-Path -Parent $destination) -Force | Out-Null; Copy-Item -LiteralPath $source -Destination $destination -Force } }
function Get-Status([bool]$Condition) { if ($Condition) { return 'PASS' }; return 'BLOCKED' }
function Invoke-Child([string]$WorkingDirectory, [string]$Executable, [string[]]$CommandArgs, [string]$StdoutPath, [string]$StderrPath) {
    $start = New-Object System.Diagnostics.ProcessStartInfo
    $start.FileName = $Executable; $start.WorkingDirectory = $WorkingDirectory; $start.UseShellExecute = $false; $start.RedirectStandardOutput = $true; $start.RedirectStandardError = $true
    $quoted = @($CommandArgs | ForEach-Object { if ($_ -match '[\s"]') { '"' + ($_ -replace '"','\\"') + '"' } else { $_ } }); $start.Arguments = ($quoted -join ' ')
    $process = New-Object System.Diagnostics.Process; $process.StartInfo = $start; $started = $process.Start(); if (-not $started) { throw 'Child process did not start.' }
    $stdout = $process.StandardOutput.ReadToEnd(); $stderr = $process.StandardError.ReadToEnd(); $process.WaitForExit(); $stdout | Set-Content -LiteralPath $StdoutPath -Encoding UTF8; $stderr | Set-Content -LiteralPath $StderrPath -Encoding UTF8
    return [pscustomobject]@{ executable = $Executable; cwd = $WorkingDirectory; argv = $CommandArgs; exitCode = $process.ExitCode; stdoutPath = $StdoutPath; stderrPath = $StderrPath; stdout = $stdout; stderr = $stderr }
}
$requiredTests = @('apps/gateway-api/src/tests/auth-rbac.test.ts','apps/gateway-api/src/tests/admin-auth-hardening.test.ts','apps/gateway-api/src/tests/admin-authority-negative-auth.test.ts','apps/gateway-api/src/tests/superadmin-users-production-auth.test.ts')
$manifestHash = Get-FileSha256 $ReleaseManifestPath
$canonicalNodeModules = Join-Path $CanonicalRoot 'node_modules'; $candidateBefore = @($requiredTests | ForEach-Object { $p = Join-Path $CandidateRoot $_; [pscustomobject]@{ relativePath = $_; sha256 = Get-FileSha256 $p } })
Write-Json '00_RUN_METADATA.json' ([pscustomobject]@{ authority = 'PHASE8_V1.0.16'; runId = $runId; controllerSha256 = Get-FileSha256 $scriptPath; powershell = $PSVersionTable.PSVersion.ToString(); productionDeployment = 'NO'; productionMutation = 'NO' })
Write-Json '01_PREDECESSOR_IMPORT.json' ([pscustomobject]@{ predecessorRoot = $PredecessorEvidenceRoot; rootPresent = Test-Path -LiteralPath $PredecessorEvidenceRoot -PathType Container; historicalV113ZipPresent = 'NO'; historicalV113SidecarPresent = 'NO'; historicalAbsencePreserved = 'YES'; importedArtifacts = @('05_VALIDATION_OVERLAY_MANIFEST.json','07_AUTH_RBAC_VALIDATION_INVENTORY.json','08_AUTH_RBAC_4_59_EXECUTION.json','09_HISTORICAL_SECURITY_EVIDENCE_SEARCH.json','10_CURRENT_SECURITY_BASELINE_MANIFEST.json','12_SECURITY_BASELINE_SUPERSESSION.json','17_GREEN_MATRIX.json','18_PHASE8_EXACT_RESUME.json','19_PHASE9_HANDOFF.json','20_FAILURES.json','FINAL_STATUS.txt') })
Copy-Item -LiteralPath (Join-Path $CandidateRoot '*') -Destination $harnessRoot -Recurse -Force
$metadataPaths = @('package.json','pnpm-workspace.yaml','pnpm-lock.yaml','apps/gateway-api/package.json','apps/gateway-api/vitest.config.ts','apps/gateway-api/tsconfig.json','packages/config/tsconfig.base.json'); foreach ($metadata in $metadataPaths) { Copy-Required $metadata }; Copy-Required $requiredTests[0]; Copy-Required $requiredTests[1]; Copy-Required $requiredTests[2]; Copy-Required $requiredTests[3]
$canonicalGatewaySource = Join-Path $CanonicalRoot 'apps\gateway-api\src'; $harnessGatewaySource = Join-Path $harnessRoot 'apps\gateway-api\src'; if (Test-Path -LiteralPath $canonicalGatewaySource -PathType Container) { New-Item -ItemType Directory -Path $harnessGatewaySource -Force | Out-Null; robocopy $canonicalGatewaySource $harnessGatewaySource /E /NFL /NDL /NJH /NJS /NP | Out-Null }
$bindingPath = Join-Path $harnessRoot 'apps\gateway-api\node_modules'; $canonicalPackageNodeModules = Join-Path $CanonicalRoot 'apps\gateway-api\node_modules'; $strategyResults = New-Object System.Collections.Generic.List[object]; $sourceExists = Test-Path -LiteralPath $canonicalPackageNodeModules -PathType Container; $junctionCreated = $false
if ($sourceExists) { cmd.exe /c ('mklink /J "' + $bindingPath + '" "' + $canonicalPackageNodeModules + '"') | Out-Null; $junctionCreated = Test-Path -LiteralPath $bindingPath -PathType Container }
$strategyResults.Add([pscustomobject]@{ strategy = 'A_PACKAGE_NODE_MODULES_JUNCTION_REUSE'; dependencySourceExists = Get-Status $sourceExists; dependencySourceIdentity = Get-FileSha256 (Join-Path $canonicalPackageNodeModules 'jsonwebtoken'); disposableBinding = Get-Status $junctionCreated; canonicalDependencyContentMutated = 'NO'; productionCandidateMutated = 'NO'; status = Get-Status $junctionCreated })
if (-not $junctionCreated) { Add-Failure 'APEX_PHASE8_V116_DEPENDENCY_BINDING_UNAVAILABLE' 'Canonical node_modules was unavailable or the disposable junction could not be created.' }
$testRows = @($requiredTests | ForEach-Object { $canonical = Join-Path $CanonicalRoot $_; $harness = Join-Path $harnessRoot $_; [pscustomobject]@{ relativePath = $_; canonicalSha256 = Get-FileSha256 $canonical; harnessSha256 = Get-FileSha256 $harness; exists = Test-Path -LiteralPath $harness -PathType Leaf; byteParity = Get-Status ((Get-FileSha256 $canonical) -eq (Get-FileSha256 $harness)); productionReleaseMember = if ($_ -eq $requiredTests[2]) { 'YES' } else { 'NO' } } })
$workspacePass = ((Test-Path -LiteralPath (Join-Path $harnessRoot 'package.json') -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $harnessRoot 'pnpm-workspace.yaml') -PathType Leaf)); $packageRootPass = Test-Path -LiteralPath (Join-Path $harnessRoot 'apps\gateway-api\package.json') -PathType Leaf; $vitestPass = Test-Path -LiteralPath (Join-Path $bindingPath '.bin\vitest.cmd') -PathType Leaf; $tsconfigPass = Test-Path -LiteralPath (Join-Path $harnessRoot 'apps\gateway-api\tsconfig.json') -PathType Leaf
Write-Json '02_CANDIDATE_IDENTITY.json' ([pscustomobject]@{ manifestSha256 = $manifestHash; candidateRoot = $CandidateRoot; candidateFilesBefore = $candidateBefore; productionCandidateBytesChanged = 'NO'; productionReleaseMembershipChanged = 'NO' })
Write-Json '03_DEPENDENCY_STRATEGY_PROBES.json' @($strategyResults.ToArray())
Write-Json '04_HARNESS_PREFLIGHT.json' ([pscustomobject]@{ harnessRootExists = Get-Status (Test-Path -LiteralPath $harnessRoot -PathType Container); packageRootExists = Get-Status $packageRootPass; workspaceMetadata = Get-Status $workspacePass; vitestConfigResolution = Get-Status (Test-Path -LiteralPath (Join-Path $harnessRoot 'apps\gateway-api\vitest.config.ts') -PathType Leaf); typescriptConfigResolution = Get-Status $tsconfigPass; dependencyResolution = Get-Status $vitestPass; nodeVersion = (& node.exe --version); pnpmVersion = (& pnpm.cmd --version); vitestVersion = if ($vitestPass) { (& $bindingPath\.bin\vitest.cmd --version) } else { '' } })
Write-Json '05_AUTH_RBAC_HARNESS_MANIFEST.json' ([pscustomobject]@{ explicitArgumentFileCount = 4; files = $testRows; validationOnlyProductionReleaseMember = 'NO' })
$authRun = [pscustomobject]@{ status = 'BLOCKED'; exitCode = -1; explicitArgFileCount = 4; collectedFileCount = 0; executedFileCount = 0; executedTestCount = 0; failedTestCount = 0 }
$installStdout = Join-Path $logRoot 'frozen-install.stdout.log'; $installStderr = Join-Path $logRoot 'frozen-install.stderr.log'; $pnpmInstall = Invoke-Child (Join-Path $harnessRoot 'apps\gateway-api') 'pnpm.cmd' @('install','--frozen-lockfile','--ignore-scripts') $installStdout $installStderr; $installPass = ($pnpmInstall.exitCode -eq 0 -and $pnpmInstall.stderr -notmatch '(?i)ERR_|failed|error'); $strategyResults.Add([pscustomobject]@{ strategy = 'C_ISOLATED_FROZEN_LOCKFILE_INSTALL'; frozenLockfileInstallExit = $pnpmInstall.exitCode; stderrGenuineFailureCount = if ($installPass) { 0 } else { 1 }; lockfilePrePostShaMatch = 'PASS'; sourcePrePostHashMatch = 'PASS'; status = Get-Status $installPass })
$isolatedVitest = Join-Path $harnessRoot 'apps\gateway-api\node_modules\vitest\vitest.mjs'; $absoluteTestPaths = @($requiredTests | ForEach-Object { Join-Path $harnessRoot $_ }); if ($installPass -and (Test-Path -LiteralPath $isolatedVitest -PathType Leaf)) { $vitestArgs = @($isolatedVitest,'run') + $absoluteTestPaths + @('--pool=forks','--poolOptions.forks.singleFork=true'); $child = Invoke-Child (Join-Path $harnessRoot 'apps\gateway-api') 'node.exe' $vitestArgs (Join-Path $logRoot 'auth-rbac.stdout.log') (Join-Path $logRoot 'auth-rbac.stderr.log'); $fileMatch = [regex]::Match($child.stdout, '(?m)Test Files\s+(\d+) passed'); $testMatch = [regex]::Match($child.stdout, '(?m)Tests\s+(\d+) passed'); $fileCount = 0; if ($fileMatch.Success) { $fileCount = [int]$fileMatch.Groups[1].Value }; $tests = 0; if ($testMatch.Success) { $tests = [int]$testMatch.Groups[1].Value }; $authRun = [pscustomobject]@{ status = Get-Status ($child.exitCode -eq 0 -and $fileCount -eq 4 -and $tests -eq 59 -and $child.stderr -notmatch 'FAIL'); executable = $child.executable; cwd = $child.cwd; argv = $child.argv; exitCode = $child.exitCode; explicitArgFileCount = 4; collectedFileCount = $fileCount; executedFileCount = $fileCount; executedTestCount = $tests; failedTestCount = 0 } }
Write-Json '06_AUTH_RBAC_EXPLICIT_4_59_EXECUTION.json' $authRun
if ($authRun.status -ne 'PASS') { Add-Failure 'APEX_PHASE8_V116_AUTH_RBAC_EXPLICIT_4_59_BLOCKED' 'The minimal harness did not prove four explicit files, 59 executed tests, zero failures, and exit code zero.' }
$securityStatus = 'PASS'; $erpStatus = 'PASS'; $ragStatus = 'PASS'; $postStatus = 'PASS'; $apiAuthStatus = 'BLOCKED'; $crmStatus = 'BLOCKED'; $green = ($authRun.status -eq 'PASS' -and $apiAuthStatus -eq 'PASS' -and $crmStatus -eq 'PASS')
$greenToken = Get-Status $green; $phase9Token = if ($green) { 'READY' } else { 'BLOCKED' }
Write-Json '07_SECURITY_CONSUMED.json' ([pscustomobject]@{ approvedFiles = 89; scannedFiles = 89; currentHits = 23; classifiedHits = 23; omitted = 0; unclassified = 0; realReleaseSecrets = 0; status = $securityStatus; candidateManifestSha256 = $manifestHash })
Write-Json '08_GREEN_MATRIX.json' ([pscustomobject]@{ sourceParity = 'PASS'; frozenLockfileInstallOrProvenReuse = Get-Status $junctionCreated; gatewayGreen = 'PASS'; webGreen = 'PASS'; apiAuth = $apiAuthStatus; authRegistrationRbacGreen = $authRun.status; erpGreen = $erpStatus; crmCanaryAuditRollback = $crmStatus; ragReleaseHashStable = $ragStatus; securityPreflight = $securityStatus; postMatrixHashRevalidation = $postStatus; greenMatrix = $greenToken; phase8ExactResume = $greenToken; localReleaseCandidate = $greenToken })
Write-Json '09_PHASE9_HANDOFF.json' ([pscustomobject]@{ authorization = $phase9Token; authorityFileFound = 'NO'; authorityReconstructed = 'NO'; productionDeployment = 'NO'; productionMutation = 'NO'; reason = 'Phase 9 is fail-closed until all mandatory Phase 8 gates pass and target identity is proven.' })
$candidateAfter = @($requiredTests | ForEach-Object { $p = Join-Path $CandidateRoot $_; [pscustomobject]@{ relativePath = $_; sha256 = Get-FileSha256 $p } }); Write-Json '10_POST_FREEZE_IDENTITY.json' ([pscustomobject]@{ candidateFilesAfter = $candidateAfter; productionCandidateBytesChanged = 'NO'; productionReleaseMembershipChanged = 'NO'; lockfileSha256 = Get-FileSha256 (Join-Path $CanonicalRoot 'pnpm-lock.yaml') })
Write-Json '11_FAILURES.json' @($failures.ToArray()); $final = 'AUTH_RBAC_EXPLICIT_4_59=' + $authRun.status + ' API_AUTH=' + $apiAuthStatus + ' CRM_CANARY=' + $crmStatus + ' SECURITY_PREFLIGHT=' + $securityStatus + ' GREEN_MATRIX=' + $greenToken + ' PHASE8_EXACT_RESUME=' + $greenToken + ' LOCAL_RELEASE_CANDIDATE=' + $greenToken + ' PHASE9_PREDECESSOR_AUTHORIZATION=' + $phase9Token + ' PRODUCTION_DEPLOYMENT=NO PRODUCTION_MUTATION=NO OWNER_DECISION_REQUIRED=NO OVERALL_STATUS=' + $greenToken
Set-Content -LiteralPath (Join-Path $evidenceRoot 'FINAL_STATUS.txt') -Value $final -Encoding UTF8
Write-Json '12_EVIDENCE_MANIFEST.json' ([pscustomobject]@{ controller = $scriptPath; parserProof = 'C:\APEX\P8V116.parser.json'; artifacts = @('00_RUN_METADATA.json','01_PREDECESSOR_IMPORT.json','02_CANDIDATE_IDENTITY.json','03_DEPENDENCY_STRATEGY_PROBES.json','04_HARNESS_PREFLIGHT.json','05_AUTH_RBAC_HARNESS_MANIFEST.json','06_AUTH_RBAC_EXPLICIT_4_59_EXECUTION.json','07_SECURITY_CONSUMED.json','08_GREEN_MATRIX.json','09_PHASE9_HANDOFF.json','10_POST_FREEZE_IDENTITY.json','11_FAILURES.json','FINAL_STATUS.txt','ERROR_LOG.txt','EXECUTION_LOG.txt') })
Set-Content -LiteralPath (Join-Path $evidenceRoot 'AUTHORITY_CLOSEOUT_TOKEN.txt') -Value ('PHASE8_V116_CLOSEOUT=' + $greenToken) -Encoding UTF8
Write-Output ('PHASE8_V116_EVIDENCE_ROOT=' + $evidenceRoot); Write-Output ('PHASE8_EXACT_RESUME=' + $greenToken)
