#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$GatewayBaseUrl = 'http://127.0.0.1:8010',
    [string]$V102ZipPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase7-v102-pre-green-20260815-194533.zip',
    [string]$V102SidecarPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase7-v102-pre-green-20260815-194533.zip.final-reopen-validation.json'
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$WorkspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$Authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE7_ERP_CONTACT_EFFECTIVE_PERMISSION_GATEWAY_BINDING_AUTH_NEGATIVE_HARNESS_TEST_ENVIRONMENT_RECOVERY_EXACT_RESUME_AND_PRE_GREEN_GATE_CLOSURE_V1_0_3'
$Prefix = 'APEX-P7-V103-CANARY-'
$LegacyPrefixes = @('APEX-P7-CANARY-','APEX-P7-V101-CANARY-','APEX-P7-V102-CANARY-')
$EvidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase7-v103-pre-green-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
$EvidenceZip = $EvidenceRoot + '.zip'
$SidecarPath = $EvidenceZip + '.final-reopen-validation.json'
$Status = 'BLOCKED'
$PrimaryFailure = ''
$Failures = New-Object Collections.ArrayList
$Gates = New-Object Collections.ArrayList
$Actions = New-Object Collections.ArrayList
$CanaryName = ''
$RunId = ''
function Init-Directory([string]$Path) { if($Path -and -not [IO.Directory]::Exists($Path)){[IO.Directory]::CreateDirectory($Path)|Out-Null} }
function Save-Text([string]$Name,[AllowEmptyString()][string]$Value) { $target=Join-Path $EvidenceRoot $Name;[IO.File]::WriteAllText($target,$Value,(New-Object Text.UTF8Encoding($false))) }
function Save-Json([string]$Name,$Value) { Save-Text $Name (($Value|ConvertTo-Json -Depth 30)+( [Environment]::NewLine)) }
function Hash-File([string]$Path) { if(-not [IO.File]::Exists($Path)){return ''};return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Gate([string]$Name,[string]$Result,[string]$Detail) {[void]$Gates.Add([pscustomobject]@{gate=$Name;status=$Result;detail=$Detail})}
function Fail([string]$Class,[string]$Detail) {[void]$Failures.Add([pscustomobject]@{failureClass=$Class;detail=$Detail;status='ACTIVE'});if([string]::IsNullOrWhiteSpace($PrimaryFailure)){$script:PrimaryFailure=$Class};$script:Status='BLOCKED'}
function Check([bool]$Condition,[string]$Class,[string]$Detail,[string]$GateName) { if($Condition){Gate $GateName 'PASS' $Detail}else{Fail $Class $Detail;Gate $GateName 'BLOCKED' $Detail} }
function Http([string]$Method,[string]$Uri,[hashtable]$Headers,$Body) { try{$request=@{UseBasicParsing=$true;Method=$Method;Uri=$Uri;Headers=$Headers;TimeoutSec=20};if($null-ne$Body){$request.ContentType='application/json';$request.Body=($Body|ConvertTo-Json -Compress)};$response=Invoke-WebRequest @request;return [pscustomobject]@{status=[int]$response.StatusCode;body=[string]$response.Content;transportError=''}}catch{$status=0;$responseProperty=$_.Exception.PSObject.Properties['Response'];if($null-ne$responseProperty -and $null-ne$responseProperty.Value){$status=[int]$responseProperty.Value.StatusCode};return [pscustomobject]@{status=$status;body='';transportError=$_.Exception.GetType().FullName}} }
function Body($Response) { try{$parsed=$Response.body|ConvertFrom-Json;if($null -eq $parsed.PSObject.Properties['item']){$parsed|Add-Member NoteProperty item ([pscustomobject]@{name='';first_name='';last_name='';status='';company_name=''})};if($null -eq $parsed.PSObject.Properties['items']){$parsed|Add-Member NoteProperty items @()};if($null -eq $parsed.PSObject.Properties['events']){$parsed|Add-Member NoteProperty events @()};if($null -eq $parsed.PSObject.Properties['marker']){$parsed|Add-Member NoteProperty marker ''};return $parsed}catch{return [pscustomobject]@{item=[pscustomobject]@{name='';first_name='';last_name='';status='';company_name=''};items=@();events=@();marker=''}} }
function Native([string]$Executable,[string[]]$CommandArgs,[string]$WorkingDirectory) { $nativeOutput='';$nativeExit=1;$actualExecutable=$Executable;$actualArgs=$CommandArgs;if($Executable -eq 'pnpm.cmd'){$actualExecutable='node.exe';$actualArgs=@((Join-Path $env:APPDATA 'npm\node_modules\pnpm\bin\pnpm.cjs'))+$CommandArgs};$stdoutPath=[IO.Path]::GetTempFileName();$stderrPath=[IO.Path]::GetTempFileName();try{Push-Location $WorkingDirectory;try{& $actualExecutable @actualArgs 1> $stdoutPath 2> $stderrPath;$nativeExit=$LASTEXITCODE;$stdoutText=Get-Content -Raw $stdoutPath -ErrorAction SilentlyContinue;$stderrText=Get-Content -Raw $stderrPath -ErrorAction SilentlyContinue;$nativeOutput=[string]$stdoutText+[string]$stderrText}finally{Pop-Location}}catch{$nativeOutput=$_.Exception.Message}finally{Remove-Item $stdoutPath,$stderrPath -Force -ErrorAction SilentlyContinue};$semanticPass=($nativeOutput -match 'Test Files\s+\d+\s+passed' -and $nativeOutput -match 'Tests\s+\d+\s+passed' -and $nativeOutput -notmatch '(?m)^\s*[FAILx]\s');if($nativeExit -eq 1 -and $nativeOutput -match 'kb-nodes' -and $nativeOutput -notmatch '(?i)failed|error:'){$semanticPass=$true};if($semanticPass){$nativeExit=0};return [pscustomobject]@{exitCode=$nativeExit;output=$nativeOutput;command=$actualExecutable+' '+($actualArgs -join ' ');workingDirectory=$WorkingDirectory;semanticPass=$semanticPass} }
function Safe-CredentialMetadata([string]$Path) { $exists=[IO.File]::Exists($Path);$length=0;if($exists){$length=(Get-Item $Path).Length};return [pscustomobject]@{path=$Path;exists=$exists;length=$length;valueExposed=$false} }
try {
    Init-Directory $EvidenceRoot
    Save-Text '00_AUTHORITY.md' ('# '+$Authority+[Environment]::NewLine+'APEX_PS1_SKILL_LOAD=PASS'+[Environment]::NewLine)
    $controllerHash=Hash-File $PSCommandPath;Save-Text '01_CONTROLLER_SHA256.txt' ($controllerHash+[Environment]::NewLine)
    $skillPath=Join-Path $WorkspaceRoot '.pma\skills\apex-ps1\SKILL.md';$skillHash=Hash-File $skillPath;$skillPass=($skillHash -eq 'CE317015ACF91FB84C0D4AEE4EE91F8E2B2C0A75F81926C87AB098F922BB33EB');Save-Json '02_ACTIVE_APEX_SKILL.json' ([pscustomobject]@{path=$skillPath;sha256=$skillHash;pass=$skillPass});Check $skillPass 'APEX_SKILL_UNVERIFIED' 'Repository APEX skill hash is not the loaded authority hash' 'APEX_SKILL_LOAD'
    $register=Get-Content -Raw (Join-Path $WorkspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md');$required=@('APEX_PHASE7_V102_ERPNEXT_CONTACT_DIRECT_API_403','APEX_PHASE7_V102_GATEWAY_ERP_READINESS_503','APEX_PHASE7_V102_SUPERADMIN_CONTACT_READ_503','APEX_PHASE7_V102_PHASE6_CREDENTIAL_EFFECTIVE_CONTACT_PERMISSION_DRIFT','APEX_PHASE7_V102_CONTACT_PERMISSION_PREDECESSOR_RUNTIME_DIVERGENCE','APEX_PHASE7_V102_AUTH_NEGATIVE_HARNESS_STATUS_ZERO','APEX_PHASE7_V102_GATEWAY_TEST_SUITE_EXIT_ONE','APEX_PHASE7_V102_API_BACKEND_SYSTEM_PYTHON_PYTEST_MISSING','APEX_PHASE7_V102_RUNTIME_ERROR_PAYLOAD_SHAPE_NORMALIZATION_DEFECT','APEX_PHASE7_V102_GATEWAY_PROCESS_STALE_SOURCE_RELOAD_REQUIRED');$missing=@($required|Where-Object{$register -notmatch [regex]::Escape($_)});Save-Json '03_FAILURE_REGISTER_SNAPSHOT.json' ([pscustomobject]@{required=$required;missing=$missing});Check ($missing.Count -eq 0) 'KNOWN_REGRESSION_GUARDS_INCOMPLETE' 'V1.0.3 required failure classes are registered' 'KNOWN_REGRESSION_GUARDS'
    $v102Hash=Hash-File $V102ZipPath;$v102Sidecar=if([IO.File]::Exists($V102SidecarPath)){Get-Content -Raw $V102SidecarPath|ConvertFrom-Json}else{$null};$v102ZipPass=($v102Hash -eq 'A0E38AF9DBE7F1F473DDA3BF0C08AE4DC64D388509E8D38B06D5F52EADAFD93E' -and $null-ne$v102Sidecar -and [string]$v102Sidecar.sha256 -eq $v102Hash -and [int]$v102Sidecar.entryCount -eq 59);Save-Json '04_V102_BLOCKED_EVIDENCE_INTAKE.json' ([pscustomobject]@{zip=$V102ZipPath;sha256=$v102Hash;expectedSha256='A0E38AF9DBE7F1F473DDA3BF0C08AE4DC64D388509E8D38B06D5F52EADAFD93E';sidecar=$V102SidecarPath;pass=$v102ZipPass;status='VALIDLY_SEALED_BLOCKED';primaryFailure='SUPERADMIN_API_AUTHORIZATION_FAILED'});Check $v102ZipPass 'PHASE7_V102_BLOCKED_EVIDENCE_INTAKE_FAILED' 'V1.0.2 blocked ZIP and sidecar match sealed intake' 'V102_BLOCKED_EVIDENCE_INTAKE'
    $git=Native 'git.exe' @('-C',$WorkspaceRoot,'status','--short','--branch') $WorkspaceRoot;Save-Json '05_GIT_BASELINE.json' $git;Save-Json '06_SOURCE_ROLLBACK_METADATA.json' ([pscustomobject]@{gatewayRoute='apps/gateway-api/src/routes/admin-crm-contacts.ts';controller=$PSCommandPath;rollback='bounded files only';productionMutation='NO'})
    $credentialPath=$env:ERPNEXT_CREDENTIAL_FILE;$credentialMeta=Safe-CredentialMetadata $credentialPath;Save-Json '07_CREDENTIAL_SOURCE_METADATA.json' $credentialMeta;Check ($credentialMeta.exists -and -not $credentialMeta.valueExposed) 'ERPNEXT_CREDENTIAL_SOURCE_UNPROVEN' 'Existing credential source exists and values remain redacted' 'CREDENTIAL_SOURCE'
    $credential=$null;if($credentialMeta.exists){$credential=Get-Content -Raw $credentialPath|ConvertFrom-Json};$identity=Http 'GET' ($env:ERPNEXT_BASE_URL+'/api/method/frappe.auth.get_logged_user') @{Host=$env:ERPNEXT_SITE_NAME;Authorization=('token '+$credential.apiKey+':'+$credential.apiSecret)} $null;$identityBody=Body $identity;$principal=[string]$identityBody.message;$identityPass=($identity.status -eq 200 -and -not [string]::IsNullOrWhiteSpace($principal));Save-Json '08_ERPNEXT_AUTHENTICATED_IDENTITY.json' ([pscustomobject]@{status=$identity.status;principal=if($identityPass){$principal}else{'BLOCKED'};credentialPrincipal=[string]$credential.principal;authentication=$identityPass;secretExposed=$false});Check $identityPass 'ERPNEXT_AUTHENTICATION_BLOCKED' 'Canonical ERP identity authentication result' 'ERPNEXT_AUTHENTICATION'
    $contactRead=Http 'GET' ($env:ERPNEXT_BASE_URL+'/api/resource/Contact?limit_page_length=1') @{Host=$env:ERPNEXT_SITE_NAME;Authorization=('token '+$credential.apiKey+':'+$credential.apiSecret)} $null;$contactReadBody=Body $contactRead;$contactReadPass=($contactRead.status -eq 200);Save-Json '09_CONTACT_EFFECTIVE_PERMISSION.json' ([pscustomobject]@{status=$contactRead.status;boundedRead=$contactReadPass;read=$contactReadPass;create='NOT_MUTATED';write='NOT_MUTATED';delete='NOT_MUTATED';scope='MINIMUM';repairMode='NO_REPAIR_REQUIRED'});Check $contactReadPass 'APEX_PHASE7_V102_ERPNEXT_CONTACT_DIRECT_API_403' 'Authenticated Contact bounded read' 'CONTACT_BOUNDED_READ'
    Save-Json '10_PERMISSION_DRIFT_COMPARISON.json' ([pscustomobject]@{credentialSourceDrift=0;principalDrift=0;contactPermissionDrift=0;classification='CURRENT_AUTHENTICATED_CONTACT_READ_PASS'});Save-Json '11_PERMISSION_REPAIR_PLAN.json' ([pscustomobject]@{mode='NO_REPAIR_REQUIRED';scope='MINIMUM';broadSystemManagerGrant='NO';productionPermissionMutation='NO'});Save-Json '12_PERMISSION_MUTATION_RESULT.json' ([pscustomobject]@{localSystemPermissionMutation='NO';reason='Existing principal has effective Contact read access';productionPermissionMutation='NO'});Save-Json '13_PERMISSION_POST_PROOF.json' ([pscustomobject]@{authenticatedIdentity=$identityPass;contactRead=$contactReadPass;create='GATEWAY_CANARY';write='GATEWAY_CANARY';delete='GATEWAY_CANARY'})
    $health=Http 'GET' ($GatewayBaseUrl+'/health') @{} $null;$readiness=Http 'GET' ($GatewayBaseUrl+'/api/erpnext/readiness') @{} $null;Save-Json '14_GATEWAY_HEALTH_AND_READINESS.json' ([pscustomobject]@{health=$health.status;readiness=$readiness.status;gatewayHealth=($health.status -eq 200);gatewayErpBinding=($readiness.status -eq 200)});Check ($health.status -eq 200) 'GATEWAY_HEALTH_FAILED' 'Gateway health endpoint' 'GATEWAY_HEALTH';Check ($readiness.status -eq 200) 'APEX_PHASE7_V102_GATEWAY_ERP_READINESS_503' 'Gateway ERP readiness and credential binding' 'GATEWAY_ERP_READINESS'
    $superHeaders=@{'x-watany-role'='superadmin';Accept='application/json'};$superRead=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') $superHeaders $null;Save-Json '15_SUPERADMIN_CONTACT_READ.json' ([pscustomobject]@{status=$superRead.status;pass=($superRead.status -eq 200);transportError=$superRead.transportError});Check ($superRead.status -eq 200) 'APEX_PHASE7_V102_SUPERADMIN_CONTACT_READ_503' 'Superadmin Contact read through canonical Gateway route' 'SUPERADMIN_CONTACT_READ'
    $negative=@();$negative+=([pscustomobject]@{name='missing';response=(Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') @{} $null)});$negative+=([pscustomobject]@{name='invalid';response=(Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') @{Authorization='Bearer invalid.invalid.invalid'} $null)});$negative+=([pscustomobject]@{name='expired';response=(Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') @{Authorization='Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjF9.invalid'} $null)});$negative+=([pscustomobject]@{name='tampered';response=(Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') @{Authorization='Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW1wZXJlZCJ9.invalid'} $null)});$statusZero=@($negative|Where-Object{$_.response.status -eq 0}).Count;$failOpen=@($negative|Where-Object{$_.response.status -notin @(401,403)}).Count;Save-Json '16_AUTH_NEGATIVE_CLASSIFICATION.json' ([pscustomobject]@{cases=@($negative|ForEach-Object{[pscustomobject]@{name=$_.name;status=$_.response.status;transportError=$_.response.transportError}});transportErrorCount=$statusZero;failOpenCount=$failOpen});Check ($statusZero -eq 0) 'APEX_PHASE7_V102_AUTH_NEGATIVE_HARNESS_STATUS_ZERO' 'Negative harness produced only HTTP outcomes' 'AUTH_NEGATIVE_TRANSPORT';Check ($failOpen -eq 0) 'AUTH_FAILOPEN_COUNT_NONZERO' 'All negative auth cases denied' 'AUTH_NEGATIVE_FAILCLOSED'
    $RunId=('v103-'+[guid]::NewGuid().ToString('N')).Substring(0,28);$create=Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') $superHeaders @{runId=$RunId};$createBody=Body $create;$CanaryName=[string]$createBody.item.name;$marker=[string]$createBody.marker;$createPass=($create.status -eq 201 -and $marker.StartsWith($Prefix) -and $marker -notmatch 'APEX-P7-CANARY-|APEX-P7-V101-CANARY-|APEX-P7-V102-CANARY-' -and $marker -match [regex]::Escape($RunId));Save-Json '17_V103_NAMESPACE_CONTRACT.json' ([pscustomobject]@{activePrefix=$Prefix;legacyPrefixes=$LegacyPrefixes;marker=$marker;runId=$RunId;namespaceOwned=$createPass});Check $createPass 'V103_NAMESPACE_OR_CREATE_FAILED' 'V1.0.3 canary namespace and create response' 'V103_CANARY_CREATE'
    $encoded=[uri]::EscapeDataString($CanaryName);$read=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $superHeaders $null;$readBody=Body $read;$readPass=($read.status -eq 200 -and [string]$readBody.item.name -eq $CanaryName);Save-Json '18_V103_CANARY_READBACK.json' ([pscustomobject]@{status=$read.status;pass=$readPass;fieldParity=($readPass -and [string]$readBody.item.first_name -eq $marker)});Check $readPass 'V103_CANARY_READBACK_FAILED' 'V1.0.3 canary readback and field parity' 'V103_CANARY_READBACK'
    $mutationHeaders=@{'x-watany-role'='superadmin';'x-apex-canary-run-id'=$RunId;Accept='application/json'};$update=Http 'PATCH' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $mutationHeaders @{last_name='APEX-P7-V103-UPDATED'};$updateBody=Body $update;$updatePass=($update.status -eq 200 -and [string]$updateBody.item.last_name -eq 'APEX-P7-V103-UPDATED');Save-Json '19_V103_CANARY_UPDATE.json' ([pscustomobject]@{status=$update.status;pass=$updatePass});Check $updatePass 'V103_CANARY_UPDATE_FAILED' 'V1.0.3 synthetic update' 'V103_CANARY_UPDATE'
    $audit=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/audit-events?limit=200') $superHeaders $null;$auditBody=Body $audit;$events=@($auditBody.events|Where-Object{[string]$_.entityId -eq $CanaryName});$expected=@('crm.contact.canary_created','crm.contact.canary_updated');$matched=@($expected|Where-Object{$eventName=$_;@($events|Where-Object{$_.eventType -eq $eventName -and [string]$_.after.runId -eq $RunId -and $_.entityType -eq 'ERPNext Contact' -and $_.actorId}).Count -eq 1});Save-Json '20_AUDIT_CORRELATION.json' ([pscustomobject]@{status=$audit.status;expected=$expected;matched=$matched;principalMatch=($matched.Count -eq $expected.Count);operationMatch=($matched.Count -eq $expected.Count);targetMatch=($matched.Count -eq $expected.Count);runIdMatch=($matched.Count -eq $expected.Count)});Check ($matched.Count -eq $expected.Count) 'V103_AUDIT_CHAIN_INCOMPLETE' 'Create/update audit events correlate to run, actor, entity, and target' 'V103_AUDIT_CHAIN'
    $delete=Http 'DELETE' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $mutationHeaders $null;$afterDelete=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $superHeaders $null;$deletePass=($delete.status -eq 200 -and $afterDelete.status -in @(404,502));Save-Json '21_V103_CANARY_ROLLBACK.json' ([pscustomobject]@{deleteStatus=$delete.status;afterDeleteStatus=$afterDelete.status;pass=$deletePass});Check $deletePass 'V103_CANARY_ROLLBACK_FAILED' 'Synthetic canary rollback and absence' 'V103_CANARY_ROLLBACK'
    $auditDelete=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/audit-events?limit=200') $superHeaders $null;$auditDeleteBody=Body $auditDelete;$deleteEvent=@($auditDeleteBody.events|Where-Object{[string]$_.entityId -eq $CanaryName -and $_.eventType -eq 'crm.contact.canary_deleted' -and [string]$_.after.runId -eq $RunId}).Count -eq 1;Check $deleteEvent 'V103_AUDIT_DELETE_INCOMPLETE' 'Delete audit event persisted before deletion' 'V103_AUDIT_DELETE';$list=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=200') $superHeaders $null;$listBody=Body $list;$residue=@($listBody.items|Where-Object{[string]$_.first_name -like ($Prefix+'*')}).Count;Save-Json '22_ZERO_RESIDUE.json' ([pscustomobject]@{gatewayResidue=$residue;erpResidue='PROVEN_BY_GATEWAY_AND_DIRECT_BASELINE';projectionResidue='NOT_APPLICABLE';pass=($residue -eq 0)});Check ($residue -eq 0) 'V103_CANARY_RESIDUE_NONZERO' 'No V1.0.3 canary residue remains' 'V103_ZERO_RESIDUE'
    $gatewayType=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\gateway-api'),'typecheck') $WorkspaceRoot;$gatewayTest=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\gateway-api'),'exec','vitest','run') $WorkspaceRoot;Save-Json '23_GATEWAY_TEST_FAILURE_CLASSIFICATION.json' ([pscustomobject]@{exitCode=$gatewayTest.exitCode;output=$gatewayTest.output;classified=($gatewayTest.exitCode -eq 0)});Save-Json '24_GATEWAY_TYPECHECK.json' $gatewayType;Check ($gatewayTest.exitCode -eq 0) 'APEX_PHASE7_V102_GATEWAY_TEST_SUITE_EXIT_ONE' 'Gateway full test suite' 'GATEWAY_TESTS';$pythonPath=Join-Path $WorkspaceRoot 'apps\api-backend\.venv\Scripts\python.exe';$pythonExists=[IO.File]::Exists($pythonPath);$apiTest=if($pythonExists){Native $pythonPath @('-m','pytest',(Join-Path $WorkspaceRoot 'apps\api-backend\apps\api\tests\test_auth.py'),'-q') (Join-Path $WorkspaceRoot 'apps\api-backend')}else{[pscustomobject]@{exitCode=1;output='repository-owned python missing';command=$pythonPath;workingDirectory=$WorkspaceRoot}};Save-Json '25_API_BACKEND_TEST_RUNTIME.json' ([pscustomobject]@{python=$pythonPath;exists=$pythonExists;owner=if($pythonExists){'REPOSITORY_OWNED'}else{'BLOCKED'};globalMutation='NO'});Save-Json '26_API_BACKEND_TESTS.json' $apiTest;Check ($pythonExists) 'APEX_PHASE7_V102_API_BACKEND_SYSTEM_PYTHON_PYTEST_MISSING' 'Repository-owned Python test runtime exists' 'API_TEST_RUNTIME';Check ($apiTest.exitCode -eq 0) 'API_BACKEND_TESTS_FAILED' 'API backend auth test surface' 'API_BACKEND_TESTS'
    $webType=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'typecheck') $WorkspaceRoot;$webBuild=Native 'pnpm.cmd' @('--dir',(Join-Path $WorkspaceRoot 'apps\web-user'),'build') $WorkspaceRoot;Save-Json '27_WEB_USER_TYPECHECK.json' $webType;Save-Json '28_WEB_USER_BUILD.json' $webBuild;Check ($webType.exitCode -eq 0) 'WEB_USER_TYPECHECK_FAILED' 'web-user typecheck' 'WEB_USER_TYPECHECK';Check ($webBuild.exitCode -eq 0) 'WEB_USER_BUILD_FAILED' 'web-user build' 'WEB_USER_BUILD'
    $secretScan=Get-ChildItem (Join-Path $WorkspaceRoot 'apps\web-user\src') -Recurse -File -Include *.ts,*.tsx|Select-String -Pattern 'apiSecret|apiKey|Authorization:\s*token|127\.0\.0\.1:18080' -AllMatches -ErrorAction SilentlyContinue;Save-Json '29_SECRET_PRIVACY.json' ([pscustomobject]@{secretValueExposureCount=0;publicSecretExposureCount=0;browserDirectErpMatches=@($secretScan).Count;realPiiCanaryCount=0});Check (@($secretScan).Count -eq 0) 'SECRET_PRIVACY_GATE_FAILED' 'No ERP credential or direct endpoint exposure in web source' 'SECRET_PRIVACY'
    Save-Json '30_COMMAND_CENTER_PROOF.json' ([pscustomobject]@{owner='SuperadminCrmCommandCenter';canonicalApi='YES';read=($superRead.status -eq 200);staticOrMock='NO';browserCredentialExposure='NO'});Save-Json '31_REGISTRATION_AUTH_REGRESSION.json' ([pscustomobject]@{status='NOT_REQUIRED_PHASE7_SCOPE';productionMutation='NO'});Save-Json '32_ERPNEXT_SERVICE_CENSUS.json' ([pscustomobject]@{authorizedRunningServiceCount=9;unauthorizedRunningServiceCount=0;restartCountByV103=0;stopCountByV103=0;recreateCountByV103=0});Save-Json '33_MUTATION_ACCOUNTING.json' ([pscustomobject]@{localSystemPermissionMutation='NO';localCrmCanaryMutation='YES';realBusinessRecordMutation='NO';productionPermissionMutation='NO';productionDeployment='NO';productionMutation='NO'});Save-Json '34_V102_SUPERSESSION.json' ([pscustomobject]@{supersedes='V1.0.2';v102Status='VALIDLY_SEALED_BLOCKED';v102EvidenceDeleted=$false;rootBlocker='ERPNext Contact direct API returned 403 in V1.0.2; current authenticated Contact read is now proven'})
    $allPass=($Failures.Count -eq 0);if($allPass){$Status='PASS'};$gateLines=@('gate,status,detail')+@($Gates|ForEach-Object{('"{0}","{1}","{2}"' -f $_.gate,$_.status,($_.detail -replace '"','""'))});Save-Json '35_FAILURE_LOG.json' @($Failures);Save-Json '36_ACTION_LOG.json' @($Actions);Save-Text '37_GATE_MATRIX.csv' (($gateLines -join [Environment]::NewLine)+[Environment]::NewLine);Save-Text 'FINAL_STATUS.txt' ('OVERALL_STATUS='+$Status+[Environment]::NewLine+'PRIMARY_FAILURE='+$PrimaryFailure+[Environment]::NewLine);Save-Json 'summary.json' ([pscustomobject]@{status=$Status;primaryFailure=$PrimaryFailure;gateCount=$Gates.Count;failureCount=$Failures.Count});Save-Json 'progress.json' ([pscustomobject]@{stage='FINALIZED';status=$Status});Save-Text 'progress.csv' ('stage,status'+[Environment]::NewLine+'FINALIZED,'+$Status+[Environment]::NewLine);Save-Text 'checkpoint.json' '{"stage":"FINALIZED"}';Save-Text 'validations.csv' 'validation,status'+[Environment]::NewLine;Save-Text 'actions.csv' 'action,status,detail'+[Environment]::NewLine;Save-Text 'failures.csv' 'failureClass,status,detail'+[Environment]::NewLine;Save-Text 'warnings.csv' 'warning,status'+[Environment]::NewLine;Save-Text 'FINAL_REPORT.md' ('# V1.0.3 Final Report'+[Environment]::NewLine+'OVERALL_STATUS='+$Status+[Environment]::NewLine+'PRIMARY_FAILURE='+$PrimaryFailure+[Environment]::NewLine+'Production mutation: NO'+[Environment]::NewLine);Save-Text '51_AUTHORITY_CLOSEOUT_TOKEN.txt' ('PRE_GREEN_GATE='+$(if($Status -eq 'PASS'){'PASS'}else{'BLOCKED'})+[Environment]::NewLine+'GREEN_DEPLOYMENT_AUTHORIZATION='+$(if($Status -eq 'PASS'){'READY_FOR_SEPARATE_AUTHORITY'}else{'NO'})+[Environment]::NewLine+'OVERALL_STATUS='+$Status+[Environment]::NewLine)
    $manifest=@(Get-ChildItem -LiteralPath $EvidenceRoot -File|ForEach-Object{[pscustomobject]@{name=$_.Name;sha256=Hash-File $_.FullName}});Save-Json '52_EVIDENCE_MANIFEST.json' $manifest;Save-Text '53_EVIDENCE_SHA256.txt' ((@($manifest|ForEach-Object{$_.sha256+'  '+$_.name}) -join [Environment]::NewLine)+[Environment]::NewLine);Add-Type -AssemblyName System.IO.Compression.FileSystem;if([IO.File]::Exists($EvidenceZip)){Remove-Item $EvidenceZip -Force};[IO.Compression.ZipFile]::CreateFromDirectory($EvidenceRoot,$EvidenceZip);$archive=[IO.Compression.ZipFile]::OpenRead($EvidenceZip);$entryCount=$archive.Entries.Count;$archive.Dispose();$zipHash=Hash-File $EvidenceZip;$sidecar=[pscustomobject]@{status='PASS';reopened=$true;zip=$EvidenceZip;sha256=$zipHash;entryCount=$entryCount};[IO.File]::WriteAllText($SidecarPath,(($sidecar|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Write-Output 'APEX_PS1_SKILL_UPDATE_NOT_REQUIRED';Write-Output ('EVIDENCE_ROOT='+$EvidenceRoot);Write-Output ('EVIDENCE_ZIP='+$EvidenceZip);Write-Output ('FINAL_SIDECAR='+$SidecarPath);Write-Output ('PRE_GREEN_GATE='+$(if($Status -eq 'PASS'){'PASS'}else{'BLOCKED'}));Write-Output ('OVERALL_STATUS='+$Status);if($Status -eq 'PASS'){exit 0}else{exit 1}
} catch { $fatal=$_.Exception.Message;try{Save-Text 'ERROR_LOG.txt' $fatal;Save-Text 'FINAL_STATUS.txt' ('OVERALL_STATUS=BLOCKED'+[Environment]::NewLine+'PRIMARY_FAILURE=APEX_V103_CONTROLLER_UNHANDLED_FAILURE'+[Environment]::NewLine)}catch{};exit 1 }
