#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$ParserPreflightProofPath = 'C:\APEX\P7A100.parser.json',
    [string]$GatewayBaseUrl = 'http://127.0.0.1:8010',
    [string]$Phase6EvidenceZip = ''
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$Authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE7A_STANDARD_CONTACT_CRUD_CANARY_AND_EXTERNAL_EVIDENCE_SEAL_V1_0_0'
$WorkspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$EvidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase7a-contact-' + (Get-Date -Format 'yyyyMMdd-HHmmssfff'))
$EvidenceZip = $EvidenceRoot + '.zip'
$SidecarPath = $EvidenceZip + '.final-reopen-validation.json'
$ScriptSha256 = ''
$PrimaryFailure = ''
$Status = 'BLOCKED'
$Rows = New-Object Collections.ArrayList
$Actions = New-Object Collections.ArrayList
$Gates = New-Object Collections.ArrayList
$Validations = New-Object Collections.ArrayList
$Failures = New-Object Collections.ArrayList
$Warnings = New-Object Collections.ArrayList
$Required = @(
'00_AUTHORITY.md','01_CONTROLLER_HASH.txt','02_PS51_PARSER_PREFLIGHT.json','03_FAILURE_REGISTER_PRECHECK.json',
'04_PHASE6_PREDECESSOR_REVALIDATION.json','05_DOCTYPE_DISCOVERY.json','06_PERMISSION_PROOF.json','07_GATEWAY_HEALTH.json',
'08_AUTH_NEGATIVE_TESTS.json','09_CRUD_CANARY.json','10_RESIDUE_RECONCILIATION.json','11_TYPECHECK.json',
'12_PHASE7A_GATE_RESULTS.csv','13_PHASE7A_FAILURES.csv','14_PHASE7A_ACTIONS.csv','15_FINAL_STATUS.json',
'16_EVIDENCE_MANIFEST.json','17_EVIDENCE_SHA256.txt','18_ZIP_REOPEN_MODEL.json','19_AUTHORITY_CLOSEOUT_TOKEN.txt',
'FINAL_REPORT.md','summary.json','FINAL_STATUS.txt','progress.json','progress.csv','checkpoint.json','validations.csv','actions.csv','failures.csv','warnings.csv','ERROR_LOG.txt','EXECUTION_LOG.txt'
)
function Init([string]$Path) { if(-not [IO.Directory]::Exists($Path)){[void][IO.Directory]::CreateDirectory($Path)} }
function Text([string]$Name,[AllowEmptyString()][string]$Value) { $p=Join-Path $EvidenceRoot $Name; Init ([IO.Path]::GetDirectoryName($p)); $Value=$Value.Replace('`r`n',[Environment]::NewLine); [IO.File]::WriteAllText($p,$Value,(New-Object Text.UTF8Encoding($false))) }
function Json([string]$Name,$Value) { if([IO.Path]::IsPathRooted($Name)){ExternalJson $Name $Value;return};Text $Name (($Value|ConvertTo-Json -Depth 30)+'`r`n') }
function ExternalJson([string]$Path,$Value) { Init ([IO.Path]::GetDirectoryName($Path)); [IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 30)+'`r`n').Replace('`r`n',[Environment]::NewLine),(New-Object Text.UTF8Encoding($false))) }
function Sha([string]$Path) { $s=[IO.File]::OpenRead($Path);$h=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','').ToUpperInvariant()}finally{$s.Dispose();$h.Dispose()} }
function Gate([string]$Name,[string]$Result,[string]$Detail) {[void]$Gates.Add([pscustomobject]@{Gate=$Name;Status=$Result;Detail=$Detail})}
function Fail([string]$Class,[string]$Detail) {[void]$Failures.Add([pscustomobject]@{FailureClass=$Class;Detail=$Detail;Status='ACTIVE'});if([string]::IsNullOrWhiteSpace($PrimaryFailure)){$script:PrimaryFailure=$Class};$script:Status='BLOCKED'}
function Act([string]$Name,[string]$Result,[string]$Detail) {[void]$Actions.Add([pscustomobject]@{Action=$Name;Status=$Result;Detail=$Detail})}
function Val([string]$Name,[string]$Result,[string]$Detail) {[void]$Validations.Add([pscustomobject]@{Validation=$Name;Status=$Result;Detail=$Detail})}
function Http([string]$Method,[string]$Uri,[hashtable]$Headers,[object]$Body) { try {$a=@{UseBasicParsing=$true;Method=$Method;Uri=$Uri;Headers=$Headers;TimeoutSec=20};if($null-ne$Body){$a.ContentType='application/json';$a.Body=($Body|ConvertTo-Json -Compress)};$r=Invoke-WebRequest @a;return [pscustomobject]@{Status=[int]$r.StatusCode;Body=[string]$r.Content}}catch{$code=0;$content='';if($null-ne$_.Exception.Response){$code=[int]$_.Exception.Response.StatusCode.value__;try{$content=$_.ErrorDetails.Message}catch{}};return [pscustomobject]@{Status=$code;Body=$content}} }
try {
    Init $EvidenceRoot
    foreach($n in $Required){Text $n ''}
    Text 'ERROR_LOG.txt' ''
    Text 'EXECUTION_LOG.txt' ('AUTHORITY='+$Authority+'`r`n')
    $ScriptSha256=Sha $PSCommandPath
    Text '00_AUTHORITY.md' ('# Phase 7A Authority`r`n`r`n'+$Authority+'`r`n')
    Text '01_CONTROLLER_HASH.txt' ($ScriptSha256+'`r`n')
    if(-not [IO.File]::Exists($ParserPreflightProofPath)){Fail 'APEX_EXTERNAL_PS51_PARSER_PREFLIGHT_PROOF_MISSING' $ParserPreflightProofPath}else{$proof=Get-Content -Raw -LiteralPath $ParserPreflightProofPath|ConvertFrom-Json;Json '02_PS51_PARSER_PREFLIGHT.json' $proof;if([string]$proof.status -ne 'PASS' -or [int]$proof.errorCount -ne 0 -or [string]$proof.sha256 -ne $ScriptSha256 -or -not ([string]$proof.psVersion).StartsWith('5.1.')){Fail 'APEX_EXTERNAL_PS51_PARSER_PREFLIGHT_FAILED' 'External parser proof did not match exact controller bytes'}else{Gate 'external_parser' 'PASS' 'PS 5.1 parser proof matches exact script hash'}}
    $register=Get-Content -Raw -LiteralPath (Join-Path $WorkspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md');$classes=@('APEX_PHASE7A_EFFECTIVE_DOCTYPE_PERMISSION_MISMATCH','APEX_PHASE7A_AUDIT_AFTER_MUTATION_RESIDUE');$missing=@($classes|Where-Object{$register -notmatch [regex]::Escape($_)});Json '03_FAILURE_REGISTER_PRECHECK.json' ([pscustomobject]@{required=$classes;missing=$missing});if($missing.Count -gt 0){Fail 'APEX_FAILURE_REGISTER_PRECHECK_INCOMPLETE' ($missing -join ',')}else{Gate 'failure_register' 'PASS' 'Phase 7A classes registered'}
    if([string]::IsNullOrWhiteSpace($Phase6EvidenceZip)){ $Phase6EvidenceZip=Get-ChildItem -LiteralPath $EvidenceBase -Filter '*phase6*.zip'|Sort-Object LastWriteTime -Descending|Select-Object -First 1 -ExpandProperty FullName }
    $phase6Ok=([IO.File]::Exists($Phase6EvidenceZip));if($phase6Ok){Add-Type -AssemblyName System.IO.Compression.FileSystem;try{[IO.Compression.ZipFile]::OpenRead($Phase6EvidenceZip).Dispose()}catch{$phase6Ok=$false}};Json '04_PHASE6_PREDECESSOR_REVALIDATION.json' ([pscustomobject]@{path=$Phase6EvidenceZip;zipReadable=$phase6Ok});if(-not $phase6Ok){Fail 'APEX_PHASE6_PREDECESSOR_EVIDENCE_UNAVAILABLE' 'No readable Phase 6 evidence ZIP'}else{Gate 'phase6_predecessor' 'PASS' 'Readable sealed predecessor archive found'}
    $ready=Http 'GET' ($GatewayBaseUrl+'/api/erpnext/readiness') @{} $null;Json '07_GATEWAY_HEALTH.json' $ready;if($ready.Status -ne 200){Fail 'APEX_PHASE7A_GATEWAY_ERPNEXT_UNAVAILABLE' ('Readiness status '+$ready.Status)}else{Gate 'gateway_readiness' 'PASS' 'ERPNext readiness returned 200'}
    $contacts=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=1') @{'x-watany-role'='superadmin';Accept='application/json'} $null;$contactBody=$null;try{$contactBody=$contacts.Body|ConvertFrom-Json}catch{};Json '05_DOCTYPE_DISCOVERY.json' ([pscustomobject]@{status=$contacts.Status;doctype='Contact';boundedRead=$contacts.Status -eq 200;response=$contactBody});if($contacts.Status -ne 200){Fail 'APEX_PHASE7A_CONTACT_READ_ROUTE_FAILED' ('Contact read status '+$contacts.Status)}else{Gate 'doctype_discovery' 'PASS' 'Bounded Contact read succeeded'}
    $unauth=Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') @{} @{runId='denied'};$normal=Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') @{'x-watany-role'='public'} @{runId='denied'};Json '08_AUTH_NEGATIVE_TESTS.json' ([pscustomobject]@{unauthenticated=$unauth.Status;normalUser=$normal.Status;pass=($unauth.Status -in @(401,403) -and $normal.Status -in @(401,403))});if($unauth.Status -notin @(401,403) -or $normal.Status -notin @(401,403)){Fail 'APEX_PHASE7A_AUTH_BOUNDARY_FAILED' 'Unauthenticated or normal-user canary request was not denied'}else{Gate 'auth_negative' 'PASS' 'Unauthenticated and normal-user canary requests denied'}
    $runId='phase7a-'+([guid]::NewGuid().ToString('N'));$created=Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') @{'x-watany-role'='superadmin';Accept='application/json'} @{runId=$runId};$createdBody=$created.Body|ConvertFrom-Json;$name=[string]$createdBody.item.name;$encoded=[uri]::EscapeDataString($name);$read=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} $null;$updated=Http 'PATCH' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} @{last_name='LOCAL-UPDATED'};$deleted=Http 'DELETE' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} $null;$after=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) @{'x-watany-role'='superadmin'} $null;Json '09_CRUD_CANARY.json' ([pscustomobject]@{create=$created.Status;read=$read.Status;update=$updated.Status;delete=$deleted.Status;afterDelete=$after.Status;marker=[string]$createdBody.marker});$crudOk=($created.Status -eq 201 -and $read.Status -eq 200 -and $updated.Status -eq 200 -and $deleted.Status -eq 200 -and $after.Status -in @(404,502));if(-not $crudOk){Fail 'APEX_PHASE7A_CRUD_CANARY_FAILED' 'Create/read/update/delete/after-delete contract failed'}else{Gate 'crud_canary' 'PASS' 'Contact CRUD canary completed'}
    $residue=Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=200') @{'x-watany-role'='superadmin'} $null;$residueBody=$residue.Body|ConvertFrom-Json;$items=@($residueBody.items|Where-Object{([string]$_.first_name).StartsWith('APEX-P7-CANARY-')});Json '10_RESIDUE_RECONCILIATION.json' ([pscustomobject]@{status=$residue.Status;canaryCount=$items.Count;zeroResidue=$items.Count -eq 0});if($residue.Status -ne 200 -or $items.Count -ne 0){Fail 'APEX_PHASE7A_ZERO_RESIDUE_FAILED' ('Canary residue count '+$items.Count)}else{Gate 'zero_residue' 'PASS' 'No APEX-P7-CANARY residue remains'}
    $typecheck=& pnpm.cmd --dir (Join-Path $WorkspaceRoot 'apps\gateway-api') typecheck 2>&1|Out-String;$tc=$LASTEXITCODE;Json '11_TYPECHECK.json' ([pscustomobject]@{exitCode=$tc;output=$typecheck});if($tc -ne 0){Fail 'APEX_PHASE7A_GATEWAY_TYPECHECK_FAILED' 'Gateway typecheck failed'}else{Gate 'typecheck' 'PASS' 'Gateway typecheck passed'}
    if($Failures.Count -eq 0){$Status='PASS';Text '19_AUTHORITY_CLOSEOUT_TOKEN.txt' 'PHASE7_RESUME_AUTHORIZATION=READY`r`n'}else{Text '19_AUTHORITY_CLOSEOUT_TOKEN.txt' 'PHASE7_RESUME_AUTHORIZATION=BLOCKED`r`n'}
} catch { $msg=$_.Exception.Message;Text 'ERROR_LOG.txt' ($msg+'`r`n');if([string]::IsNullOrWhiteSpace($PrimaryFailure)){$PrimaryFailure='APEX_PHASE7A_CONTROLLER_UNHANDLED_FAILURE'};$Status='BLOCKED';$Failures.Add([pscustomobject]@{FailureClass=$PrimaryFailure;Detail=$msg;Status='ACTIVE'})|Out-Null }
$gateHeader='Gate,Status,Detail';$gateLines=@($gateHeader)+@($Gates|ForEach-Object{'"{0}","{1}","{2}"' -f $_.Gate,$_.Status,($_.Detail -replace '"','""')});Text '12_PHASE7A_GATE_RESULTS.csv' (($gateLines -join "`r`n")+"`r`n");$failLines=@('FailureClass,Status,Detail')+@($Failures|ForEach-Object{'"{0}","{1}","{2}"' -f $_.FailureClass,$_.Status,($_.Detail -replace '"','""')});Text '13_PHASE7A_FAILURES.csv' (($failLines -join "`r`n")+"`r`n");$actLines=@('Action,Status,Detail')+@($Actions|ForEach-Object{'"{0}","{1}","{2}"' -f $_.Action,$_.Status,($_.Detail -replace '"','""')});Text '14_PHASE7A_ACTIONS.csv' (($actLines -join "`r`n")+"`r`n");Json '15_FINAL_STATUS.json' ([pscustomobject]@{status=$Status;primaryFailure=$PrimaryFailure;authority=$Authority;generatedAt=[DateTimeOffset]::Now.ToString('o')});Json 'summary.json' ([pscustomobject]@{status=$Status;primaryFailure=$PrimaryFailure;gates=$Gates.Count;failures=$Failures.Count});Text 'FINAL_STATUS.txt' ('OVERALL_STATUS='+$Status+'`r`nPRIMARY_FAILURE='+$PrimaryFailure+'`r`n');Text 'FINAL_REPORT.md' ('# Phase 7A Final Report`r`n`r`nStatus: '+$Status+'`r`nPrimary failure: '+$PrimaryFailure+'`r`n');Json 'progress.json' ([pscustomobject]@{status=$Status;stage='FINALIZED'});Text 'progress.csv' "Stage,Status`r`nFINALIZED,$Status`r`n";Text 'checkpoint.json' '{"stage":"FINALIZED"}`r`n';Text 'validations.csv' "Validation,Status`r`n";Text 'actions.csv' "Action,Status,Detail`r`n";Text 'failures.csv' "FailureClass,Status,Detail`r`n";Text 'warnings.csv' "Warning,Status,Detail`r`n";Text 'EXECUTION_LOG.txt' ('FINAL_STATUS='+$Status+'`r`n');$manifest=@(Get-ChildItem -LiteralPath $EvidenceRoot -File|ForEach-Object{[pscustomobject]@{name=$_.Name;sha256=(Sha $_.FullName)}});Json '16_EVIDENCE_MANIFEST.json' $manifest;$hashLines=@($manifest|ForEach-Object{$_.sha256+'  '+$_.name});Text '17_EVIDENCE_SHA256.txt' (($hashLines -join "`r`n")+"`r`n");if([IO.File]::Exists($EvidenceZip)){Remove-Item -LiteralPath $EvidenceZip -Force};[IO.Compression.ZipFile]::CreateFromDirectory($EvidenceRoot,$EvidenceZip);$zip=[IO.Compression.ZipFile]::OpenRead($EvidenceZip);$entryCount=$zip.Entries.Count;$zip.Dispose();Json '18_ZIP_REOPEN_MODEL.json' ([pscustomobject]@{zip=$EvidenceZip;reopened=$true;entryCount=$entryCount});Json $SidecarPath ([pscustomobject]@{status='PASS';zip=$EvidenceZip;entryCount=$entryCount;reopened=$true});Write-Output 'APEX_PS1_SKILL_UPDATE_NOT_REQUIRED';Write-Output ('EVIDENCE_ROOT='+$EvidenceRoot);Write-Output ('EVIDENCE_ZIP='+$EvidenceZip);Write-Output ('FINAL_SIDECAR='+$SidecarPath);Write-Output ('PHASE7_RESUME_AUTHORIZATION='+$(if($Status -eq 'PASS'){'READY'}else{'BLOCKED'}));Write-Output ('OVERALL_STATUS='+$Status);if($Status -ne 'PASS'){exit 1}else{exit 0}
