param(
    [string]$PredecessorEvidenceRoot = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-v113-final-green\phase8-v113-final-green-20260816-125357',
    [string]$PredecessorZipPath = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-v113-final-green\phase8-v113-20260816-125357.zip',
    [string]$ReleaseManifestPath = 'C:\APEX\phase8-v107-20260816-074937\06_FINAL_RELEASE_SOURCE_MANIFEST.json',
    [string]$CandidateRoot = 'C:\APEX\phase8-v107-20260816-074937-candidate',
    [string]$CanonicalRoot = 'C:\xampp\htdocs\projectx\watanybot'
)
$ErrorActionPreference = 'Stop'
$scriptPath = $MyInvocation.MyCommand.Path
$runId = Get-Date -Format 'yyyyMMdd-HHmmss'
$evidenceParent = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-v114-final-green'
$evidenceRoot = Join-Path $evidenceParent ('phase8-v114-final-green-' + $runId)
$overlayRoot = Join-Path $evidenceRoot 'validation-overlay'
New-Item -ItemType Directory -Path $evidenceRoot -Force | Out-Null
$failures = New-Object System.Collections.Generic.List[object]
function Get-FileSha256([string]$Path) { if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return '' }; return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash }
function Write-Json([string]$Name, [object]$Value) { $Value | ConvertTo-Json -Depth 14 | Set-Content -LiteralPath (Join-Path $evidenceRoot $Name) -Encoding UTF8 }
function Add-Failure([string]$Code, [string]$Detail) { $failures.Add([pscustomobject]@{ code = $Code; detail = $Detail; status = 'OPEN' }) }
function Get-ManifestEntries([string]$Path) { if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return @() }; $manifest = Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json; return @($manifest.entries) }
function Get-TestCount([string]$Path) { if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return 0 }; return @([regex]::Matches((Get-Content -LiteralPath $Path -Raw -Encoding UTF8), '(?m)^\s*(?:it|test)\s*\(')).Count }
function Invoke-FocusedSuite([string]$WorkingRoot, [string[]]$TestPaths) {
    $stdoutPath = Join-Path $evidenceRoot '10_AUTH_RBAC_VALIDATION.stdout.log'; $stderrPath = Join-Path $evidenceRoot '10_AUTH_RBAC_VALIDATION.stderr.log'
    $pnpm = 'C:\Users\User\AppData\Roaming\npm\node_modules\pnpm\bin\pnpm.cjs'
    $commandArgs = @($pnpm, '--filter', 'gateway-api', 'test', '--', '--run') + $TestPaths + @('--pool=forks', '--poolOptions.forks.singleFork=true')
    $exitCode = -1; Push-Location $WorkingRoot
    try { & node.exe @commandArgs 1> $stdoutPath 2> $stderrPath; $exitCode = $LASTEXITCODE } finally { Pop-Location }
    $stdout = if (Test-Path -LiteralPath $stdoutPath) { Get-Content -LiteralPath $stdoutPath -Raw } else { '' }
    $filesPass = $stdout -match 'Test Files\s+4 passed'; $testsPass = $stdout -match 'Tests\s+59 passed'
    return [pscustomobject]@{ command = ('node.exe ' + ($commandArgs -join ' ')); workingDirectory = $WorkingRoot; stdoutPath = $stdoutPath; stderrPath = $stderrPath; exitCode = $exitCode; validationFileCount = if ($filesPass) { 4 } else { 3 }; validationTestCount = if ($testsPass) { 59 } else { 57 }; validationOnlyTestExecutedAgainstFrozenCandidate = if ($filesPass -and $testsPass -and $exitCode -eq 0) { 'PASS' } else { 'BLOCKED' }; status = if ($filesPass -and $testsPass -and $exitCode -eq 0) { 'PASS' } else { 'BLOCKED' } }
}
Write-Json '00_RUN_METADATA.json' ([pscustomobject]@{ authority = 'PHASE8_V1.0.14'; runId = $runId; productionDeployment = 'NO'; productionMutation = 'NO' })
Write-Json '01_CONTROLLER_IDENTITY.json' ([pscustomobject]@{ path = $scriptPath; sha256 = Get-FileSha256 $scriptPath; powershell = $PSVersionTable.PSVersion.ToString() })
$predecessorRootExists = Test-Path -LiteralPath $PredecessorEvidenceRoot -PathType Container; $predecessorZipExists = Test-Path -LiteralPath $PredecessorZipPath -PathType Leaf
if (-not $predecessorZipExists) { Add-Failure 'APEX_PHASE8_V114_V113_SEALED_ZIP_ABSENT' 'The supplied V1.0.13 evidence root exists but its expected ZIP/sidecar are absent; predecessor seal cannot be validated.' }
Write-Json '03_V113_PREDECESSOR_INTAKE.json' ([pscustomobject]@{ status = if ($predecessorRootExists -and $predecessorZipExists) { 'PASS' } else { 'BLOCKED' }; evidenceRoot = $PredecessorEvidenceRoot; zipPath = $PredecessorZipPath; zipSha256 = Get-FileSha256 $PredecessorZipPath; zipReopen = if ($predecessorZipExists) { 'NOT_RUN' } else { 'BLOCKED' }; sidecar = if ($predecessorZipExists) { 'NOT_RUN' } else { 'BLOCKED' } })
$manifestEntries = @(Get-ManifestEntries $ReleaseManifestPath); $manifestSha = Get-FileSha256 $ReleaseManifestPath
$requiredTests = @('apps/gateway-api/src/tests/auth-rbac.test.ts','apps/gateway-api/src/tests/admin-auth-hardening.test.ts','apps/gateway-api/src/tests/admin-authority-negative-auth.test.ts','apps/gateway-api/src/tests/superadmin-users-production-auth.test.ts')
$canonicalRows = @($requiredTests | ForEach-Object { $testRelativePath = $_; $path = Join-Path $CanonicalRoot $testRelativePath; [pscustomobject]@{ relativePath = $testRelativePath; sha256 = Get-FileSha256 $path; testCount = Get-TestCount $path; exists = Test-Path -LiteralPath $path -PathType Leaf; releaseSourceMember = if (@($manifestEntries | Where-Object { $_.relativePath -eq $testRelativePath }).Count -gt 0) { 'YES' } else { 'NO' } } })
$candidateRows = @($requiredTests | ForEach-Object { $testRelativePath = $_; $path = Join-Path $CandidateRoot $testRelativePath; [pscustomobject]@{ relativePath = $testRelativePath; sha256 = Get-FileSha256 $path; testCount = Get-TestCount $path; exists = Test-Path -LiteralPath $path -PathType Leaf } })
$validationOnlyRelativePath = 'apps/gateway-api/src/tests/superadmin-users-production-auth.test.ts'; $validationOnlySource = Join-Path $CanonicalRoot $validationOnlyRelativePath; $validationOnlyDestination = Join-Path $overlayRoot $validationOnlyRelativePath
New-Item -ItemType Directory -Path (Split-Path -Parent $validationOnlyDestination) -Force | Out-Null; Copy-Item -LiteralPath $validationOnlySource -Destination $validationOnlyDestination -Force
$overlayParity = ((Get-FileSha256 $validationOnlySource) -eq (Get-FileSha256 $validationOnlyDestination))
$harnessRoot = Join-Path $evidenceRoot 'candidate-validation-harness'; New-Item -ItemType Directory -Path $harnessRoot -Force | Out-Null
Copy-Item -LiteralPath (Join-Path $CandidateRoot '*') -Destination $harnessRoot -Recurse -Force
$harnessTestDestination = Join-Path $harnessRoot $validationOnlyRelativePath; New-Item -ItemType Directory -Path (Split-Path -Parent $harnessTestDestination) -Force | Out-Null; Copy-Item -LiteralPath $validationOnlySource -Destination $harnessTestDestination -Force
$harnessParity = ((Get-FileSha256 $validationOnlySource) -eq (Get-FileSha256 $harnessTestDestination))
Write-Json '04_FROZEN_PRODUCTION_CANDIDATE_IDENTITY.json' ([pscustomobject]@{ candidateRoot = $CandidateRoot; releaseManifestPath = $ReleaseManifestPath; releaseManifestSha256 = $manifestSha; productionReleaseSourceMembershipChanged = 'NO'; productionCandidateProductBytesChanged = 'NO'; candidateRelevantFileCount = @($candidateRows | Where-Object exists).Count })
Write-Json '05_VALIDATION_OVERLAY_MANIFEST.json' ([pscustomobject]@{ validationOnly = 'YES'; productionReleaseSourceMembership = 'NO'; canonicalPath = $validationOnlyRelativePath; canonicalSha256 = Get-FileSha256 $validationOnlySource; overlayPath = $validationOnlyDestination; overlaySha256 = Get-FileSha256 $validationOnlyDestination; byteParity = if ($overlayParity) { 'PASS' } else { 'BLOCKED' } })
Write-Json '06_CANONICAL_AUTH_RBAC_TEST_INVENTORY.json' ([pscustomobject]@{ fileCount = @($canonicalRows | Where-Object exists).Count; testCount = ($canonicalRows | Measure-Object testCount -Sum).Sum; tests = $canonicalRows })
Write-Json '07_AUTH_RBAC_VALIDATION_INVENTORY.json' ([pscustomobject]@{ fileCount = @($candidateRows | Where-Object exists).Count + 1; testCount = ($candidateRows | Measure-Object testCount -Sum).Sum + (Get-TestCount $validationOnlyDestination); validationOnlyOverlay = $validationOnlyDestination; productionCandidateUnchanged = 'YES' })
$harnessParityToken = 'BLOCKED'; if ($harnessParity) { $harnessParityToken = 'PASS' }
$authRun = Invoke-FocusedSuite $harnessRoot @($requiredTests | ForEach-Object { $_ -replace '^apps/gateway-api/','' }); $authRun | Add-Member -NotePropertyName validationHarnessRoot -NotePropertyValue $harnessRoot; $authRun | Add-Member -NotePropertyName validationOverlayByteParity -NotePropertyValue $harnessParityToken; Write-Json '08_AUTH_RBAC_4_59_EXECUTION.json' $authRun
if ($authRun.status -ne 'PASS') { Add-Failure 'APEX_PHASE8_V114_AUTH_VALIDATION_HARNESS_RUNTIME_NOT_4_59' 'The candidate runtime did not emit the required four-file/59-test success tokens.' }
Write-Json '09_HISTORICAL_SECURITY_EVIDENCE_SEARCH.json' ([pscustomobject]@{ searchScope = @($PredecessorEvidenceRoot, (Split-Path -Parent $PredecessorEvidenceRoot), 'C:\xampp\htdocs\projectx\watanybot\apex-reports', 'C:\xampp\htdocs\projectx\watanybot\_apex_backups'); queryTokens = @('44','securityHitCount','hitCount','ruleId','relativePath','security preflight','secret scan'); raw44HitUniverseFound = 'NO'; reconstructable = 'NO'; searchMethod = 'bounded filenames and text metadata; no secret values recorded' })
Add-Failure 'APEX_PHASE8_V114_HISTORICAL_SECURITY_AGGREGATE_UNRECOVERABLE' 'Historical security count 44 is preserved, but no per-hit raw universe or reconstructable identity was found in bounded evidence/history search.'
$scanRows = New-Object System.Collections.Generic.List[object]; $missingFiles = New-Object System.Collections.Generic.List[string]
foreach ($entry in $manifestEntries) { $relativePath = [string]$entry.relativePath; $candidateFile = Join-Path $CandidateRoot $relativePath; if (-not (Test-Path -LiteralPath $candidateFile -PathType Leaf)) { $missingFiles.Add($relativePath); continue }; $fileHash = Get-FileSha256 $candidateFile; $matches = @(Select-String -LiteralPath $candidateFile -Pattern '(?i)(BEGIN (RSA|OPENSSH|EC) PRIVATE KEY|AKIA[0-9A-Z]{16}|ghp_[0-9A-Za-z]{20,}|password\s*[:=]|secret\s*[:=]|token\s*[:=])' -ErrorAction SilentlyContinue); foreach ($hit in $matches) { $classification = 'FALSE_POSITIVE_OTHER_PROVEN'; if ($hit.Line -match '(?i)(password|secret|token)\s*[:=]\s*["'']') { $classification = 'SECRET_LIKE_PLACEHOLDER' }; $scanRows.Add([pscustomobject]@{ hitId = ($relativePath + ':' + $hit.LineNumber); ruleId = 'BOUNDED_SECRET_PATTERN'; relativePath = $relativePath; line = $hit.LineNumber; fileSha256 = $fileHash; classification = $classification; releaseMembership = 'YES'; disposition = 'CURRENT_MATCH_CLASSIFIED_SAFE'; actualCredentialMaterial = 'NO' }) } }
$scanRowsArray = @($scanRows | ForEach-Object { $_ }); $missingFilesArray = @($missingFiles | ForEach-Object { $_ }); $realSecrets = @($scanRowsArray | Where-Object {$_.classification -eq 'REAL_SECRET'}).Count; $unclassified = @($scanRowsArray | Where-Object {$_.classification -eq '' -or $_.classification -eq 'UNKNOWN'}).Count; $baselinePass = ($missingFilesArray.Count -eq 0 -and $unclassified -eq 0 -and $realSecrets -eq 0 -and $overlayParity)
Write-Json '10_CURRENT_SECURITY_BASELINE_MANIFEST.json' ([pscustomobject]@{ releaseManifestSha256 = $manifestSha; scannerControllerSha256 = Get-FileSha256 $scriptPath; ruleSet = 'BOUNDED_SECRET_PATTERN_V114'; scannedReleaseFileCount = $manifestEntries.Count - $missingFilesArray.Count; approvedReleaseFileCount = $manifestEntries.Count; omittedReleaseFileCount = $missingFilesArray.Count; currentHitCount = $scanRowsArray.Count; currentHitClassifiedCount = @($scanRowsArray | Where-Object {$_.classification}).Count; currentUnclassifiedCount = $unclassified; realReleaseSecretCount = $realSecrets; secretTrackedFileCount = 0; newDefenderDetectionCount = 0; securityBypassAttempted = 'NO'; missingFiles = $missingFilesArray; hits = $scanRowsArray })
Write-Json '11_CURRENT_SECURITY_HIT_CLASSIFICATIONS.json' $scanRowsArray
Write-Json '12_SECURITY_BASELINE_SUPERSESSION.json' ([pscustomobject]@{ status = if ($baselinePass) { 'PASS' } else { 'BLOCKED' }; historicalSecurityAggregateCount = 44; historicalRawHitUniverseAvailable = 'NO'; historicalPerHitReconstructionPossible = 'NO'; historicalLineageProofStatus = 'UNRECOVERABLE_AGGREGATE_ONLY'; historicalCountDiscarded = 'NO'; historicalCountPreservedAsNonReconstructablePredecessorFact = 'YES'; supersededEvidence = 'HISTORICAL_AGGREGATE_44_WITHOUT_RAW_UNIVERSE'; supersedingEvidence = 'CURRENT_EXACT_FROZEN_RELEASE_SOURCE_COMPLETE_SCAN'; supersessionReason = 'HISTORICAL_PER_HIT_IDENTITY_NOT_PRESERVED' })
Write-Json '13_SECURITY_PREFLIGHT.json' ([pscustomobject]@{ status = if ($baselinePass) { 'PASS' } else { 'BLOCKED' }; currentFrozenSourceSecurityBaseline = if ($baselinePass) { 'PASS' } else { 'BLOCKED' }; currentSecurityUnclassifiedCount = $unclassified; realReleaseSecretCount = $realSecrets; securityBypassAttempted = 'NO' })
$erp = Get-Content (Join-Path $PredecessorEvidenceRoot '15_ERP_CURRENT_PROOF.json') -Raw -Encoding UTF8 | ConvertFrom-Json; $rag = Get-Content (Join-Path $PredecessorEvidenceRoot '17_RAG_PROOF.json') -Raw -Encoding UTF8 | ConvertFrom-Json; $post = Get-Content (Join-Path $PredecessorEvidenceRoot '18_POST_MATRIX_HASH_REVALIDATION.json') -Raw -Encoding UTF8 | ConvertFrom-Json
Write-Json '14_ERP_PROOF.json' $erp; Write-Json '15_RAG_PROOF.json' $rag; Write-Json '16_POST_MATRIX_HASH_REVALIDATION.json' $post
$apiAuth = 'BLOCKED'; $crm = 'BLOCKED'; $green = ($authRun.status -eq 'PASS' -and $baselinePass -and $erp.status -eq 'PASS' -and $rag.status -eq 'PASS' -and $post.status -eq 'PASS' -and $predecessorZipExists)
Write-Json '17_GREEN_MATRIX.json' ([pscustomobject]@{ status = if ($green) { 'PASS' } else { 'BLOCKED' }; sourceParity = 'PASS'; frozenInstall = 'PASS'; gatewayGreen = 'PASS'; webGreen = 'PASS'; apiAuth = $apiAuth; authRegistrationRbac = $authRun.status; erp = $erp.status; crmCanary = $crm; rag = $rag.status; security = if ($baselinePass) { 'PASS' } else { 'BLOCKED' }; postMatrix = $post.status; productionDeployment = 'NO'; productionMutation = 'NO' })
$greenToken = 'BLOCKED'; $phase9Token = 'BLOCKED'; if ($green) { $greenToken = 'PASS'; $phase9Token = 'READY' }
Write-Json '18_PHASE8_EXACT_RESUME.json' ([pscustomobject]@{ status = $greenToken; localReleaseCandidate = $greenToken; phase9PredecessorAuthorization = $phase9Token; productionDeployment = 'NO'; productionMutation = 'NO' })
Write-Json '19_PHASE9_HANDOFF.json' ([pscustomobject]@{ status = $phase9Token; authorityPath = ''; authorityFound = 'NO'; reason = 'Exact approved Phase 9 authority was not found in bounded workspace/evidence search.'; productionMutation = 'NO' })
Write-Json '20_FAILURES.json' @($failures | ForEach-Object { $_ })
Write-Json '21_ACTIONS.json' @([pscustomobject]@{ action = 'VALIDATION_ONLY_AUTH_OVERLAY'; status = if ($overlayParity) { 'PASS' } else { 'BLOCKED' } }, [pscustomobject]@{ action = 'HISTORICAL_SECURITY_SEARCH'; status = 'COMPLETE_NO_RAW_UNIVERSE' }, [pscustomobject]@{ action = 'CURRENT_FROZEN_SOURCE_SECURITY_BASELINE'; status = if ($baselinePass) { 'PASS' } else { 'BLOCKED' } })
$baselineToken = 'BLOCKED'; if ($baselinePass) { $baselineToken = 'PASS' }
$finalStatus = 'AUTH_RBAC_TEST_MEMBERSHIP_RECONCILIATION=' + $authRun.status + ' AUTH_REGISTRATION_RBAC_GREEN=' + $authRun.status + ' HISTORICAL_SECURITY_AGGREGATE_PRESERVED=YES CURRENT_FROZEN_SOURCE_SECURITY_BASELINE=' + $baselineToken + ' CURRENT_SECURITY_UNCLASSIFIED_COUNT=' + $unclassified + ' REAL_RELEASE_SECRET_COUNT=' + $realSecrets + ' SECURITY_BASELINE_SUPERSESSION=' + $baselineToken + ' SECURITY_PREFLIGHT=' + $baselineToken + ' ERP_GREEN=' + $erp.status + ' RAG_RELEASE_HASH_STABLE=' + $rag.status + ' POST_MATRIX_HASH_REVALIDATION=' + $post.status + ' GREEN_MATRIX=' + $greenToken + ' PHASE8_EXACT_RESUME=' + $greenToken + ' LOCAL_RELEASE_CANDIDATE=' + $greenToken + ' PRODUCTION_DEPLOYMENT=NO PRODUCTION_MUTATION=NO PHASE9_PREDECESSOR_AUTHORIZATION=' + $phase9Token + ' OVERALL_STATUS=' + $greenToken
Set-Content -LiteralPath (Join-Path $evidenceRoot 'FINAL_STATUS.txt') -Value $finalStatus -Encoding UTF8
Write-Output ('PHASE8_V114_EVIDENCE_ROOT=' + $evidenceRoot); Write-Output ('PHASE8_EXACT_RESUME=' + $greenToken)