#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$PredecessorRoot = '',
    [string]$ParserPreflightProofPath = ''
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$workspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE8A_REMAINING_12_PATH_OWNERSHIP_RESOLUTION_RELEASE_SOURCE_SET_FINAL_FREEZE_EXACT_PHASE8_GREEN_RESUME_AND_PRODUCTION_PREDECESSOR_SEAL_V1_0_1'
$skillExpected = 'CE317015ACF91FB84C0D4AEE4EE91F8E2B2C0A75F81926C87AB098F922BB33EB'
$evidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase8a-v101-final-freeze-' + (Get-Date -Format 'yyyyMMdd-HHmmss'))
$evidenceZip = $evidenceRoot + '.zip'
$sidecarPath = $evidenceZip + '.final-reopen-validation.json'
$failures = New-Object Collections.ArrayList
$gates = New-Object Collections.ArrayList
$primaryFailure = ''

function Ensure-Directory([string]$path) { if (-not [IO.Directory]::Exists($path)) { [IO.Directory]::CreateDirectory($path) | Out-Null } }
function Get-Hash([string]$path) { if (-not [IO.File]::Exists($path)) { return '' }; (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Write-Artifact([string]$name, [AllowEmptyString()][string]$value) { [IO.File]::WriteAllText((Join-Path $evidenceRoot $name), $value, (New-Object Text.UTF8Encoding($false))) }
function Write-Json([string]$name, $value) { Write-Artifact $name (($value | ConvertTo-Json -Depth 40) + [Environment]::NewLine) }
function Add-Gate([string]$name, [string]$status, [string]$detail) { [void]$gates.Add([pscustomobject]@{gate=$name;status=$status;detail=$detail}) }
function Add-Failure([string]$class, [string]$detail) { [void]$failures.Add([pscustomobject]@{failureClass=$class;detail=$detail;status='ACTIVE'}); if ([string]::IsNullOrWhiteSpace($primaryFailure)) { $script:primaryFailure = $class } }
function Gate([bool]$condition, [string]$name, [string]$failureClass, [string]$detail) { if ($condition) { Add-Gate $name 'PASS' $detail } else { Add-Failure $failureClass $detail; Add-Gate $name 'BLOCKED' $detail } }
function Git-Result([string[]]$commandArgs) {
    $stdoutPath=[IO.Path]::GetTempFileName(); $stderrPath=[IO.Path]::GetTempFileName()
    try { & git.exe -C $workspaceRoot -c core.autocrlf=false @commandArgs 1> $stdoutPath 2> $stderrPath; $exitCode=$LASTEXITCODE; $stdout=''; $stderr=''; if(Test-Path $stdoutPath){$stdout=[IO.File]::ReadAllText($stdoutPath)}; if(Test-Path $stderrPath){$stderr=[IO.File]::ReadAllText($stderrPath)}; [pscustomobject]@{exitCode=$exitCode;lines=@($stdout -split [Environment]::NewLine | Where-Object{$_ -ne ''});raw=$stdout;stderr=$stderr} } finally { Remove-Item $stdoutPath,$stderrPath -Force -ErrorAction SilentlyContinue }
}
function Status-Records {
    $result=Git-Result @('status','--porcelain=v1','-z','--untracked-files=all'); if($result.exitCode -ne 0){throw ('git status failed: ' + $result.exitCode)}
    $records=@(); foreach($part in ([string]$result.raw -split [char]0)){if([string]::IsNullOrWhiteSpace($part)){continue};if($part.Length -lt 4){continue};$records += [pscustomobject]@{status=$part.Substring(0,2);path=$part.Substring(3)}}; return ,$records
}
function Classify([string]$path, [string]$status, [string]$diffText) {
    $lower=$path.ToLowerInvariant(); $class='UNKNOWN_OR_CONFLICTING_OWNERSHIP'; $basis='No positive ownership rule matched'; $owner='unknown'; $release='EXCLUDE'; $include=$false; $phase='UNPROVEN'; $generated='UNKNOWN'; $secret='SCANNED_NO_VALUE'; $decision=$true
    if($lower -match '(^|[\\/])\.env($|\.)|credential|password|private[-_]?key|api[-_]?key|token|secret'){ $class='SECRET_OR_CREDENTIAL_MATERIAL';$basis='Credential-shaped filename requires exclusion';$owner='local-security';$phase='LOCAL';$generated='NO';$secret='REVIEW_REQUIRED';$decision=$false }
    elseif($lower -eq 'watany_kb_tables_v4/watany_rag_chunks_v4.jsonl' -or $lower -eq 'watany_kb_tables_v4\watany_rag_chunks_v4.jsonl'){ $class='INTENTIONALLY_RELEASED_DATA_OR_CONTENT';$basis='Tracked RAG runtime asset; referenced by Gateway config and prior runtime/deployment evidence';$owner='gateway-kb';$release='INCLUDE';$include=$true;$phase='GATEWAY_RUNTIME';$generated='NO';$decision=$false }
    elseif($lower -match '(^|[\\/])\.tmp_|(^|[\\/])tmp[\\/]|(^|[\\/])temp[_-]|\.cache'){ $class='LOCAL_RUNTIME_OR_CACHE';$basis='Temporary local consumer inventory';$owner='local-runtime';$phase='LOCAL';$generated='YES_OR_LOCAL';$decision=$false }
    elseif($lower -match '\.parser-preflight\.json$|\.ps51-parser-preflight\.json$|(^|[\\/])apex-reports([\\/])|(^|[\\/])evidence([\\/])|\.zip$|\.final-reopen-validation\.json$'){ $class='GENERATED_EVIDENCE_OR_REPORT';$basis='Parser proof, report, archive, or evidence artifact';$owner='APEX-governance';$phase='APEX';$generated='YES';$decision=$false }
    elseif($lower -match '^apex_.*\.(ps1|md)$|(^|[\\/])pma[\\/]|(^|[\\/])\.pma[\\/]|(^|[\\/])scripts[\\/]|(^|[\\/])tools[\\/]'){ $class='APEX_CONTROLLER_OR_AUTHORITY';$basis='Governance controller, register, script, or tool';$owner='APEX-governance';$phase='APEX';$generated='NO_OR_LOCAL';$decision=$false }
    elseif($lower -eq 'apps/web-user/src/components/superadmin/superadmincrmcommandcenter.tsx' -or $lower -eq 'apps\\web-user\\src\\components\\superadmin\\superadmincrmcommandcenter.tsx'){ $class='APPROVED_STAGE_X_RELEASE_SOURCE';$basis='Predecessor-approved Stage X Superadmin CRM source path';$owner='Stage-X CRM';$release='INCLUDE';$include=$true;$phase='PHASE7_CONSUMED';$generated='NO';$decision=$false }
    elseif($lower -match '^apps[\\/]|^packages[\\/]|^public[\\/]|^data[\\/]|^mof[\\/]'){ $class='PREEXISTING_UNRELATED_USER_WORK';$basis='Application/content path outside the two proven approved source entries';$owner='workspace-user';$phase='OUTSIDE_PHASE8A';$generated='NO_OR_UNKNOWN';$decision=$false }
    else { $class='PREEXISTING_UNRELATED_USER_WORK';$basis='Non-release workspace material with no approved Stage X lineage';$owner='workspace-user';$phase='OUTSIDE_PHASE8A';$generated='NO_OR_UNKNOWN';$decision=$false }
    [pscustomobject]@{classification=$class;classificationBasis=$basis;likelyOwner=$owner;releaseRelevance=$release;includeInReleaseSourceSet=$include;phaseLineage=$phase;generatedArtifactStatus=$generated;secretScanStatus=$secret;requiresUserDecision=$decision;notes='Preserved in canonical worktree'}
}

try {
    Ensure-Directory $evidenceRoot
    $artifactNames=@('00_AUTHORITY.txt','01_CONTROLLER_IDENTITY.json','02_APEX_SKILL.json','03_FAILURE_REGISTER.json','04_PREDECESSOR_VALIDATION.json','05_REMAINING_PATH_INPUT.json','06_REMAINING_PATH_RECONCILIATION.json','07_REMAINING_PATH_CLASSIFICATIONS.json','08_REMAINING_PATH_CLASSIFICATIONS.csv','09_RELEASE_SOURCE_SET_FINAL.json','10_RELEASE_SOURCE_SET_FINAL.csv','11_RELEASE_SOURCE_SET_FINAL.sha256','12_RELEASE_EXCLUSION_SET_FINAL.json','13_RELEASE_SOURCE_SECRET_SCAN.json','14_VALIDATION_SOURCE_IDENTITY.json','15_VALIDATION_SOURCE_HASHES.json','16_PHASE8_EXACT_RESUME.json','17_PHASE9_HANDOFF.json','18_MUTATION_ACCOUNTING.json','19_GATE_MATRIX.csv','20_FAILURE_LOG.json','FINAL_STATUS.txt','FINAL_REPORT.md','EXECUTION_LOG.txt','ERROR_LOG.txt','AUTHORITY_CLOSEOUT_TOKEN.txt','EVIDENCE_MANIFEST.json','EVIDENCE_SHA256.txt')
    foreach($artifact in $artifactNames){Write-Artifact $artifact ('NOT_STARTED' + [Environment]::NewLine)}
    Write-Artifact '00_AUTHORITY.txt' ($authority + [Environment]::NewLine + 'PRODUCTION_DEPLOYMENT=NO' + [Environment]::NewLine)
    Write-Artifact 'EXECUTION_LOG.txt' ('START=' + (Get-Date -Format o) + [Environment]::NewLine)
    $controllerHash=Get-Hash $PSCommandPath
    $proofObject=$null; if(-not [string]::IsNullOrWhiteSpace($ParserPreflightProofPath) -and (Test-Path $ParserPreflightProofPath)){ $proofObject=Get-Content -Raw -Encoding UTF8 $ParserPreflightProofPath|ConvertFrom-Json }
    $proofPass=($null -ne $proofObject -and [string]$proofObject.sha256 -eq $controllerHash -and [int]$proofObject.parserErrorCount -eq 0 -and [string]$proofObject.psVersion -like '5.1*')
    Write-Json '01_CONTROLLER_IDENTITY.json' ([pscustomobject]@{authority=$authority;path=$PSCommandPath;sha256=$controllerHash;parserProofPath=$ParserPreflightProofPath;parserProofMatch=$proofPass})
    $skillPath=Join-Path $workspaceRoot '.pma\skills\apex-ps1\SKILL.md';$skillHash=Get-Hash $skillPath;Write-Json '02_APEX_SKILL.json' ([pscustomobject]@{path=$skillPath;sha256=$skillHash;expectedSha256=$skillExpected;pass=($skillHash -eq $skillExpected)});Gate ($skillHash -eq $skillExpected) 'APEX_PS1_SKILL_LOAD' 'APEX_SKILL_UNVERIFIED' 'Repository skill hash';Gate $proofPass 'PS51_PARSER_PREFLIGHT' 'APEX_PHASE8A_V101_PARSER_PROOF_INVALID' 'External exact-byte parser proof'
    $registerPath=Join-Path $workspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md';$registerText=Get-Content -Raw -Encoding UTF8 $registerPath;$registerPass=$registerText -match 'APEX_PHASE8A_PHASE8_RESUME_WEAKENED_GATE';Write-Json '03_FAILURE_REGISTER.json' ([pscustomobject]@{path=$registerPath;sha256=Get-Hash $registerPath;newGuardPresent=$registerPass});Gate $registerPass 'KNOWN_REGRESSION_GUARDS' 'APEX_PHASE8A_FAILURE_REGISTER_GUARD_MISSING' 'V1.0.1 guard registered'
    if([string]::IsNullOrWhiteSpace($PredecessorRoot)){ $candidate=Get-ChildItem $EvidenceBase -Directory|Where-Object{$_.Name -like 'watany-control-center-crm-phase8a-source-freeze-*'}|Sort-Object LastWriteTime -Descending|Select-Object -First 1;$PredecessorRoot=[string]$candidate.FullName }
    $predZip=$PredecessorRoot+'.zip';$predSide=$predZip+'.final-reopen-validation.json';$sideObject=$null;if(Test-Path $predSide){$sideObject=Get-Content -Raw -Encoding UTF8 $predSide|ConvertFrom-Json};$predHash=Get-Hash $predZip;$predPass=($null -ne $sideObject -and [string]$sideObject.status -eq 'PASS' -and [string]$sideObject.sha256 -eq $predHash -and (Test-Path (Join-Path $PredecessorRoot '11_CLASSIFICATION_SUMMARY.json')) -and (Test-Path (Join-Path $PredecessorRoot '15_PHASE8_EXACT_RESUME_IDENTITY.json')));$summary=Get-Content -Raw -Encoding UTF8 (Join-Path $PredecessorRoot '11_CLASSIFICATION_SUMMARY.json')|ConvertFrom-Json;$priorInput=@($summary.unclassifiedPaths);Write-Json '04_PREDECESSOR_VALIDATION.json' ([pscustomobject]@{root=$PredecessorRoot;zip=$predZip;zipSha256=$predHash;sidecarSha256=[string]$sideObject.sha256;sidecarStatus=[string]$sideObject.status;pass=$predPass});Write-Json '05_REMAINING_PATH_INPUT.json' ([pscustomobject]@{source='11_CLASSIFICATION_SUMMARY.json';count=$priorInput.Count;paths=$priorInput});Gate $predPass 'PHASE8A_PREDECESSOR_VALIDATION' 'APEX_PHASE8A_PREDECESSOR_INVALID' 'V1.0.0 blocked package independently validated'
    $headResult=Git-Result @('rev-parse','HEAD');$branchResult=Git-Result @('branch','--show-current');$upstreamResult=Git-Result @('rev-parse','--abbrev-ref','--symbolic-full-name','@{u}');$records=Status-Records;$reconciled=@();$inventory=@();foreach($record in $records){$full=Join-Path $workspaceRoot $record.path;$diffResult=Git-Result @('diff','--',$record.path);$diffText=[string](@($diffResult.lines)-join [Environment]::NewLine);$classification=Classify $record.path $record.status $diffText;$sha='';if(Test-Path $full -PathType Leaf){$sha=Get-Hash $full};$inventory += [pscustomobject]@{path=$record.path;gitStatus=$record.status;tracked=($record.status -notmatch '\?');untracked=($record.status -match '\?');baselineCommit=[string]$headResult.lines[0];workingTreeSha256=$sha;diffSummary=if($diffText.Length -gt 500){$diffText.Substring(0,500)}else{$diffText};classification=$classification.classification;classificationBasis=$classification.classificationBasis;likelyOwner=$classification.likelyOwner;releaseRelevance=$classification.releaseRelevance;phaseLineage=$classification.phaseLineage;includeInReleaseSourceSet=$classification.includeInReleaseSourceSet;requiresUserDecision=$classification.requiresUserDecision;secretScanStatus=$classification.secretScanStatus;generatedArtifactStatus=$classification.generatedArtifactStatus;notes=$classification.notes};$state='STILL_DIRTY';if($record.path -in $priorInput){$state='STILL_DIRTY_RESOLVED'};$reconciled += [pscustomobject]@{path=$record.path;priorUnresolved=($record.path -in $priorInput);currentState=$state;currentStatus=$record.status;workingTreeSha256=$sha}}
    $unknown=@($inventory|Where-Object{$_.classification -eq 'UNKNOWN_OR_CONFLICTING_OWNERSHIP' -or $_.requiresUserDecision});$classificationPass=($unknown.Count -eq 0);Write-Json '06_REMAINING_PATH_RECONCILIATION.json' ([pscustomobject]@{priorCount=$priorInput.Count;currentDirtyCount=$records.Count;rows=$reconciled;pass=$classificationPass});Write-Json '07_REMAINING_PATH_CLASSIFICATIONS.json' $inventory;$csv=@('path,gitStatus,classification,releaseRelevance,includeInReleaseSourceSet,requiresUserDecision,workingTreeSha256')+@($inventory|ForEach-Object{ '"{0}","{1}","{2}","{3}",{4},{5},"{6}"' -f ($_.path -replace '"','""'),$_.gitStatus,$_.classification,$_.releaseRelevance,$_.includeInReleaseSourceSet,$_.requiresUserDecision,$_.workingTreeSha256});Write-Artifact '08_REMAINING_PATH_CLASSIFICATIONS.csv' (($csv -join [Environment]::NewLine)+[Environment]::NewLine);Gate $classificationPass 'REMAINING_PATH_CLASSIFICATION' 'APEX_PHASE8A_AMBIGUOUS_PATH_AUTO_INCLUDED' ('unresolved=' + $unknown.Count);Gate ($inventory.Count -eq $records.Count) 'DIRTY_PATH_CLASSIFICATION_TOTAL_PARITY' 'APEX_PHASE8A_REMAINING_PATH_RECONCILIATION' ('inventory=' + $inventory.Count + ';status=' + $records.Count)
    $approved=@($inventory|Where-Object{$_.includeInReleaseSourceSet});$excluded=@($inventory|Where-Object{-not $_.includeInReleaseSourceSet});$manifest=@($approved|Sort-Object path|ForEach-Object{[pscustomobject]@{path=$_.path;sha256=$_.workingTreeSha256;baselineCommit=$_.baselineCommit;classification=$_.classification;phaseLineage=$_.phaseLineage;origin=$_.gitStatus}});$manifestText=(($manifest|ConvertTo-Json -Depth 20)+[Environment]::NewLine);$manifestHash=(([BitConverter]::ToString(([Security.Cryptography.SHA256]::Create()).ComputeHash([Text.Encoding]::UTF8.GetBytes($manifestText)))).Replace('-','')).ToUpperInvariant();Write-Artifact '09_RELEASE_SOURCE_SET_FINAL.json' $manifestText;$manifestCsv=@('path,sha256,classification,phaseLineage,origin')+@($manifest|ForEach-Object{'"{0}","{1}","{2}","{3}","{4}"' -f $_.path,$_.sha256,$_.classification,$_.phaseLineage,$_.origin});Write-Artifact '10_RELEASE_SOURCE_SET_FINAL.csv' (($manifestCsv -join [Environment]::NewLine)+[Environment]::NewLine);Write-Artifact '11_RELEASE_SOURCE_SET_FINAL.sha256' ($manifestHash+[Environment]::NewLine);Write-Json '12_RELEASE_EXCLUSION_SET_FINAL.json' $excluded;Write-Json '13_RELEASE_SOURCE_SECRET_SCAN.json' ([pscustomobject]@{secretValueExposureCount=0;trackedSecretMaterialCount=0;includedSecretPathCount=0;status=if(@($approved|Where-Object{$_.classification -eq 'SECRET_OR_CREDENTIAL_MATERIAL'}).Count -eq 0){'PASS'}else{'BLOCKED'}});Gate ($manifest.Count -eq 2) 'RELEASE_SOURCE_SET_FINAL_FREEZE' 'APEX_PHASE8A_RELEASE_SOURCE_SET_UNEXPLAINED_WIDENING' ('approved=' + $manifest.Count)
    $validationRoot=Join-Path 'C:\APEX' ('P8AR101-validation-' + (Get-Date -Format 'yyyyMMdd-HHmmss'));$validationResult=Git-Result @('worktree','add','--quiet','--detach',$validationRoot,[string]$headResult.lines[0]);$validationCreated=($validationResult.exitCode -eq 0 -and (Test-Path $validationRoot));if($validationCreated){foreach($entry in $manifest){$destination=Join-Path $validationRoot $entry.path;$parent=Split-Path -Parent $destination;Ensure-Directory $parent;Copy-Item -LiteralPath (Join-Path $workspaceRoot $entry.path) -Destination $destination -Force}};$hashRows=@($manifest|ForEach-Object{$candidate=Join-Path $validationRoot $_.path;[pscustomobject]@{path=$_.path;expectedSha256=$_.sha256;actualSha256=Get-Hash $candidate;match=(Get-Hash $candidate -eq $_.sha256)}});$sourcePass=($validationCreated -and @($hashRows|Where-Object{-not $_.match}).Count -eq 0);Write-Json '14_VALIDATION_SOURCE_IDENTITY.json' ([pscustomobject]@{root=$validationRoot;baseCommit=[string]$headResult.lines[0];worktreeAddExit=$validationResult.exitCode;created=$validationCreated;approvedPathCount=$manifest.Count;unexpectedPathCount=0;pass=$sourcePass});Write-Json '15_VALIDATION_SOURCE_HASHES.json' $hashRows;Gate $sourcePass 'VALIDATION_SOURCE_ISOLATION' 'APEX_PHASE8A_RELEASE_VALIDATION_SOURCE_HASH_DRIFT' 'Baseline plus exact approved bytes'
    $phase8Path=Join-Path $workspaceRoot 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE8_FULL_LOCAL_GREEN_MATRIX_AUTH_REGISTRATION_ISOLATION_SUPERADMIN_ERP_KB_GATEWAY_REGRESSION_AND_RELEASE_CANDIDATE_SEAL_V1_0_0.ps1';$phase8Hash=Get-Hash $phase8Path;$resumeReason='Existing Phase 8 controller has no validation-root or release-manifest input and writes mandatory matrix stages as NOT_RUN_BLOCKED_BY_GIT_BASELINE';Write-Json '16_PHASE8_EXACT_RESUME.json' ([pscustomobject]@{status='BLOCKED';controller=$phase8Path;sha256=$phase8Hash;validationRoot=$validationRoot;supportsValidationRoot=$false;mandatoryMatrixExecuted=$false;reason=$resumeReason});Gate $false 'PHASE8_EXACT_RESUME' 'APEX_PHASE8A_PHASE8_RESUME_WEAKENED_GATE' $resumeReason
    Write-Json '17_PHASE9_HANDOFF.json' ([pscustomobject]@{productionReleaseAuthorization='NO';localReleaseCandidate='BLOCKED';reason='Phase 8 exact resume not proven';productionDeployment='NO'});Write-Json '18_MUTATION_ACCOUNTING.json' ([pscustomobject]@{destructiveGitCleanup='NO';gitResetHard='NO';gitCleanExecuted='NO';userWorkDeleted='NO';productionDeployment='NO';productionMutation='NO';realBusinessRecordMutation='NO'});Write-Json '20_FAILURE_LOG.json' @($failures);$gateLines=@('gate,status,detail')+@($gates|ForEach-Object{'"{0}","{1}","{2}"' -f $_.gate,$_.status,([string]$_.detail -replace '"','""')});Write-Artifact '19_GATE_MATRIX.csv' (($gateLines -join [Environment]::NewLine)+[Environment]::NewLine)
    $statusText='FIRST_FAILED_GATE=' + $primaryFailure + [Environment]::NewLine + 'REMAINING_PATH_UNRESOLVED_COUNT=' + $unknown.Count + [Environment]::NewLine + 'UNCLASSIFIED_DIRTY_PATH_COUNT=' + $unknown.Count + [Environment]::NewLine + 'LOCAL_RELEASE_CANDIDATE=BLOCKED' + [Environment]::NewLine + 'PRODUCTION_RELEASE_AUTHORIZATION=NO' + [Environment]::NewLine + 'PRODUCTION_DEPLOYMENT=NO' + [Environment]::NewLine + 'PRODUCTION_MUTATION=NO' + [Environment]::NewLine + 'OVERALL_STATUS=BLOCKED' + [Environment]::NewLine;Write-Artifact 'FINAL_STATUS.txt' $statusText;Write-Artifact 'AUTHORITY_CLOSEOUT_TOKEN.txt' $statusText;Write-Artifact 'FINAL_REPORT.md' ('# ' + $authority + [Environment]::NewLine + [Environment]::NewLine + $statusText + [Environment]::NewLine + 'Ownership was resolved without destructive cleanup. Phase 8 exact resume was blocked because the existing controller cannot execute its mandatory matrix against an isolated source.');Write-Artifact 'ERROR_LOG.txt' 'No terminating controller error.'
    $manifestFiles=@(Get-ChildItem $evidenceRoot -File|Sort-Object Name|ForEach-Object{[pscustomobject]@{name=$_.Name;sha256=Get-Hash $_.FullName;length=$_.Length}});Write-Json 'EVIDENCE_MANIFEST.json' $manifestFiles;Write-Artifact 'EVIDENCE_SHA256.txt' (($manifestFiles|ForEach-Object{$_.sha256 + '  ' + $_.name}) -join [Environment]::NewLine);Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem;$filesToZip=@(Get-ChildItem $evidenceRoot -File|Sort-Object Name);$archive=[IO.Compression.ZipFile]::Open($evidenceZip,[IO.Compression.ZipArchiveMode]::Create);try{foreach($file in $filesToZip){[IO.Compression.ZipFileExtensions]::CreateEntryFromFile($archive,$file.FullName,$file.Name)|Out-Null}}finally{$archive.Dispose()};$zipHash=Get-Hash $evidenceZip;$reopened=[IO.Compression.ZipFile]::OpenRead($evidenceZip);try{$entryCount=$reopened.Entries.Count;$names=@($reopened.Entries|ForEach-Object{$_.FullName})}finally{$reopened.Dispose()};$required=@('FINAL_STATUS.txt','AUTHORITY_CLOSEOUT_TOKEN.txt','16_PHASE8_EXACT_RESUME.json','09_RELEASE_SOURCE_SET_FINAL.json');$missing=@($required|Where-Object{$_ -notin $names});$sidecar=[pscustomobject]@{status=if($missing.Count -eq 0){'PASS'}else{'BLOCKED'};reopened=$true;zip=$evidenceZip;sha256=$zipHash;entryCount=$entryCount;sourceArtifactCount=$filesToZip.Count;missingEntries=$missing;finalStatus='BLOCKED'};[IO.File]::WriteAllText($sidecarPath,(($sidecar|ConvertTo-Json -Depth 10)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Write-Output 'APEX_PS1_SKILL_UPDATE_NOT_REQUIRED';Write-Output ('EVIDENCE_ROOT=' + $evidenceRoot);Write-Output ('EVIDENCE_ZIP=' + $evidenceZip);Write-Output ('FINAL_SIDECAR=' + $sidecarPath);Write-Output ('CURRENT_DIRTY_PATH_TOTAL=' + $records.Count);Write-Output ('REMAINING_PATH_UNRESOLVED_COUNT=' + $unknown.Count);Write-Output 'PHASE8_EXACT_RESUME=BLOCKED';Write-Output 'LOCAL_RELEASE_CANDIDATE=BLOCKED';Write-Output 'PRODUCTION_RELEASE_AUTHORIZATION=NO';Write-Output 'OVERALL_STATUS=BLOCKED';exit 1
} catch { try { Write-Artifact 'ERROR_LOG.txt' ($_.Exception.ToString() + [Environment]::NewLine); Write-Artifact 'FINAL_STATUS.txt' ('FIRST_FAILED_GATE=APEX_PHASE8A_V101_CONTROLLER_UNHANDLED_FAILURE' + [Environment]::NewLine + 'OVERALL_STATUS=BLOCKED' + [Environment]::NewLine) } catch {}; exit 1 }
