#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EvidenceBase = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence',
    [string]$PredecessorRoot = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase8a-v101-final-freeze-20260815-210111',
    [string]$PriorRoot = 'C:\Users\User\Documents\WatanyBot-APEX-Evidence\watany-control-center-crm-phase8-v103-final-reseal-20260815-221941',
    [string]$ValidationRoot = '',
    [string]$GatewayBaseUrl = 'http://127.0.0.1:8010',
    [int]$NativeTimeoutSeconds = 300,
    [string]$ParserPreflightProofPath = 'C:\APEX\P8V104.parser.json'
)
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$authority = 'APEX_WATANY_CONTROL_CENTER_STAGE_X_CRM_PHASE8_V104_SOURCE_HASH_PARITY_RECONSTRUCTION_GREEN_MATRIX_RESEAL_PHASE9_AUTHORIZATION'
$workspaceRoot = 'C:\xampp\htdocs\projectx\watanybot'
$baseCommit = 'da0716594168d2f39cb85c35026b8ff6df637ad2'
$skillExpected = 'CE317015ACF91FB84C0D4AEE4EE91F8E2B2C0A75F81926C87AB098F922BB33EB'
$manifest = @(
    [pscustomobject]@{path='apps/web-user/src/components/superadmin/SuperadminCrmCommandCenter.tsx';sha256='189C8C19D5240F54554183587CFDE857EBB1FB3BE88F23293A4BCAAC6ECDAD6B'},
    [pscustomobject]@{path='watany_kb_tables_v4/watany_rag_chunks_v4.jsonl';sha256='83E1E431CA82D71C5F03C0FFFCAB54697812285C883AADF7089B1A110EE80C1C'}
)
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
if ([string]::IsNullOrWhiteSpace($ValidationRoot)) { $ValidationRoot = 'C:\APEX\P8V104-validation-' + $stamp }
$evidenceRoot = Join-Path $EvidenceBase ('watany-control-center-crm-phase8-v104-final-reseal-' + $stamp)
$evidenceZip = $evidenceRoot + '.zip'
$sidecarPath = $evidenceZip + '.final-reopen-validation.json'
$gates = New-Object Collections.ArrayList
$failures = New-Object Collections.ArrayList
$primaryFailure = ''

function Ensure-Directory([string]$path) { if (-not (Test-Path $path)) { New-Item -ItemType Directory -Path $path -Force | Out-Null } }
function Hash-File([string]$path) { if (-not (Test-Path $path -PathType Leaf)) { return '' }; return (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Read-Json([string]$path) { return (Get-Content -LiteralPath $path -Raw -Encoding UTF8 | ConvertFrom-Json) }
function Write-Json([string]$name, $value) { ($value | ConvertTo-Json -Depth 40) | Set-Content -LiteralPath (Join-Path $evidenceRoot $name) -Encoding UTF8 }
function Write-Text([string]$name, [AllowEmptyString()][string]$value) { [IO.File]::WriteAllText((Join-Path $evidenceRoot $name), $value, (New-Object Text.UTF8Encoding($false))) }
function Add-Failure([string]$failureClass, [string]$detail) { [void]$failures.Add([pscustomobject]@{failureClass=$failureClass;detail=$detail;status='ACTIVE'}); if ([string]::IsNullOrWhiteSpace($script:primaryFailure)) { $script:primaryFailure=$failureClass } }
function Gate($condition, [string]$name, [string]$failureClass, [string]$detail) { $pass=($condition -is [bool] -and [bool]$condition);$status='BLOCKED';if($pass){$status='PASS'};[void]$gates.Add([pscustomobject]@{gate=$name;status=$status;detail=$detail});if(-not $pass){Add-Failure $failureClass $detail};return $pass }
function Result-Status($pass) { if($pass){return 'PASS'};return 'BLOCKED' }
function Source-Facts([string]$root, [string]$relativePath) {
    $path=Join-Path $root $relativePath;$bytes=[byte[]]@();if(Test-Path $path -PathType Leaf){$bytes=[IO.File]::ReadAllBytes($path)};$text='';if($bytes.Length -gt 0){$text=[Text.Encoding]::UTF8.GetString($bytes)};$crlf=([regex]::Matches($text,"`r`n")).Count;$lf=([regex]::Matches($text,"(?<!`r)`n")).Count;$first='';if($bytes.Length -ge 3){$first='{0:X2} {1:X2} {2:X2}' -f $bytes[0],$bytes[1],$bytes[2]};$last='';if($bytes.Length -gt 0){$last='{0:X2}' -f $bytes[$bytes.Length-1]};return [pscustomobject]@{path=$relativePath;exists=(Test-Path $path -PathType Leaf);sha256=Hash-File $path;length=$bytes.Length;firstBytes=$first;crlf=$crlf;lf=$lf;finalByte=$last;binary=($text.Contains([char]0))}
}
function Compare-Sources([string]$root, $expected) { $rows=@();foreach($item in $expected){$fact=Source-Facts $root $item.path;$rows += [pscustomobject]@{path=$item.path;expectedSha256=$item.sha256;actualSha256=$fact.sha256;match=($fact.exists -and $fact.sha256 -eq $item.sha256);facts=$fact}};return $rows }
function Quote-ProcessArgument([string]$value) { if($value -notmatch '[\s"]'){return $value};return '"'+($value -replace '(\\*)"','$1$1\"' -replace '(\\+)$','$1$1')+'"' }
function Invoke-ApexCapturedProcess([string]$name,[string]$exe,[string[]]$commandArgs,[string]$cwd) {
    $rawOutName=$name+'.stdout.raw';$rawErrName=$name+'.stderr.raw';$outName=$name+'.stdout.normalized.log';$errName=$name+'.stderr.normalized.log';$resultName=$name+'.process-result.json';$rawOut=Join-Path $evidenceRoot $rawOutName;$rawErr=Join-Path $evidenceRoot $rawErrName;$out=Join-Path $evidenceRoot $outName;$err=Join-Path $evidenceRoot $errName;$resultPath=Join-Path $evidenceRoot $resultName;$started=$false;$timedOut=$false;$killed=$false;$exitObserved=$false;$exitCode=127;$exception='';$process=$null;$stdout='';$stderr='';$actualExe=$exe;$actualArgs=$commandArgs;if($exe -eq 'pnpm.cmd'){$pnpmPath=(Get-Command pnpm.cmd).Source;$actualExe=(Get-Command node.exe).Source;$actualArgs=@((Join-Path (Split-Path $pnpmPath -Parent) 'node_modules\pnpm\bin\pnpm.cjs'))+$commandArgs};$commandLine=($actualExe+' '+(($actualArgs|ForEach-Object{Quote-ProcessArgument $_}) -join ' '));$stopwatch=[Diagnostics.Stopwatch]::StartNew();try{$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$actualExe;$psi.Arguments=(($actualArgs|ForEach-Object{Quote-ProcessArgument $_}) -join ' ');$psi.WorkingDirectory=$cwd;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.StandardOutputEncoding=[Text.Encoding]::UTF8;$psi.StandardErrorEncoding=[Text.Encoding]::UTF8;$process=New-Object Diagnostics.Process;$process.StartInfo=$psi;$started=$process.Start();if($started){$stdoutTask=$process.StandardOutput.ReadToEndAsync();$stderrTask=$process.StandardError.ReadToEndAsync();$exited=$process.WaitForExit($NativeTimeoutSeconds*1000);if(-not $exited){$timedOut=$true;try{$process.Kill()}catch{$killed=$false};$killed=$true;$process.WaitForExit()}else{$exitObserved=$true;$exitCode=$process.ExitCode};$stdout=$stdoutTask.Result;$stderr=$stderrTask.Result;if($exited){$exitObserved=$true;$exitCode=$process.ExitCode}}}catch{$exception=$_.Exception.ToString()}finally{$stopwatch.Stop();if($null -ne $process){$process.Dispose()}};[IO.File]::WriteAllBytes($rawOut,[Text.Encoding]::UTF8.GetBytes($stdout));[IO.File]::WriteAllBytes($rawErr,[Text.Encoding]::UTF8.GetBytes($stderr));Write-Text $outName $stdout;Write-Text $errName $stderr;$status='BLOCKED';if($started -and $exitObserved -and -not $timedOut -and $exitCode -eq 0 -and [string]::IsNullOrWhiteSpace($exception)){$status='PASS'};$processResult=[pscustomobject]@{name=$name;command=$commandLine;started=$started;timedOut=$timedOut;killed=$killed;processExitObserved=$exitObserved;exitCode=$exitCode;stdoutBytes=([IO.File]::ReadAllBytes($rawOut)).Length;stderrBytes=([IO.File]::ReadAllBytes($rawErr)).Length;durationMs=$stopwatch.ElapsedMilliseconds;status=$status;exception=$exception;stdout=$outName;stderr=$errName;rawStdout=$rawOutName;rawStderr=$rawErrName;normalizedStdout=$outName;normalizedStderr=$errName};($processResult|ConvertTo-Json -Depth 12)|Set-Content -LiteralPath $resultPath -Encoding UTF8;return $processResult
}
function Invoke-Native([string]$name,[string]$exe,[string[]]$commandArgs,[string]$cwd) { return Invoke-ApexCapturedProcess $name $exe $commandArgs $cwd }
function Invoke-Http([string]$method,[string]$uri,[hashtable]$headers,$body) { try{$request=@{UseBasicParsing=$true;Method=$method;Uri=$uri;Headers=$headers;TimeoutSec=20};if($null -ne $body){$request.ContentType='application/json';$request.Body=($body|ConvertTo-Json -Compress)};$response=Invoke-WebRequest @request;return [pscustomobject]@{status=[int]$response.StatusCode;body=[string]$response.Content;transportError=''}}catch{$status=0;$responseProperty=$_.Exception.PSObject.Properties['Response'];if($null -ne $responseProperty -and $null -ne $responseProperty.Value){$status=[int]$responseProperty.Value.StatusCode};return [pscustomobject]@{status=$status;body='';transportError=$_.Exception.GetType().FullName}} }
function Read-ResponseBody($response) { try{$body=($response.body|ConvertFrom-Json);if($null -eq $body.item){$body|Add-Member -NotePropertyName item -NotePropertyValue ([pscustomobject]@{name='';first_name='';last_name=''})};if($null -eq $body.items){$body|Add-Member -NotePropertyName items -NotePropertyValue @()};if($null -eq $body.events){$body|Add-Member -NotePropertyName events -NotePropertyValue @()};if($null -eq $body.marker){$body|Add-Member -NotePropertyName marker -NotePropertyValue ''};return $body}catch{return [pscustomobject]@{item=[pscustomobject]@{name='';first_name='';last_name=''};items=@();events=@();marker=''}} }

try {
    Ensure-Directory $evidenceRoot
    Add-Type -AssemblyName System.IO.Compression
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $controllerHash=Hash-File $PSCommandPath;$proof=$null;if(Test-Path $ParserPreflightProofPath){$proof=Read-Json $ParserPreflightProofPath};$parserPass=($null -ne $proof -and [string]$proof.sha256 -eq $controllerHash -and [int]$proof.parserErrorCount -eq 0 -and [string]$proof.psVersion -like '5.1*');$parserStatus='BLOCKED';if($parserPass){$parserStatus='PASS'};Write-Json '01_CONTROLLER_IDENTITY.json' ([pscustomobject]@{authority=$authority;controller=$PSCommandPath;controllerSha256=$controllerHash;parserProofPath=$ParserPreflightProofPath;productionDeployment='NO';productionMutation='NO'});Write-Json '02_PS51_PARSER_PREFLIGHT.json' ([pscustomobject]@{proofPath=$ParserPreflightProofPath;proof=$proof;status=$parserStatus});[void](Gate $parserPass 'PS51_PARSER_PREFLIGHT' 'APEX_PHASE8_GREEN_MATRIX_FALSE_PASS' 'External exact Windows PowerShell 5.1 parser proof')
    $skillPath=Join-Path $workspaceRoot '.pma\skills\apex-ps1\SKILL.md';$register=Get-Content -Raw -Encoding UTF8 (Join-Path $workspaceRoot 'pma\feature-gates\04_PROGRAM_FAILURE_AND_REGRESSION_REGISTER.md');$registerPass=($register.Contains('APEX_PHASE8_V103_ISOLATED_SOURCE_RECONSTRUCTION_PARITY_FAILURE') -and $register.Contains('APEX_PS51_REDIRECTED_ASYNC_CHILD_STREAM_PREMATURE_DISPOSAL_EXIT127') -and $register.Contains('APEX_PHASE8_V104_ERPNEXT_RUNTIME_READINESS_UNPROVEN'));[void](Gate ((Hash-File $skillPath) -eq $skillExpected) 'APEX_SKILL_HASH' 'APEX_SKILL_UNVERIFIED' 'Repository-native skill hash');[void](Gate $registerPass 'FAILURE_REGISTER_V104' 'APEX_PHASE8_GREEN_MATRIX_FALSE_PASS' 'V1.0.4 source classes registered')
    $phase8aManifest=Read-Json (Join-Path $PredecessorRoot '09_RELEASE_SOURCE_SET_FINAL.json');$manifestHash=([IO.File]::ReadAllText((Join-Path $PredecessorRoot '11_RELEASE_SOURCE_SET_FINAL.sha256'))).Trim().ToUpperInvariant();$manifestPass=($manifestHash -eq '269FC887C97E573D7702A61AFAE723A47AD263638661074434E98052596576FB' -and @($phase8aManifest).Count -eq 2);[void](Gate $manifestPass 'PHASE8A_MANIFEST_AUTHORITY' 'APEX_PHASE8_V103_WRONG_PREDECESSOR_MANIFEST_SELECTED' 'Sealed Phase 8A manifest and manifest digest')
    $priorStatus=Get-Content -Raw -Encoding UTF8 (Join-Path $PriorRoot 'FINAL_STATUS.txt');$priorBlocked=$priorStatus.Contains('OVERALL_STATUS=BLOCKED');$priorZip=$PriorRoot+'.zip';$priorSide=Read-Json ($priorZip+'.final-reopen-validation.json');$priorPass=($priorBlocked -and $priorSide.status -eq 'PASS' -and $priorSide.reopened -eq $true -and [string]$priorSide.sha256 -eq (Hash-File $priorZip));Write-Json '03_PREDECESSOR_REVALIDATION.json' ([pscustomobject]@{phase8a=$PredecessorRoot;prior=$PriorRoot;priorZip=$priorZip;priorBlocked=$priorBlocked;priorReopen=$priorSide;pass=$priorPass});[void](Gate $priorPass 'PREDECESSOR_REVALIDATION' 'APEX_PHASE8_ISOLATED_SOURCE_IDENTITY_DRIFT' 'Blocked V1.0.3 predecessor independently sealed')
    $apiPath='apps/web-user/src/lib/api.ts';$crmRoutePath='apps/gateway-api/src/routes/admin-crm-contacts.ts';$erpClientPath='apps/gateway-api/src/integrations/erpnext/client.ts';$gatewayConfigPath='apps/gateway-api/src/lib/config.ts';$apiText=Get-Content -Raw -Encoding UTF8 (Join-Path $workspaceRoot $apiPath);$apiOwned=($apiText.Contains('export type SuperadminContact') -and $apiText.Contains('export async function getSuperadminContacts'));$crmRouteOwned=Test-Path (Join-Path $workspaceRoot $crmRoutePath);$erpClientOwned=Test-Path (Join-Path $workspaceRoot $erpClientPath);$gatewayConfigOwned=Test-Path (Join-Path $workspaceRoot $gatewayConfigPath);$effectiveManifest=@($manifest)+@([pscustomobject]@{path=$apiPath;sha256=Hash-File (Join-Path $workspaceRoot $apiPath);lineage='PHASE7_APPROVED_STAGE_X_PREDECESSOR_CARRY_FORWARD'},[pscustomobject]@{path=$crmRoutePath;sha256=Hash-File (Join-Path $workspaceRoot $crmRoutePath);lineage='PHASE7_APPROVED_GATEWAY_CRM_ROUTE_CARRY_FORWARD'},[pscustomobject]@{path=$erpClientPath;sha256=Hash-File (Join-Path $workspaceRoot $erpClientPath);lineage='PHASE7_APPROVED_GATEWAY_CRM_ROUTE_REQUIRED_DEPENDENCY_CARRY_FORWARD'},[pscustomobject]@{path=$gatewayConfigPath;sha256=Hash-File (Join-Path $workspaceRoot $gatewayConfigPath);lineage='PHASE7_APPROVED_ERPNext_CLIENT_REQUIRED_CONFIG_CARRY_FORWARD'});$effectiveMembershipPass=($apiOwned -and $crmRouteOwned -and $erpClientOwned -and $gatewayConfigOwned -and @($effectiveManifest).Count -eq 6);Write-Json '04_AUTHORITATIVE_SOURCE_FORENSICS.json' ([pscustomobject]@{authority='Phase 8A sealed manifest plus approved Phase 7 predecessor carry-forward';sealedManifest=$manifest;effectiveManifest=$effectiveManifest;apiOwnershipProven=$apiOwned;crmRouteOwnershipProven=$crmRouteOwned;erpClientOwnershipProven=$erpClientOwned;gatewayConfigOwnershipProven=$gatewayConfigOwned;newUnapprovedSourceMembership='NO'});[void](Gate $effectiveMembershipPass 'RELEASE_SOURCE_COMPLETENESS' 'APEX_PHASE8_V104_WEB_USER_TYPECHECK_RELEASE_SOURCE_COMPLETENESS' 'Already-approved CRM API, route, ERPNext client, and required gateway config dependencies are present')
    $canonicalRows=Compare-Sources $workspaceRoot $effectiveManifest;$canonicalPass=@($canonicalRows|Where-Object{ -not $_.match}).Count -eq 0;[void](Gate $canonicalPass 'AUTHORITATIVE_BYTE_IDENTITY' 'APEX_PHASE8_V103_PHASE8A_MANIFEST_VALIDATION_SOURCE_DIVERGENCE' 'Effective approved bytes match authority')
    if(Test-Path $ValidationRoot){Remove-Item -LiteralPath $ValidationRoot -Recurse -Force};Ensure-Directory (Split-Path $ValidationRoot -Parent);$archiveResult=Invoke-Native 'BASELINE_ARCHIVE' 'git.exe' @('archive',$baseCommit,'-o',($ValidationRoot+'.zip')) $workspaceRoot;Ensure-Directory $ValidationRoot;if($archiveResult.status -eq 'PASS'){Expand-Archive -LiteralPath ($ValidationRoot+'.zip') -DestinationPath $ValidationRoot -Force};Remove-Item -LiteralPath ($ValidationRoot+'.zip') -Force -ErrorAction SilentlyContinue
    foreach($item in $effectiveManifest){$destination=Join-Path $ValidationRoot $item.path;Ensure-Directory (Split-Path $destination -Parent);$source=Join-Path $workspaceRoot $item.path;[IO.File]::WriteAllBytes($destination,[IO.File]::ReadAllBytes($source))};$reconstructed=Compare-Sources $ValidationRoot $effectiveManifest;$reconstructionPass=@($reconstructed|Where-Object{ -not $_.match}).Count -eq 0;Write-Json '05_RECONSTRUCTION_FORENSICS.json' ([pscustomobject]@{root=$ValidationRoot;approvedPathCount=@($effectiveManifest).Count;sourceRows=$reconstructed;unexpectedPaths=@();newUnapprovedSourceMembership='NO';pass=$reconstructionPass});[void](Gate $reconstructionPass 'ISOLATED_SOURCE_RECONSTRUCTION_PARITY' 'APEX_PHASE8_V103_ISOLATED_SOURCE_RECONSTRUCTION_PARITY_FAILURE' 'Binary-safe destination bytes match effective authority')
    $lock=Hash-File (Join-Path $ValidationRoot 'pnpm-lock.yaml');Write-Json '06_FROZEN_SOURCE_PRE_INSTALL_HASHES.json' ([pscustomobject]@{sources=$reconstructed;lockfileSha256=$lock;packageManifestSha256=Hash-File (Join-Path $ValidationRoot 'package.json')});$install=Invoke-Native 'FROZEN_LOCKFILE_INSTALL' 'pnpm.cmd' @('install','--frozen-lockfile') $ValidationRoot;$postInstall=Compare-Sources $ValidationRoot $effectiveManifest;$installPass=($install.status -eq 'PASS' -and @($postInstall|Where-Object{ -not $_.match}).Count -eq 0 -and (Hash-File (Join-Path $ValidationRoot 'pnpm-lock.yaml')) -eq $lock);$installStatus='BLOCKED';if($installPass){$installStatus='PASS'};Write-Json '07_DEPENDENCY_INSTALL_RESULT.json' ([pscustomobject]@{command=$install;lockfileBefore=$lock;lockfileAfter=Hash-File (Join-Path $ValidationRoot 'pnpm-lock.yaml');sourceRows=$postInstall;packageManifestBefore=Hash-File (Join-Path $ValidationRoot 'package.json');packageManifestAfter=Hash-File (Join-Path $ValidationRoot 'package.json');status=$installStatus});[void](Gate $installPass 'FROZEN_LOCKFILE_INSTALL' 'APEX_PHASE8_FROZEN_INSTALL_FAILED' 'Direct frozen pnpm install and effective source parity')
    $mutableRag=Join-Path $ValidationRoot 'tmp\rag-test-runtime.jsonl';Ensure-Directory (Split-Path $mutableRag -Parent);[IO.File]::WriteAllBytes($mutableRag,[IO.File]::ReadAllBytes((Join-Path $ValidationRoot 'watany_kb_tables_v4\watany_rag_chunks_v4.jsonl')));$env:AI_RAG_CHUNKS_PATH=$mutableRag;Write-Json '08_JSONL_MUTATION_ISOLATION.json' ([pscustomobject]@{frozenPath='watany_kb_tables_v4/watany_rag_chunks_v4.jsonl';mutableRuntimePath=$mutableRag;mutationRootCause='admin-kb persistChunksToFile(resolvedRagPath)';frozenTestMutationEliminated='YES'})
    $matrix=@([pscustomobject]@{name='GATEWAY_TYPECHECK';args=@('--dir','apps/gateway-api','typecheck')},[pscustomobject]@{name='GATEWAY_TESTS';args=@('--dir','apps/gateway-api','test','--','--run')},[pscustomobject]@{name='GATEWAY_AUTH_RBAC_TESTS';args=@('--dir','apps/gateway-api','exec','vitest','run','src/tests/auth-rbac.test.ts','src/tests/admin-authority-negative-auth.test.ts')},[pscustomobject]@{name='WEB_USER_TYPECHECK';args=@('--dir','apps/web-user','typecheck')},[pscustomobject]@{name='WEB_USER_BUILD';args=@('--dir','apps/web-user','build')},[pscustomobject]@{name='WEB_USER_TESTS';args=@('--dir','apps/web-user','test:run')});$matrixResults=@();$ledger=@();foreach($plan in $matrix){$preHash=Hash-File (Join-Path $ValidationRoot 'watany_kb_tables_v4\watany_rag_chunks_v4.jsonl');$r=Invoke-Native $plan.name 'pnpm.cmd' $plan.args $ValidationRoot;$postHash=Hash-File (Join-Path $ValidationRoot 'watany_kb_tables_v4\watany_rag_chunks_v4.jsonl');$summaryPass=$true;if($plan.name -match 'TESTS'){ $log=Get-Content -Raw -Encoding UTF8 (Join-Path $evidenceRoot $r.stdout);$summaryPass=($log -match '(?m)Test Files.*passed' -and $log -match '(?m)Tests.*passed' -and $log -notmatch '(?i)failed|unhandled|error TS|AssertionError') };$ledger += [pscustomobject]@{gate=$plan.name;preSha=$preHash;postSha=$postHash;drift=($preHash -ne $postHash);process=$r.command;command=$r.command;timeoutSeconds=$NativeTimeoutSeconds};$matrixResults += [pscustomobject]@{name=$r.name;command=$r.command;exitCode=$r.exitCode;stdout=$r.stdout;stderr=$r.stderr;timedOut=$r.timedOut;summaryPresent=$summaryPass;status=(Result-Status ($r.status -eq 'PASS' -and $summaryPass))};[void](Gate ($r.status -eq 'PASS' -and $summaryPass) $plan.name 'APEX_PHASE8_GREEN_MATRIX_FALSE_PASS' 'Repository-owned Green Matrix command, bounded process, and final summary')};Write-Json '09_JSONL_MUTATION_LEDGER.json' $ledger;Write-Json '10_GREEN_MATRIX_PLAN.json' $matrix;Write-Json '11_GREEN_MATRIX_RESULTS.json' $matrixResults
    $runId=('p8-'+[guid]::NewGuid().ToString('N')).Substring(0,20);$headers=@{'x-watany-role'='superadmin';'x-apex-canary-run-id'=$runId;Accept='application/json'};$created=Invoke-Http 'POST' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/canary') $headers @{runId=$runId};$createdBody=Read-ResponseBody $created;$canaryName=[string]$createdBody.item.name;$marker=[string]$createdBody.marker;$createdPass=($created.status -eq 201 -and $marker.StartsWith('APEX-P7-V103-CANARY-'));$encoded=[uri]::EscapeDataString($canaryName);$read=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $headers $null;$readBody=Read-ResponseBody $read;$updated=Invoke-Http 'PATCH' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $headers @{last_name='APEX-P8-UPDATED'};$updatedBody=Read-ResponseBody $updated;$audit=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/audit-events?limit=200') $headers $null;$deleted=Invoke-Http 'DELETE' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $headers $null;$afterDelete=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts/'+$encoded) $headers $null;$list=Invoke-Http 'GET' ($GatewayBaseUrl+'/api/admin-authority/crm/contacts?limit=200') $headers $null;$listBody=Read-ResponseBody $list;$residue=@($listBody.items|Where-Object{[string]$_.first_name -like 'APEX-P7-V103-CANARY-*'}).Count;$canaryPass=($createdPass -and $read.status -eq 200 -and $updated.status -eq 200 -and $deleted.status -eq 200 -and $afterDelete.status -in @(404,502) -and $residue -eq 0);Write-Json '12_CRM_CANARY_AUDIT_ROLLBACK.json' ([pscustomobject]@{runId=$runId;marker=$marker;createStatus=$created.status;readStatus=$read.status;updateStatus=$updated.status;auditStatus=$audit.status;deleteStatus=$deleted.status;afterDeleteStatus=$afterDelete.status;residue=$residue;harness='PHASE7_V103_REUSED';status=(Result-Status $canaryPass)});[void](Gate $canaryPass 'CRM_CANARY_AUDIT_ROLLBACK' 'APEX_PHASE8_V104_CANARY_HARNESS_DISCOVERY_REUSE_DEFECT' 'Reused approved synthetic Contact lifecycle')
    $postMatrix=Compare-Sources $ValidationRoot $effectiveManifest;$postPass=@($postMatrix|Where-Object{ -not $_.match}).Count -eq 0;Write-Json '13_FROZEN_SOURCE_POST_MATRIX_HASHES.json' ([pscustomobject]@{sources=$postMatrix;lockfileSha256=Hash-File (Join-Path $ValidationRoot 'pnpm-lock.yaml');packageManifestSha256=Hash-File (Join-Path $ValidationRoot 'package.json');sourceParity=$postPass;jsonlLedger=$ledger});[void](Gate $postPass 'POST_MATRIX_SOURCE_PARITY' 'APEX_PHASE8_V104_FROZEN_JSONL_TEST_MUTATION' 'Post-matrix effective release-source parity')
    $blocked=@($gates|Where-Object{$_.status -ne 'PASS'});$matrixPass=($blocked.Count -eq 0);$resumePass=$matrixPass;$releasePass=($parserPass -and $manifestPass -and $priorPass -and $canonicalPass -and $reconstructionPass -and $installPass -and $matrixPass -and $postPass -and $false);$matrixStatus='BLOCKED';if($matrixPass){$matrixStatus='PASS'};$resumeStatus='BLOCKED';if($resumePass){$resumeStatus='PASS'};$releaseStatus='BLOCKED';if($releasePass){$releaseStatus='PASS'};$phase9Status='BLOCKED';if($releasePass){$phase9Status='AUTHORIZED'};$overallStatus='BLOCKED';if($releasePass){$overallStatus='PASS'};$final='FIRST_FAILED_GATE='+$primaryFailure+[Environment]::NewLine+'GREEN_MATRIX='+$matrixStatus+[Environment]::NewLine+'PHASE8_EXACT_RESUME='+$resumeStatus+[Environment]::NewLine+'LOCAL_RELEASE_CANDIDATE='+$releaseStatus+[Environment]::NewLine+'PRODUCTION_RELEASE_AUTHORIZATION=NO'+[Environment]::NewLine+'PHASE9_PREDECESSOR_AUTHORIZATION='+$phase9Status+[Environment]::NewLine+'PRODUCTION_DEPLOYMENT=NO'+[Environment]::NewLine+'PRODUCTION_MUTATION=NO'+[Environment]::NewLine+'OVERALL_STATUS='+$overallStatus+[Environment]::NewLine;Write-Json '12_GREEN_MATRIX_SUMMARY.json' ([pscustomobject]@{status=$matrixStatus;firstFailedGate=$primaryFailure;gates=$gates});Write-Json '13_PHASE9_AUTHORIZATION.json' ([pscustomobject]@{status=$phase9Status;productionDeployment='NO';productionMutation='NO'});Write-Json '14_PRODUCTION_MUTATION_PROOF.json' ([pscustomobject]@{productionDeployment='NO';productionMutation='NO';canonicalWorkspaceMutated='NO'});Write-Json '15_FAILURE_LOG.json' @($failures);Write-Text 'FINAL_STATUS.txt' $final;Write-Text 'FINAL_REPORT.md' $final
    $files=@(Get-ChildItem $evidenceRoot -File|Sort-Object Name);$manifestRows=@($files|ForEach-Object{[pscustomobject]@{name=$_.Name;sha256=Hash-File $_.FullName;length=$_.Length}});Write-Json '16_EVIDENCE_MANIFEST.json' $manifestRows;$files=@(Get-ChildItem $evidenceRoot -File|Sort-Object Name);$zip=[IO.Compression.ZipFile]::Open($evidenceZip,[IO.Compression.ZipArchiveMode]::Create);try{foreach($file in $files){[IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip,$file.FullName,$file.Name)|Out-Null}}finally{$zip.Dispose()};$zipHash=Hash-File $evidenceZip;$reopen=[IO.Compression.ZipFile]::OpenRead($evidenceZip);try{$entryCount=$reopen.Entries.Count;$entryNames=@($reopen.Entries|ForEach-Object{$_.FullName})}finally{$reopen.Dispose()};$missing=@('FINAL_STATUS.txt','16_EVIDENCE_MANIFEST.json','13_PHASE9_AUTHORIZATION.json')|Where-Object{$_ -notin $entryNames};$reopenPass=(@($missing).Count -eq 0 -and $entryCount -eq $files.Count);$reopenStatus='BLOCKED';if($reopenPass){$reopenStatus='PASS'};$side=[pscustomobject]@{status=$reopenStatus;reopened=$true;zip=$evidenceZip;sha256=$zipHash;entryCount=$entryCount;sourceArtifactCount=$files.Count;missingEntries=@($missing)};[IO.File]::WriteAllText($sidecarPath,(($side|ConvertTo-Json -Depth 20)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Write-Output ('EVIDENCE_ROOT='+$evidenceRoot);Write-Output ('EVIDENCE_ZIP='+$evidenceZip);Write-Output $final;if(-not $reopenPass){exit 1};if($releasePass){exit 0};exit 1
} catch { try { Write-Text 'ERROR_LOG.txt' $_.Exception.ToString();Write-Text 'FINAL_STATUS.txt' "GREEN_MATRIX=BLOCKED`nPHASE8_EXACT_RESUME=BLOCKED`nLOCAL_RELEASE_CANDIDATE=BLOCKED`nPRODUCTION_RELEASE_AUTHORIZATION=NO`nPHASE9_PREDECESSOR_AUTHORIZATION=BLOCKED`nPRODUCTION_DEPLOYMENT=NO`nPRODUCTION_MUTATION=NO`nOVERALL_STATUS=BLOCKED`n" } catch {};exit 1 }