// Auto-generated by APEX WatanyBot Freelancer Skill Registry + Custom Entry v1.0
// Civilian Jobs & Services / فرص العمل المدنية والخدمات only.
// This file must remain independent from إعلانات التطويع.

export type FreelancerSkillCategory =
  | "construction_maintenance"
  | "automotive"
  | "transport"
  | "home_services"
  | "security"
  | "hospitality"
  | "healthcare_support"
  | "education"
  | "agriculture"
  | "office_services"
  | "digital_media"
  | "software_it"
  | "military_to_civilian"
  | "volunteer_services"
  | "small_business_services"
  | "custom_pending_review";

export type FreelancerSkillStatus = "approved" | "pending_review" | "rejected";

export interface FreelancerSkillDefinition {
  skillId: string;
  arabicName: string;
  englishName: string;
  category: FreelancerSkillCategory;
  status: FreelancerSkillStatus;
  aliases: string[];
  searchableText: string;
}

export interface FreelancerCustomSkillSuggestion {
  suggestionId: string;
  rawLabel: string;
  normalizedLabel: string;
  suggestedByUserId?: string;
  suggestedByPhone?: string;
  status: "pending_review" | "approved" | "rejected";
  matchedExistingSkillId?: string;
  adminNote?: string;
  createdAt: string;
  reviewedAt?: string;
  reviewedBy?: string;
}

function normalizeSkillText(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[إأآا]/g, "ا")
    .replace(/[ىي]/g, "ي")
    .replace(/[ة]/g, "ه")
    .replace(/\s+/g, " ");
}

function makeSkill(
  skillId: string,
  arabicName: string,
  englishName: string,
  category: FreelancerSkillCategory,
  aliases: string[] = [],
): FreelancerSkillDefinition {
  const searchableText = [skillId, arabicName, englishName, ...aliases]
    .map(normalizeSkillText)
    .join(" ");
  return { skillId, arabicName, englishName, category, status: "approved", aliases, searchableText };
}

export const FREELANCER_SKILL_REGISTRY: FreelancerSkillDefinition[] = [
  // Construction & Maintenance
  makeSkill("CON_BUILD_001", "عامل بناء", "Construction Worker", "construction_maintenance", ["بناء", "معلم بناء"]),
  makeSkill("CON_BUILD_002", "طوبرجي", "Formwork Carpenter", "construction_maintenance", ["نجار باطون", "formwork"]),
  makeSkill("CON_BUILD_003", "قصير", "Plasterer", "construction_maintenance", ["لياسة", "قصارة"]),
  makeSkill("CON_BUILD_004", "مبلط", "Tile Setter", "construction_maintenance", ["بلاط", "تركيب بلاط"]),
  makeSkill("CON_BUILD_005", "حجار", "Stone Mason", "construction_maintenance", ["حجر", "بناء حجر"]),
  makeSkill("CON_BUILD_006", "حداد باطون", "Rebar Worker", "construction_maintenance", ["حديد باطون", "rebar"]),
  makeSkill("CON_CARP_001", "نجار", "Carpenter", "construction_maintenance", ["نجار خشب", "carpenter"]),
  makeSkill("CON_CARP_002", "نجار ألمنيوم", "Aluminum Carpenter", "construction_maintenance", ["ألمنيوم", "الومنيوم"]),
  makeSkill("CON_CARP_003", "نجار مطابخ", "Kitchen Carpenter", "construction_maintenance", ["مطابخ", "خزائن"]),
  makeSkill("CON_ELEC_001", "كهربجي", "Electrician", "construction_maintenance", ["كهربائي", "فني كهرباء", "electrician"]),
  makeSkill("CON_ELEC_002", "كهربائي منازل", "Residential Electrician", "construction_maintenance", ["تمديد كهرباء", "منازل"]),
  makeSkill("CON_ELEC_003", "كهربائي صناعي", "Industrial Electrician", "construction_maintenance", ["صناعي", "معامل"]),
  makeSkill("CON_ELEC_004", "كهربائي طاقة شمسية", "Solar Electrician", "construction_maintenance", ["طاقة شمسية", "solar"]),
  makeSkill("CON_PLUMB_001", "سنكري", "Plumber", "construction_maintenance", ["سباك", "تمديدات صحية", "plumber"]),
  makeSkill("CON_PAINT_001", "دهان", "Painter", "construction_maintenance", ["دهين", "طلاء", "painter"]),
  makeSkill("CON_PAINT_002", "دهان ديكور", "Decorative Painter", "construction_maintenance", ["ديكور", "ورق جدران"]),
  makeSkill("CON_GYPS_001", "جبس بورد", "Gypsum Board Installer", "construction_maintenance", ["جبصين", "جبسن بورد"]),
  makeSkill("CON_METAL_001", "حداد", "Blacksmith", "construction_maintenance", ["حديد", "metal work"]),
  makeSkill("CON_METAL_002", "لحام", "Welder", "construction_maintenance", ["تلحيم", "welder"]),
  makeSkill("CON_METAL_003", "فني ستانلس", "Stainless Steel Technician", "construction_maintenance", ["ستانلس", "stainless"]),

  // Automotive
  makeSkill("AUTO_MECH_001", "ميكانيكي سيارات", "Auto Mechanic", "automotive", ["ميكانيك", "mechanic"]),
  makeSkill("AUTO_ELEC_001", "كهربائي سيارات", "Auto Electrician", "automotive", ["كهربجي سيارات"]),
  makeSkill("AUTO_BODY_001", "سمكري سيارات", "Auto Body Technician", "automotive", ["سمكرة", "body repair"]),
  makeSkill("AUTO_PAINT_001", "دهان سيارات", "Auto Painter", "automotive", ["بويا سيارات"]),
  makeSkill("AUTO_TIRE_001", "فني إطارات", "Tire Technician", "automotive", ["دواليب", "إطارات"]),
  makeSkill("AUTO_OIL_001", "فني زيوت", "Oil Change Technician", "automotive", ["غيار زيت"]),
  makeSkill("AUTO_BATT_001", "فني بطاريات", "Battery Technician", "automotive", ["بطاريات"]),

  // Transport
  makeSkill("TRN_DRV_001", "سائق", "Driver", "transport", ["driver"]),
  makeSkill("TRN_DRV_002", "سائق خاص", "Private Driver", "transport", ["سائق عائلي"]),
  makeSkill("TRN_DRV_003", "سائق عمومي", "Public Driver", "transport", ["تاكسي", "عمومي"]),
  makeSkill("TRN_DRV_004", "سائق شاحنة", "Truck Driver", "transport", ["شاحنات", "truck"]),
  makeSkill("TRN_DRV_005", "سائق فان", "Van Driver", "transport", ["فان", "باص صغير"]),
  makeSkill("TRN_DRV_006", "سائق توصيل", "Delivery Driver", "transport", ["توصيل", "delivery"]),
  makeSkill("TRN_DRV_007", "سائق معدات ثقيلة", "Heavy Equipment Driver", "transport", ["معدات ثقيلة", "جرافة"]),

  // Home services
  makeSkill("HOME_CLEAN_001", "عامل تنظيف", "Cleaner", "home_services", ["تنظيف", "cleaning"]),
  makeSkill("HOME_CLEAN_002", "مدبرة منزل", "Housekeeper", "home_services", ["تدبير منزلي"]),
  makeSkill("HOME_CLEAN_003", "جلي بلاط", "Floor Polishing", "home_services", ["جلي", "تلميع بلاط"]),
  makeSkill("HOME_CLEAN_004", "تنظيف خزانات", "Tank Cleaning", "home_services", ["خزانات مياه"]),
  makeSkill("HOME_CLEAN_005", "تنظيف سجاد", "Carpet Cleaning", "home_services", ["سجاد"]),
  makeSkill("HOME_CAR_001", "غسيل سيارات متنقل", "Mobile Car Wash", "home_services", ["غسيل سيارات"]),

  // Security
  makeSkill("SEC_GUARD_001", "حارس أمن", "Security Guard", "security", ["امن", "security"]),
  makeSkill("SEC_SUP_001", "مشرف أمن", "Security Supervisor", "security", ["مسؤول أمن"]),
  makeSkill("SEC_CCTV_001", "مراقبة كاميرات", "CCTV Operator", "security", ["كاميرات", "cctv"]),
  makeSkill("SEC_EVENT_001", "أمن مناسبات", "Event Security", "security", ["حماية مناسبات"]),
  makeSkill("SEC_SITE_001", "أمن منشآت", "Site Security", "security", ["منشآت"]),

  // Hospitality
  makeSkill("HOSP_WAITER_001", "نادل", "Waiter", "hospitality", ["ويتر", "waiter"]),
  makeSkill("HOSP_COOK_001", "طاهي", "Cook", "hospitality", ["شيف", "chef"]),
  makeSkill("HOSP_COOK_002", "مساعد طاهي", "Kitchen Assistant", "hospitality", ["مساعد شيف"]),
  makeSkill("HOSP_SWEET_001", "حلواني", "Pastry Chef", "hospitality", ["حلويات"]),
  makeSkill("HOSP_BAR_001", "باريستا", "Barista", "hospitality", ["قهوة", "barista"]),
  makeSkill("HOSP_REC_001", "موظف استقبال", "Receptionist", "hospitality", ["استقبال"]),

  // Healthcare support
  makeSkill("HEALTH_NURSE_001", "ممرض", "Nurse", "healthcare_support", ["تمريض"]),
  makeSkill("HEALTH_NURSE_002", "مساعد ممرض", "Nursing Assistant", "healthcare_support", ["مساعد تمريض"]),
  makeSkill("HEALTH_CARE_001", "مرافق مسنين", "Elderly Caregiver", "healthcare_support", ["رعاية مسنين"]),
  makeSkill("HEALTH_CARE_002", "مرافق مرضى", "Patient Caregiver", "healthcare_support", ["رعاية مرضى"]),
  makeSkill("HEALTH_FIRST_001", "مسعف", "First Aid Responder", "healthcare_support", ["إسعاف", "اسعاف"]),
  makeSkill("HEALTH_PHYS_001", "معالج فيزيائي", "Physical Therapist", "healthcare_support", ["علاج فيزيائي"]),

  // Education
  makeSkill("EDU_TUTOR_001", "مدرس خصوصي", "Private Tutor", "education", ["دروس خصوصية"]),
  makeSkill("EDU_MATH_001", "مدرس رياضيات", "Math Tutor", "education", ["رياضيات"]),
  makeSkill("EDU_AR_001", "مدرس لغة عربية", "Arabic Tutor", "education", ["عربي"]),
  makeSkill("EDU_EN_001", "مدرس لغة إنكليزية", "English Tutor", "education", ["انكليزي", "english"]),
  makeSkill("EDU_SCI_001", "مدرس علوم", "Science Tutor", "education", ["علوم"]),
  makeSkill("EDU_VOC_001", "مدرب مهني", "Vocational Trainer", "education", ["تدريب مهني"]),

  // Agriculture
  makeSkill("AGR_WORK_001", "عامل زراعي", "Agricultural Worker", "agriculture", ["زراعة"]),
  makeSkill("AGR_FARM_001", "مزارع", "Farmer", "agriculture", ["مزرعة"]),
  makeSkill("AGR_GARD_001", "عامل بساتين", "Gardener", "agriculture", ["بستاني", "حدائق"]),
  makeSkill("AGR_IRR_001", "عامل ري", "Irrigation Worker", "agriculture", ["ري"]),

  // Office services
  makeSkill("OFF_DATA_001", "مدخل بيانات", "Data Entry", "office_services", ["data entry"]),
  makeSkill("OFF_SEC_001", "سكرتير", "Secretary", "office_services", ["سكرتاريا"]),
  makeSkill("OFF_ACC_001", "محاسب", "Accountant", "office_services", ["محاسبة"]),
  makeSkill("OFF_INV_001", "أمين مستودع", "Warehouse Clerk", "office_services", ["مستودع"]),
  makeSkill("OFF_ARCH_001", "موظف أرشيف", "Archive Clerk", "office_services", ["أرشيف"]),
  makeSkill("OFF_ADMIN_001", "موظف إداري", "Administrative Clerk", "office_services", ["إدارة"]),

  // Digital media
  makeSkill("DIG_DES_001", "مصمم جرافيك", "Graphic Designer", "digital_media", ["graphic design"]),
  makeSkill("DIG_UI_001", "مصمم UI", "UI Designer", "digital_media", ["ui"]),
  makeSkill("DIG_UX_001", "مصمم UX", "UX Designer", "digital_media", ["ux"]),
  makeSkill("DIG_PHOTO_001", "مصور", "Photographer", "digital_media", ["تصوير"]),
  makeSkill("DIG_VIDEO_001", "مصور فيديو", "Videographer", "digital_media", ["فيديو"]),
  makeSkill("DIG_EDIT_001", "مونتير", "Video Editor", "digital_media", ["مونتاج"]),
  makeSkill("DIG_WRITE_001", "كاتب محتوى", "Content Writer", "digital_media", ["محتوى"]),
  makeSkill("DIG_TRANS_001", "مترجم", "Translator", "digital_media", ["ترجمة"]),
  makeSkill("DIG_SOCIAL_001", "مدير صفحات", "Social Media Manager", "digital_media", ["سوشال ميديا"]),
  makeSkill("DIG_MKT_001", "مسوق رقمي", "Digital Marketer", "digital_media", ["digital marketing"]),
  makeSkill("DIG_SEO_001", "SEO", "SEO Specialist", "digital_media", ["سيو"]),

  // Software & IT
  makeSkill("IT_WEB_001", "مطور ويب", "Web Developer", "software_it", ["web developer"]),
  makeSkill("IT_REACT_001", "مطور React", "React Developer", "software_it", ["react"]),
  makeSkill("IT_NEXT_001", "مطور Next.js", "Next.js Developer", "software_it", ["nextjs", "next.js"]),
  makeSkill("IT_MOB_001", "مطور Mobile", "Mobile Developer", "software_it", ["موبايل", "mobile"]),
  makeSkill("IT_BACK_001", "مطور Backend", "Backend Developer", "software_it", ["backend"]),
  makeSkill("IT_DEVOPS_001", "DevOps", "DevOps Engineer", "software_it", ["devops"]),
  makeSkill("IT_QA_001", "QA Tester", "QA Tester", "software_it", ["اختبار برمجيات"]),
  makeSkill("IT_SUPPORT_001", "Support Technician", "IT Support Technician", "software_it", ["دعم تقني"]),
  makeSkill("IT_NET_001", "Network Engineer", "Network Engineer", "software_it", ["شبكات"]),
  makeSkill("IT_CYBER_001", "Cyber Security", "Cyber Security Specialist", "software_it", ["أمن سيبراني"]),

  // Military-to-civilian skills
  makeSkill("MIL_FIT_001", "مدرب لياقة", "Fitness Trainer", "military_to_civilian", ["رياضة", "fitness"]),
  makeSkill("MIL_DISC_001", "مدرب انضباط", "Discipline Trainer", "military_to_civilian", ["انضباط"]),
  makeSkill("MIL_FIRST_001", "مدرب إسعافات أولية", "First Aid Trainer", "military_to_civilian", ["اسعافات", "إسعاف"]),
  makeSkill("MIL_SEC_001", "مدرب أمن", "Security Trainer", "military_to_civilian", ["تدريب أمن"]),
  makeSkill("MIL_OPS_001", "مشرف عمليات", "Operations Supervisor", "military_to_civilian", ["عمليات"]),
  makeSkill("MIL_LOG_001", "مشرف لوجستيات", "Logistics Supervisor", "military_to_civilian", ["لوجستيات"]),
  makeSkill("MIL_TRANS_001", "منسق نقل", "Transport Coordinator", "military_to_civilian", ["نقل"]),
  makeSkill("MIL_FIELD_001", "مراقب ميداني", "Field Monitor", "military_to_civilian", ["ميداني"]),

  // Volunteer services
  makeSkill("VOL_FIRST_001", "متطوع إسعاف", "First Aid Volunteer", "volunteer_services", ["إسعاف", "اسعاف"]),
  makeSkill("VOL_ENV_001", "متطوع بيئي", "Environmental Volunteer", "volunteer_services", ["بيئة"]),
  makeSkill("VOL_SOC_001", "متطوع اجتماعي", "Social Volunteer", "volunteer_services", ["اجتماعي"]),
  makeSkill("VOL_EDU_001", "متطوع تعليمي", "Education Volunteer", "volunteer_services", ["تعليمي"]),
  makeSkill("VOL_RELIEF_001", "متطوع إغاثة", "Relief Volunteer", "volunteer_services", ["إغاثة", "اغاثة"]),
  makeSkill("VOL_NGO_001", "متطوع جمعيات", "NGO Volunteer", "volunteer_services", ["جمعيات"]),

  // Small business services
  makeSkill("BIZ_SALES_001", "مندوب مبيعات", "Sales Representative", "small_business_services", ["مبيعات"]),
  makeSkill("BIZ_COLLECT_001", "مندوب تحصيل", "Collection Representative", "small_business_services", ["تحصيل"]),
  makeSkill("BIZ_INS_001", "وكيل تأمين", "Insurance Agent", "small_business_services", ["تأمين"]),
  makeSkill("BIZ_REAL_001", "سمسار عقاري", "Real Estate Broker", "small_business_services", ["عقارات"]),
  makeSkill("BIZ_BROKER_001", "وسيط تجاري", "Business Broker", "small_business_services", ["وسيط"]),
  makeSkill("BIZ_SHIP_001", "وكيل شحن", "Shipping Agent", "small_business_services", ["شحن"]),
];

export function getApprovedFreelancerSkills(): FreelancerSkillDefinition[] {
  return FREELANCER_SKILL_REGISTRY.filter((skill) => skill.status === "approved");
}

export function findFreelancerSkills(query: string): FreelancerSkillDefinition[] {
  const normalized = normalizeSkillText(query);
  if (!normalized) return getApprovedFreelancerSkills();
  return getApprovedFreelancerSkills().filter((skill) => skill.searchableText.includes(normalized));
}

export function findFreelancerSkillsByIds(skillIds: string[]): FreelancerSkillDefinition[] {
  const wanted = new Set(skillIds);
  return getApprovedFreelancerSkills().filter((skill) => wanted.has(skill.skillId));
}

export function makeCustomFreelancerSkillSuggestion(input: {
  rawLabel: string;
  suggestedByUserId?: string;
  suggestedByPhone?: string;
}): FreelancerCustomSkillSuggestion {
  const normalizedLabel = normalizeSkillText(input.rawLabel);
  const matched = findFreelancerSkills(normalizedLabel)[0];
  return {
    suggestionId: `custom-skill-${Date.now()}`,
    rawLabel: input.rawLabel.trim(),
    normalizedLabel,
    suggestedByUserId: input.suggestedByUserId,
    suggestedByPhone: input.suggestedByPhone,
    status: "pending_review",
    matchedExistingSkillId: matched?.skillId,
    createdAt: new Date().toISOString(),
  };
}

export function isValidFreelancerSkillSelection(skillIds: string[]): boolean {
  if (!Array.isArray(skillIds)) return false;
  if (skillIds.length === 0) return false;
  const approvedIds = new Set(getApprovedFreelancerSkills().map((skill) => skill.skillId));
  return skillIds.every((skillId) => approvedIds.has(skillId));
}