// Auto-generated by APEX WatanyBot Freelancer Skill Registry + Custom Entry v1.0
// In-memory pending queue scaffold. Replace with repository-backed persistence in Wave12 hardening.

import {
  FreelancerCustomSkillSuggestion,
  makeCustomFreelancerSkillSuggestion,
} from "./civilian-jobs.skill-registry";

const pendingSuggestions: FreelancerCustomSkillSuggestion[] = [];

export function submitCustomFreelancerSkillSuggestion(input: {
  rawLabel: string;
  suggestedByUserId?: string;
  suggestedByPhone?: string;
}): FreelancerCustomSkillSuggestion {
  const suggestion = makeCustomFreelancerSkillSuggestion(input);
  if (!suggestion.rawLabel || suggestion.normalizedLabel.length < 2) {
    throw new Error("CUSTOM_SKILL_LABEL_TOO_SHORT");
  }
  pendingSuggestions.push(suggestion);
  return suggestion;
}

export function listPendingCustomFreelancerSkillSuggestions(): FreelancerCustomSkillSuggestion[] {
  return pendingSuggestions.filter((suggestion) => suggestion.status === "pending_review");
}

export function approveCustomFreelancerSkillSuggestion(
  suggestionId: string,
  reviewedBy: string,
  adminNote?: string,
): FreelancerCustomSkillSuggestion | undefined {
  const suggestion = pendingSuggestions.find((item) => item.suggestionId === suggestionId);
  if (!suggestion) return undefined;
  suggestion.status = "approved";
  suggestion.reviewedBy = reviewedBy;
  suggestion.reviewedAt = new Date().toISOString();
  suggestion.adminNote = adminNote;
  return suggestion;
}

export function rejectCustomFreelancerSkillSuggestion(
  suggestionId: string,
  reviewedBy: string,
  adminNote?: string,
): FreelancerCustomSkillSuggestion | undefined {
  const suggestion = pendingSuggestions.find((item) => item.suggestionId === suggestionId);
  if (!suggestion) return undefined;
  suggestion.status = "rejected";
  suggestion.reviewedBy = reviewedBy;
  suggestion.reviewedAt = new Date().toISOString();
  suggestion.adminNote = adminNote;
  return suggestion;
}