// Auto-generated by APEX WatanyBot Freelancer Skill Registry + Custom Entry v1.0
// Fastify plugin scaffold for freelancer skill registry and pending custom entries.

import type { FastifyInstance } from "fastify";
import {
  findFreelancerSkills,
  getApprovedFreelancerSkills,
} from "./civilian-jobs.skill-registry";
import {
  approveCustomFreelancerSkillSuggestion,
  listPendingCustomFreelancerSkillSuggestions,
  rejectCustomFreelancerSkillSuggestion,
  submitCustomFreelancerSkillSuggestion,
} from "./civilian-jobs.freelancer-skill-suggestions";
import { requireRole } from "../auth/rbac.js";

export async function registerCivilianJobsFreelancerSkillRoutes(app: FastifyInstance) {
  app.get("/api/civilian-jobs/freelancer-skills", async (request) => {
    const query = (request.query as { q?: string }).q;
    return query ? findFreelancerSkills(query) : getApprovedFreelancerSkills();
  });

  app.post("/api/civilian-jobs/freelancer-skills/suggestions", async (request, reply) => {
    const body = request.body as { rawLabel?: string; suggestedByUserId?: string; suggestedByPhone?: string };
    if (!body.rawLabel || body.rawLabel.trim().length < 2) {
      return reply.code(400).send({ error: "CUSTOM_SKILL_LABEL_TOO_SHORT" });
    }
    const suggestion = submitCustomFreelancerSkillSuggestion({
      rawLabel: body.rawLabel,
      suggestedByUserId: body.suggestedByUserId,
      suggestedByPhone: body.suggestedByPhone,
    });
    return reply.code(201).send(suggestion);
  });

  app.get(
    "/api/admin/civilian-jobs/freelancer-skills/suggestions",
    { preHandler: [requireRole("admin")] },
    async () => listPendingCustomFreelancerSkillSuggestions(),
  );

  app.post(
    "/api/admin/civilian-jobs/freelancer-skills/suggestions/:id/approve",
    { preHandler: [requireRole("admin")] },
    async (request, reply) => {
      const params = request.params as { id: string };
      const body = request.body as { reviewedBy?: string; adminNote?: string };
      const result = approveCustomFreelancerSkillSuggestion(params.id, body.reviewedBy ?? "admin", body.adminNote);
      if (!result) return reply.code(404).send({ error: "CUSTOM_SKILL_SUGGESTION_NOT_FOUND" });
      return result;
    },
  );

  app.post(
    "/api/admin/civilian-jobs/freelancer-skills/suggestions/:id/reject",
    { preHandler: [requireRole("admin")] },
    async (request, reply) => {
      const params = request.params as { id: string };
      const body = request.body as { reviewedBy?: string; adminNote?: string };
      const result = rejectCustomFreelancerSkillSuggestion(params.id, body.reviewedBy ?? "admin", body.adminNote);
      if (!result) return reply.code(404).send({ error: "CUSTOM_SKILL_SUGGESTION_NOT_FOUND" });
      return result;
    },
  );
}