export type LafResponsibleSection = { id: string; titleAr: string; parentId?: string; pathAr: string[] };
export type LafAdministrativeRequest = { id: string; order: number; titleAr: string; responsibleSectionId: string; responsiblePathAr: string[]; documents: string[]; sourceUrl: string; detailSourceUrl?: string; localNotes: string[] };
export const lafAdministrativeSource = { id: "laf-administrative-transactions-2344", titleAr: "معاملات إدارية - مديرية الإشارة", providerAr: "الجيش اللبناني", sourceUrl: "https://www.lebarmy.gov.lb/ar/administrative_transactions/2344", route: "/services/official/laf-administrative-transactions", rebuiltFile: "laf.html", mode: "LOCAL_GUIDE_WITH_OFFICIAL_SOURCE" };
export const lafResponsibleSections: LafResponsibleSection[] = [
  { id:"libanpost", titleAr:"Liban Post", pathAr:["معاملات إدارية","Liban Post"] }, { id:"libanpost-requests", titleAr:"طلبات ومراجعات", parentId:"libanpost", pathAr:["معاملات إدارية","Liban Post","طلبات ومراجعات"] },
  { id:"circulars", titleAr:"تعاميم", pathAr:["معاملات إدارية","تعاميم"] }, { id:"aircraft-circulars", titleAr:"تعاميم خاصة بالطائرات", parentId:"circulars", pathAr:["معاملات إدارية","تعاميم","تعاميم خاصة بالطائرات"] },
  { id:"directorate-guidance", titleAr:"مديرية التوجيه", pathAr:["معاملات إدارية","مديرية التوجيه"] }, { id:"directorate-geographic", titleAr:"مديرية الشؤون الجغرافية", pathAr:["معاملات إدارية","مديرية الشؤون الجغرافية"] }, { id:"air-force", titleAr:"القوات الجوية", pathAr:["معاملات إدارية","القوات الجوية"] },
  { id:"staff-personnel", titleAr:"أركان الجيش للعديد", pathAr:["معاملات إدارية","أركان الجيش للعديد"] }, { id:"staff-personnel-admin", titleAr:"مكتب إداري", parentId:"staff-personnel", pathAr:["معاملات إدارية","أركان الجيش للعديد","مكتب إداري"] }, { id:"veterans-care", titleAr:"جهاز الرعاية والشؤون الاجتماعية للعسكريين القدامى", parentId:"staff-personnel", pathAr:["معاملات إدارية","أركان الجيش للعديد","جهاز الرعاية والشؤون الاجتماعية للعسكريين القدامى"] }, { id:"staff-personnel-technical", titleAr:"مكتب تقني", parentId:"staff-personnel", pathAr:["معاملات إدارية","أركان الجيش للعديد","مكتب تقني"] }, { id:"protocol-device", titleAr:"جهاز المراسم", parentId:"staff-personnel", pathAr:["معاملات إدارية","أركان الجيش للعديد","جهاز المراسم"] }, { id:"mobilization-directorate", titleAr:"مديرية التعبئة", parentId:"staff-personnel", pathAr:["معاملات إدارية","أركان الجيش للعديد","مديرية التعبئة"] }, { id:"personnel-directorate", titleAr:"مديرية الأفراد", parentId:"staff-personnel", pathAr:["معاملات إدارية","أركان الجيش للعديد","مديرية الأفراد"] }, { id:"ihl-human-rights", titleAr:"مديرية القانون الدولي الإنساني وحقوق الإنسان", parentId:"staff-personnel", pathAr:["معاملات إدارية","أركان الجيش للعديد","مديرية القانون الدولي الإنساني وحقوق الإنسان"] },
  { id:"staff-operations", titleAr:"أركان الجيش للعمليات", pathAr:["معاملات إدارية","أركان الجيش للعمليات"] }, { id:"education-directorate", titleAr:"مديرية التعليم", parentId:"staff-operations", pathAr:["معاملات إدارية","أركان الجيش للعمليات","مديرية التعليم"] }, { id:"operations-directorate", titleAr:"مديرية العمليات", parentId:"staff-operations", pathAr:["معاملات إدارية","أركان الجيش للعمليات","مديرية العمليات"] }, { id:"signal-directorate", titleAr:"مديرية الإشارة", parentId:"staff-operations", pathAr:["معاملات إدارية","أركان الجيش للعمليات","مديرية الإشارة"] }, { id:"mine-action-center", titleAr:"المركز اللبناني للأعمال المتعلقة بالألغام", parentId:"staff-operations", pathAr:["معاملات إدارية","أركان الجيش للعمليات","المركز اللبناني للأعمال المتعلقة بالألغام"] },
  { id:"staff-equipment", titleAr:"أركان الجيش للتجهيز", pathAr:["معاملات إدارية","أركان الجيش للتجهيز"] }, { id:"real-estate-office", titleAr:"مكتب الشؤون العقارية", parentId:"staff-equipment", pathAr:["معاملات إدارية","أركان الجيش للتجهيز","مكتب الشؤون العقارية"] }, { id:"equipment-technical-office", titleAr:"المكتب التقني", parentId:"staff-equipment", pathAr:["معاملات إدارية","أركان الجيش للتجهيز","المكتب التقني"] }, { id:"equipment-admin-office", titleAr:"مكتب إداري", parentId:"staff-equipment", pathAr:["معاملات إدارية","أركان الجيش للتجهيز","مكتب إداري"] }
];
const signal = ["معاملات إدارية","أركان الجيش للعمليات","مديرية الإشارة"];
export const lafAdministrativeRequests: LafAdministrativeRequest[] = [
  { id:"temporary-vsat-stations", order:1, titleAr:"طلب الموافقة على إدخال محطات إرسال أرضية وفضائية (VSAT أو ما شابه) بصورة مؤقتة.", responsibleSectionId:"signal-directorate", responsiblePathAr:signal, sourceUrl:lafAdministrativeSource.sourceUrl, documents:["كتاب من صاحب العلاقة يتضمن تفاصيل الطلب، بما في ذلك معلومات عن المحطة ومكان استخدامها.","معلومات عن المحطة ومكان استخدامها.","إثبات هوية صاحب العلاقة: بطاقة هوية أو بيان قيد إفرادي أو بطاقة خدمات اجتماعية أو دفتر تقاعد."], localNotes:["الطلب متعلق بتجهيزات إرسال أرضية وفضائية بصورة مؤقتة."] },
  { id:"civilian-entry-military-centers", order:2, titleAr:"طلب السماح بدخول مدنيين إلى مراكز عسكرية (للكشف، صيانة، تعهد أبراج إرسال تابعة لهم...).", responsibleSectionId:"signal-directorate", responsiblePathAr:signal, sourceUrl:lafAdministrativeSource.sourceUrl, documents:["كتاب من صاحب العلاقة يتضمن تفاصيل الطلب.","صور عن هويات العاملين أو الأشخاص الذين يريدون الدخول إلى الثكنة.","إثبات هوية صاحب العلاقة: بطاقة هوية أو بيان قيد إفرادي أو جواز سفر أجنبي ساري الصلاحية لغير اللبنانيين."], localNotes:["هذا الدليل لا يمنح إذن دخول؛ هو فقط يعرض المستندات المطلوبة من المصدر الرسمي."] },
  { id:"install-towers-near-military-centers", order:3, titleAr:"طلب الموافقة على تركيب أبراج، محطات أو عتاد بالقرب من الثكنات والمراكز العسكرية.", responsibleSectionId:"signal-directorate", responsiblePathAr:signal, sourceUrl:lafAdministrativeSource.sourceUrl, documents:["كتاب من صاحب العلاقة يتضمن تفاصيل الطلب.","خريطة تبين مكان تركيب البرج ومميزات العتاد مثل المصدر والمميزات الفنية والتردد.","إثبات هوية صاحب العلاقة: بطاقة هوية أو بيان قيد إفرادي أو بطاقة خدمات اجتماعية أو دفتر تقاعد."], localNotes:["الطلب خاص بالمواقع القريبة من الثكنات والمراكز العسكرية."] },
  { id:"install-signal-boosters-inside-military-centers", order:4, titleAr:"طلب الموافقة على تركيب أبراج تقوية إرسال داخل الثكنات والمراكز العسكرية.", responsibleSectionId:"signal-directorate", responsiblePathAr:signal, sourceUrl:lafAdministrativeSource.sourceUrl, documents:["كتاب من صاحب العلاقة يتضمن تفاصيل الطلب.","خريطة تبين مكان تركيب البرج وأنواع العتاد المقترح تركيبه مثل المواصفات والمميزات الفنية والترددات.","إثبات هوية المودع: بطاقة هوية أو بيان قيد إفرادي.","إثبات هوية أصحاب العلاقة الذين يريدون الدخول إلى الثكنة: بطاقة هوية أو بيان قيد إفرادي أو جواز سفر أجنبي ساري الصلاحية لغير اللبنانيين."], localNotes:["الطلب خاص بأبراج تقوية الإرسال داخل الثكنات والمراكز العسكرية."] }
];
export function getLafAdministrativeRequest(id: string) { return lafAdministrativeRequests.find((item) => item.id === id); }

// APEX_CIRCULARS_TAXONOMY_ADAPTER_EXPORT_START
export { CIRCULAR_TAXONOMY, getCircularTaxonomyLabelAr, inferCircularCategory, normalizeCircularRecord, normalizeCircularRecords } from "../circulars";
// APEX_CIRCULARS_TAXONOMY_ADAPTER_EXPORT_END
