import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { authFetch } from "../lib/api";
import { useApp } from "../store/app";

type Field={fieldKey:string;label:string;fieldType:string;required:boolean;placeholder:string;helpText:string;options:string[]};
const types=[['text','نص'],['textarea','نص طويل'],['number','رقم'],['email','بريد'],['tel','هاتف'],['date','تاريخ'],['select','قائمة'],['radio','اختيار واحد'],['checkbox','مربع اختيار']];
export default function EmployerJobBuilderPage(){
 const {apiBaseUrl}=useApp(); const {jobId}=useParams(); const nav=useNavigate(); const editing=Boolean(jobId&&jobId!=='new');
 const [meta,setMeta]=useState({title:'',slug:'',summary:'',description:'',employmentType:'',workMode:'',governorate:'',caza:'',locality:'',salaryText:'',closesAt:''});
 const [fields,setFields]=useState<Field[]>([{fieldKey:'q_1',label:'',fieldType:'text',required:true,placeholder:'',helpText:'',options:[]}]);
 const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!editing)return; (async()=>{const r=await authFetch(`${apiBaseUrl}/api/jobs/builder/jobs/${jobId}/manage`);if(!r.ok)return setMessage('تعذّر تحميل الوظيفة.');const x=(await r.json()).item;setMeta({title:x.title||'',slug:x.slug||'',summary:x.summary||'',description:x.description||'',employmentType:x.employment_type||'',workMode:x.work_mode||'',governorate:x.governorate||'',caza:x.caza||'',locality:x.locality||'',salaryText:x.salary_text||'',closesAt:x.closes_at?String(x.closes_at).slice(0,16):''});setFields((x.fields||[]).map((f:any)=>({fieldKey:f.fieldKey,label:f.label,fieldType:f.fieldType,required:Boolean(f.required),placeholder:f.placeholder||'',helpText:f.helpText||'',options:f.options||[]})));})();},[apiBaseUrl,jobId,editing]);
 function addField(){setFields(v=>[...v,{fieldKey:`q_${Date.now()}`,label:'',fieldType:'text',required:false,placeholder:'',helpText:'',options:[]}]);}
 function updateField(i:number,patch:Partial<Field>){setFields(v=>v.map((f,n)=>n===i?{...f,...patch}:f));}
 function move(i:number,d:number){const n=i+d;if(n<0||n>=fields.length)return;const a=[...fields];[a[i],a[n]]=[a[n],a[i]];setFields(a);}
 async function save(publish=false){setSaving(true);setMessage('');const body={...meta,closesAt:meta.closesAt||null,fields};const url=editing?`${apiBaseUrl}/api/jobs/builder/jobs/${jobId}`:`${apiBaseUrl}/api/jobs/builder/jobs`;const r=await authFetch(url,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){setSaving(false);setMessage('تعذّر حفظ الوظيفة. تحقق من العنوان والأسئلة.');return;}const item=(await r.json()).item; if(publish){const p=await authFetch(`${apiBaseUrl}/api/jobs/builder/jobs/${item.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'PUBLISHED'})});if(!p.ok){setSaving(false);setMessage('تم الحفظ كمسودة، لكن تعذّر النشر.'); if(!editing)nav(`/jobs/employer/builder/${item.id}`,{replace:true});return;}} setSaving(false);setMessage(publish?'تم الحفظ والنشر.':'تم الحفظ كمسودة.'); if(!editing)nav(`/jobs/employer/builder/${item.id}`,{replace:true});}
 return <main className="page-shell" dir="rtl"><section className="profile-section-card space-y-3"><div className="flex justify-between gap-3"><div><h1>{editing?'تعديل الوظيفة':'إنشاء وظيفة جديدة'}</h1><p>الاسم ورقم الهاتف والبريد حقول أساسية تلقائية. أضف الأسئلة الخاصة بهذه الوظيفة أدناه.</p></div><a className="btn" href="/jobs/employer/dashboard">العودة للوحة</a></div>
 <div className="grid gap-3 md:grid-cols-2"><label className="profile-field"><span>عنوان الوظيفة *</span><input className="input" value={meta.title} onChange={e=>setMeta({...meta,title:e.target.value})}/></label><label className="profile-field"><span>الرابط المختصر (اختياري)</span><input className="input" value={meta.slug} onChange={e=>setMeta({...meta,slug:e.target.value})}/></label><label className="profile-field"><span>نوع الدوام</span><input className="input" value={meta.employmentType} onChange={e=>setMeta({...meta,employmentType:e.target.value})}/></label><label className="profile-field"><span>نمط العمل</span><input className="input" value={meta.workMode} onChange={e=>setMeta({...meta,workMode:e.target.value})}/></label><label className="profile-field"><span>المحافظة</span><input className="input" value={meta.governorate} onChange={e=>setMeta({...meta,governorate:e.target.value})}/></label><label className="profile-field"><span>القضاء</span><input className="input" value={meta.caza} onChange={e=>setMeta({...meta,caza:e.target.value})}/></label><label className="profile-field"><span>المنطقة/البلدة</span><input className="input" value={meta.locality} onChange={e=>setMeta({...meta,locality:e.target.value})}/></label><label className="profile-field"><span>الراتب</span><input className="input" value={meta.salaryText} onChange={e=>setMeta({...meta,salaryText:e.target.value})}/></label><label className="profile-field"><span>إغلاق التقديم</span><input className="input" type="datetime-local" value={meta.closesAt} onChange={e=>setMeta({...meta,closesAt:e.target.value})}/></label></div>
 <label className="profile-field"><span>ملخص</span><textarea className="input" value={meta.summary} onChange={e=>setMeta({...meta,summary:e.target.value})}/></label><label className="profile-field"><span>وصف الوظيفة</span><textarea className="input" rows={6} value={meta.description} onChange={e=>setMeta({...meta,description:e.target.value})}/></label></section>
 <section className="profile-section-card space-y-3"><div className="flex justify-between"><div><h2>أسئلة نموذج التقديم</h2><p>استخدم مفتاحاً ثابتاً مثل experience_years كي يمكن تعبئته لاحقاً من طلب أو قالب سابق.</p></div><button className="btn btn-primary" type="button" onClick={addField}>إضافة سؤال</button></div>{fields.map((f,i)=><article key={f.fieldKey} className="rounded-xl border p-3 space-y-2"><div className="grid gap-2 md:grid-cols-3"><input className="input" placeholder="عنوان السؤال" value={f.label} onChange={e=>updateField(i,{label:e.target.value})}/><input className="input" placeholder="field_key" value={f.fieldKey} onChange={e=>updateField(i,{fieldKey:e.target.value})}/><select className="input" value={f.fieldType} onChange={e=>updateField(i,{fieldType:e.target.value})}>{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="grid gap-2 md:grid-cols-2"><input className="input" placeholder="نص توضيحي داخل الحقل" value={f.placeholder} onChange={e=>updateField(i,{placeholder:e.target.value})}/><input className="input" placeholder="مساعدة قصيرة" value={f.helpText} onChange={e=>updateField(i,{helpText:e.target.value})}/></div>{['select','radio'].includes(f.fieldType)?<input className="input" placeholder="الخيارات مفصولة بفواصل" value={f.options.join(', ')} onChange={e=>updateField(i,{options:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/>:null}<div className="flex flex-wrap gap-2"><label><input type="checkbox" checked={f.required} onChange={e=>updateField(i,{required:e.target.checked})}/> مطلوب</label><button className="btn" type="button" onClick={()=>move(i,-1)}>↑</button><button className="btn" type="button" onClick={()=>move(i,1)}>↓</button><button className="btn" type="button" onClick={()=>setFields(v=>v.filter((_,n)=>n!==i))}>حذف</button></div></article>)}</section>
 <section className="profile-section-card"><div className="flex flex-wrap gap-2"><button className="btn" disabled={saving} onClick={()=>void save(false)}>حفظ كمسودة</button><button className="btn btn-primary" disabled={saving||fields.length===0} onClick={()=>void save(true)}>حفظ ونشر</button></div>{message?<p aria-live="polite">{message}</p>:null}</section></main>;
}