import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { authFetch } from "../lib/api";
import { useApp } from "../store/app";

const statuses=['SUBMITTED','SCREENING','CONTACTED','SHORTLISTED','INTERVIEW','ACCEPTED','REJECTED','WITHDRAWN'];
const labels:Record<string,string>={SUBMITTED:'مقدّم',SCREENING:'قيد الفرز',CONTACTED:'تم التواصل',SHORTLISTED:'قائمة مختصرة',INTERVIEW:'مقابلة',ACCEPTED:'مقبول',REJECTED:'مرفوض',WITHDRAWN:'منسحب'};
export default function EmployerJobApplicationsPage(){
 const {apiBaseUrl}=useApp(); const {jobId}=useParams(); const [job,setJob]=useState<any>(null),[items,setItems]=useState<any[]>([]),[filter,setFilter]=useState(''),[message,setMessage]=useState('');
 async function load(){const q=filter?`?status=${filter}`:'';const r=await authFetch(`${apiBaseUrl}/api/jobs/builder/jobs/${jobId}/applications${q}`);if(!r.ok){setMessage('تعذّر تحميل الطلبات.');return;}const x=await r.json();setJob(x.job);setItems(x.items??[]);}
 useEffect(()=>{void load();},[apiBaseUrl,jobId,filter]);
 async function save(item:any){const r=await authFetch(`${apiBaseUrl}/api/jobs/builder/applications/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:item.status,employerNotes:item.employer_notes||''})});setMessage(r.ok?'تم حفظ المتابعة.':'تعذّر حفظ المتابعة.');if(r.ok)await load();}
 return <main className="page-shell" dir="rtl"><section className="profile-section-card"><div className="flex flex-wrap justify-between gap-3"><div><h1>متابعة طلبات التقديم</h1><p>{job?.title||'الوظيفة'} · {items.length} طلب ضمن العرض الحالي</p></div><a className="btn" href="/jobs/employer/dashboard">العودة للوظائف</a></div><div className="flex flex-wrap gap-2 mt-3"><button className={filter===''?'btn btn-primary':'btn'} onClick={()=>setFilter('')}>الكل</button>{statuses.map(s=><button key={s} className={filter===s?'btn btn-primary':'btn'} onClick={()=>setFilter(s)}>{labels[s]}</button>)}</div></section>{message?<p aria-live="polite">{message}</p>:null}<section className="space-y-3">{items.length===0?<div className="profile-section-card">لا توجد طلبات ضمن هذه الحالة.</div>:null}{items.map((item,i)=><article key={item.id} className="profile-section-card space-y-3"><div className="flex flex-wrap justify-between gap-2"><div><strong>{item.applicant_name}</strong><p dir="ltr">{item.applicant_phone}{item.applicant_email?` · ${item.applicant_email}`:''}</p></div><span>{labels[item.status]||item.status} · {item.prefill_source}</span></div><div className="grid gap-2 md:grid-cols-2">{Object.entries(item.answers||{}).map(([k,v])=><div key={k} className="rounded-xl border p-2"><strong>{k}</strong><p>{typeof v==='boolean'?(v?'نعم':'لا'):String(v??'')}</p></div>)}</div><label className="profile-field"><span>الحالة</span><select className="input" value={item.status} onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,status:e.target.value}:x))}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label className="profile-field"><span>ملاحظات صاحب العمل</span><textarea className="input" value={item.employer_notes||''} onChange={e=>setItems(v=>v.map((x,n)=>n===i?{...x,employer_notes:e.target.value}:x))}/></label><button className="btn btn-primary" onClick={()=>void save(item)}>حفظ المتابعة</button></article>)}</section></main>;
}