import type { WatanyV4IconName } from "./iconRegistry";

const FEATURE_ICON_NAMES: Record<string, WatanyV4IconName> = {
  "for-you": "important",
  latest: "latest",
  popular: "most-requested",
  tools: "tools",
  designs: "designs",
  login: "login",
  bookmarks: "profile",
  profile: "profile",
  "saved-chats": "messages",
  settings: "settings",
  install: "install",
  documents: "documents",
  notifications: "notifications",
  messages: "messages",
  administration: "administration",
  users: "users",
  roles: "roles",
  "activity-log": "activity-log",
  news: "news",
  "fake-fact": "fake-fact",
  circulars: "circulars",
  "useful-links": "links",
  marketplace: "marketplace",
  jobs: "jobs",
  ads: "ads",
  salary: "salary",
  transactions: "transactions",
  forms: "forms",
  schools: "schools",
  network: "network",
  taxi: "taxi",
  voting: "voting",
  faq: "faq",
  laws: "laws",
  procedures: "procedures",
  "world-cup": "world-cup",
  community: "community",
  voice: "voice",
  "chat-sessions": "messages",
  deaths: "deaths",
  health: "health",
  "ask-watany": "ask-watany",
  home: "most-requested",
  children: "users",
  sports: "world-cup",
};

export function getWatanyV4IconName(featureId: string): WatanyV4IconName {
  return FEATURE_ICON_NAMES[featureId] || "ask-watany";
}