export const WATANY_V4_LOGO_PATH = "/watany-v4/brand/mowatany-logo.png" as const;

export const WATANY_V4_ICONS = {
  "most-requested": "/watany-v4/icons/most-requested.png",
  "latest": "/watany-v4/icons/latest.png",
  "important": "/watany-v4/icons/for-you.png",
  "tools": "/watany-assets/after-reference-icons/tools.png",
  "designs": "/watany-assets/after-reference-icons/tools.png",
  "for-you": "/watany-v4/icons/for-you.png",
  "login": "/watany-assets/icons/login.svg",
  "profile": "/watany-v4/icons/profile.png",
  "install": "/watany-v4/icons/install.png",
  "documents": "/watany-v4/icons/documents.png",
  "notifications": "/watany-v4/icons/notifications.png",
  "messages": "/watany-v4/icons/messages.png",
  "administration": "/watany-v4/icons/administration.png",
  "users": "/watany-v4/icons/users.png",
  "roles": "/watany-v4/icons/roles.png",
  "activity-log": "/watany-v4/icons/activity-log.png",
  "news": "/watany-v4/icons/news.png",
  "fake-fact": "/watany-v4/icons/fake-fact.png",
  "circulars": "/watany-v4/icons/circulars.png",
  "links": "/watany-assets/icons/links.svg",
  "marketplace": "/watany-v4/icons/marketplace.png",
  "jobs": "/watany-v4/icons/jobs.png",
  "ads": "/watany-v4/icons/ads.png",
  "calculator": "/watany-v4/icons/calculator.png",
  "tariff": "/watany-v4/icons/tariff.png",
  "salary": "/watany-v4/icons/salary.png",
  "transactions": "/watany-v4/icons/transactions.png",
  "forms": "/watany-v4/icons/forms.png",
  "schools": "/watany-v4/icons/schools.png",
  "network": "/watany-v4/icons/network.png",
  "taxi": "/watany-v4/icons/taxi.png",
  "voting": "/watany-v4/icons/voting.png",
  "faq": "/watany-v4/icons/faq.png",
  "laws": "/watany-v4/icons/laws.png",
  "procedures": "/watany-v4/icons/procedures.png",
  "world-cup": "/watany-v4/icons/world-cup.png",
  "community": "/watany-v4/icons/community.png",
  "voice": "/watany-v4/icons/voice.png",
  "deaths": "/watany-v4/icons/deaths.png",
  "health": "/watany-v4/icons/health.png",
  "ask-watany": "/watany-v4/icons/ask-watany.png"
} as const;

export type WatanyV4IconName = keyof typeof WATANY_V4_ICONS;

export const WATANY_V4_HOME_FEATURES = [
  { id: "most-requested", labelAr: "الأكثر طلباً", action: "feature", roleRestricted: false, icon: "most-requested" },
  { id: "latest", labelAr: "الأحدث", action: "ticker", roleRestricted: false, icon: "latest" },
  { id: "for-you", labelAr: "ممكن يهمك", action: "feature", roleRestricted: false, icon: "for-you" },
  { id: "login", labelAr: "الدخول", action: "login", roleRestricted: false, icon: "login" },
  { id: "profile", labelAr: "الملف", action: "feature", roleRestricted: false, icon: "profile" },
  { id: "install", labelAr: "تثبيت التطبيق", action: "feature", roleRestricted: false, icon: "install" },
  { id: "documents", labelAr: "مستنداتي", action: "forms", roleRestricted: false, icon: "documents" },
  { id: "notifications", labelAr: "الإشعارات", action: "feature", roleRestricted: false, icon: "notifications" },
  { id: "messages", labelAr: "الرسائل", action: "chat", roleRestricted: false, icon: "messages" },
  { id: "administration", labelAr: "الإدارة", action: "feature", roleRestricted: true, icon: "administration" },
  { id: "users", labelAr: "المستخدمون", action: "feature", roleRestricted: true, icon: "users" },
  { id: "roles", labelAr: "الأدوار", action: "feature", roleRestricted: true, icon: "roles" },
  { id: "activity-log", labelAr: "سجل النشاط", action: "feature", roleRestricted: true, icon: "activity-log" },
  { id: "news", labelAr: "الأخبار", action: "ticker", roleRestricted: false, icon: "news" },
  { id: "fake-fact", labelAr: "زائف / حقيقة", action: "feature", roleRestricted: false, icon: "fake-fact" },
  { id: "circulars", labelAr: "التعاميم", action: "listings", roleRestricted: false, icon: "circulars" },
  { id: "marketplace", labelAr: "السوق", action: "listings", roleRestricted: false, icon: "marketplace" },
  { id: "jobs", labelAr: "الوظائف", action: "listings", roleRestricted: false, icon: "jobs" },
  { id: "ads", labelAr: "الإعلانات", action: "listings", roleRestricted: false, icon: "ads" },
  { id: "salary", labelAr: "المعاش", action: "salary", roleRestricted: false, icon: "salary" },
  { id: "transactions", labelAr: "المعاملات", action: "feature", roleRestricted: false, icon: "transactions" },
  { id: "forms", labelAr: "النماذج", action: "forms", roleRestricted: false, icon: "forms" },
  { id: "schools", labelAr: "المدارس", action: "feature", roleRestricted: false, icon: "schools" },
  { id: "network", labelAr: "الشبكة", action: "feature", roleRestricted: false, icon: "network" },
  { id: "taxi", labelAr: "تاكسي", action: "feature", roleRestricted: false, icon: "taxi" },
  { id: "voting", labelAr: "التصويت", action: "feature", roleRestricted: false, icon: "voting" },
  { id: "faq", labelAr: "الأسئلة الشائعة", action: "feature", roleRestricted: false, icon: "faq" },
  { id: "laws", labelAr: "القوانين", action: "feature", roleRestricted: false, icon: "laws" },
  { id: "procedures", labelAr: "الإجراءات", action: "feature", roleRestricted: false, icon: "procedures" },
  { id: "world-cup", labelAr: "كأس العالم 2026", action: "feature", roleRestricted: false, icon: "world-cup" },
  { id: "community", labelAr: "نشاطات المجتمع", action: "feature", roleRestricted: false, icon: "community" },
  { id: "voice", labelAr: "صوت", action: "feature", roleRestricted: false, icon: "voice" },
  { id: "deaths", labelAr: "الوفيات", action: "listings", roleRestricted: false, icon: "deaths" },
  { id: "health", labelAr: "الصحة", action: "feature", roleRestricted: false, icon: "health" },
  { id: "ask-watany", labelAr: "اسأل وطني", action: "chat", roleRestricted: false, icon: "ask-watany" }
] as const;
