import type { WatanyV4CompatProps } from "./WatanyV4Glyph";
import { WatanyV4Glyph } from "./WatanyV4Glyph";

function WatanyV4Arrow({ direction, size = 24, title, className = "" }: WatanyV4CompatProps & { direction: "←" | "→" }) {
	return <span aria-hidden={title ? undefined : true} aria-label={title} title={title} className={className} style={{ fontSize: typeof size === "number" ? `${size}px` : size, lineHeight: 1 }}>{direction}</span>;
}

export type AddCircle24Regular = WatanyV4CompatProps;
export const AddCircle24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="add" />;
export type Alert24Regular = WatanyV4CompatProps;
export const Alert24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="warning" />;
export type AppsList24Regular = WatanyV4CompatProps;
export const AppsList24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Archive24Regular = WatanyV4CompatProps;
export const Archive24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="folder" />;
export type ArrowCircleRight24Regular = WatanyV4CompatProps;
export const ArrowCircleRight24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="back" />;
export type ArrowClockwise24Regular = WatanyV4CompatProps;
export const ArrowClockwise24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="calendar" />;
export type ArrowCounterclockwise24Regular = WatanyV4CompatProps;
export const ArrowCounterclockwise24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="calendar" />;
export type ArrowLeft24Regular = WatanyV4CompatProps;
export const ArrowLeft24Regular = (props: WatanyV4CompatProps) => <WatanyV4Arrow {...props} direction="←" />;
export type ArrowRight24Regular = WatanyV4CompatProps;
export const ArrowRight24Regular = (props: WatanyV4CompatProps) => <WatanyV4Arrow {...props} direction="→" />;
export type ArrowUpRight24Regular = WatanyV4CompatProps;
export const ArrowUpRight24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="back" />;
export type Bookmark24Regular = WatanyV4CompatProps;
export const Bookmark24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type BookmarkMultiple24Regular = WatanyV4CompatProps;
export const BookmarkMultiple24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type BookOpen24Regular = WatanyV4CompatProps;
export const BookOpen24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type BookRegular = WatanyV4CompatProps;
export const BookRegular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Brain24Regular = WatanyV4CompatProps;
export const Brain24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Briefcase24Regular = WatanyV4CompatProps;
export const Briefcase24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Broom24Regular = WatanyV4CompatProps;
export const Broom24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Building24Regular = WatanyV4CompatProps;
export const Building24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Calculator24Regular = WatanyV4CompatProps;
export const Calculator24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type CalculatorRegular = WatanyV4CompatProps;
export const CalculatorRegular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type CalendarCancel24Regular = WatanyV4CompatProps;
export const CalendarCancel24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="calendar" />;
export type CalendarCheckmark24Regular = WatanyV4CompatProps;
export const CalendarCheckmark24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="check" />;
export type CalendarLtr24Regular = WatanyV4CompatProps;
export const CalendarLtr24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="calendar" />;
export type Chat24Regular = WatanyV4CompatProps;
export const Chat24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="chat" />;
export type ChatMultiple24Regular = WatanyV4CompatProps;
export const ChatMultiple24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="chat" />;
export type CheckmarkCircle24Filled = WatanyV4CompatProps;
export const CheckmarkCircle24Filled = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="check" />;
export type CheckmarkCircle24Regular = WatanyV4CompatProps;
export const CheckmarkCircle24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="check" />;
export type ChevronDown24Regular = WatanyV4CompatProps;
export const ChevronDown24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type ChevronLeft24Regular = WatanyV4CompatProps;
export const ChevronLeft24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="back" />;
export type Clipboard24Regular = WatanyV4CompatProps;
export const Clipboard24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" asset="documents" />;
export type ClipboardCheckmark24Regular = WatanyV4CompatProps;
export const ClipboardCheckmark24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="check" />;
export type Clock24Regular = WatanyV4CompatProps;
export const Clock24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="calendar" />;
export type DataBarVertical24Regular = WatanyV4CompatProps;
export const DataBarVertical24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Desktop24Regular = WatanyV4CompatProps;
export const Desktop24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Dismiss24Regular = WatanyV4CompatProps;
export const Dismiss24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="close" />;
export type DocumentRegular = WatanyV4CompatProps;
export const DocumentRegular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" asset="documents" />;
export type DocumentText24Regular = WatanyV4CompatProps;
export const DocumentText24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" asset="documents" />;
export type Drop24Regular = WatanyV4CompatProps;
export const Drop24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Eye24Regular = WatanyV4CompatProps;
export const Eye24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Filter24Regular = WatanyV4CompatProps;
export const Filter24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="filter" />;
export type Flash24Regular = WatanyV4CompatProps;
export const Flash24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Folder24Regular = WatanyV4CompatProps;
export const Folder24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="folder" />;
export type Food24Regular = WatanyV4CompatProps;
export const Food24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type FullScreenMaximize24Regular = WatanyV4CompatProps;
export const FullScreenMaximize24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Globe24Regular = WatanyV4CompatProps;
export const Globe24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="globe" />;
export type Heart24Regular = WatanyV4CompatProps;
export const Heart24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type HeartPulse24Regular = WatanyV4CompatProps;
export const HeartPulse24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Home24Regular = WatanyV4CompatProps;
export const Home24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="home" />;
export type Hourglass24Regular = WatanyV4CompatProps;
export const Hourglass24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="calendar" />;
export type Image24Regular = WatanyV4CompatProps;
export const Image24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type LightbulbFilament24Regular = WatanyV4CompatProps;
export const LightbulbFilament24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Link24Regular = WatanyV4CompatProps;
export const Link24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Location24Regular = WatanyV4CompatProps;
export const Location24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Mail24Regular = WatanyV4CompatProps;
export const Mail24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Map24Regular = WatanyV4CompatProps;
export const Map24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Medal24Regular = WatanyV4CompatProps;
export const Medal24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Megaphone24Regular = WatanyV4CompatProps;
export const Megaphone24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Mic24Regular = WatanyV4CompatProps;
export const Mic24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="mic" />;
export type MoreHorizontal24Regular = WatanyV4CompatProps;
export const MoreHorizontal24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Navigation24Regular = WatanyV4CompatProps;
export const Navigation24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="menu" />;
export type News24Regular = WatanyV4CompatProps;
export const News24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" asset="news" />;
export type NumberSymbol24Regular = WatanyV4CompatProps;
export const NumberSymbol24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Open24Regular = WatanyV4CompatProps;
export const Open24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type People24Regular = WatanyV4CompatProps;
export const People24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="people" asset="users" />;
export type Person24Regular = WatanyV4CompatProps;
export const Person24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="user" />;
export type PersonAdd24Regular = WatanyV4CompatProps;
export const PersonAdd24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="user" />;
export type PersonHeart24Regular = WatanyV4CompatProps;
export const PersonHeart24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="user" />;
export type Phone24Filled = WatanyV4CompatProps;
export const Phone24Filled = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Phone24Regular = WatanyV4CompatProps;
export const Phone24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Poll24Regular = WatanyV4CompatProps;
export const Poll24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type QuestionCircle24Regular = WatanyV4CompatProps;
export const QuestionCircle24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Rocket24Regular = WatanyV4CompatProps;
export const Rocket24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Save24Regular = WatanyV4CompatProps;
export const Save24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Search24Regular = WatanyV4CompatProps;
export const Search24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="search" />;
export type Send24Regular = WatanyV4CompatProps;
export const Send24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Settings24Regular = WatanyV4CompatProps;
export const Settings24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Share24Regular = WatanyV4CompatProps;
export const Share24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Shield24Regular = WatanyV4CompatProps;
export const Shield24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type ShieldCheckmark24Filled = WatanyV4CompatProps;
export const ShieldCheckmark24Filled = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="check" />;
export type ShieldCheckmark24Regular = WatanyV4CompatProps;
export const ShieldCheckmark24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="check" />;
export type ShieldError24Regular = WatanyV4CompatProps;
export const ShieldError24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="warning" />;
export type ShieldRegular = WatanyV4CompatProps;
export const ShieldRegular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type ShoppingBag24Regular = WatanyV4CompatProps;
export const ShoppingBag24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type SignOut24Regular = WatanyV4CompatProps;
export const SignOut24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Sparkle24Regular = WatanyV4CompatProps;
export const Sparkle24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Speaker224Regular = WatanyV4CompatProps;
export const Speaker224Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="volume" />;
export type Star24Filled = WatanyV4CompatProps;
export const Star24Filled = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Star24Regular = WatanyV4CompatProps;
export const Star24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Stop24Regular = WatanyV4CompatProps;
export const Stop24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="stop" />;
export type Target24Regular = WatanyV4CompatProps;
export const Target24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Temperature24Regular = WatanyV4CompatProps;
export const Temperature24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type TextBulletList24Regular = WatanyV4CompatProps;
export const TextBulletList24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" asset="documents" />;
export type TextFont24Regular = WatanyV4CompatProps;
export const TextFont24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Trophy24Regular = WatanyV4CompatProps;
export const Trophy24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="trophy" />;
export type VehicleCab24Filled = WatanyV4CompatProps;
export const VehicleCab24Filled = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="document" />;
export type Video24Regular = WatanyV4CompatProps;
export const Video24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="video" />;
export type Warning24Regular = WatanyV4CompatProps;
export const Warning24Regular = (props: WatanyV4CompatProps) => <WatanyV4Glyph {...props} semantic="warning" />;
