-- Auto-generated by tools/implement_recommendations.py
-- Purpose: Option A tracking ("عرض حالة") for personal requests/issues/follow-ups.
-- Defaults: minimal, safe fields.

CREATE TABLE IF NOT EXISTS cases (
  case_id UUID PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- identify user even if anonymous (session-based)
  user_id UUID NULL,
  session_id TEXT NULL,

  -- status lifecycle
  status TEXT NOT NULL DEFAULT 'open',   -- open | pending | closed
  priority TEXT NOT NULL DEFAULT 'normal', -- low|normal|high

  category TEXT NULL,     -- salary|rights|service|other
  summary TEXT NOT NULL,  -- short human-readable
  details TEXT NULL,      -- optional longer description

  last_action TEXT NULL,  -- last system note
  assigned_to TEXT NULL   -- later: staff username/id
);

CREATE INDEX IF NOT EXISTS idx_cases_created_at ON cases(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(status);
CREATE INDEX IF NOT EXISTS idx_cases_session ON cases(session_id);
CREATE INDEX IF NOT EXISTS idx_cases_user ON cases(user_id);

-- update trigger for updated_at (optional; safe if your DB supports it)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'cases_set_updated_at'
  ) THEN
    CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $f$
    BEGIN
      NEW.updated_at = now();
      RETURN NEW;
    END;
    $f$ LANGUAGE plpgsql;

    CREATE TRIGGER cases_set_updated_at
    BEFORE UPDATE ON cases
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
  END IF;
END$$;
