/* ── Job Search Feature – Seed data ──────────────────── */
import type {
  JobCategory,
  Employer,
  JobPosting,
  JobApplicationRecord,
  SavedJob,
} from "./types.js";

/* ── Categories ──────────────────────────────────────── */

export const SEED_CATEGORIES: JobCategory[] = [
  { id: 1,  name_ar: "الأمن والحراسة",       name_en: "Security & Protection",     icon: "ph-fill ph-shield-checkered",   description_ar: "وظائف في مجال الأمن والحماية" },
  { id: 2,  name_ar: "النقل والسياقة",        name_en: "Transportation & Driving",   icon: "ph-fill ph-truck",              description_ar: "وظائف سائقين ونقل" },
  { id: 3,  name_ar: "الصيانة والإصلاح",      name_en: "Maintenance & Repair",       icon: "ph-fill ph-wrench",             description_ar: "وظائف الصيانة الفنية" },
  { id: 4,  name_ar: "الإدارة والمكتب",       name_en: "Administration & Office",    icon: "ph-fill ph-briefcase",          description_ar: "وظائف إدارية ومكتبية" },
  { id: 5,  name_ar: "التكنولوجيا",           name_en: "Technology & IT",            icon: "ph-fill ph-laptop",             description_ar: "وظائف تقنية وتكنولوجيا المعلومات" },
  { id: 6,  name_ar: "التعليم والتدريب",      name_en: "Education & Training",       icon: "ph-fill ph-graduation-cap",     description_ar: "وظائف تعليمية وتدريبية" },
  { id: 7,  name_ar: "الصحة والطب",           name_en: "Healthcare",                 icon: "ph-fill ph-hospital",           description_ar: "وظائف في القطاع الصحي" },
  { id: 8,  name_ar: "البناء والمقاولات",     name_en: "Construction",               icon: "ph-fill ph-hard-hat",           description_ar: "وظائف في مجال البناء" },
  { id: 9,  name_ar: "الضيافة والسياحة",      name_en: "Hospitality & Tourism",      icon: "ph-fill ph-building",           description_ar: "وظائف الفنادق والسياحة" },
  { id: 10, name_ar: "المبيعات والتسويق",     name_en: "Sales & Marketing",          icon: "ph-fill ph-chart-line",         description_ar: "وظائف المبيعات والترويج" },
];

/* ── Employers ───────────────────────────────────────── */

export const SEED_EMPLOYERS: Employer[] = [
  {
    id: "emp_001",
    company_name: "الشركة اللبنانية للحراسة والأمن",
    company_name_en: "Lebanese Security Services",
    industry: "أمن",
    company_size: "51-200",
    email: "hr@lss-lb.com",
    phone: "+961-1-234567",
    city: "بيروت",
    description_ar: "شركة رائدة في خدمات الأمن والحراسة، تفضّل المتقاعدين العسكريين",
    verified: true,
    veteran_friendly: true,
  },
  {
    id: "emp_002",
    company_name: "مكتب خدمات المجتمع",
    company_name_en: "Community Services Office",
    industry: "خدمات اجتماعية",
    company_size: "11-50",
    email: "jobs@cso-lb.org",
    phone: "+961-1-345678",
    city: "طرابلس",
    description_ar: "منظمة غير ربحية لدعم المحاربين القدامى وعائلاتهم",
    verified: true,
    veteran_friendly: true,
  },
  {
    id: "emp_003",
    company_name: "شركة النقل والتوزيع",
    company_name_en: "Transport & Distribution Co.",
    industry: "نقل",
    company_size: "11-50",
    email: "hr@transport-lb.com",
    city: "صيدا",
    description_ar: "شركة نقل وتوصيل ولوجستيات",
    verified: true,
    veteran_friendly: false,
  },
  {
    id: "emp_004",
    company_name: "المستشفى العسكري",
    company_name_en: "Military Hospital",
    industry: "صحة",
    company_size: "201-500",
    email: "hr@milhosp.gov.lb",
    city: "بيروت",
    description_ar: "المستشفى العسكري المركزي",
    verified: true,
    veteran_friendly: true,
  },
  {
    id: "emp_005",
    company_name: "تكنولوجيا الشرق",
    company_name_en: "EastTech Solutions",
    industry: "تكنولوجيا",
    company_size: "11-50",
    email: "careers@easttech.lb",
    city: "بيروت",
    description_ar: "شركة تقنية متخصصة في الحلول الأمنية الرقمية",
    verified: true,
    veteran_friendly: true,
  },
];

/* ── Job Postings ────────────────────────────────────── */

export const SEED_JOBS: JobPosting[] = [
  {
    id: "job_v2_001",
    employer_id: "emp_001",
    category_id: 1,
    title_ar: "مسؤول أمن وحماية — فترة ليلية",
    title_en: "Night Shift Security Officer",
    description_ar: "المطلوب مسؤول أمن لفترة ليلية. يُفضَّل ذوو خبرة عسكرية. المهام: مراقبة كاميرات، تسيير دوريات، كتابة تقارير الحوادث.",
    requirements_ar: "خبرة ٣ سنوات في الأمن أو خدمة عسكرية سابقة",
    experience_years: 3,
    education_level: "high_school",
    job_type: "full_time",
    employment_type: "permanent",
    salary_min: 800,
    salary_max: 1200,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    benefits: ["تأمين صحي", "إجازة سنوية مدفوعة", "بدل نقل"],
    location_city: "بيروت",
    location_area: "الحمرا",
    remote_work: false,
    hybrid_work: false,
    skills_required: ["مراقبة كاميرات", "كتابة تقارير", "إدارة أمنية"],
    languages_required: ["العربية"],
    veteran_only: false,
    veteran_preferred: true,
    military_rank_suitable: ["رقيب", "رقيب أول", "مساعد"],
    application_deadline: "2026-04-01",
    status: "active",
    featured: true,
    urgent: false,
    views_count: 145,
    applications_count: 12,
    published_at: "2026-02-15",
    created_at: "2026-02-14",
  },
  {
    id: "job_v2_002",
    employer_id: "emp_002",
    category_id: 4,
    title_ar: "مسؤول متابعة قضايا المتقاعدين",
    title_en: "Veterans Case Follow-up Officer",
    description_ar: "متابعة ملفات المتقاعدين العسكريين وتقديم الإرشاد حول الحقوق والاستحقاقات. العمل مع فرق  المجتمعي.",
    requirements_ar: "شهادة جامعية أو خبرة إدارية. يُفضَّل خلفية عسكرية.",
    experience_years: 2,
    education_level: "bachelor",
    job_type: "full_time",
    salary_min: 600,
    salary_max: 900,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    benefits: ["إجازة مدفوعة", "تدريب مستمر"],
    location_city: "طرابلس",
    remote_work: false,
    hybrid_work: true,
    skills_required: ["متابعة ملفات", "تواصل", "إرشاد"],
    languages_required: ["العربية", "الإنكليزية"],
    veteran_only: false,
    veteran_preferred: true,
    application_deadline: "2026-03-20",
    status: "active",
    featured: false,
    urgent: false,
    views_count: 87,
    applications_count: 6,
    published_at: "2026-02-18",
    created_at: "2026-02-17",
  },
  {
    id: "job_v2_003",
    employer_id: "emp_003",
    category_id: 2,
    title_ar: "سائق شاحنة توزيع — رخصة ثالثة",
    title_en: "Distribution Truck Driver",
    description_ar: "مطلوب سائق شاحنة لتوزيع البضائع في المنطقة الجنوبية. رخصة ثالثة إلزامية.",
    requirements_ar: "رخصة سوق فئة ثالثة + خبرة سنتين",
    experience_years: 2,
    education_level: "high_school",
    job_type: "full_time",
    salary_min: 500,
    salary_max: 700,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    benefits: ["بدل بنزين"],
    location_city: "صيدا",
    remote_work: false,
    hybrid_work: false,
    skills_required: ["سياقة شاحنات", "صيانة أولية"],
    languages_required: ["العربية"],
    veteran_only: false,
    veteran_preferred: false,
    application_deadline: "2026-03-15",
    status: "active",
    featured: false,
    urgent: true,
    views_count: 210,
    applications_count: 18,
    published_at: "2026-02-10",
    created_at: "2026-02-09",
  },
  {
    id: "job_v2_004",
    employer_id: "emp_004",
    category_id: 7,
    title_ar: "ممرّض/ممرّضة — قسم الطوارئ",
    title_en: "ER Nurse",
    description_ar: "مطلوب ممرّض أو ممرّضة للعمل في قسم الطوارئ بالمستشفى العسكري. خبرة في الإسعافات الأولية ضرورية.",
    requirements_ar: "إجازة في التمريض + خبرة سنتين في الطوارئ",
    experience_years: 2,
    education_level: "bachelor",
    job_type: "full_time",
    salary_min: 700,
    salary_max: 1000,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    benefits: ["تأمين صحي شامل", "إجازة سنوية", "بدل نوبات ليلية"],
    location_city: "بيروت",
    remote_work: false,
    hybrid_work: false,
    skills_required: ["تمريض طوارئ", "إسعافات أولية", "إبر وريدية"],
    languages_required: ["العربية", "الإنكليزية"],
    veteran_only: false,
    veteran_preferred: true,
    status: "active",
    featured: true,
    urgent: true,
    views_count: 320,
    applications_count: 25,
    published_at: "2026-02-20",
    created_at: "2026-02-19",
  },
  {
    id: "job_v2_005",
    employer_id: "emp_005",
    category_id: 5,
    title_ar: "مسؤول أمن سيبراني",
    title_en: "Cybersecurity Analyst",
    description_ar: "تحليل التهديدات الرقمية ومراقبة الأنظمة الأمنية. يُشترط خبرة في أنظمة SIEM وتحليل الحوادث.",
    requirements_ar: "شهادة في هندسة الحاسوب أو أمن المعلومات",
    experience_years: 3,
    education_level: "bachelor",
    job_type: "full_time",
    salary_min: 1200,
    salary_max: 2000,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    benefits: ["عمل مرن", "تأمين صحي", "تدريب"],
    location_city: "بيروت",
    remote_work: false,
    hybrid_work: true,
    skills_required: ["SIEM", "تحليل تهديدات", "شبكات", "Linux"],
    languages_required: ["العربية", "الإنكليزية"],
    veteran_only: false,
    veteran_preferred: true,
    military_rank_suitable: ["ملازم", "نقيب"],
    application_deadline: "2026-04-15",
    status: "active",
    featured: true,
    urgent: false,
    views_count: 189,
    applications_count: 9,
    published_at: "2026-02-22",
    created_at: "2026-02-21",
  },
  {
    id: "job_v2_006",
    employer_id: "emp_001",
    category_id: 1,
    title_ar: "مدرّب أمن وسلامة",
    title_en: "Safety & Security Trainer",
    description_ar: "تدريب الموظفين الجدد على إجراءات الأمن والسلامة. يُفضَّل ضبّاط متقاعدون.",
    requirements_ar: "خبرة ١٠ سنوات في مجال الأمن أو الجيش",
    experience_years: 10,
    education_level: "diploma",
    job_type: "part_time",
    salary_min: 400,
    salary_max: 600,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    benefits: ["ساعات مرنة"],
    location_city: "بيروت",
    remote_work: false,
    hybrid_work: false,
    skills_required: ["تدريب", "إدارة أمنية", "كتابة مناهج"],
    languages_required: ["العربية"],
    veteran_only: true,
    veteran_preferred: true,
    status: "active",
    featured: false,
    urgent: false,
    views_count: 65,
    applications_count: 4,
    published_at: "2026-02-25",
    created_at: "2026-02-24",
  },
  {
    id: "job_v2_007",
    employer_id: "emp_002",
    category_id: 6,
    title_ar: "مدرّب رياضي — نادي رياضي",
    title_en: "Fitness Trainer",
    description_ar: "مطلوب مدرّب رياضي لتدريب الشباب في نادٍ مجتمعي. يُفضَّل ذوو خبرة عسكرية في اللياقة البدنية.",
    requirements_ar: "خبرة في التدريب الرياضي العسكري أو المدني",
    experience_years: 3,
    education_level: "diploma",
    job_type: "part_time",
    salary_min: 300,
    salary_max: 500,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    location_city: "طرابلس",
    remote_work: false,
    hybrid_work: false,
    skills_required: ["لياقة بدنية", "تدريب", "إسعافات أولية"],
    languages_required: ["العربية"],
    veteran_only: false,
    veteran_preferred: true,
    status: "active",
    featured: false,
    urgent: false,
    views_count: 120,
    applications_count: 15,
    published_at: "2026-02-28",
    created_at: "2026-02-27",
  },
  {
    id: "job_v2_008",
    employer_id: "emp_003",
    category_id: 3,
    title_ar: "فنّي صيانة كهربائية",
    title_en: "Electrical Maintenance Technician",
    description_ar: "صيانة الأنظمة الكهربائية في المنشآت الصناعية. العمل بنظام ورديات.",
    requirements_ar: "شهادة فنية في الكهرباء + خبرة ٣ سنوات",
    experience_years: 3,
    education_level: "diploma",
    job_type: "full_time",
    salary_min: 600,
    salary_max: 800,
    salary_currency: "USD",
    salary_period: "monthly",
    show_salary: true,
    benefits: ["تأمين صحي", "بدل نقل"],
    location_city: "جونية",
    remote_work: false,
    hybrid_work: false,
    skills_required: ["صيانة كهربائية", "PLC", "أنظمة تحكم"],
    languages_required: ["العربية"],
    veteran_only: false,
    veteran_preferred: false,
    status: "active",
    featured: false,
    urgent: false,
    views_count: 95,
    applications_count: 8,
    published_at: "2026-03-01",
    created_at: "2026-02-28",
  },
];

/* ── Mutable stores (in-memory) ──────────────────────── */

export const applications: JobApplicationRecord[] = [];
export const savedJobs: SavedJob[] = [];
