import { useEffect, useState } from "react";
import { adminFetch } from "../lib/api";
import { AdminErrorState, AdminLoadingState, AdminPageSection, AdminStatusBadge } from "../components/admin/AdminPrimitives";

type Provider = { id: string; name: string; status: string; accountId: string | null };
type Placement = { id: string; name: string; routePattern: string; format: string; enabled: boolean; priority: number; startAt: string | null; endAt: string | null; creative: string | null };
type AdsState = { provider: Provider; placements: Placement[]; adsTxt: string };
const emptyDraft = { name: "", routePattern: "/", format: "display", priority: 1, startAt: "", endAt: "", creative: "", enabled: true };

export default function AdminAdsPage() {
  const [state, setState] = useState<AdsState | null>(null);
  const [draft, setDraft] = useState(emptyDraft);
  const [accountId, setAccountId] = useState("");
  const [editing, setEditing] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(""); try { const response = await adminFetch("/api/admin/ads/status"); setState(await response.json()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load Ads authority."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const saveProvider = async () => { if (!state) return; await adminFetch("/api/admin/ads/provider", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: state.provider.id, name: state.provider.name, accountId }) }); await load(); };
  const savePlacement = async () => { const payload = { ...draft, priority: Number(draft.priority), startAt: draft.startAt || null, endAt: draft.endAt || null, creative: draft.creative || null }; await adminFetch(editing ? `/api/admin/ads/placements/${editing}` : "/api/admin/ads/placements", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setDraft(emptyDraft); setEditing(null); await load(); };
  const togglePlacement = async (placement: Placement) => { await adminFetch(`/api/admin/ads/placements/${placement.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...placement, enabled: !placement.enabled }) }); await load(); };
  const editPlacement = (placement: Placement) => { setEditing(placement.id); setDraft({ name: placement.name, routePattern: placement.routePattern, format: placement.format, priority: placement.priority, startAt: placement.startAt || "", endAt: placement.endAt || "", creative: placement.creative || "", enabled: placement.enabled }); };
  if (loading) return <AdminPageSection title="إدارة الإعلانات" description="إعدادات الإعلانات والمعاينة الآمنة مملوكة لـ Gateway."><AdminLoadingState /></AdminPageSection>;
  if (error || !state) return <AdminPageSection title="إدارة الإعلانات" description="إعدادات الإعلانات والمعاينة الآمنة مملوكة لـ Gateway."><AdminErrorState message={error || "إدارة الإعلانات غير متاحة."} /></AdminPageSection>;
  return <div className="ops-page-stack">
    <AdminPageSection title="إعدادات المزوّد" description="هوية المزوّد وإعدادات العرض مملوكة لـ Gateway."><div className="ops-form-grid"><label><span>المزوّد</span><input value={state.provider.name} readOnly /></label><label><span>معرّف حساب المزوّد</span><input value={accountId || state.provider.accountId || ""} onChange={(event) => setAccountId(event.target.value)} /></label><label><span>حالة الإعداد</span><AdminStatusBadge status={state.provider.status} /></label><div className="ops-form-actions"><button className="accent" type="button" onClick={() => void saveProvider()}>حفظ التغييرات</button></div></div><div className="ops-code-row"><strong>ads.txt</strong><code>{state.adsTxt}</code></div></AdminPageSection>
    <AdminPageSection title={editing ? "تعديل الموضع الإعلاني" : "إنشاء موضع إعلاني"} description="استهداف محدد للمسار ومحتوى احتياطي آمن."><div className="ops-form-grid"><label><span>الاسم</span><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label><span>المسار المستهدف</span><input value={draft.routePattern} onChange={(event) => setDraft({ ...draft, routePattern: event.target.value })} /></label><label><span>التنسيق</span><select value={draft.format} onChange={(event) => setDraft({ ...draft, format: event.target.value })}><option value="display">عرض</option><option value="native">أصلي</option><option value="house">داخلي</option></select></label><label><span>الأولوية</span><input type="number" value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: Number(event.target.value) })} /></label><label><span>البداية</span><input type="datetime-local" value={draft.startAt} onChange={(event) => setDraft({ ...draft, startAt: event.target.value })} /></label><label><span>النهاية</span><input type="datetime-local" value={draft.endAt} onChange={(event) => setDraft({ ...draft, endAt: event.target.value })} /></label><label className="ops-field-wide"><span>المحتوى الاحتياطي</span><input value={draft.creative} onChange={(event) => setDraft({ ...draft, creative: event.target.value })} /></label></div><div className="ops-form-actions"><button className="accent" type="button" onClick={() => void savePlacement()}>{editing ? "تحديث الموضع" : "إنشاء الموضع"}</button>{editing && <button className="ghost" type="button" onClick={() => { setEditing(null); setDraft(emptyDraft); }}>إلغاء</button>}</div></AdminPageSection>
    <AdminPageSection title="المواضع الإعلانية" description="المواضع الحالية وحالة عرضها على المسارات."><div className="admin-data-table-wrap"><table className="admin-data-table"><thead><tr><th>الاسم</th><th>المسار</th><th>التنسيق</th><th>الأولوية</th><th>الحالة</th><th>الجدولة</th><th>الإجراءات</th></tr></thead><tbody>{state.placements.map((placement) => <tr key={placement.id}><td>{placement.name}</td><td dir="ltr">{placement.routePattern}</td><td>{placement.format}</td><td>{placement.priority}</td><td><AdminStatusBadge status={placement.enabled ? "Enabled" : "Disabled"} /></td><td>{placement.startAt || placement.endAt ? `${placement.startAt || "-"} إلى ${placement.endAt || "-"}` : "دائماً"}</td><td><div className="ops-row-actions"><button className="ghost sm" type="button" onClick={() => editPlacement(placement)}>تعديل</button><button className="ghost sm" type="button" onClick={() => void togglePlacement(placement)}>{placement.enabled ? "تعطيل" : "تفعيل"}</button><button className="ghost sm" type="button" onClick={() => void adminFetch(`/api/admin/ads/placements/${placement.id}/preview`).then((response) => response.json()).then((preview) => window.alert(JSON.stringify(preview.preview)))}>معاينة</button></div></td></tr>)}</tbody></table></div></AdminPageSection>
  </div>;
}
