import { useEffect, useState } from "react";
import { adminFetch } from "../lib/api";
import { AdminErrorState, AdminLoadingState, AdminNotice, AdminPageSection } from "../components/admin/AdminPrimitives";

type Contact = { name: string; first_name?: string; last_name?: string; email_id?: string; status?: string };

export default function AdminCrmPage() {
  const [contacts, setContacts] = useState<Contact[]>([]); const [namespace, setNamespace] = useState("PHASE8"); const [selected, setSelected] = useState<Contact | null>(null); const [lastName, setLastName] = useState(""); const [status, setStatus] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(""); try { const response = await adminFetch("/api/admin-authority/crm/contacts?limit=50"); const payload = await response.json(); setContacts(payload.items || []); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر تحميل جهات اتصال CRM."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const createCanary = async () => { setMessage(""); setError(""); try { const response = await adminFetch("/api/admin-authority/crm/contacts/canary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ namespace }) }); const payload = await response.json(); setMessage(payload.synthetic ? `تم إنشاء المؤشر الاصطناعي ${namespace}: ${payload.item.name}` : "لم يكتمل إنشاء المؤشر."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر إنشاء المؤشر الاصطناعي."); } };
  const updateContact = async () => {
    if (!selected) return;
    try { setError(""); const response = await adminFetch(`/api/admin-authority/crm/contacts/${encodeURIComponent(selected.name)}`, { method: "PATCH", headers: { "Content-Type": "application/json", "x-apex-canary-run-id": "web-admin" }, body: JSON.stringify({ last_name: lastName, status }) }); const payload = await response.json(); setMessage(payload.synthetic ? `تم تحديث المؤشر الاصطناعي ${selected.name} وتسجيل حدث التدقيق.` : "لم يكتمل التحديث."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر تحديث المؤشر الاصطناعي."); }
  };
  const deleteContact = async () => {
    if (!selected || !window.confirm(`Delete synthetic canary ${selected.name}?`)) return;
    try { setError(""); const response = await adminFetch(`/api/admin-authority/crm/contacts/${encodeURIComponent(selected.name)}`, { method: "DELETE", headers: { "x-apex-canary-run-id": "web-admin" } }); const payload = await response.json(); setMessage(payload.synthetic ? `تم حذف المؤشر الاصطناعي ${selected.name} وتسجيل حدث التدقيق.` : "لم يكتمل الحذف."); setSelected(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر حذف المؤشر الاصطناعي."); }
  };
  if (loading) return <AdminPageSection title="CRM" description="جهات اتصال الإدارة العليا مملوكة لجهة CRM في Gateway."><AdminLoadingState /></AdminPageSection>;
  if (error) return <AdminPageSection title="CRM" description="جهات اتصال الإدارة العليا مملوكة لجهة CRM في Gateway."><AdminErrorState message={error} /></AdminPageSection>;
  return <><AdminPageSection title="CRM" description="اعرض جهات الاتصال وأدر المؤشرات الاصطناعية فقط. لا يمكن تعديل جهات الإنتاج أو حذفها هنا."><AdminNotice tone="info">جهة التكامل: Gateway CRM / ERPNext. جهات الإنتاج للقراءة فقط؛ وتقتصر أدوات التعديل على المؤشرات الاصطناعية مع تسجيل التدقيق.</AdminNotice><div className="admin-toolbar"><select aria-label="نطاق المؤشر" value={namespace} onChange={(event) => setNamespace(event.target.value)}><option value="PHASE8">مؤشر المرحلة 8</option><option value="PHASE7">مؤشر المرحلة 7</option></select><button className="accent" type="button" onClick={() => void createCanary()}>إنشاء مؤشر اصطناعي</button>{message ? <output>{message}</output> : null}</div></AdminPageSection><AdminPageSection title="جهات الاتصال" description="اختر مؤشراً لفحص أدوات التعديل والتنظيف المحدودة."><div className="table-wrap"><table><thead><tr><th>الاسم</th><th>الاسم الأول</th><th>البريد الإلكتروني</th><th>الحالة</th><th>النطاق</th></tr></thead><tbody>{contacts.map((contact) => <tr key={contact.name} onClick={() => { setSelected(contact); setLastName(contact.last_name || ""); setStatus(contact.status || ""); }}><td>{contact.name}</td><td>{contact.first_name || ""}</td><td>{contact.email_id || ""}</td><td>{contact.status || ""}</td><td>{contact.first_name?.startsWith("APEX-P") ? "مؤشر اصطناعي" : "للقراءة فقط"}</td></tr>)}</tbody></table></div></AdminPageSection>{selected ? <AdminPageSection title={`ضوابط المؤشر: ${selected.name}`} description="يرفض Gateway التعديلات على جهات الاتصال غير الاصطناعية ويسجل التعديلات المقبولة في سجل تدقيق الإدارة."><div className="admin-toolbar"><input aria-label="اسم المؤشر الأخير" value={lastName} onChange={(event) => setLastName(event.target.value)} placeholder="اسم العائلة" /><input aria-label="حالة المؤشر" value={status} onChange={(event) => setStatus(event.target.value)} placeholder="الحالة" /><button className="accent" type="button" onClick={() => void updateContact()}>تحديث المؤشر</button><button className="ghost" type="button" onClick={() => void deleteContact()}>حذف المؤشر</button></div></AdminPageSection> : null}</>;
}
