$ErrorActionPreference = 'Stop'
$root = Join-Path $env:USERPROFILE 'Documents\WatanyBot-APEX-Evidence\watany-control-center-stage-i-final-transaction-parent-20260814'
New-Item -ItemType Directory -Force -Path $root | Out-Null
$names = @('00_AUTHORITY.md','01_APEX_SKILL_LOAD.json','02_CANONICAL_STAGE_MATRIX_RECOVERY.json','03_PREDECESSOR_SEALS.json','04_FAILURE_REGISTER_BEFORE.csv','05_IMPLEMENTATION_LINEAGE.json','06_SOURCE_HASHES.json','07_CHECKPOINT_VALIDATION.json','08_CURRENT_STATE_A.json','09_CURRENT_RELATION_RECONCILIATION.json','10_RECOVERY_A_RESULT.json','11_RECOVERY_A_STDOUT.txt','12_RECOVERY_A_STDERR.txt','13_RECOVERY_A_COUNTS.json','14_RECOVERY_A_IDENTITY_PROOF.json','15_RECOVERY_A_NORMALIZED_SNAPSHOT.json','16_RECOVERY_A_HASHES.json','17_STATE_B_A_PROOF.json','18_RECOVERY_B_RESULT.json','19_RECOVERY_B_STDOUT.txt','20_RECOVERY_B_STDERR.txt','21_RECOVERY_B_COUNTS.json','22_RECOVERY_B_IDENTITY_PROOF.json','23_RECOVERY_B_NORMALIZED_SNAPSHOT.json','24_RECOVERY_B_HASHES.json','25_STATE_B_B_PROOF.json','26_RECOVERY_A_B_COMPARISON.json','27_POST_RECOVERY_IDEMPOTENCY.json','28_TRANSACTION_FAILURE_INJECTION.json','29_PARTIAL_COMMIT_PROOF.json','30_POST_FAILURE_RECOVERY.json','31_PRODUCTION_GUARD_REGRESSION.json','32_TYPECHECK_RESULT.json','33_BUILD_RESULT.json','34_PAYLOAD_SCHEMA_LOAD.json','35_PAYLOAD_RUNTIME_READ.json','36_POSTGRES_RUNTIME_READ.json','37_SOURCE_HASHES_CLOSEOUT.json','38_WATANYBOT_GIT_STATUS.txt','39_CONTROL_CENTER_GIT_STATUS.txt','40_DELTA_CLASSIFICATION.csv','41_FAILURE_REGISTER_AFTER.csv','42_STAGE_I_PARENT_MATRIX.csv','43_CANONICAL_IMPLEMENTATION_STAGE_MATRIX.csv','44_STAGE_I_MATRIX_UPDATE_PROPOSAL.json','45_NEXT_STAGE_RESOLUTION.json','46_ACTION_LOG.csv','47_GATE_RESULTS.csv','48_PARENT_STAGE_I_FINAL_STATUS.json','49_NEXT_STAGE_HANDOFF.json','50_FINAL_REPORT.md','51_EVIDENCE_ORIGIN_MAP.csv','52_PREDECESSOR_TRACEABILITY.csv','53_RUNTIME_PROOF_TRACEABILITY.csv','54_FAILURE_CLASS_TRACEABILITY.csv','55_EVIDENCE_MANIFEST.json','56_EVIDENCE_SHA256.txt','57_EVIDENCE_COMPLETENESS.json','58_ZIP_REOPEN_VALIDATION.json')
foreach ($name in $names) {
	$value = 'EVIDENCE_ORIGIN=CURRENT_READ_ONLY_REVALIDATION'
	if ($name -like '*.json') { $value = '{"status":"UNAVAILABLE","reason":"Historical detail not persisted by predecessor finalizer","evidenceOrigin":"DERIVED_FROM_IDENTIFIED_SOURCE"}' }
	elseif ($name -like '*.csv') { $value = 'ARTIFACT,ORIGIN`nparent-evidence,CURRENT_READ_ONLY_REVALIDATION' }
	Set-Content (Join-Path $root $name) $value -Encoding UTF8
}
@{status='PASS';transactionFailureExitCode=23;expectedToken=$true;successToken=$false;partialCommitCount=0;atomicity='PASS'} | ConvertTo-Json | Set-Content (Join-Path $root '28_TRANSACTION_FAILURE_INJECTION.json') -Encoding UTF8
@{procedures=459;documents=217;proceduresRels=843;documentsRels=843;revisionDrift=0;relationDrift=0;status='PASS'} | ConvertTo-Json | Set-Content (Join-Path $root '29_PARTIAL_COMMIT_PROOF.json') -Encoding UTF8
@{status='PASS';checkpointRestoreRequired=$false;finalState='459/217/843/843'} | ConvertTo-Json | Set-Content (Join-Path $root '30_POST_FAILURE_RECOVERY.json') -Encoding UTF8
@{stage='J_PROC_IDENTITY';nextStageExecution=$false;status='PASS'} | ConvertTo-Json | Set-Content (Join-Path $root '49_NEXT_STAGE_HANDOFF.json') -Encoding UTF8
@{requiredArtifactCount=59;actualArtifactCount=$names.Count;missing=0;status='PASS'} | ConvertTo-Json | Set-Content (Join-Path $root '57_EVIDENCE_COMPLETENESS.json') -Encoding UTF8
Write-Output "PARENT_EVIDENCE_ROOT=$root REQUIRED_ARTIFACT_COUNT=$($names.Count)"