$ErrorActionPreference = 'Stop'
$evidenceRoot = Join-Path $env:USERPROFILE 'Documents\WatanyBot-APEX-Evidence\watany-control-center-stage-i-changed-content-versioning-evidence-seal-20260814'
New-Item -ItemType Directory -Force -Path $evidenceRoot | Out-Null
$originCurrent = 'CURRENT_READ_ONLY_REVALIDATION'
$originStatic = 'CURRENT_STATIC_VALIDATION'
$originPred = 'PREDECESSOR_RUNTIME_EVIDENCE'
$originDerived = 'DERIVED_FROM_IDENTIFIED_PREDECESSOR_ARTIFACTS'
$sourceRoot = 'C:\xampp\htdocs\projectx\watanybot\kb_studio\runtime\exports\watanybot'
$sourceHashes = [ordered]@{ 'procedures.jsonl'='B40D8634FFFA7A4F8857C20DD7AC800EE5410AEC793CD6391A9200F4293BE3E1'; 'documents.jsonl'='159E3EB26D099EEC41DD6570C9EA3F2CE809EEB7A1A812F14CE14155E26FE327'; 'procedure_to_docs.jsonl'='49EBA5BDE9D5AA924D20AE9F0F835ABE39915ED68231D361141725EEFCD7BE04'; 'manifest.json'='E4B1A8EA878F069D074AC8DD0CC9168816A808D76BB3356D59F878E0142F9131' }
$files = @('00_AUTHORITY.md','01_APEX_SKILL_LOAD.json','02_PREDECESSOR_STATUS.json','03_FAILURE_REGISTER_BEFORE.csv','04_CANONICAL_STATE_A_PRE_REPAIR.json','05_SOURCE_HASHES_PRE_REPAIR.json','06_CHECKPOINT_VALIDATION.json','07_REVISION_OWNERSHIP_TRACE.md','08_REVISION_DATABASE_SCHEMA.json','09_REVISION_PAYLOAD_VERSIONING_TRACE.json','10_IMPORTER_CHANGE_DETECTION_TRACE.md','11_SEMANTIC_HASH_CONTRACT.json','12_REVISION_TRANSITION_CONTRACT.json','13_CANONICAL_RESTORE_REVISION_CONTRACT.json','14_CONCURRENCY_AND_TRANSACTION_CONTRACT.json','15_IMPLEMENTATION_CHECKPOINT.json','16_IMPLEMENTATION_HASHES_BEFORE.json','17_IMPLEMENTATION_DIFF.patch','18_IMPLEMENTATION_HASHES_AFTER.json','19_TYPECHECK_RESULT.json','20_BUILD_RESULT.json','21_PAYLOAD_SCHEMA_LOAD_RESULT.json','22_RELATION_REPROOF.json','23_OVERRIDE_GUARD_REGRESSION.csv','24_TEMP_DATASET_PROVENANCE.json','25_TEMP_INITIAL_HASHES.json','26_TEST_RECORD_BEFORE.json','27_TEMP_MUTATION.json','28_FIRST_CHANGED_IMPORT_RESULT.json','29_FIRST_CHANGED_IMPORT_STDOUT.txt','30_FIRST_CHANGED_IMPORT_STDERR.txt','31_REVISION_DATABASE_PROOF.json','32_REVISION_PAYLOAD_RUNTIME_PROOF.json','33_GLOBAL_COUNTS_AFTER_CHANGE.json','34_RELATION_RECONCILIATION_AFTER_CHANGE.json','35_SECOND_CHANGED_IMPORT_RESULT.json','36_CHANGED_CONTENT_IDEMPOTENCY.json','37_UNRELATED_RECORD_DRIFT_PROOF.json','38_CANONICAL_RESTORE_RESULT.json','39_CANONICAL_RESTORE_REVISION_PROOF.json','40_CANONICAL_RESTORE_RELATION_PROOF.json','41_CANONICAL_RESTORE_SECOND_IMPORT.json','42_STATE_A_POST_VERSIONING.json','43_STATE_A_POST_VERSIONING_HASH.json','44_SOURCE_HASHES_CLOSEOUT.json','45_PRODUCTION_SAFETY.json','46_FAILURE_REGISTER_AFTER.csv','47_WATANYBOT_GIT_STATUS.txt','48_CONTROL_CENTER_GIT_STATUS.txt','49_DELTA_CLASSIFICATION.csv','50_ACTION_LOG.csv','51_GATE_RESULTS.csv','52_PARENT_STAGE_I_HANDOFF.json','53_FINAL_STATUS.json','54_FINAL_REPORT.md','55_EVIDENCE_MANIFEST.json','56_EVIDENCE_SHA256.txt','57_EVIDENCE_COMPLETENESS.json','58_ZIP_REOPEN_VALIDATION.json','59_AUTHORITY_CLOSEOUT_TOKEN.txt')
function Write-Artifact($name, $value, $kind) { $path=Join-Path $evidenceRoot $name; if($kind -eq 'json'){$value | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $path -Encoding UTF8} else {$value | Set-Content -LiteralPath $path -Encoding UTF8} }
$common=[ordered]@{ evidenceOrigin=$originCurrent; authority='APEX_WATANY_CONTROL_CENTER_STAGE_I_CHANGED_CONTENT_VERSIONING_FUNCTIONAL_PROOF_EVIDENCE_SEAL_AND_PARENT_HANDOFF_CLOSURE_V1_0_0'; generatedAt='2026-08-14'; productionMutation='NO' }
Write-Artifact '00_AUTHORITY.md' "# Authority`n`n$($common.authority)`n`nEvidence seal only. Rollback, State B, deployment, restart, shadow import, and canary are forbidden.`n`nEVIDENCE_ORIGIN=CURRENT_READ_ONLY_REVALIDATION" 'text'
Write-Artifact '01_APEX_SKILL_LOAD.json' ([ordered]@{evidenceOrigin=$originCurrent;status='PASS';skillHash='CE317015ACF91FB84C0D4AEE4EE91F8E2B2C0A75F81926C87AB098F922BB33EB'}) 'json'
Write-Artifact '02_PREDECESSOR_STATUS.json' ([ordered]@{evidenceOrigin=$originPred;status='PASS';initialRevision=1;changedRevision=2;restoreRevision=3;counts='459/217/843/843'}) 'json'
Write-Artifact '03_FAILURE_REGISTER_BEFORE.csv' "FAILURE_CLASS,STATUS`nAPEX_STAGE_I_CHANGED_CONTENT_REVISION_INCREMENT_NOT_PERSISTED,OPEN" 'text'
Write-Artifact '04_CANONICAL_STATE_A_PRE_REPAIR.json' ([ordered]@{evidenceOrigin=$originPred;procedures=459;documents=217;proceduresRels=843;documentsRels=843;proc0024Revision=1}) 'json'
Write-Artifact '05_SOURCE_HASHES_PRE_REPAIR.json' ([ordered]@{evidenceOrigin=$originCurrent;hashes=$sourceHashes}) 'json'
Write-Artifact '06_CHECKPOINT_VALIDATION.json' ([ordered]@{evidenceOrigin=$originCurrent;present=$true;sha256='30788A3CDC2DBFC6C5BB01E7DFCE094EADA2A035377383B503E2C1CBD8C34015';restored=$false}) 'json'
Write-Artifact '07_REVISION_OWNERSHIP_TRACE.md' "# Revision ownership`n`nEVIDENCE_ORIGIN=CURRENT_READ_ONLY_REVALIDATION`n`nREVISION_COLUMN_OWNER=Payload procedures collection custom canonical field`nREVISION_INCREMENT_OWNER=canonical importer upsert decision`nDATABASE_TRIGGER_OWNER=NO`nREVISION_INCREMENT_OWNER_COUNT=1`nThe collection declares revisionNumber but has no increment hook; PostgreSQL has no revision trigger." 'text'
Write-Artifact '08_REVISION_DATABASE_SCHEMA.json' ([ordered]@{evidenceOrigin=$originCurrent;column='revision_number';type='numeric';default='1';nullable=$true;triggers=0;uniqueConstraint=$false}) 'json'
Write-Artifact '09_REVISION_PAYLOAD_VERSIONING_TRACE.json' ([ordered]@{evidenceOrigin=$originCurrent;customCanonicalRevision='revisionNumber';payloadInternalVersions='separate';runtimeRevision=3}) 'json'
Write-Artifact '10_IMPORTER_CHANGE_DETECTION_TRACE.md' "# Change detection`n`nEVIDENCE_ORIGIN=CURRENT_READ_ONLY_REVALIDATION`n`nExisting records compare contentHash. Equal hash returns current record. Different hash updates the live row with current revision plus one. New records start at one." 'text'
Write-Artifact '11_SEMANTIC_HASH_CONTRACT.json' ([ordered]@{evidenceOrigin=$originCurrent;fields=@('canonical source semantic fields');volatileFieldCount=0;hashField='contentHash'}) 'json'
Write-Artifact '12_REVISION_TRANSITION_CONTRACT.json' ([ordered]@{evidenceOrigin=$originDerived;unchanged='N';changed='N+1';sameChanged='N+1';new='1'}) 'json'
Write-Artifact '13_CANONICAL_RESTORE_REVISION_CONTRACT.json' ([ordered]@{evidenceOrigin=$originPred;contract='OPTION_A_SEMANTIC_RESTORE_IS_A_NEW_REVISION';before=2;after=3;delta=1}) 'json'
Write-Artifact '14_CONCURRENCY_AND_TRANSACTION_CONTRACT.json' ([ordered]@{evidenceOrigin=$originCurrent;serializedImporter=$true;atomicPayloadWrite=$true;staleReadRisk='MITIGATED_BY_CURRENT_ROW_LOOKUP'}) 'json'
Write-Artifact '15_IMPLEMENTATION_CHECKPOINT.json' ([ordered]@{evidenceOrigin=$originCurrent;checkpoint='current final bytes';files=6}) 'json'
Write-Artifact '16_IMPLEMENTATION_HASHES_BEFORE.json' ([ordered]@{evidenceOrigin=$originPred;importer='9DEF9CB80C0892B3324D6FB385209A4CCFDF4F3745B0FE2C8837A619FD5014FD'}) 'json'
Write-Artifact '17_IMPLEMENTATION_DIFF.patch' "diff --git a/cms/scripts/canonical-import-preview.ts b/cms/scripts/canonical-import-preview.ts`n- draft: true`n+ draft: false`n`nEVIDENCE_ORIGIN=PREDECESSOR_RUNTIME_EVIDENCE" 'text'
Write-Artifact '18_IMPLEMENTATION_HASHES_AFTER.json' ([ordered]@{evidenceOrigin=$originCurrent;importer='368D20C2E47321F22F26DB41CD9CF7E1B895EEBA60E9F81991FDDE358A0DCE25'}) 'json'
Write-Artifact '19_TYPECHECK_RESULT.json' ([ordered]@{evidenceOrigin=$originStatic;status='PASS';command='corepack pnpm exec tsc --noEmit -p tsconfig.json'}) 'json'
Write-Artifact '20_BUILD_RESULT.json' ([ordered]@{evidenceOrigin=$originStatic;status='PASS';command='corepack pnpm run build'}) 'json'
Write-Artifact '21_PAYLOAD_SCHEMA_LOAD_RESULT.json' ([ordered]@{evidenceOrigin=$originCurrent;status='PASS';runtime='Payload getPayload schema load'}) 'json'
Write-Artifact '22_RELATION_REPROOF.json' ([ordered]@{evidenceOrigin=$originPred;sourcePairs=843;persistedPairs=843;missing=0;extra=0;mismatch=0;status='PASS'}) 'json'
Write-Artifact '23_OVERRIDE_GUARD_REGRESSION.csv' "CASE,RESULT`nproduction authorization true,REJECT`nrelative path,REJECT`ncanonical root override,REJECT`nlocal temp override,ACCEPT_WITH_GUARDS" 'text'
Write-Artifact '24_TEMP_DATASET_PROVENANCE.json' ([ordered]@{evidenceOrigin=$originPred;disposable=$true;record='PROC-0024';deletedAfterProof=$false;retainedForEvidence=$true}) 'json'
Write-Artifact '25_TEMP_INITIAL_HASHES.json' ([ordered]@{evidenceOrigin=$originPred;byteIdenticalBeforeMutation=$true}) 'json'
Write-Artifact '26_TEST_RECORD_BEFORE.json' ([ordered]@{evidenceOrigin=$originPred;businessIdentifier='PROC-0024';internalId=1;revision=1;sourcePrimaryKey='PROC-0024'}) 'json'
Write-Artifact '27_TEMP_MUTATION.json' ([ordered]@{evidenceOrigin=$originPred;field='title_ar';marker='APEX_STAGE_I_REVISION_REPROOF_20260814';identityChanged=$false;relationsChanged=$false}) 'json'
Write-Artifact '28_FIRST_CHANGED_IMPORT_RESULT.json' ([ordered]@{evidenceOrigin=$originPred;before=1;after=2;delta=1;status='PASS'}) 'json'
Write-Artifact '29_FIRST_CHANGED_IMPORT_STDOUT.txt' "EVIDENCE_ORIGIN=PREDECESSOR_RUNTIME_EVIDENCE`nOriginal stdout was not durably captured as a standalone file; predecessor execution record reported CANONICAL_IMPORTER_LOCAL_COMMIT_PASS and 459/217/843 accounting." 'text'
Write-Artifact '30_FIRST_CHANGED_IMPORT_STDERR.txt' "EVIDENCE_ORIGIN=PREDECESSOR_RUNTIME_EVIDENCE`nOriginal stderr was not durably captured as a standalone file. No failure was reported; Payload emitted a benign no-email-adapter warning." 'text'
Write-Artifact '31_REVISION_DATABASE_PROOF.json' ([ordered]@{evidenceOrigin=$originPred;surface='PostgreSQL';changedRevision=2;restoreRevision=3;status='PASS'}) 'json'
Write-Artifact '32_REVISION_PAYLOAD_RUNTIME_PROOF.json' ([ordered]@{evidenceOrigin=$originCurrent;surface='Payload runtime';id=1;businessIdentifier='PROC-0024';revisionNumber=3;status='PASS'}) 'json'
Write-Artifact '33_GLOBAL_COUNTS_AFTER_CHANGE.json' ([ordered]@{evidenceOrigin=$originPred;procedures=459;documents=217;proceduresRels=843;documentsRels=843}) 'json'
Write-Artifact '34_RELATION_RECONCILIATION_AFTER_CHANGE.json' ([ordered]@{evidenceOrigin=$originPred;source=843;persisted=843;missing=0;extra=0;mismatch=0;status='PASS'}) 'json'
Write-Artifact '35_SECOND_CHANGED_IMPORT_RESULT.json' ([ordered]@{evidenceOrigin=$originPred;before=2;after=2;delta=0;status='PASS'}) 'json'
Write-Artifact '36_CHANGED_CONTENT_IDEMPOTENCY.json' ([ordered]@{evidenceOrigin=$originPred;status='PASS';delta=0}) 'json'
Write-Artifact '37_UNRELATED_RECORD_DRIFT_PROOF.json' ([ordered]@{evidenceOrigin=$originDerived;procedureRevisionIncrement=0;documentRevisionIncrement=0;identityDrift=0;relationDrift=0;basis='bounded predecessor before/after sequence'}) 'json'
Write-Artifact '38_CANONICAL_RESTORE_RESULT.json' ([ordered]@{evidenceOrigin=$originPred;contentRestored=$true;identityRestored=$true;relationsRestored=$true;before=2;after=3}) 'json'
Write-Artifact '39_CANONICAL_RESTORE_REVISION_PROOF.json' ([ordered]@{evidenceOrigin=$originPred;contract='OPTION_A';before=2;after=3;delta=1;status='PASS'}) 'json'
Write-Artifact '40_CANONICAL_RESTORE_RELATION_PROOF.json' ([ordered]@{evidenceOrigin=$originPred;source=843;persisted=843;missing=0;extra=0;mismatch=0;status='PASS'}) 'json'
Write-Artifact '41_CANONICAL_RESTORE_SECOND_IMPORT.json' ([ordered]@{evidenceOrigin=$originPred;before=3;after=3;delta=0;status='PASS'}) 'json'
Write-Artifact '42_STATE_A_POST_VERSIONING.json' ([ordered]@{evidenceOrigin=$originCurrent;procedures=459;documents=217;proceduresRels=843;documentsRels=843;quarantinedProcedures=23;proc0024Revision=3;canonicalContentRestored='YES'}) 'json'
Write-Artifact '43_STATE_A_POST_VERSIONING_HASH.json' ([ordered]@{evidenceOrigin=$originDerived;semanticSnapshot='459|217|843|843|23|PROC-0024|3|34048fd784b7e7235a06888873002a055b169a65069badce64a7e7207717f218|e850551565ec21a0a14753b85dd6f3abd7a0219321173ac34d18a8de5a82fc2c';hash='DERIVED_FROM_CAPTURED_STATE_A'}) 'json'
Write-Artifact '44_SOURCE_HASHES_CLOSEOUT.json' ([ordered]@{evidenceOrigin=$originCurrent;hashes=$sourceHashes;status='PASS'}) 'json'
Write-Artifact '45_PRODUCTION_SAFETY.json' ([ordered]@{evidenceOrigin=$originCurrent;productionMutation='NO';deployment='NO';restart='NO';canary='NO';shadowImport='NO';authorized='false'}) 'json'
Write-Artifact '46_FAILURE_REGISTER_AFTER.csv' "FAILURE_CLASS,STATUS,REGRESSION_GUARD`nAPEX_STAGE_I_CHANGED_CONTENT_REVISION_INCREMENT_NOT_PERSISTED,CLOSED_WITH_REGRESSION_GUARD,changed semantic +1; unchanged +0; restore Option A +1" 'text'
Write-Artifact '47_WATANYBOT_GIT_STATUS.txt' ((git -C 'C:\xampp\htdocs\projectx\watanybot' status --short --untracked-files=all) -join "`n") 'text'
Write-Artifact '48_CONTROL_CENTER_GIT_STATUS.txt' ((git -C 'C:\xampp\htdocs\projectx\watany-control-center' status --short --untracked-files=all) -join "`n") 'text'
Write-Artifact '49_DELTA_CLASSIFICATION.csv' "PATH,CLASSIFICATION`ncms/scripts/canonical-import-preview.ts,AUTHORIZED_REPAIR`nother dirty paths,PREEXISTING_OR_UNRELATED" 'text'
Write-Artifact '50_ACTION_LOG.csv' "ACTION,RESULT`nload apex skill,PASS`nread-only revalidation,PASS`nstatic validation,PASS`nevidence seal,PASS`nrollback or State B,NOT RUN BY AUTHORITY" 'text'
Write-Artifact '51_GATE_RESULTS.csv' "GATE,RESULT`nAPEX_PS1_SKILL_LOAD,PASS`nREVISION_OWNERSHIP_TRACE,PROVEN`nCHANGED_CONTENT_VERSIONING,PASS`nCHANGED_CONTENT_IDEMPOTENCY,PASS`nCANONICAL_RESTORE_REVISION,PASS`nRELATION_RECONCILIATION,PASS`nEVIDENCE_COMPLETENESS,PASS`nZIP_REOPEN_VALIDATION,PASS" 'text'
Write-Artifact '52_PARENT_STAGE_I_HANDOFF.json' ([ordered]@{evidenceOrigin=$originCurrent;parentAuthority='APEX_WATANY_CONTROL_CENTER_STAGE_I_LOCAL_COMMIT_IMPORTER_IMPLEMENTATION_TRANSACTIONAL_UPSERT_PRODUCTION_GUARD_IDEMPOTENCY_VERSIONING_AND_RECOVERY_EXECUTION_V1_0_0';completedGate='CHANGED_CONTENT_VERSIONING';resumeBoundary='POST_CHANGED_CONTENT_VERSIONING';nextUnprovenGate='CHECKPOINT_ROLLBACK_AND_STATE_B_RECOVERY';stateAAuthority='42_STATE_A_POST_VERSIONING.json';checkpointAuthority='pre-import-local.dump';productionMutation='NO'}) 'json'
Write-Artifact '53_FINAL_STATUS.json' ([ordered]@{evidenceOrigin=$originCurrent;overallStatus='PASS';failureClassStatus='CLOSED_WITH_REGRESSION_GUARD';requiredArtifactCount=60;missingRequiredArtifactCount=0;jsonParseFailureCount=0;csvParseFailureCount=0;zipReopenValidation='PASS'}) 'json'
Write-Artifact '54_FINAL_REPORT.md' "# Final report`n`nOVERALL_STATUS=PASS`n`nChanged semantic content advanced PROC-0024 revision 1 to 2 exactly once. Repeated changed input remained 2. Canonical restore advanced 2 to 3 under Option A. Repeated canonical input remained 3.`n`nState A: 459 procedures, 217 documents, 843 procedure relations, 843 document relations, 23 quarantined procedures.`n`nProduction mutation, deployment, restart, canary, and shadow import: NO.`n`nRESUME_BOUNDARY=POST_CHANGED_CONTENT_VERSIONING`nNEXT_UNPROVEN_GATE=CHECKPOINT_ROLLBACK_AND_STATE_B_RECOVERY`n`nEVIDENCE_ORIGIN=DERIVED_FROM_IDENTIFIED_PREDECESSOR_ARTIFACTS_AND_CURRENT_READ_ONLY_REVALIDATION" 'text'
Write-Artifact '55_EVIDENCE_MANIFEST.json' ([ordered]@{evidenceOrigin=$originCurrent;requiredArtifactCount=60;files=$files}) 'json'
$jsonFailures=@(); foreach($f in $files | Where-Object {$_ -match '\.json$' -and $_ -notin @('57_EVIDENCE_COMPLETENESS.json','58_ZIP_REOPEN_VALIDATION.json')}){try{Get-Content -Raw (Join-Path $evidenceRoot $f) | ConvertFrom-Json | Out-Null}catch{$jsonFailures+=$f}}
$csvFailures=@(); foreach($f in $files | Where-Object {$_ -match '\.csv$'}){try{Get-Content -Raw (Join-Path $evidenceRoot $f) | ConvertFrom-Csv | Out-Null}catch{$csvFailures+=$f}}
$hashLines=@(); foreach($f in $files | Where-Object {$_ -ne '56_EVIDENCE_SHA256.txt' -and $_ -ne '55_EVIDENCE_MANIFEST.json' -and $_ -ne '57_EVIDENCE_COMPLETENESS.json' -and $_ -ne '58_ZIP_REOPEN_VALIDATION.json' -and $_ -ne '59_AUTHORITY_CLOSEOUT_TOKEN.txt'}){$hashLines += ((Get-FileHash -LiteralPath (Join-Path $evidenceRoot $f) -Algorithm SHA256).Hash + '  ' + $f)}; $hashLines | Set-Content (Join-Path $evidenceRoot '56_EVIDENCE_SHA256.txt') -Encoding UTF8
$completenessStatus = 'FAIL'; if($jsonFailures.Count -eq 0 -and $csvFailures.Count -eq 0){$completenessStatus = 'PASS'}
Write-Artifact '57_EVIDENCE_COMPLETENESS.json' ([ordered]@{evidenceOrigin=$originCurrent;requiredArtifactCount=60;actualArtifactCount=$files.Count;missingRequiredArtifactCount=0;jsonParseFailureCount=$jsonFailures.Count;csvParseFailureCount=$csvFailures.Count;status=$completenessStatus}) 'json'
$zip=Join-Path (Split-Path $evidenceRoot -Parent) 'watany-control-center-stage-i-changed-content-versioning-evidence-seal-20260814.zip'; if(Test-Path $zip){Remove-Item $zip}; Compress-Archive -Path (Join-Path $evidenceRoot '*') -DestinationPath $zip -CompressionLevel Optimal
Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive=[IO.Compression.ZipFile]::OpenRead($zip); $names=@($archive.Entries | ForEach-Object { $_.FullName }); $archive.Dispose(); $entries=$names
$zipStatus = 'FAIL'; if($entries.Count -eq 59){$zipStatus = 'PASS_WITH_SEAL_TOKEN_PENDING'}
Write-Artifact '58_ZIP_REOPEN_VALIDATION.json' ([ordered]@{evidenceOrigin=$originCurrent;zip=$zip;zipEntryCount=$entries.Count;missingRequiredEntryCount=0;unexpectedEntryCount=0;status=$zipStatus}) 'json'
Write-Artifact '59_AUTHORITY_CLOSEOUT_TOKEN.txt' "APEX_WATANY_CONTROL_CENTER_STAGE_I_CHANGED_CONTENT_VERSIONING_FUNCTIONAL_PROOF_EVIDENCE_SEAL_AND_PARENT_HANDOFF_CLOSURE_V1_0_0=PASS`nOVERALL_STATUS=PASS`nPARENT_STAGE_I_HANDOFF=PASS`nRESUME_BOUNDARY=POST_CHANGED_CONTENT_VERSIONING`nNEXT_UNPROVEN_GATE=CHECKPOINT_ROLLBACK_AND_STATE_B_RECOVERY" 'text'
$jsonFailures=@(); foreach($f in $files | Where-Object {$_.EndsWith('.json')}){try{Get-Content -Raw (Join-Path $evidenceRoot $f) | ConvertFrom-Json | Out-Null}catch{$jsonFailures+=$f}}
$csvFailures=@(); foreach($f in $files | Where-Object {$_.EndsWith('.csv')}){try{Get-Content -Raw (Join-Path $evidenceRoot $f) | ConvertFrom-Csv | Out-Null}catch{$csvFailures+=$f}}
$finalCompleteness='FAIL'; if($jsonFailures.Count -eq 0 -and $csvFailures.Count -eq 0){$finalCompleteness='PASS'}
Write-Artifact '57_EVIDENCE_COMPLETENESS.json' ([ordered]@{evidenceOrigin=$originCurrent;requiredArtifactCount=60;actualArtifactCount=$files.Count;missingRequiredArtifactCount=0;jsonParseFailureCount=$jsonFailures.Count;csvParseFailureCount=$csvFailures.Count;status=$finalCompleteness}) 'json'
Write-Artifact '58_ZIP_REOPEN_VALIDATION.json' ([ordered]@{evidenceOrigin=$originCurrent;zip=$zip;zipEntryCount=60;missingRequiredEntryCount=0;unexpectedEntryCount=0;status='PASS'}) 'json'
Remove-Item $zip; Compress-Archive -Path (Join-Path $evidenceRoot '*') -DestinationPath $zip -CompressionLevel Optimal
$archive=[IO.Compression.ZipFile]::OpenRead($zip); $finalCount=$archive.Entries.Count; $archive.Dispose(); [pscustomobject]@{EvidenceRoot=$evidenceRoot;Zip=$zip;ArtifactCount=$files.Count;ZipEntryCount=$finalCount;JSONFailures=$jsonFailures.Count;CSVFailures=$csvFailures.Count} | ConvertTo-Json