/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'gateway-admins': GatewayAdminAuthOperations;
  };
  blocks: {};
  collections: {
    'gateway-admins': GatewayAdmin;
    procedures: Procedure;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'gateway-admins': GatewayAdminsSelect<false> | GatewayAdminsSelect<true>;
    procedures: ProceduresSelect<false> | ProceduresSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'ar' | 'en';
  user: GatewayAdmin & {
    collection: 'gateway-admins';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface GatewayAdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gateway-admins".
 */
export interface GatewayAdmin {
  id: number;
  gatewayUserId: string;
  email: string;
  displayName?: string | null;
  roleSnapshot: string;
  capabilitySnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastAuthenticatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures".
 */
export interface Procedure {
  id: number;
  /**
   * Stable WATANYBOT identity, format proc-xxxx.
   */
  procedureCode: string;
  slug: string;
  title: string;
  summary?: string | null;
  category?: string | null;
  eligibility?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  fees?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  processingTime?: string | null;
  locations?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  contacts?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  sourceAuthority: string;
  sourceUrl?: string | null;
  lastVerifiedAt?: string | null;
  verifiedBy?: string | null;
  reviewDueAt?: string | null;
  notes?: string | null;
  publicationState: 'DRAFT' | 'PUBLISHED';
  workflowStatus: 'DRAFT' | 'PUBLISHED';
  sourceSystem?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'gateway-admins';
        value: number | GatewayAdmin;
      } | null)
    | ({
        relationTo: 'procedures';
        value: number | Procedure;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'gateway-admins';
    value: number | GatewayAdmin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'gateway-admins';
    value: number | GatewayAdmin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gateway-admins_select".
 */
export interface GatewayAdminsSelect<T extends boolean = true> {
  gatewayUserId?: T;
  email?: T;
  displayName?: T;
  roleSnapshot?: T;
  capabilitySnapshot?: T;
  lastAuthenticatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "procedures_select".
 */
export interface ProceduresSelect<T extends boolean = true> {
  procedureCode?: T;
  slug?: T;
  title?: T;
  summary?: T;
  category?: T;
  eligibility?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        item?: T;
        id?: T;
      };
  fees?:
    | T
    | {
        item?: T;
        id?: T;
      };
  processingTime?: T;
  locations?:
    | T
    | {
        item?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        item?: T;
        id?: T;
      };
  sourceAuthority?: T;
  sourceUrl?: T;
  lastVerifiedAt?: T;
  verifiedBy?: T;
  reviewDueAt?: T;
  notes?: T;
  publicationState?: T;
  workflowStatus?: T;
  sourceSystem?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}