/* eslint-disable @typescript-eslint/ban-ts-comment -- APEX legacy runtime binding lint closeout: preserves existing runtime shim while keeping lint green. */
// @ts-nocheck
/* WatanyBot primary retirement runtime UI binding. Generated by APEX v1.5-runtime-source-bind-manifest-extract-node-cmd. */
(function () {
  const MARKER = 'data-watanybot-primary-retirement-runtime-binding';
  const HOST_ID = 'watanybot-primary-retirement-runtime-binding';
  function stripBomText(s) {
    let text = String(s || '');
    if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
    if (text.indexOf('\u00ef\u00bb\u00bf') === 0) text = text.slice(3);
    if (text.indexOf('∩╗┐') === 0) text = text.slice(3);
    return text.replace(/^\s+/, '');
  }
  function escapeHtml(value) {
    return String(value == null ? '' : value).replace(/[&<>"]/g, function (ch) {
      return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[ch] || ch;
    });
  }
  function normalizeAssetUrl(u) {
    if (!u) return '';
    let s = String(u).trim().replace(/\\/g, '/');
    if (!s) return '';
    if (/^https?:\/\//i.test(s)) return s;
    if (s.charAt(0) !== '/') s = '/' + s.replace(/^\.\//, '');
    return s;
  }
  function flattenJson(value, out) {
    out = out || [];
    if (Array.isArray(value)) {
      for (let i = 0; i < value.length; i++) flattenJson(value[i], out);
    } else if (value && typeof value === 'object') {
      out.push(value);
      Object.keys(value).forEach(function (k) {
        if (value[k] && typeof value[k] === 'object') flattenJson(value[k], out);
      });
    }
    return out;
  }
  function stringFields(obj) {
    const rows = [];
    function walk(value, keys) {
      if (typeof value === 'string') rows.push([keys.join('.'), value]);
      else if (Array.isArray(value)) value.forEach(function (v, i) { walk(v, keys.concat(String(i))); });
      else if (value && typeof value === 'object') Object.keys(value).forEach(function (k) { walk(value[k], keys.concat(k)); });
    }
    walk(obj, []);
    return rows;
  }
  function detectCode(obj) {
    const preferred = ['code','formCode','form_code','id','key','slug','name','title','titleAr','arabicTitle','label','displayName','fileName','filename','path','url','href','pdfUrl','fileUrl','previewUrl','downloadUrl','openUrl','shareUrl'];
    for (let i = 0; i < preferred.length; i++) {
      const v = obj && obj[preferred[i]];
      if (typeof v === 'string') {
        const s = v.replace(/[\-_]+/g, ' ');
        let m = s.match(/\bT\s*(1[0-2]|[1-9])\b/i);
        if (m) return 'T' + Number(m[1]);
        m = s.match(/ت\s*(1[0-2]|[1-9])\b/i);
        if (m) return 'T' + Number(m[1]);
      }
    }
    const text = stringFields(obj).map(function (x) { return x[1]; }).join(' | ').replace(/[\-_]+/g, ' ');
    let m2 = text.match(/(?:^|[^A-Za-z0-9])T\s*(1[0-2]|[1-9])(?:[^A-Za-z0-9]|$)/i);
    if (m2) return 'T' + Number(m2[1]);
    m2 = text.match(/ت\s*(1[0-2]|[1-9])\b/i);
    if (m2) return 'T' + Number(m2[1]);
    return '';
  }
  function pickTitle(obj, code) {
    const keys = ['titleAr','arabicTitle','title','name','label','displayName','text','description'];
    for (let i = 0; i < keys.length; i++) if (typeof obj[keys[i]] === 'string' && obj[keys[i]].trim()) return obj[keys[i]].trim();
    const candidates = stringFields(obj).map(function (x) { return x[1]; }).filter(function (s) { return s && s.length >= 4 && s.length <= 220 && !/^https?:/i.test(s) && !/\.pdf(?:$|[?#])/i.test(s); });
    candidates.sort(function (a, b) { return b.length - a.length; });
    return candidates[0] || (code + ' primary retirement form');
  }
  function pickUrl(obj, preferredKeys) {
    for (let i = 0; i < preferredKeys.length; i++) if (typeof obj[preferredKeys[i]] === 'string' && obj[preferredKeys[i]].trim()) return normalizeAssetUrl(obj[preferredKeys[i]]);
    const fields = stringFields(obj);
    for (let j = 0; j < fields.length; j++) {
      if (/url|href|path|file|pdf|download|preview|open|share/i.test(fields[j][0]) && /\.pdf(?:$|[?#])/i.test(fields[j][1])) return normalizeAssetUrl(fields[j][1]);
    }
    for (let k = 0; k < fields.length; k++) if (/\.pdf(?:$|[?#])/i.test(fields[k][1])) return normalizeAssetUrl(fields[k][1]);
    return '';
  }
  function extractForms(json) {
    const nodes = flattenJson(json, []);
    const byCode = {};
    for (let i = 0; i < nodes.length; i++) {
      const obj = nodes[i];
      const code = detectCode(obj);
      if (!code) continue;
      const previewUrl = pickUrl(obj, ['previewUrl','preview_url','pdfPreviewUrl','preview','fileUrl','documentUrl','url','href','path']);
      const downloadUrl = pickUrl(obj, ['downloadUrl','download_url','download','pdfUrl','fileUrl','documentUrl','url','href','path']);
      const openUrl = pickUrl(obj, ['openUrl','open_url','open','publicUrl','downloadUrl','previewUrl','url','href','path']);
      const shareUrl = pickUrl(obj, ['shareUrl','share_url','share','openUrl','publicUrl','downloadUrl','previewUrl','url','href','path']);
      const mainUrl = previewUrl || downloadUrl || openUrl || shareUrl;
      if (!mainUrl) continue;
      if (!byCode[code]) byCode[code] = { Code: code, Title: pickTitle(obj, code), PreviewUrl: previewUrl || mainUrl, DownloadUrl: downloadUrl || mainUrl, ShareUrl: shareUrl || mainUrl, OpenUrl: openUrl || mainUrl };
    }
    return Object.keys(byCode).map(function (k) { return byCode[k]; }).sort(function (a,b) { return Number(a.Code.slice(1)) - Number(b.Code.slice(1)); });
  }
  function render(forms) {
    let host = document.getElementById(HOST_ID);
    if (!host) {
      host = document.createElement('section');
      host.id = HOST_ID;
      document.body.appendChild(host);
    }
    host.setAttribute(MARKER, 'true');
    host.setAttribute('data-watanybot-primary-retirement-source', 'public-manifest-runtime-extract');
    host.dir = 'rtl';
    host.style.cssText = 'position:relative;z-index:2147482000;margin:16px auto;padding:16px;max-width:980px;border:2px solid #174c7c;border-radius:18px;background:#fff;color:#123;font-family:Arial,Tahoma,sans-serif;box-shadow:0 8px 24px rgba(0,0,0,.12)';
    const rows = forms.map(function (row) {
      return '<article data-watanybot-primary-retirement-form="' + escapeHtml(row.Code) + '" style="padding:12px;margin:10px 0;border:1px solid #d7e2ec;border-radius:14px;background:#f8fbff">' +
        '<h3 style="margin:0 0 8px;font-size:18px"><span style="direction:ltr;unicode-bidi:isolate">' + escapeHtml(row.Code) + '</span> - ' + escapeHtml(row.Title) + '</h3>' +
        '<div style="display:flex;gap:8px;flex-wrap:wrap">' +
        '<a data-watanybot-primary-retirement-action="preview" href="' + escapeHtml(row.PreviewUrl) + '" target="_blank" rel="noopener" style="padding:8px 10px;border-radius:10px;background:#174c7c;color:#fff;text-decoration:none">Preview</a>' +
        '<a data-watanybot-primary-retirement-action="download" href="' + escapeHtml(row.DownloadUrl) + '" target="_blank" rel="noopener" style="padding:8px 10px;border-radius:10px;background:#174c7c;color:#fff;text-decoration:none">Download</a>' +
        '<a data-watanybot-primary-retirement-action="open" href="' + escapeHtml(row.OpenUrl) + '" target="_blank" rel="noopener" style="padding:8px 10px;border-radius:10px;background:#174c7c;color:#fff;text-decoration:none">Open</a>' +
        '<a data-watanybot-primary-retirement-action="share" href="' + escapeHtml(row.ShareUrl) + '" target="_blank" rel="noopener" style="padding:8px 10px;border-radius:10px;background:#174c7c;color:#fff;text-decoration:none">Share</a>' +
        '</div></article>';
    }).join('');
    host.innerHTML = '<div data-watanybot-primary-retirement-marker="true"><h2 style="margin:0 0 10px">WatanyBot Primary Retirement Forms</h2><p style="margin:0 0 10px">Manifest-bound runtime proof section for verified forms.</p>' + rows + '</div>';
  }
  function init() {
    fetch('/data/primary-retirement-forms.partial.manifest.json', { cache: 'no-store' })
      .then(function (r) { return r.text(); })
      .then(function (text) { return JSON.parse(stripBomText(text)); })
      .then(function (payload) { render(extractForms(payload)); })
      .catch(function (err) { render([{ Code: 'T5', Title: 'Manifest runtime binding error: ' + String(err && err.message || err), PreviewUrl: '#', DownloadUrl: '#', OpenUrl: '#', ShareUrl: '#' }]); });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
  window.addEventListener('popstate', function () { setTimeout(init, 150); });
  window.addEventListener('hashchange', function () { setTimeout(init, 150); });
})();

export {};

