import type { LandingConfig } from "./MobileFeatureLandingPage";

export const marketMobileLandingConfig: LandingConfig = {
  id: "market",
  title: "السوق والخدمات",
  eyebrow: "سوق موطني الموثوق",
  subtitle: "إعلانات بيع وشراء وخدمات قريبة، مع متابعة واضحة للحالة والثقة والحفظ من شاشة واحدة.",
  navLabel: "تنقل السوق الداخلي",
  searchLabel: "بحث السوق",
  searchPlaceholder: "ابحث عن غرض، خدمة، بائع، منطقة...",
  primaryActionLabel: "أضف إعلان",
  primaryActionHref: "/marketplace?section=create",
  secondaryActionLabel: "إعلاناتي",
  secondaryActionHref: "/marketplace?section=my-listings",
  navItems: [
    { icon: "HOME", label: "الرئيسية", href: "/market" },
    { icon: "SEARCH", label: "بحث السوق", href: "/marketplace?section=browse" },
    { icon: "CATS", label: "الفئات", href: "/marketplace?section=categories" },
    { icon: "ADD", label: "إنشاء إعلان", href: "/marketplace?section=create" },
    { icon: "LIST", label: "إعلاناتي", href: "/marketplace?section=my-listings" },
    { icon: "SAVE", label: "المحفوظات", href: "/marketplace?section=saved" },
    { icon: "TRUST", label: "الثقة والبلاغات", href: "/marketplace?section=trust" },
  ],
  filters: [
    { icon: "✨", label: "الكل", value: "all" },
    { icon: "📍", label: "قريب مني", value: "nearby" },
    { icon: "✅", label: "موثوق", value: "trusted" },
    { icon: "⏳", label: "بانتظار مراجعة الإدارة", value: "pending" },
    { icon: "↕", label: "الترتيب", value: "sort" },
    { icon: "⚙️", label: "التصفية", value: "filter" },
  ],
  shortcuts: [
    { icon: "🛍️", label: "تصفح السوق", description: "آخر الإعلانات المقبولة والموثوقة", href: "/marketplace?section=browse" },
    { icon: "➕", label: "إنشاء إعلان", description: "أضف بيعاً أو خدمة أو طلب شراء", href: "/marketplace?section=create" },
    { icon: "📋", label: "إعلاناتي", description: "راجع المنشور والمعلّق والمطلوب تعديله", href: "/marketplace?section=my-listings" },
    { icon: "🔖", label: "محفوظاتي", description: "إعلانات تريد متابعتها لاحقاً", href: "/marketplace?section=saved" },
    { icon: "🗂️", label: "الفئات", description: "سيارات، عقارات، خدمات، أدوات وغيرها", href: "/marketplace?section=categories" },
    { icon: "📍", label: "قريب مني", description: "رتّب حسب المحافظة والقضاء والبلدة", href: "/marketplace?section=nearby" },
    { icon: "⏳", label: "قيد المراجعة", description: "تعرف على ما ينتظر موافقة الإدارة", href: "/marketplace?section=pending" },
    { icon: "🛡️", label: "الثقة والبلاغات", description: "تحقق من البائعين وبلّغ عن المخالفات", href: "/marketplace?section=trust" },
  ],
  categories: [
    { icon: "🚗", label: "سيارات", description: "بيع، شراء، وقطع تبديل", href: "/marketplace?category=cars&section=cars" },
    { icon: "🏠", label: "عقارات", description: "شقق، غرف، وإيجارات", href: "/marketplace?category=property&section=property" },
    { icon: "🛠️", label: "خدمات", description: "صيانة، نقل، وحرف", href: "/marketplace?category=services&section=services" },
    { icon: "💻", label: "إلكترونيات", description: "هواتف، لابتوبات، وملحقات", href: "/marketplace?category=items&section=electronics" },
    { icon: "🪑", label: "أثاث", description: "بيت، مكتب، وتجهيزات", href: "/marketplace?category=items&section=furniture" },
    { icon: "🩺", label: "دعم طبي", description: "معدات، أجهزة، واحتياجات صحية", href: "/marketplace?category=items&section=medical" },
    { icon: "🧰", label: "أدوات", description: "عدة، معدات، وورش", href: "/marketplace?category=items&section=tools" },
    { icon: "📦", label: "أغراض متنوعة", description: "طلبات وعروض متنوعة", href: "/marketplace?category=items&section=other" },
  ],
  statusCards: [
    { icon: "⏳", label: "قيد المراجعة", description: "3 إعلانات تنتظر موافقة الإدارة", href: "/marketplace?section=pending" },
    { icon: "✅", label: "مقبولة", description: "6 إعلانات منشورة وجاهزة للعرض", href: "/marketplace?section=approved" },
    { icon: "🔖", label: "محفوظة", description: "8 عناصر تتابعها للرجوع لاحقاً", href: "/marketplace?section=saved" },
    { icon: "🚩", label: "بلاغات السوق", description: "مراجعة الثقة وسلامة التعامل", href: "/marketplace?section=reports" },
  ],
  categoryRails: [
    {
      id: "cars",
      icon: "🚗",
      title: "سيارات ونقل",
      description: "عروض سيارات وخدمات نقل داخل المناطق.",
      actionLabel: "عرض سيارات ونقل",
      actionHref: "/marketplace?category=cars&section=cars",
      items: [
        { title: "سيارة كيا ريو 2014 للبيع", meta: "زحلة · أوتوماتيك · ميكانيك نظيف", badge: "موثّق", href: "/marketplace?category=cars&section=cars" },
        { title: "تاكسي من وإلى المطار", meta: "بيروت · حجز مسبق · على مدار الساعة", badge: "متاح", href: "/marketplace?category=transport&section=nearby" },
        { title: "خدمة نقل يومية بيروت - جونية", meta: "ذهاب وإياب · حجوزات أسبوعية", badge: "طلب عالٍ", href: "/marketplace?category=transport&section=services" },
      ],
    },
    {
      id: "property",
      icon: "🏠",
      title: "عقارات وسكن",
      description: "شقق وغرف وإيجارات شهرية واضحة.",
      actionLabel: "عرض العقارات",
      actionHref: "/marketplace?category=property&section=property",
      items: [
        { title: "شقة مفروشة للإيجار الشهري", meta: "الحدث · غرفتان · قريبة من الخدمات", badge: "جديد", href: "/marketplace?category=property&section=property" },
        { title: "غرفة مستقلة قرب الجامعة", meta: "جونية · مفروشة · فاتورة إنترنت", badge: "موثّق", href: "/marketplace?category=property&section=property" },
        { title: "مكتب صغير للعمل المشترك", meta: "الأشرفية · عنوان تجاري · مرن", badge: "جاهز", href: "/marketplace?category=property&section=property" },
      ],
    },
    {
      id: "services",
      icon: "🛠️",
      title: "خدمات ومهارات",
      description: "حرفيون ومقدمو خدمات من المجتمع.",
      actionLabel: "عرض الخدمات",
      actionHref: "/marketplace?category=services&section=services",
      items: [
        { title: "صيانة كهرباء ومولدات منزلية", meta: "جونية · متاح اليوم · كشف قبل العمل", badge: "موصى به", href: "/marketplace?category=services&section=services" },
        { title: "فريق دهان وترميم للشقق", meta: "المتن · مواعيد سريعة · ضمان عمل", badge: "رائج", href: "/marketplace?category=services&section=services" },
        { title: "مرشد سياحي للجبل والشمال", meta: "عربي / إنجليزي · حجز خاص", badge: "موثّق", href: "/marketplace?category=freelance&section=services" },
        { title: "تصوير مناسبات ومنتجات", meta: "صور · خبرة بالإعلانات والمتاجر", badge: "متاح", href: "/marketplace?category=freelance&section=services" },
      ],
    },
    {
      id: "items",
      icon: "📦",
      title: "أغراض وإلكترونيات",
      description: "أغراض منزلية وأجهزة بحالة موصوفة.",
      actionLabel: "عرض الأغراض",
      actionHref: "/marketplace?category=items&section=browse",
      items: [
        { title: "كرسي متحرك خفيف الوزن", meta: "الأشرفية · بحالة جيدة · 120 دولار", badge: "محفوظ", href: "/marketplace?category=items&section=browse" },
        { title: "كمبيوتر محمول للعمل المكتبي", meta: "جل الديب · مناسب للدراسة والعمل", badge: "جديد", href: "/marketplace?category=items&section=browse" },
        { title: "سرير تمريضي قابل للتعديل", meta: "كفررمان · مناسب للرعاية المنزلية", badge: "موثّق", href: "/marketplace?category=items&section=medical" },
        { title: "مكتب خشبي مع أدراج", meta: "القبة · مناسب للمكتب المنزلي", badge: "عرض", href: "/marketplace?category=items&section=furniture" },
      ],
    },
  ],
  sections: [
    {
      title: "إعلانات مميزة اليوم",
      actionLabel: "عرض السوق",
      actionHref: "/marketplace?section=browse",
      items: [
        { title: "سيارة اقتصادية في بيروت", meta: "إعلان موثوق مع صور وفحص أولي", badge: "جديد", href: "/marketplace?category=cars&section=featured" },
        { title: "شقة مفروشة في المتن", meta: "إيجار شهري مناسب للعائلات", badge: "موثوق", href: "/marketplace?category=property&section=featured" },
        { title: "معدات طبية منزلية", meta: "احتياجات صحية بحالة ممتازة", badge: "جاهز", href: "/marketplace?category=items&section=medical" },
      ],
    },
    {
      title: "متابعة إعلاناتك",
      actionLabel: "إعلاناتي",
      actionHref: "/marketplace?section=my-listings",
      items: [
        { title: "إعلان يحتاج تعديل وصف", meta: "أكمل التفاصيل ليعود إلى المراجعة", badge: "تنبيه", href: "/marketplace?section=pending" },
        { title: "إعلان منشور ويتلقى اتصالات", meta: "تابع المشاهدات ورسائل المهتمين", badge: "نشط", href: "/marketplace?section=approved" },
        { title: "طلب شراء محفوظ", meta: "عد إليه عند توفر عرض مناسب", badge: "محفوظ", href: "/marketplace?section=saved&intent=buy" },
      ],
    },
    {
      title: "خدمات مطلوبة بكثرة",
      actionLabel: "عرض الخدمات",
      actionHref: "/marketplace?category=services&section=services",
      items: [
        { title: "نقل وتوصيل داخل المناطق", meta: "حجوزات يومية وسريعة", badge: "طلب عالٍ", href: "/marketplace?category=transport&section=nearby" },
        { title: "صيانة كهرباء ومولدات", meta: "خدمات منزلية وتجارية", badge: "خدمة", href: "/marketplace?category=services&intent=service&section=services" },
        { title: "أعمال دهان وترميم", meta: "طلبات متكررة ضمن السوق", badge: "رائج", href: "/marketplace?category=services&intent=service&section=services" },
      ],
    },
  ],
};

export const jobsMobileLandingConfig: LandingConfig = {
  id: "jobs",
  title: "الوظائف والفرص",
  eyebrow: "فرص عمل واضحة ومتابعة سهلة",
  subtitle: "ابحث، صفّي، احفظ، قدّم، وتابع طلباتك من شاشة واحدة منظمة.",
  navLabel: "تنقل الوظائف الداخلي",
  searchLabel: "البحث عن وظيفة",
  searchPlaceholder: "ابحث عن وظيفة، قطاع، شركة، منطقة...",
  primaryActionLabel: "ابحث عن وظيفة",
  primaryActionHref: "/jobs?section=search",
  secondaryActionLabel: "طلباتي",
  secondaryActionHref: "/jobs?section=applications",
  navItems: [
    { icon: "🔎", label: "الوظائف", href: "/jobs" },
    { icon: "📨", label: "طلباتي", href: "/jobs?section=applications" },
    { icon: "🔖", label: "المحفوظة", href: "/jobs?section=saved" },
    { icon: "📄", label: "السيرة الذاتية", href: "/jobs?section=cv" },
  ],
  filters: [
    { icon: "✨", label: "الكل", value: "all" },
  ],
  shortcuts: [],
  categories: [
    { icon: "🏛️", label: "إدارة", description: "مكاتب وإدارة", href: "/jobs?sector=administration" },
    { icon: "🛡️", label: "أمن", description: "حراسة وسلامة", href: "/jobs?sector=security" },
    { icon: "🏫", label: "تعليم", description: "مدارس وتدريب", href: "/jobs?sector=education" },
    { icon: "🩺", label: "صحة", description: "مستشفيات ورعاية", href: "/jobs?sector=healthcare" },
    { icon: "⚙️", label: "هندسة", description: "تقنية ومشاريع", href: "/jobs?sector=engineering" },
    { icon: "🚚", label: "لوجستيات", description: "نقل وتوزيع", href: "/jobs?sector=logistics" },
    { icon: "🤝", label: "منظمات", description: "NGO/UN", href: "/jobs?sector=ngo" },
    { icon: "🧰", label: "حرف", description: "مهارات ومهن", href: "/jobs?sector=trades" },
  ],
  statusCards: [
    { icon: "📨", label: "طلبات قيد المتابعة", description: "حالة التقديم", href: "/jobs?section=applications" },
    { icon: "✨", label: "مطابقات جديدة", description: "فرص حسب ملفك", href: "/jobs?section=recommended" },
    { icon: "🔖", label: "محفوظة", description: "فرص تريد حفظها", href: "/jobs?section=saved" },
    { icon: "🔔", label: "تنبيهات مفعّلة", description: "لا تفوت الفرص", href: "/jobs?section=alerts" },
  ],
  featuredListings: [
    {
      title: "قطاف التفاح في عين الحفة - تنورين",
      company: "فرصة عمل موسمية",
      location: "تنورين",
      summary: "تسجيل موسمي للعسكريين المتقاعدين وأفراد عائلاتهم، مع سكن مؤمّن وأجر يومي.",
      badge: "تسجيل مفتوح",
      href: "/jobs/ainelhafeh",
    },
  ],
  sections: [
    {
      title: "وظائف مقترحة",
      actionLabel: "عرض المزيد",
      actionHref: "/jobs?section=recommended",
      items: [
        { title: "فرص تناسب الخبرة العسكرية", meta: "إدارة، أمن، لوجستيات", badge: "مقترح" },
        { title: "وظائف قريبة من منطقتك", meta: "تستخدم المحافظة والقضاء", badge: "قريب" },
      ],
    },
    {
      title: "متابعة التقديم",
      actionLabel: "طلباتي",
      actionHref: "/jobs?section=applications",
      items: [
        { title: "طلبات مفتوحة", meta: "تابع الحالة من مكان واحد", badge: "متابعة" },
        { title: "وظائف بتقديم سريع", meta: "استخدم ملفك أو سيرتك الذاتية", badge: "سريع" },
      ],
    },
  ],
};